### ISSUE TITLE
Chaos Mod Effect Suggestions

### ISSUE THREAD

**Issue by TammysHead** [gta-chaos-mod/ChaosModV#10]
I didn't find anything to suggest effects _publicly_ so I just open this issue here so I  and other people can suggest more effects.

Effect Suggestions: 
-Remove current vehicle
-~Teleport 10 metres to the right/left~
-Swap left/right keys
-Invert Mouse
-Spawn Companion Davey
-Replace every ped model with (friendly) Jesus
-Lock at 20 fps

Thanks ^^

**Comment by pongo1231** [comment]
Please separate each suggestion into its own issue so keeping track of every suggestion is easier. Thank you.
