### ISSUE TITLE
[Effect Suggestion] Spawn Big Orange Ball

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1003]
**Name of effect**
Spawn Big Orange Ball

**Duration if timed effect (long or short timed?)**
Not timed

**Effect Description**
It'll spawn  that giant orange ball on Juice stands., see the attachment below:
![image](https://user-images.githubusercontent.com/80320765/114166260-cacde000-992d-11eb-8bed-f861f17fd3f8.png)

**Comment by anto4440** [comment]
...Does the big orange ball do anything?

**Comment by pipecek** [comment]
> 
> 
> ...Does the big orange ball do anything?

I mean, you can move it around it. It's quite heavy aswell... It's like the Tug Boat you know...

**Comment by anto4440** [comment]
Thats a shame.

**Comment by pipecek** [comment]
hmm, I thought of something else stupid. I suggested this before but I decided to make it a little better.

**Comment by anto4440** [comment]
There is no difference between the two?

**Comment by TheRealAyCe** [comment]
Can you shoot it around? That would set it apart from other big spawns.

**Comment by Last0xygen** [comment]
> Can you shoot it around? That would set it apart from other big spawns.

yes
