### ISSUE TITLE
[Effect Suggestion] It's Raining Men

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1004]
**Name of effect**
It's Raining Men

**Duration if timed effect (long or short timed?)**
for around 30 seconds

**Effect Description**
Male NPCs fall out of the sky just like in that 80s song.

**Comment by anto4440** [comment]
#754

**Comment by TheRealAyCe** [comment]
...by the same user? :D

**Comment by Last0xygen** [comment]
Come on, you already requested this 😂
