### ISSUE TITLE
[Effect Suggestion] Wait for a minute

### ISSUE THREAD

**Issue by Ryakushin** [gta-chaos-mod/ChaosModV#1005]
**Name of effect**
Wait for a minute

**Duration if timed effect (long or short timed?)**
1 minute

**Effect Description**
Its does nothing until a minute is pass away, the player if he is wait (stay still) nearby when the effect comes they will be rewarded like getting an adder or teleport to the mission (can be random). If the player didn't wait for a minute then they will be punish like explode or suicide

**Comment by Da-Best** [comment]
it feels like its time for a break which made it so the character couldn't use any keybinds which most players didn't like and it sometimes caused mission fail loops(which is fixed in the latest update). Imo i find effects where you don't do anything boring to play / watch.

**Comment by Last0xygen** [comment]
Seems like a mixture of „it’s Time for a Break“ and „Simeon says“.
I don’t think this effect is a good Addition, as it mostly already exists

**Comment by TheRealAyCe** [comment]
But maybe "It's time for a break" could have a beneficial effect as a reward for patience? Like healing you completely?

**Comment by Last0xygen** [comment]
> But maybe "It's time for a break" could have a beneficial effect as a reward for patience? Like healing you completely?

Could be easily Rekt of the next effect ist suicide or something to Fail the mission 🤷‍♂️

**Comment by SeanMirrsen** [comment]
Effects that cause the player to stop playing are usually not fun. That's the reason the failsafe mechanic was added, so that the player won't be stuck in a mission-fail loop and not play the game for an extended period of time. Because that's boring.
