### ISSUE TITLE
[Effect Suggestion] HEY I’M WALKING HERE

### ISSUE THREAD

**Issue by SampleTextYT** [gta-chaos-mod/ChaosModV#1012]
**Name of effect**
HEY I’M WALKING HERE!

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
When triggered, player should stay at a slow steady walking pace for a varied distance based off of time.

**Comment by liamjmbta** [comment]
isn't that just the no sprint effect?

**Comment by Da-Best** [comment]
i think that is the "no sprint and no jump" effect

**Comment by Last0xygen** [comment]
Correct, that is the "no sprint and no jump" effect
