### ISSUE TITLE
[Effect Suggestion] SA Sightseeing

### ISSUE THREAD

**Issue by aimlessB** [gta-chaos-mod/ChaosModV#1019]
**Name of effect**
SA Sightseeing/Sightseeing/random teleport

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Player gets teleported to a random place on the map every 3 Seconds.

**Comment by anto4440** [comment]
Ten seconds is a bit long... Make it 5 or maybe a bit less.
