### ISSUE TITLE
[Effect Suggestion] GTA Online

### ISSUE THREAD

**Issue by aimlessB** [gta-chaos-mod/ChaosModV#1020]
**Name of effect**
GTA Online

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
NPCs wearing tipical GTA Online Tryhard gear driving Deluxos, Tanks and Oppressors spawn near the player and try to grief him.

**Comment by anto4440** [comment]
Thats actually... pretty good. It sounds like something fun, the name is fitting. Only thing is that i would recommend that the effect be instant, like 'spawn greifer jesus' is. Otherwise if it *was* a timed effect, it could be like there would constantly be one person greifing you.

**Comment by TheRealAyCe** [comment]
Maybe also jail the player with some likelihood, like hackers do.

**Comment by aimlessB** [comment]
> Maybe also jail the player with some likelihood, like hackers do. 
I think thats mire of a thing for a seperate Effect but pretty cool

**Comment by aimlessB** [comment]
> Thats actually... pretty good. It sounds like something fun, the name is fitting. Only thing is that i would recommend that the effect be instant, like 'spawn greifer jesus' is. Otherwise if it _was_ a timed effect, it could be like there would constantly be one person greifing you.

It would also be very cool if you'd be able to get e.g. the Deluxo, just like you get the Opressor by killing extreme griefer jesus.

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn", "ped spawn" or "ped driving vehicle" effects. (We have enough already.)
