### ISSUE TITLE
[Effect Suggestion] Robbers

### ISSUE THREAD

**Issue by aimlessB** [gta-chaos-mod/ChaosModV#1036]
**Name of effect**
Robbers Paradise/ spawn robbers/ robbers

**Duration if timed effect (long or short timed?)**
Medium or instant 

**Effect Description**
Some peds get robbers and are dressed like robbers and try to knock over the player and steal his money, just like when you call Lamar in Gta Online.

**Comment by Last0xygen** [comment]
Already created, waiting for review https://github.com/gta-chaos-mod/ChaosModV/pull/524
