### ISSUE TITLE
[Bug] Set player into random vehicle seat - why?

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#1039]
https://www.twitch.tv/videos/984800744?t=0h28m30s ~0:28:30
https://www.twitch.tv/videos/984800744?t=0h40m50s ~0:40:50

Why does this happen? Can it be fixed?

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/730 duplicate of this, i will close the other one

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/pull/1040
