### ISSUE TITLE
[Effect Suggestion] Back To The Past!

### ISSUE THREAD

**Issue by ReiDaTecnologia** [gta-chaos-mod/ChaosModV#1043]
**Name of effect**
Back To The Past!
**Effect Description**
Spawn a Deluxo in front of the player (If inside of a vehicle already, replace it) and if the Deluxo get to 88mph, do the Back to the future effect and if the player don't leave the vehicle, don't get below 88mph before the effect ends, loads the previous save. Would be cool to do a save before loading the previous save so people don't get mad lmao xD

Note: I searched and didn't found any similar suggestion, sorry if it already exist.

**Comment by pipecek** [comment]
can you please explain a bit more clearly? It's quite confusing...

**Comment by Last0xygen** [comment]
Loading an old save has already been requested, https://github.com/gta-chaos-mod/ChaosModV/issues/358
Adding the Deluxo would be one thing, but I don’t know what you mean with „back to the future effect“ (burning tires?).
If so, I don’t think that’s a good Addition

**Comment by ReiDaTecnologia** [comment]
> Loading an old save has already been requested, #358
> Adding the Deluxo would be one thing, but I don’t know what you mean with „back to the future effect“ (burning tires?).
> If so, I don’t think that’s a good Addition

This effect: https://youtu.be/Psxktpxkc6o?t=230
Hm. according to that issue, it isn't possible or easy so i guess this suggestion can be closed as it is unviable.

**Comment by Last0xygen** [comment]
There’s a mod for it on https://www.gta5-mods.com/ if you want to use it.
As an effect I just thing there’s not „enough“, sorry
