### ISSUE TITLE
[Effect Suggestion] Bulldozer Time

### ISSUE THREAD

**Issue by BillNyeTheRussianSpyV2** [gta-chaos-mod/ChaosModV#1047]
**Name of effect**
Bulldozer Time
Your up against the the Wall.

**Effect Description**
Spawns Bulldozer unit with Minigun and the armor from the Pelto Score. Mayby include lines from the payday 2 Bulldozer.

**Comment by Last0xygen** [comment]
Already in the works
https://github.com/gta-chaos-mod/ChaosModV/pull/889
