### ISSUE TITLE
[Effect Suggestion] Blaine County Community Hour

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1048]
**Name of effect**
Blaine County Radio Community Hour
BCRCH
Nervous Ron

**Duration if timed effect (long or short timed?)**
Long (1 minute)

**Effect Description**
Plays the Blaine County Radio Community Hour podcast in the background. Not that interesting but quite funny nevertheless.

I don't know if this effect would get someone copy right claimed since this features no music....

**Comment by SeanMirrsen** [comment]
For the record, and for the future. If you want to completely change your suggestion, just close the one you opened, and open another one.
