### ISSUE TITLE
[Effect Suggestion] Blaine County Community Hour

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1055]
**Name of effect**
Blaine County Radio Community Hour
Nervous Ron
BCRCH
Community Hour

**Duration if timed effect (long or short timed?)**
as long as "on-demand TV" so around 1 minute and 30 seconds

**Effect Description**
Plays Blaine County Radio Community Hour. This shouldn't cause any issues as this has no songs in it...

**Comment by Last0xygen** [comment]
I just checked the scripts, there's currently no string public on how to set this radio show

**Comment by pipecek** [comment]
> 
> 
> I just checked the scripts, there's currently no string public on how to set this radio show

aha. How hard is it to make a string for said radio station? If it's difficult then you can close this...

**Comment by Last0xygen** [comment]
it's pretty much "impossible", unless someone figures out all the stations

**Comment by pipecek** [comment]
> it's pretty much "impossible", unless someone figures out all the stations

And would it be possible to maybe play the dialogue in the background?

**Comment by Last0xygen** [comment]
No, sorry

**Comment by pipecek** [comment]
> No, sorry

Oh k
