### ISSUE TITLE
[Effect Suggestion] Improve 'First Person'

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1058]
**Effect Description**
'First person' could be improved by changing the camera during cutscenes to match that of the players face. Im assuming that changing the camera in cutscenes is possible.

**Comment by pipecek** [comment]
not possible...

**Comment by anto4440** [comment]
Aw, thats a shame.

**Comment by ProfessorBiddle** [comment]
it is actually possible, just requires some pretty complex math. https://www.gta5-mods.com/scripts/first-person-cutscenes
