### ISSUE TITLE
[Effect Suggestion] One Hit KO Revamped

### ISSUE THREAD

**Issue by ComradeCanOpener** [gta-chaos-mod/ChaosModV#1066]
**Name of effect**
Same as it is currently
"One Hit KO"

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
30 seconds
**Effect Description**
Description of the effect; what should it do?
One Hit KO as it is now however it disables Trevor's ability, making it this true to the title, as Trevor's special ability doesn't prevent the player from being hit.

**Comment by anto4440** [comment]
Isnt this already implemented?

**Comment by ComradeCanOpener** [comment]
No, watch the latest episode of DarkViper's chaos mod, unless he was using an out of date version of chaos mod. In that episode he uses Trevor's ability while one Hit KO is on and he doesn't die.
