### ISSUE TITLE
[Effect Suggestion] Spawn Angry Cougar

### ISSUE THREAD

**Issue by MAL345** [gta-chaos-mod/ChaosModV#1067]
**Name of effect**
Spawn Angry Cougar
Spawn Angry Cougars

**Effect Description**
Spawn one or more cougars that has more health (or normal health), and is aggressive.

**Comment by BillNyeTheRussianSpyV2** [comment]
The name should be Their aren't cougars in chaos

**Comment by Last0xygen** [comment]
Already requested ~6 times
Please use the search before requesting a new effect :)
https://github.com/gta-chaos-mod/ChaosModV/issues?q=Cougar
