### ISSUE TITLE
[Effect Suggestion] yee yee ass haircut 

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#1069]
**Name of effect**
Yee yee ass haircut 

**Effect Description**
Change the players haircut

**Comment by pipecek** [comment]
suggested before #381

**Comment by anto4440** [comment]
Yeah. #381

**Comment by FAR95d** [comment]
> Doesn't "change random outfit" already do that?

Where do i see if its suggested or not?

**Comment by anto4440** [comment]
you dont. Its something you start to remember after a long time being active here; which effects already have been submitted and whatnot. but dont feel bad about it, it happens to the best of us

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=stuff here. replace stuff with your search terms

**Comment by anto4440** [comment]
Yeah, but its rare that they have the exact same name/description

**Comment by Last0xygen** [comment]
Already implement into „randomize player clothes“
