### ISSUE TITLE
[Suggestion] Jesus Dont Take The Wheel

### ISSUE THREAD

**Issue by Ecko27** [gta-chaos-mod/ChaosModV#107]
I don't know if it's possible at all, but lets say imaginary jesus comes and takes one of your wheels.
I have no idea if it would be possible to take a wheel of a car/bike in gta.

**Comment by Last0xygen** [comment]
I don’t think there’s a way to entirely remove a wheel, just burst the tire.

**Comment by pongo1231** [comment]
Not sure if there's a native for removing wheels, if not would need to do something in game memory.

**Comment by JustTunerYT** [comment]
I remember, that they can be ejected, when you hit hard one of ped's car. I bet it's possible

**Comment by TheRealAyCe** [comment]
@Last0xygen It DOES seem to be possible to lose wheels! https://www.twitch.tv/videos/984800744?t=0h38m35s

**Comment by DEATHCON1** [comment]
A possible name for this effect could be 'The Goddamn Wheel Fell Off!'

**Comment by MoneyWasted** [comment]
Yes, you can remove wheels from vehicles. Though it only seems to be vehicles that were released with the game that can do this. Examples being the Adder, T20 and Gauntlet. As Pongo said maybe we can do this through memory for all vehicles somehow.
