### ISSUE TITLE
[Effect Suggestion] Pause

### ISSUE THREAD

**Issue by BillNyeTheRussianSpyV2** [gta-chaos-mod/ChaosModV#1072]
**Name of effect**
Pause

**Effect Description**
Pauses the Game

**Comment by anto4440** [comment]
Couldnt you just... unpause it?

**Comment by Aljotzi** [comment]
> Couldnt you just... unpause it?

Yeah. It doesn't seem like it would be a very big inconvenience

**Comment by ProfessorBiddle** [comment]
It would be a milder effect, could probably use some more of those. I'll see if this is possible.
