### ISSUE TITLE
[Effect Suggestion] Spawn Tug -> Spawn Evergreen

### ISSUE THREAD

**Issue by TA40** [gta-chaos-mod/ChaosModV#1073]
**Name of effect**
Spawn Evergreen

**Effect Description**
Rename the effect "Spawn Tug" to "Spawn Evergreen" and make the boat green.

**Comment by pipecek** [comment]
but why?

**Comment by TA40** [comment]
Just for giggles

**Comment by turg-the-sad-cat** [comment]
Can’t you just individually name it evergreen yourself?

**Comment by turg-the-sad-cat** [comment]
And if you want it a new effect, it’s too close to the other affect
