### ISSUE TITLE
[Effect Suggestion] Sun is a deadly laser

### ISSUE THREAD

**Issue by BillNyeTheRussianSpyV2** [gta-chaos-mod/ChaosModV#1076]
**Name of effect**
Sun is a deadly laser.

**Duration if timed effect (long or short timed?)**
Medium

**Effect Description**
When ever you outside (Not in a vehicle or building) you slowly take damage.

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/480
