### ISSUE TITLE
[Effect Suggestion] Spawn Companion Johnny

### ISSUE THREAD

**Issue by cheeto-0** [gta-chaos-mod/ChaosModV#1079]
Spawns Johnny Klebitz riding his white and blue Hexer motorcycle, he is friendly to the player and will let you ride on the back of his chopper, and if anyone attacks you he will defend you with his sawed off shotgun. Maybe he will drive to your waypoint like Jesus Take the Wheel if you are riding on the back of his chopper.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
