### ISSUE TITLE
[Effect Suggestion] Spawn Extreme Space Ranger

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#1088]
Spawns a Space Ranger with a Widowmaker

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/pull/890
was the first weapon choice but got reduced :)

**Comment by lZevex** [comment]
That's why I said Extreme Space Ranger. It's not like Griefer Jesus because you have a little bit more time to react and the shots are avoidable from cover, and the shots can't hit you in a vehicle from certain angles
