### ISSUE TITLE
[Effect Suggestion] Activate Special Ability

### ISSUE THREAD

**Issue by aimlessB** [gta-chaos-mod/ChaosModV#1089]
**Name of effect**
Permanent Trevors/Michaels/Franklins Special Ability ; ActivateTrevors/Michaels/Franklins Special Ability

**Duration if timed effect (long or short timed?)**
Medium

**Effect Description**
3 Different and seperate Effects, each one permanently activates either Michaels, Franklins or Trevors Special ability for the effect duration.

**Comment by anto4440** [comment]
Interesting

**Comment by Last0xygen** [comment]
Duplicate #927
