### ISSUE TITLE
Mercenaries still not aggressive enough

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#109]
You barely notice them. Can anything be done about it?

**Comment by TheRealAyCe** [comment]
@Last0xygen Pinging you

**Comment by Last0xygen** [comment]
@TheRealAyCe will look it, but open for suggestions. 
Maybe something like
`Object task;
OPEN_SEQUENCE_TASK(&task);
TASK_COMBAT_HATED_TARGETS_AROUND_PED(ped, 5000, 0);
TASK_VEHICLE_CHASE(ped, targetPed);
REGISTER_TARGET(ped, targetPed);
TASK_COMBAT_PED(ped, targetPed, 0, 16);
TASK_SHOOT_AT_ENTITY(ped, targetPed, 4000, firingPattern);
CLOSE_SEQUENCE_TASK(task);
TASK_PERFORM_SEQUENCE(ped, task); `

Or, I’ll have to spawn them even closer, which I would like to avoid as it „breaks the illusion“ or would just be too „spammy“

**Comment by TheRealAyCe** [comment]
@Last0xygen Maybe the targetting of the enemies in the chopper is too bad when the player is within the city due to buildings and such? Maybe the chopper needs a certain angle for effective fire?

How does it behave right now? Despawn and respawn the chopper when the player gets too far away?
