### ISSUE TITLE
[Feature Request] Online Chaos Mod 3.0 (FiveM)

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1091]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Basically a old school chaos mod, but it's online and everyone can join as a spectator (make them invisible not ghosted), 
**Describe alternatives you've considered**
Certain effect can trigger these players to f up matto like 
Give "Players" Assault Rifle (which disable the invisibility and gave everyone a assault rifle to kill matto)
Enable "Players" 
To avoid lags or crash, limit how many player will affected by the effects (like maximum of 16 players will be "unghosted") then for the next effect only 16 players that isn't affected 
**Additional context**
I can't explain it properly but you get the idea

**Comment by Aran8276** [comment]
Or only allow subs/patreon members that could join

**Comment by JustTunerYT** [comment]
OOB: Not "A old school", "AN old school"

**Comment by JustTunerYT** [comment]
Good idea, but then matt will have to make server everytime and i'm not sure, if he can. Unless it's a "ready server", that's active everytime. Also, i can add something to this feature suggestion.
MISSIONS: Every 2 minutes after each mission complete/fail, there will be a mission (such as RACE, DEATHMATCH, MISSION, WAVES). Ofc, players can decide, if they want to complete a mission or not. Rewards are decidable (they can, or can not be awarded)
ADMIN RIGHTS: Admins can edit timer duration, effect duration, effect appearence e.t.c. Ofc, host have to make someone admin (Host might be Matt) to make them able to edit chaos mod.
WELCOME SCREEN: Everytime player joins, if chaos mod is enable, players screen shows welcome screen (Contributors, players online, admins online e.t.c).

**Comment by TheRealAyCe** [comment]
I'm pretty sure an online version if this mod would be a completely different mod entirely.

**Comment by pongo1231** [comment]
Yep this is out of the scope of this mod and should be completely its own thing.
