### ISSUE TITLE
[Effect Suggestion] Spawn Angry Tryhard

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1093]
**Name of effect**
Spawn Angry Tryhard
Spawn Angry Wannabe Tryhard 
**Duration if timed effect (long or short timed?)**
Short
No timer
**Effect Description**
Wannabe: [Short] Constantly Spawn Hostile Tryhard Ped+Oppressor Mk2 every 2 seconds if the bike is not destroyed 
Tryhard: Spawn tryhard ped that attacks you with RPG

**Comment by anto4440** [comment]
Kinda like #1020

**Comment by aimlessB** [comment]
This was already suggested

**Comment by LordRygar** [comment]
It's also stupid and I don't want it anywhere near my game.

**Comment by ProfessorBiddle** [comment]
> It's also stupid
>
please post constructive feedback rather than impertinent statements

>

**Comment by LordRygar** [comment]
> It's also stupid
> please post constructive feedback rather than impertinent statements
> […](#)

Certainly.  The Mod "Suicide" already exists and there is no need for this.  This is just a more harassing way to do the Suicide mod, and I'd rather just die outright.

**Comment by aimlessB** [comment]
> > It's also stupid
> > please post constructive feedback rather than impertinent statements
> > […](#)
> 
> Certainly. The Mod "Suicide" already exists and there is no need for this. This is just a more harassing way to do the Suicide mod, and I'd rather just die outright.

I think its better the way it is in #1020 , where it works just like Spawn Griefer Jesus. If you constantly keep Spawning Enemies, its nothing but annoying.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
