### ISSUE TITLE
[Effect Suggestion] Turn player into Jesus

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1095]
**Name of effect**
Turn player into Jesus

**Duration if timed effect (long or short timed?)**
3 minutes

**Effect Description**
Turns player's character model into the model of Jesus.

I edited this because I realized it could break a few effects.

**Comment by drunderscore** [comment]
Unfortunately changing the player model will break a lot of things, especially when it's not one of the story mode characters. A big problem being not being able to start missions, no text messages/phone calls for any character, etc.

**Comment by Last0xygen** [comment]
agreed, changing the player-model creates many problems
