### ISSUE TITLE
[Effect Suggestion] Spawn Random Supercar

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1098]
**Name of effect**
Spawn Random Supercar

**Duration if timed effect (long or short timed?)**

**Effect Description**
Spawn random vehicle in Supercar Class

**Comment by lZevex** [comment]
There are 3 effects that can spawn DLC vehicles, no need to add this in

**Comment by Last0xygen** [comment]
Already exists as "Spawn Random Vehicle"
