### ISSUE TITLE
Chaos Mod Effect Suggestions

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#11]
Effect Suggestions:
Remove money
Hello? (Telephone Up)
No Brakes
Weapon Lock
Peaceful World (No attacking peds/No weapons/No wanted level)
Rick Rolled (Never Gonna Give You Up Song)

**Comment by pongo1231** [comment]
Please separate each suggestion into its own issue so keeping track of every suggestion is easier. Thank you.
