### ISSUE TITLE
[Effect Suggestion] Car Guns

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1100]
**Name of effect**
Yo I got a modded gun

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Basically catto guns, but it shoots Dilettante/Random Cars instead of cats

**Comment by Last0xygen** [comment]
Already in progress https://github.com/gta-chaos-mod/ChaosModV/pull/1065
