### ISSUE TITLE
[Effect Suggestion] The cruelest 'improvement' you will ever read

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1104]
**Effect Description**
'Improve' DVD screensaver by making it so its always milliseconds from hitting the corner when it ends.

**Comment by Last0xygen** [comment]
Not possible, as in the effect you have no idea how long the effect lasts

**Comment by anto4440** [comment]
so?

**Comment by Last0xygen** [comment]
> so?

So you don’t know when it’s gonna End?

**Comment by anto4440** [comment]
...no. Why is that important?

**Comment by Last0xygen** [comment]
Because that’s what you wrote in your request?
„... its always milliseconds from hitting the corner when it ends.“

**Comment by Last0xygen** [comment]
Yes? The effect doesn’t know when it’s gonna End, we can’t check if we should go close to the corner and so on.

**Comment by turg-the-sad-cat** [comment]
Exactly, someone might have the effect for 15 or 30 seconds

**Comment by anto4440** [comment]
oh, now i see; i thought it worked a bit differently. I thought that you could simply make it so that i starts in a cornor, and then work backwards from there.
