### ISSUE TITLE
[Effect Suggestion] This isn't Minecraft!?

### ISSUE THREAD

**Issue by nicksours-design** [gta-chaos-mod/ChaosModV#1105]
**Name of effect**
Potential name(s) for the effect
 This isn't minecraft!?

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
 1 minute

**Effect Description**
Description of the effect; what should it do?
 turn the entire los Santos and san andreas map into a minecraft version of the world and all characters will become minecraft versions of themselves

**Comment by nicksours-design** [comment]
> Not even possible

ive seen 1:1 scales of los santos in minecraft they could use that and im sure its not that hard to find or create skins, not saying i can do it but if someone is skilled enough they could

**Comment by Last0xygen** [comment]
Yes, but that is out of the scope for this mod. The profit would be a fraction of the time spent to develop, design and Code this effect.
Also: changing the player model and/or world is either prone to crash or not possible

**Comment by turg-the-sad-cat** [comment]
I know this is closed but I just want to bring this up, I searched it up and there has been nothing of turning gta 5 into Minecraft, all I’ve seen is turning Minecraft into gta
