### ISSUE TITLE
[Effect Suggestion] HALO jump

### ISSUE THREAD

**Issue by mmmoo123** [gta-chaos-mod/ChaosModV#1106]
**Name of effect**
HALO jump

**Effect Description**
Cargo plane gets spawn high in the air and player is teleported inside the cargo room and has to run and jump out of it like in the mission Minor Turbulence.

**Comment by Last0xygen** [comment]
already exists as "Teleport To Heaven", but without the "running out the cargo room. This could result in instant death if the player is driving a vehicle thats too big
