### ISSUE TITLE
[Feature Suggestion] Under the seeeaaa

### ISSUE THREAD

**Issue by Reaper1357531** [gta-chaos-mod/ChaosModV#1107]
**Is your feature request related to a problem? Please describe.**
Nope, just making a new one

**Describe the solution you'd like**
When this effect is applied, you are teleported to the lowest possible (or furthest possible) depth away from land, hence the "under the sea" part. The player is given oxygen breathing apparatus when this effect takes place, so they can't just win with the sweet release of death. nah, they gotta swim ALLLLLLLL the way back up (or die to a shark lmao).
**Describe alternatives you've considered**
maybe make it so they spawn in a sub if diving equipment can't do, or hell, just let em drown if that suits.

**Additional context**
Nothing to add here

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/266, #633, #603 and so on 😅

**Comment by Reaper1357531** [comment]
> Same as #266, #633, #603 and so on 😅

Blast, I thought I had checked them all
