### ISSUE TITLE
[Effect Suggestion] Meta Effect - Player's Choice

### ISSUE THREAD

**Issue by Wikitorix** [gta-chaos-mod/ChaosModV#1109]
**Name of effect**
Player's Choice

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
While in effect, when the timer fills completely, the next three (or four or five or whatever) inputs determine the effect, so that for example, pressing W, space, left-click will teleport the player a few meters, or W, S, F will put the player into a random vehicle

**Comment by Last0xygen** [comment]
and who would create such a list of combinations of all effects and all coming future effects?
this would not be anything a player would understand once the effect starts
