### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by Paralied** [gta-chaos-mod/ChaosModV#1110]
Greifer Jesus but He is in a TM-02 KhanJali or A Rhino Tank

**Comment by lZevex** [comment]
"Spawn Extreme Griefer Jesus" (Spawns Jesus on a MK2) exists, and he's hard enough to kill already, a tank would just mean a deathloop

**Comment by TheRealAyCe** [comment]
Please put the effect name in the ticket title

**Comment by Last0xygen** [comment]
he already has a MK2, no need for a tank :D
