### ISSUE TITLE
[Effect Suggestion] Spawn random online vehicle

### ISSUE THREAD

**Issue by wojtekpolska** [gta-chaos-mod/ChaosModV#1111]
**Name of effect**
"Spaw Random Online Vehicle" "Is this GTA:Online ?"

**Effect Description**
Will spawn a random vehicle (can be restricted to only cars, to avoid spawning planes/helis/boats too often) from GTA:Online in front the player, *or* in the player (they will automatically be placed in the driver seat)

**Comment by lZevex** [comment]
Already exists with "Replace current Vehicle", "Random Traffic", and "Vehicle Rain", all of which can spawn DLC vehicles

**Comment by wojtekpolska** [comment]
> Already exists with "Replace current Vehicle", "Random Traffic", and "Vehicle Rain", all of which can spawn DLC vehicles

i think it'd still be good idea, you rarely see online vehicles in chaos mod anyway

**Comment by lZevex** [comment]
Just found the effect already exists, couldn't remember if it was a thing or not

**Comment by Last0xygen** [comment]
Also „spawn random vehicle“ exists.
The thing with online vehicles is that they may despawn because of R*s „protection“ to spawn online vehicles in single player.
As we don’t have a fix for that and already have a spawn effect for it  I don’t see a need for this request
