### ISSUE TITLE
[Effect Suggestion] Halloween Weather

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1113]
**Name of effect**
Halloween Weather
Spoopy Weather

**Duration if timed effect (long or short timed?)**
1 minute 45 seconds

**Effect Description**
It makes the weather the Halloween weather, below is a screenshot with what I'M talking about.
![Snímek obrazovky 2021-04-21 140157](https://user-images.githubusercontent.com/80320765/115550450-298a4680-a2aa-11eb-90e8-3dbea3b1077a.png)

**Comment by Last0xygen** [comment]
This already exists. this is "Neutral Weather" at a specific time, which sadly only affects the northern part of the map (see here: https://wiki.gtanet.work/index.php?title=Weather)
