### ISSUE TITLE
[Effect Suggestion] Animal Planet

### ISSUE THREAD

**Issue by noahr03** [gta-chaos-mod/ChaosModV#1115]
**Name of effect**
Animal Planet

**Duration if timed effect (long or short timed?)**
30 seconds 

**Effect Description**
Morphs the player (possibly NPCs as well) into a random animal, similar to the GTA Creator mode.

**Comment by Last0xygen** [comment]
Already requested several times
https://github.com/gta-chaos-mod/ChaosModV/issues/797
