### ISSUE TITLE
Do Every Effect.. Yes

### ISSUE THREAD

**Issue by BitGhostYT** [gta-chaos-mod/ChaosModV#1120]
**Name of effect**
Every Effect
Game Crash

**Effect Description**
This Will Do Every Single Effect In The Mod, Essentially a way to crash the game

**Comment by aimlessB** [comment]
Isn't it dumb to intentionally crash the game? It would be nothing but annoying for the player.

**Comment by Last0xygen** [comment]
Crashing the game on purpose? No thank you
