### ISSUE TITLE
[Effect Suggestion] Randomise Player & Peds

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1121]
**Name of effect**
Randomise Player & Peds

**Effect Description**
Changes the model of the player and all peds to a random model.

**Comment by pipecek** [comment]
Won't work,check #1095 for reason

**Comment by Last0xygen** [comment]
Yup, duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1095
