### ISSUE TITLE
[Bug] Vehicles shoot rockets doesn't work

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#1123]
https://www.twitch.tv/videos/996119892  ~1:03:00

It doesn't seem to work.

**Comment by Last0xygen** [comment]
Just tested, working fine for me 🤷‍♂️

**Comment by TheRealAyCe** [comment]
Any idea why it didn't work in that case?

**Comment by Last0xygen** [comment]
Well its working for him at https://www.twitch.tv/videos/996119892?t=1h34m1s 🤷‍♂️

**Comment by TheRealAyCe** [comment]
Yeah, strange...

**Comment by Last0xygen** [comment]
i'll close this. if it comes up again, we can look at it again :)
