### ISSUE TITLE
[Effect Suggestion] Did someone say yoga?

### ISSUE THREAD

**Issue by BaronVonDelta** [gta-chaos-mod/ChaosModV#1127]
**Name of effect**
Did someone say yoga?

**Duration if timed effect (long or short timed?)**
Short term, probably just one specific yoga move

**Effect Description**
Have you stop and do the yoga minigame

**Comment by Da-Best** [comment]
similar to #648

**Comment by Last0xygen** [comment]
Blocking the player from playing the game without any "fun" reason like the hacking minigame is not suitable right now
