### ISSUE TITLE
[Effect Suggestion] Merriweather fleets here bro

### ISSUE THREAD

**Issue by KillerCatLion** [gta-chaos-mod/ChaosModV#1132]
**Name of effect**
Merriweather fleets here bro

**Effect Duration**
Long

**Effect Description**
Change the "Mercenaries" effect name to "Merriweather fleets here bro" and play Trevor's line from Derailed when Trevor alerts Micheal of Merriweather's presence. 

Sort of an Easter egg from DarkViperAU's OHKO because he spent hours trying to complete Derailed and he listened to Trevor say Merriweather fleets here bro hundreds of times.

(small detail) maybe fake crash could minimize the game to make it look more realistic

**Comment by Last0xygen** [comment]
Already requested several times 😅
See discussion here for more info
https://github.com/gta-chaos-mod/ChaosModV/issues/61#issuecomment-668251263
