### ISSUE TITLE
[Effect Suggestion] Mirror the screen

### ISSUE THREAD

**Issue by Riffcat** [gta-chaos-mod/ChaosModV#1138]
Mirror screen; Am I looking through a mirror?; Is this what a mirror sees?; take a look in the mirror.

long

It should mirror the screen so it looks like you're watching through a mirror and all the controls mirror with it so it is still easy to play, it would especially screw with Matt's mind considering he is so used to the world, kinda like in this video: https://www.youtube.com/watch?v=DyYzrWsmYIw. 

![mirrored](https://user-images.githubusercontent.com/59796110/115914202-f0043780-a471-11eb-996b-285647259503.png)

**Comment by Da-Best** [comment]
similar to #762

**Comment by Riffcat** [comment]
> similar to #762

sorry
