### ISSUE TITLE
[Effect Suggestion] Raging Alien

### ISSUE THREAD

**Issue by AbRayy** [gta-chaos-mod/ChaosModV#1140]
**Name of effect**
Raging Alien

**Effect Description**
Spawn an alien with a lazer minigun

**Comment by turg-the-sad-cat** [comment]
I think it’s just too close to the other alien affect

**Comment by AbRayy** [comment]
Imo this is better bc of the gun

**Comment by Last0xygen** [comment]
Already exists with the space ranger
