### ISSUE TITLE
[Effect Suggestion] DLC common cars

### ISSUE THREAD

**Issue by AbRayy** [gta-chaos-mod/ChaosModV#1141]
**Name of effect**
Gotta go fast/spawn itali gto
Tesla tank/soawn khanjali
Spawn Chad opressor/spawn opressor
Spawn virgin mosquito/spawn opressor mk2
Spawn anti griefer van/spawn nightshark
Spawn fun truck/spawn phantom wedge

**Effect Description**
Spawn those common online cars, that can be useful in a chaos run for various reasons

**Comment by JustTunerYT** [comment]
About "Virgin mosquito". Two effects are replacing this. These are "You're a wizard, Franklin" and "Spawn Extreme Griefer Jesus". They both spawn Oppressor MK2

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
