### ISSUE TITLE
[Effect Suggestion] Familiar Faces

### ISSUE THREAD

**Issue by Enderneer** [gta-chaos-mod/ChaosModV#1144]
**Name of effect**
Familiar Faces

**Duration if timed effect (long or short timed?)**
Medium. Around 30 seconds.

**Effect Description**
Every NPC that is loaded into the map, or is already spawned in, is replaced with a randomly selected ped model. This will make it so every person looks the same. The only peds that are excluded from this effect are allies, and of course the player.

**Comment by Last0xygen** [comment]
Replacing Peds is not something this mod supports as it could lead to easy softlocks
