### ISSUE TITLE
[Effect Suggestion] Pavel wants you to play a Russian sport with him.

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1148]
**Name of effect**
Very Good Sport In Russia, Kapitan!
Try And Shoot Me Down, Kapitan!
Play My Sport With Me, Kapitan!

**Effect Description**
Spawns Pavel on an Oppressor MkII attacking you.

**Comment by pipecek** [comment]
So basically like Extreme griefer jesus with just a different character model... DUPLICATE

**Comment by Last0xygen** [comment]
Too similar to „Spawn griefer Jesus“
