### ISSUE TITLE
[Effect Suggestion] Spawn Clifford's Mercenaries

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1150]
**Name of effect**
Spawn Clifford's Mercenaries

**Duration if timed effect (long or short timed?)**
Instantaneous

**Effect Description**
It spawns Clifford's Mercenaries that attack the player. They spawn in a Barrage because I think the Khanjali would be way too op...

**Comment by Last0xygen** [comment]
already exists as "Mercenaries" 😅

**Comment by pipecek** [comment]
> already exists as "Mercenaries" 😅

Aha, didn't realize it actually spawned them in a vehicle
