### ISSUE TITLE
[Effect Suggestion] Spawn Companion John Marston

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1152]
**Name of effect**
Spawn Companion John Marston

**Effect Description**
Spawns John Marston as a Companion with his voice lines from RDR2, if possible and a Double-Action Revolver equppied.

**Comment by pipecek** [comment]
There isn't a model of John Marston in GTA V.

**Comment by DEATHCON1** [comment]
There is, the ped model name is Martson01 and the hash number is 943915367. Someone just has to complete the model though.

**Comment by Last0xygen** [comment]
> There is, the ped model name is Martson01 and the hash number is 943915367. Someone just has to complete the model though.

And how is that gonna work? 😅

**Comment by Thunderstorm64** [comment]
> > There is, the ped model name is Martson01 and the hash number is 943915367. Someone just has to complete the model though.
> 
> And how is that gonna work? 😅

Just Break all known coding laws.

**Comment by Da-Best** [comment]
the model has no feet and arms as it is the module from gtao iirc

**Comment by Last0xygen** [comment]
yeah, this will not happen then :D
