### ISSUE TITLE
[Effect Suggestion] I'm A Millionaire!

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1156]
**Name of effect**
I'm A Millionaire!
Millionaire
Miilion Dollar Look

**Effect Description**
Gives the player $1 million and a random suit. Also applies gold paint and chrome Dollar Sign rims to the current vehicle.

**Comment by Numi43** [comment]
I wonder if GTA Online outfit can be applied to GTA V characters or it is locked.

**Comment by lZevex** [comment]
> I wonder if GTA Online outfit can be applied to GTA V characters or it is locked.

From what i've heard modifying character models has the potential to break the game, especially if you try to use them in missions

**Comment by lZevex** [comment]
HESOYAM already exists (Gives full health, armor and 250k), adding this would be kind of useless

**Comment by Last0xygen** [comment]
This is a combination of HESOYAM and "Midas"
