### ISSUE TITLE
[Effect Suggestion] Everyone Roastes You

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1159]
**Name of effect**
Everyone Roastes you

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
All nearby peds surrounds the player and insults them.

**Comment by turg-the-sad-cat** [comment]
I’m pretty sure that’s already a thing

**Comment by Numi43** [comment]
= Unfriendly Neighborhood

**Comment by Last0xygen** [comment]
Mix of „you’re famous“ and „unfriendly neighborhood“
