### ISSUE TITLE
[Effect Suggestion] Triggerbot

### ISSUE THREAD

**Issue by xx3roxx** [gta-chaos-mod/ChaosModV#1165]
**Name of effect**
Triggerbot

**Duration if timed effect (long or short timed?)**
Long timed

**Effect Description**
Gives triggerbot to the player

**Comment by anto4440** [comment]
i do believe there is alredy some sort of aimbot effect.

**Comment by Last0xygen** [comment]
Yup, there is an „Aimbot“ effect already. I don’t see any reason to have an additional triggerbot

**Comment by lZevex** [comment]
Triggerbot means you need to aim at your target to hit it rather than auto hitting enemies no matter where they are or where your gun is aiming, it adds some extra effort in

**Comment by Last0xygen** [comment]
I do know what a triggerbot is, but I still don’t see any advantage over the „Aimbot“ effect. If anything the Aimbot effect is even more chaotic 😊

**Comment by lZevex** [comment]
It's not meant to be an advantage, you have to aim at your targets instead of the game aiming for you

**Comment by anto4440** [comment]
So?

**Comment by lZevex** [comment]
So it takes longer to kill enemies? And it's a downgrade from kicking your feet up doing nothing?

**Comment by anto4440** [comment]
Well, i would say yes... i would prefer an aimbot over a trigggerbot, and the same thing applies to this mod.
