### ISSUE TITLE
[Effect Suggestion] T-Posing Player & Peds

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1170]
**Name of effect**
Gmod Prop Hunt
Please Add Animations!
No Animations

**Duration if timed effect (long or short timed?)**
Long-timed

**Effect Description**
Everyone T-Poses with no other animations. For walking, running, jumping, climbing, swimming, parachuting, game triggers, cutscenes, getting in and out of vehicles, sitting in vehicles, falling, ragdolling, etc.

**Comment by Thunderstorm64** [comment]
That would seriously break the game.

**Comment by Last0xygen** [comment]
T-posing nearby peds already exists with „low render distance“
