### ISSUE TITLE
[Feature Suggestion] Improvements to Fake Death

### ISSUE THREAD

**Issue by dumbdumb89** [gta-chaos-mod/ChaosModV#1175]
**Is your feature request related to a problem? Please describe.**
Fake Death needs to be improved

**Describe the solution you'd like**
Whenever you are on foot, the message on the right side of the screen should say "Suicide" until the death message appears and it changes to "Fake Death", if the player is in a vehicle it should say "Explode Current Vehicle" until the death message appears and then the message turns to "Fake Death"

**Comment by Last0xygen** [comment]
Already being worked on 
https://github.com/gta-chaos-mod/ChaosModV/pull/325
