### ISSUE TITLE
[Effect Suggestion] The Goddamn Wheel Fell Off!

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1184]
**Name of effect**
The Goddamn wheel fell off!

**Effect Description**
The player's last used or currently used vehicle has a random wheel fall off.

**Comment by anto4440** [comment]
#407

**Comment by anto4440** [comment]
no, wait

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/107
duplicate
