### ISSUE TITLE
[Effect Suggestion] Spawn Joking Jesus

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1185]
**Name of effect**
Spawn Joking Jesus
Spawn Friendly Jesus

**Effect Description**
When this effect activates, the mod doesn't tell you it has activated on the right side of the screen until 5 seconds later. While five seconds is counting down, it Spawns Griefer Jesus that looks like he's about to shoot you but doesn't. After the 5 seconds is up, he puts his gun down and does nothing, then the mod prompts you on the right side of the screen that it was a Friendly Jesus.

**Comment by SteamyNinja** [comment]
Haha, I like this one. I could already see real jesus being spawned, Matt saying "Nah it's a fake" then getting blown to shreds.

**Comment by NotGrieferJesus** [comment]
> Haha, I like this one. I could already see real jesus being spawned, Matt saying "Nah it's a fake" then getting blown to shreds.

Matt is not only playing this other streamers too.

**Comment by Last0xygen** [comment]
„Fake Jesus“ and „friendly Jesus“ we’re already requested
