### ISSUE TITLE
[Effect Suggestion] Jimmy Astley/Rick De Santa

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#1186]
**Name of effect**
Jimmy Astley
Rick De Santa

**Effect Description**
Spawns Jimmy that dances like Rick Astley in 'Never gonna give you up'.

**Comment by Last0xygen** [comment]
There is no animation like that in gta 5

**Comment by DEATHCON1** [comment]
Wait 'In The Hood', that dance exists in the game?

**Comment by Last0xygen** [comment]
Yes
