### ISSUE TITLE
[Effect Suggestion] Firework guns

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#1189]
**Name of effect**
Firework guns

**Duration if timed effect (long or short timed?)**
20 seconds

**Effect Description**
Makes fireworks come out of you guns, I tried this on my potato PC and it didn't crash GTA V

**Comment by anto4440** [comment]
#1025

**Comment by anto4440** [comment]
this is a bloody dupe of your own suggestion

**Comment by pipecek** [comment]
frick
I forgot about it lmfao

**Comment by anto4440** [comment]
Lmao
