### ISSUE TITLE
[Effect Suggestion] Simeon says

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1192]
**Effect Description**
Improve semion says by also making false orders without semion says in front of them. sorry of this is a dupe :(

**Comment by TheRealAyCe** [comment]
You mean _without_ Simeon says, right? So the order is only to be executed when it's prefixed with "Simeon says" and to be explicitly ignored (or rather, inverted?) when there is no such prefix?

**Comment by anto4440** [comment]
yah, right, of course. by bad lol
