### ISSUE TITLE
Effect Suggestion

### ISSUE THREAD

**Issue by CallMeOOF** [gta-chaos-mod/ChaosModV#1195]
Pilot bros

it's like "bus bois" and "scooter brothers" except it puts everyone in a random plane
Planes that will not spawn: Avenger (Yes, that counts as a plane), Titan, Hydra (Oppressor isn't a plane, but no, it will not spawn either)

**Comment by TheRealAyCe** [comment]
Maybe "Pilot Pals" for the alliteration?

**Comment by CallMeOOF** [comment]
Can you explain me what „Alliteration“ means lol, I forgot what it means

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pipecek** [comment]
USE THE CORRECT FORMAT!
