### ISSUE TITLE
[Effect Suggestion] Ghost Town

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#1198]
Merge Invisible Vehicles and Everyone is a Ghost into one effect

**Comment by TheRealAyCe** [comment]
Wasn't that "Where did everything go?"?

**Comment by Da-Best** [comment]
i would think that is no traffic

**Comment by Last0xygen** [comment]
There are already effects doing this, like those mentioned by other people here.

**Comment by lZevex** [comment]
Those 2 effects on their own don't do much. I just thought it would be more annoying if the 2 effects were merged into one. "Where did everything go?" means you can see literally nothing, "No traffic" means there's no vehicles spawning. With this effect there are vehicles spawning and being used but you're completely having to guess where they are
