### ISSUE TITLE
[Effect Suggestion] Car Leaks, out of gas.

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#1200]
**Name of effect**
Potential name(s) for the effect

Car Leaks!
Leaking car!
Need gas!
Out of gas!

**Effect Description**
Description of the effect; what should it do?

When applied, make it so the car slowly leaks it's gas/petrol. Just like when you shoot the fuel area of a car, and drives it.
(It's a one time thing, therefor no timer)

**Comment by lZevex** [comment]
Too similar to oil trails

**Comment by TheRealAyCe** [comment]
But maybe such an effect could be added to Oil Trails?

**Comment by lZevex** [comment]
As far as I know leaks don't affect vehicle performance, or at least not by much

**Comment by Last0xygen** [comment]
Already exists as „oil trails“

**Comment by KatieDeForest** [comment]
Idk how gas and oil are the same, but fair enough.
Oil is just a funny gag, while a car, not being able to get driven because the lack of gas, would be an annoyance, which was kind of more my idea.

**Comment by Last0xygen** [comment]
„Oil trails“ is not oil but petrol ;) 
That’s why it catches fire if it gets shot.
Slowly „dying“ already exists too with „kill engine of every vehicle“

**Comment by KatieDeForest** [comment]
Omg, I'm dumb, yup, never shot the oil trails in gta. Fair enough, give sense.
