### ISSUE TITLE
**We in Minecraft now**

### ISSUE THREAD

**Issue by SekySmirfBoi** [gta-chaos-mod/ChaosModV#1203]
**Name of effect**
We in Minecraft now
Notch is a programmer
Microsoft owns GTA 5

**Effect Description**
It is like low render distance but every thing is turned into cubes instead of the shapes in low render distance

**Comment by turg-the-sad-cat** [comment]
Too similar to low render distance

**Comment by Last0xygen** [comment]
Can’t really be done, low render distance is the closest we can get right now ^^
