### ISSUE TITLE
What is reality? (META)

### ISSUE THREAD

**Issue by ImCook1e** [gta-chaos-mod/ChaosModV#1205]
Multiple effects are shown but only 1 is really active. Or perhaps the active effect even switches between the ones shown to the player.

**Comment by Last0xygen** [comment]
So, "Whats Happening?" but faking names?

**Comment by ImCook1e** [comment]
> So, "Whats Happening?" but faking names?

Yep but only 1 is really happening and the rest is just the name to throw the player off

**Comment by Last0xygen** [comment]
Huh, i don't know... this seems like much work for little payout, as its basically the """same""" as "Whats Happening" (obfuscating what's really going on)
also this would require faking several effects, even with durations :|
