### ISSUE TITLE
[Effect Suggestion] BOSSFIGHT

### ISSUE THREAD

**Issue by itshenchman** [gta-chaos-mod/ChaosModV#1206]
**Name of effect**
Boss Fight

**Duration if timed effect (long or short timed?)**
until finished 

**Effect Description**
Starts a boss fight between player and a random npc or the chaos villains angry alien, jesus, impotent rage, jimmy etc... you get teleported to a arena and you have to beat the enemy npc in a fist fight.

**Comment by lZevex** [comment]
This would just cause a permanent deathloop as every enemy except for impotent rage has a weapon, and even so would be a pointless effect

**Comment by itshenchman** [comment]
i said fist fight not weapon fight. also it would be a one time thing so if it’s in a mission and you fail it it won’t happen again

**Comment by lZevex** [comment]
Even then, still useless, they're easy to kill, would just be a 12 second fight every time.

**Comment by itshenchman** [comment]
Idk thought it would be pretty interesting

**Comment by Last0xygen** [comment]
> Idk thought it would be pretty interesting

Interesting idea, but I don’t see any „advantages“ over the „normal“ spawns of Jesus, alien and so on. The additional teleport is just another hurdle an/or instant fail potential
