### ISSUE TITLE
[Effect Suggestion] You dense mother****er!

### ISSUE THREAD

**Issue by BBNCYT** [gta-chaos-mod/ChaosModV#1207]
**Name of effect**
Potential name(s) for the effect
Dense Mother****er 
Disingenuous Dense Mother ****er 
YOU COULDN’T TIE YOUR SHOES!

**Effect Description**
Description of the effect; what should it do?
One time it would play DarkViperAu screaming “You disingenuous dense mother****er, OBVIOUSLY YOU HAVE TO KNOW SOMETHING ABOUT SOMETHING OR YOU COULDN’T TIE YOUR SHOES!!!”

**Comment by turg-the-sad-cat** [comment]
1. I don’t think you can add audio clips in the files and 2. Most people would never understand the reference

**Comment by ProfessorBiddle** [comment]
this mod isn't just for Matt, so this probably isn't a good idea.

**Comment by turg-the-sad-cat** [comment]
Especially with a mod that has the effects sometimes repeated a couple times, that will get annoying

**Comment by lZevex** [comment]
> this mod isn't just for Matt, so this probably isn't a good idea.

Oh i'm sure most people know who Matt is

**Comment by Last0xygen** [comment]
This mod is not only for matto ;)
You can set any sound you want for any effect :)
This won’t be set by default
