### ISSUE TITLE
[Effect Suggestion]  Meta effect - OG Chaos

### ISSUE THREAD

**Issue by Slothboi42** [gta-chaos-mod/ChaosModV#1208]
**Name of effect**
OG Chaos

**Duration if timed effect (long or short timed?)** Long 

**Effect Description**
The effect would remove the voting mechanic for a portion of time making the effects completely random like the original chaos mod

**Comment by Da-Best** [comment]
how will this work for people who don't do twitch chaos. chaos isn't just a mod for twitch streams it also has a non twitch community so this wont work for them

**Comment by Last0xygen** [comment]
> how will this work for people who don't do twitch chaos. chaos isn't just a mod for twitch streams it also has a non twitch community so this wont work for them

Yes. Also random effects will already be chosen if a meta effect like „combo Time“ or „5x timer speed“ gets chosen (as they can’t possibly choose that fast 😅)
