### ISSUE TITLE
Deep Fried does not reactivate when you die while it's active

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#121]
Shouldn't it reapply the effect after you respawned?

**Comment by Last0xygen** [comment]
Checked it. It seems to reduce the effect after respawning but couldn't find a reliable combination to "reactivate" it the way it was

**Comment by pongo1231** [comment]
It does constantly apply the effect but the timecyc modifier used by the effect is only really noticeable during daytime which is being set once the effect activates but not any time afterwards. Forcing time to be daytime on tick could be an option though there are certain missions where daytime will cause a mission fail which would cause a fail loop for 90 seconds.
