### ISSUE TITLE
[Effect Suggestion] Hunter Griefer Jesus

### ISSUE THREAD

**Issue by TitanY0MaMa** [gta-chaos-mod/ChaosModV#1210]
**Name of effect**
Spawn Hunter Griefer Jesus

**Effect Description**
Spawns Griefer Jesus Holding a Railgun with a little less health and a new feature that enables him to track the player down.

When selected, Hunter Griefer Jesus does not spawn in the immediate vicinity of the player, rather a little further away.     

The player might then believe that nothing happened, only to get obliterated minutes later. 

Hunter Griefer Jesus can swim or teleport nearby the player, however he IS killable and either one punch or one shot to the head would finish him.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
