### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Nghtmxre** [gta-chaos-mod/ChaosModV#1225]
**Name of effect**
Potential name(s) “Last Man on Earth”

**Effect Description**
Description of the effect; It should wipe all of the NPCS and cars completely everything including mission NPCS.

**Comment by MoonMan21** [comment]
Thats basically "no traffic"

**Comment by Nghtmxre** [comment]
I mean like absolutely no npc or traffic across the whole map including mission npcs.

**Comment by lZevex** [comment]
No traffic already exists, removing regular peds won't do anything and deleting mission peds will just cause a softlock

**Comment by Last0xygen** [comment]
This is basically no traffic including peds. 
mission entities will „always“ be excluded from those effects as they’re either deathloops or softlocks.

**Comment by Nghtmxre** [comment]
It is ment to be a softlock

**Comment by turg-the-sad-cat** [comment]
No one likes intentional softlocks
