### ISSUE TITLE
[Effect Suggestion] Spawn Balla Gang

### ISSUE THREAD

**Issue by WhyNotArmor** [gta-chaos-mod/ChaosModV#1226]
**Name of effect**
Spawn Balla Gang

**Effect Description**
Spawns either 10-20 enemy Ballas with Guns (maybe some with cars) around the player.

**Comment by Nghtmxre** [comment]
Gg.

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Effects/db/Peds/PedsSpawnBallaSquad.cpp

**Comment by Last0xygen** [comment]
Generally, spawning 10-20 Peds should be avoided, it’s just not a good effect. If you struggle with 3 enemies already having 10 does not increase the „fun“
Spawning a balla squad in a car ist already an effect, so I don’t see this as a Good Addition to the mod, sorry
