### ISSUE TITLE
[Effect Suggestion] I forgot my sunglasses!

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#1228]
**Name of effect**
Potential name(s) for the effect

Forgot my sunglasses.
Broken sunglasses.
Blinded by the light.
Extreme light

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

Short

**Effect Description**
Description of the effect; what should it do?

Make it so the sun is extremely bright, but only the sun.
So not the whole screen like the other effects.
Meaning if you are under cover and stuff like that, It's fine, but if you look at it you get blinded.
Okay just walk outside and look at the sun, then you'll get the idea.

**Comment by Last0xygen** [comment]
Too similar to „Deep Fried“
