### ISSUE TITLE
[Effect Suggestion] Jesus take the car

### ISSUE THREAD

**Issue by ato-gamecat** [gta-chaos-mod/ChaosModV#1232]
**Name of effect**
Potential name(s) for the effect
Jesus take the car
Jesus the repo guy

**Effect Description**
Description of the effect; what should it do?
You will be kicked out of the car and Jesus will try to take the car away from you.

**Comment by lZevex** [comment]
Jesus take the Wheel already exists

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
Also, we already have "Jesus Take the Wheel"
