### ISSUE TITLE
[Effect Suggestion] Changes to Fake Death

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#1234]
With Explode Current Vehicle not being an effect anymore, some people may catch on that it's fake if their vehicle explodes instantly. What you could do is add a chance to lock the current vehicle when Detonate Current Vehicle is activated and make a fake version of this for fake death so it's more convincing

**Comment by TheRealAyCe** [comment]
There are still other effects the explode it

**Comment by lZevex** [comment]
No, there are now no effects that instantly explode your vehicle upon activation. People are going to notice this and they'll always know it's fake

**Comment by TheRealAyCe** [comment]
Obliterate nearby peds with passengers?

**Comment by lZevex** [comment]
It only obliterates peds, there won't always be peds in the vehicle and it even plays the orbital sound effect

**Comment by kolyaventuri** [comment]
This has been resolved with recent updates to Fake Death, as it now emulates detonate current vehicle
