### ISSUE TITLE
Meta effect: all 4 effects are named "Random effect"

### ISSUE THREAD

**Issue by 810CK-A1D** [gta-chaos-mod/ChaosModV#1236]
**Name of effect**
Random four
**Duration if timed effect (long or short timed?)**
long timed, 3 periods

**Effect Description**
basically all 4 options are named random, so chat doesnt know what they are voting for

**Comment by TheRealAyCe** [comment]
Maybe the names flicker a bit?

**Comment by Da-Best** [comment]
how will this effect work on people who don't play twitch plays so this meta wont do anything then.

**Comment by Last0xygen** [comment]
This doesn’t impact everyone playing without twitch and also kind of happens already with combo time, which executes random effect additionally to the chosen effect
