### ISSUE TITLE
[Effect Suggestion] Suicidal

### ISSUE THREAD

**Issue by Edelgaspirat** [gta-chaos-mod/ChaosModV#1239]
**Name of effect**
Suicidal, Trigger-Happy

**Duration if timed effect (long or short timed?)**
short

**Effect Description**
Everytime the player shoots, he shoots himself in the head instead (like in GTA Online)

**Comment by lZevex** [comment]
Pacifist already exists

**Comment by Last0xygen** [comment]
Too similar to pacifist
