### ISSUE TITLE
Did somebody say yoga

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#1245]
**Name of effect**
Did somebody say yoga

**Effect Description**
Teleports you to one of the two yoga mats on the map.

**Comment by TheRealAyCe** [comment]
Merge with
https://github.com/gta-chaos-mod/ChaosModV/issues/648 and
https://github.com/gta-chaos-mod/ChaosModV/issues/1127
pls.

**Comment by DEATHCON1** [comment]
What about the ones that the peds use?

**Comment by Nextarity** [comment]
Maybe it kills the ped Idk
