### ISSUE TITLE
[Effect Suggestion] Teleport to Cayo Perico

### ISSUE THREAD

**Issue by Nghtmxre** [gta-chaos-mod/ChaosModV#1247]
**Name of effect**
Potential name(s) “Teleport to Cayo Perico”
Not Sure If Suggested Before.
**Effect Description**
Description of the effect; teleports you to cayo perico.

**Comment by turg-the-sad-cat** [comment]
It has and sadly not possible, since it’s really a online only map

**Comment by Nghtmxre** [comment]
> It has and sadly not possible, since it’s really a online only map

Well, there is some mods that do it, so maybe it can render it.

**Comment by turg-the-sad-cat** [comment]
But it has been suggested before and people have said no

**Comment by ProfessorBiddle** [comment]
You can load the assets but I believe it has to be done on game load for
singleplayer. It would also cause all sorts of issues with missions etc.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/710
