### ISSUE TITLE
[Effect Suggestion] Mobile Radio.

### ISSUE THREAD

**Issue by Nghtmxre** [gta-chaos-mod/ChaosModV#1248]
**Name of effect**
Potential name(s) Mobile Radio
(Like i said in the last suggestion, I do not know if this has been suggested before, This is ment to be harmless
**Description**
Description of the effect; Allow you to use the radio on ground?

**Comment by turg-the-sad-cat** [comment]
Most people who use this mod (streamers) have the music turned off

**Comment by turg-the-sad-cat** [comment]
And has been suggested before

**Comment by lZevex** [comment]
Not possible because of copyright

**Comment by pipecek** [comment]
Copy of my idea#964

**Comment by Last0xygen** [comment]
Duplicate #428
