### ISSUE TITLE
[Effect Suggestion] Stoned

### ISSUE THREAD

**Issue by tigercat710** [gta-chaos-mod/ChaosModV#1250]
**Name of effect**
Stoned, Baked, High

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Gives the player the visual and audio effect of being high, like the LSD and Drunk effects already in the game/mod. Effect of being high already exists in the game, from the weed in Franklin’s safehouse and Jimmy’s room.

**Comment by Last0xygen** [comment]
I don’t think we need another visual effect that’s too similar to LSD
