### ISSUE TITLE
[Effect Suggestion San Andreas Graphics 

### ISSUE THREAD

**Issue by Nghtmxre** [gta-chaos-mod/ChaosModV#1253]
**Name of effect**
Potential name(s) GTA SA Graphics.

**Duration if timed effect (long or short timed?)**
If not a timed effect, 1-2 minutes i perfer 1.

**Effect Description**
Description of the effect; This is combined with low render distance so basically what it will do is lower the graphics, lower the res and low render distance.

**Comment by lZevex** [comment]
That's literally what low render distance is

**Comment by Last0xygen** [comment]
Yeah, that’s low render distance. Lowering the resolution won’t work „on demand“
