### ISSUE TITLE
[Effect Suggestion] Spawn slight Griefer Jesus

### ISSUE THREAD

**Issue by Nextarity** [gta-chaos-mod/ChaosModV#1261]
**Name of effect**
Spawn slight Griefer Jesus

**Effect Description**
Its Griefer Jesus but instead of a railgun Jesus has a pistol

**Comment by turg-the-sad-cat** [comment]
Too close to spawn griefer Jesus

**Comment by Nextarity** [comment]
We have extreme Jesus so what about adding the opposite?

**Comment by Last0xygen** [comment]
No need for this slight variation
