### ISSUE TITLE
Random Griefer Jesus

### ISSUE THREAD

**Issue by Takasu96** [gta-chaos-mod/ChaosModV#1262]
Spawns Griefer Jesus but he has a different weapon each time he is spawned. Saw the other guy suggested Jesus spawn with a pistol so I thought why not suggest spawning Jesus but he will have a different weapon each time he's spawned in? I understand if this is too impossible to code in

**Comment by Last0xygen** [comment]
It’s not impossible to code, but I don’t see any advantages for this over „spawn random enemy“ for example
