### ISSUE TITLE
[Effect Suggestion] Fake Crash (Changes)

### ISSUE THREAD

**Issue by Goodguy140** [gta-chaos-mod/ChaosModV#1263]
**Name of effect**
Fake Crash

**Effect Description**
Instead of right after the line finishes the fake crash happens, you could make it so when fake crash is chosen then randomly within the next purple line the fake crash happens. Making it seem like it didn't happen from Chaos until it actually happens.

**Comment by Numi43** [comment]
Already suggested like million times.

**Comment by lZevex** [comment]
#328 #570 #771

**Comment by Last0xygen** [comment]
Yup, duplicate
