### ISSUE TITLE
1776

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#1266]
**Name of effect**
1776 

**Effect Description**
Give everyone a Flintlock weapon. Player and NPCs. If it is possible it replaces all the players weapons with just Flintlock weapons. So the flintlock pistol and musket

**Comment by Takasu96** [comment]
Not a developer but this is possible but it just gives them the weapons not replacing the other weapons unfortunately so if they have other weapons, the Flintlock weapons would just be added with the others.

**Comment by juhana** [comment]
You can obviously remove all other weapons before giving the flintlock weapons to get the desired effect.

**Comment by TheRealAyCe** [comment]
duplicate
https://github.com/gta-chaos-mod/ChaosModV/issues/450
https://github.com/gta-chaos-mod/ChaosModV/issues/884

**Comment by Last0xygen** [comment]
Duplicates
