### ISSUE TITLE
Jesus Overload 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1267]
**Name of effect**
Jesus Overload 

**Duration if timed effect (long or short timed?)**
long timed

**Effect Description**
All peds turn into Attacking Jesus

**Comment by lZevex** [comment]
All Peds Attack Player already exists, there's no reason to have the same effect only switching ped models

**Comment by psych-s1** [comment]
I have asked for All peds are Jesus and also attack the player..

**Comment by lZevex** [comment]
I know, but it's literally the same effect but replacing the ped models, there's 0 reason to add it

**Comment by psych-s1** [comment]
I thought we can add it for the memes you know...

**Comment by lZevex** [comment]
There needs to be more reason to adding a duplicate effect than "For the memes"

**Comment by turg-the-sad-cat** [comment]
Dude, it’s closed, that means no

**Comment by Da-Best** [comment]
i mean if they get a rail gun/ompressor then it wont be "all peds attack player"

**Comment by Nghtmxre** [comment]
> i mean if they get a rail gun/ompressor then it wont be "all peds attack player"

This.

**Comment by lZevex** [comment]
Peds Riot already exists, and the effect is annoying enough with them not specifically attacking you, giving them weapons of any kind would mean a permanent deathloop
