### ISSUE TITLE
LightViperAU 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1268]
**Name of effect**
LightViperAu

**Duration if timed effect (long or short timed?)**
Short timed

**Effect Description**
The screen turns super bright white in colour and also starts to flash.

**Comment by pipecek** [comment]
DarkViperAU isn't the only YouTuber who plays chaos. Some people don't even know him.

**Comment by lZevex** [comment]
The Mod isn't specifically for Matt, and Deep Fried already exists. Don't think there's any need to add more seizure inducing effects into the game 😂

**Comment by Last0xygen** [comment]
It also is already an effect („Deep Fried“)
