### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1278]
**Name of effect**
Glitch or Twitched
**Duration if timed effect (long or short timed?)**
Long Timed - 20 Seconds

**Effect Description**
The screen would have the glitch effect on a higher scale.

**Comment by Last0xygen** [comment]
What glitch effect are you talking about?

**Comment by psych-s1** [comment]
Google glitch effect

**Comment by Last0xygen** [comment]
I don’t see any gta 5 glitch effects. 
please update your Suggestion with additional info

**Comment by psych-s1** [comment]
how do i explain? Glitch effect is this...(given below) 
![image](https://user-images.githubusercontent.com/83582395/116992002-040e2b80-acf3-11eb-8020-e817fa037555.png)

**Comment by psych-s1** [comment]
alright?

**Comment by psych-s1** [comment]
![image](https://user-images.githubusercontent.com/83582395/116992273-6535ff00-acf3-11eb-8ac4-7a63562a38da.png)

**Comment by anto4440** [comment]
meh.. this is just the old effect 'blind'

**Comment by psych-s1** [comment]
Nope, you're very wrong bruh

**Comment by Last0xygen** [comment]
I still don’t understands what you want. 
if you want a custom glitch effect: this does not exist in gta -> can’t be done

**Comment by psych-s1** [comment]
> I still don’t understands what you want.
> if you want a custom glitch effect: this does not exist in gta -> can’t be done

do you UNDERSTANDS anything? lol

**Comment by pipecek** [comment]
> > I still don’t understands what you want.
> > if you want a custom glitch effect: this does not exist in gta -> can’t be done
> 
> do you UNDERSTANDS anything? lol

He is much smarter than you... He knows code,etc... What do you NOT understand about if it's a custom screen it can't be done. It has to be in gta V..

**Comment by psych-s1** [comment]
You are good at jokes.

**Comment by psych-s1** [comment]
BTW, I'm making a joke of UNDERSTANDS not Last0xygen.

**Comment by Last0xygen** [comment]
Yup, autocorrect is really funny ;) 
This request is closed, no further conversation needed

**Comment by psych-s1** [comment]
ikr, of course there is a reason you are handling these requests.

**Comment by TitanY0MaMa** [comment]
Doesn't this already exist as Bubble Vision?

**Comment by psych-s1** [comment]
No, it's different.

**Comment by turg-the-sad-cat** [comment]
1. This effect is close, no need to continue and 2. Over and over again everyone has said this isn’t possible

**Comment by psych-s1** [comment]
I know, just clarifying one's question.
