### ISSUE TITLE
ol' times

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1280]
**Name of effect**
Ol' times, old times, 80s

**Duration if timed effect (long or short timed?)**
Long Timed
**Effect Description**
Everything goes Black and White or Noir....if possible, peds now ride horses, the characters seem like they are  in RDR2....dresses etc.....police turns into sheriffs etc

**Comment by Last0xygen** [comment]
„LS Noire“ already exists and there are no horses in GTA 5
