### ISSUE TITLE
Desktop Goose 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1281]
**Name of effect**
Goose Hacker...Poking Goose

**Duration if timed effect (long or short timed?)**
Long Timed

**Effect Description**
If you have heard of the Desktop Goose game, what it does is that, it pokes the player, by bringing in annoying things, like pictures, memes, dragging away cursor, making noises etc. This is a really good one. Reply back, if you want links to how it looks.

**Comment by Last0xygen** [comment]
I have no idea what you mean this effect should do.
I do know what you’re talking about, but still don’t understand what you expect.
DVD Screensaver already exist by obscuring the vision 🤷‍♂️

**Comment by psych-s1** [comment]
Google glitch effect

**Comment by psych-s1** [comment]
No no google Desktop Goose

**Comment by psych-s1** [comment]
Should I link some references?

**Comment by psych-s1** [comment]
https://www.youtube.com/watch?v=Fqf_84YgtPc
https://samperson.itch.io/desktop-goose

**Comment by psych-s1** [comment]
Check this out, believe me, this is will be very funny

**Comment by Last0xygen** [comment]
Please make a request so everything is explained. Things like „google this or that“ is not sufficient IMO.
Again, I know what Desktop goose is, but I still don’t know what you expect this effect to do. 
drag random scenes into the view? That’s „On Demand TV“.
Obscuring the view? That’s dvd screensaver 🤔
This seems like a request to replicate something that could be just used by using desktop goose itself 😅

**Comment by psych-s1** [comment]
Actually yes, I indeed wanted a replica of the goose,  as its not
internally possible to integrate such a system into Chaos.

**Comment by lZevex** [comment]
There's this app that you can install that has a goose walking around on your screen blocking your input wherever it is and sometimes playing media and dragging images onto the screen. Would be a weird effect to add though

**Comment by psych-s1** [comment]
ikr, that's what chaos should be...
