### ISSUE TITLE
[Meta Effect suggestion] old chaos

### ISSUE THREAD

**Issue by UjjwalJ-5107** [gta-chaos-mod/ChaosModV#1284]
This effect would activate some of the old chaos effects that are no longer in the mod. The effects can be modified in the config. It only has mods that were not removed for being 'bad', it should include the ones that were decent but removed for being old.

**Comment by Last0xygen** [comment]
I don’t think there are and effects that got removed for being „old“.
Several effects got replaced by other, more interesting effects or because they just stop the player from playing the game
