### ISSUE TITLE
[Effect Suggestion] Lazlow horde

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#1293]
**Name of effect**
Lazlow horde

**Duration if timed effect (long)**

**Effect Description**
Spawn a crowd of lazlows that will attack the player

**Comment by Last0xygen** [comment]
Please fill out the request or it will be closed

**Comment by Hazemkaid** [comment]
So what,why not,it will be good

**Comment by Hazemkaid** [comment]
Nevermind I will edit it

**Comment by Last0xygen** [comment]
Spawning  a ped multiple times is not really a good effect, sorry
