### ISSUE TITLE
[Effect Suggestion] Online Bait

### ISSUE THREAD

**Issue by viniboi2006** [gta-chaos-mod/ChaosModV#1295]
**Online Bait**
Potential name(s) for the effect:
"Click to Online", "Go to Online Bait."

**Duration if timed effect**
Can be 30 seconds to 2 minutes.

**Effect Description**
Basically, when the effect is applied, some text will appear saying "Press (W, A, S, or D or any of the most used keys) to go to GTA Online", then if the player presses it which is very likely, create an auto save and put the player on one of those loading screens for online, after one or two minutes send the player back to where they were, or alternatively actually send the player online and then the player has to go back on the save file.

**Comment by Last0xygen** [comment]
1. you can’t Start online with mods
2. an effect that just blocks the player from playing is not something we want to add to the mod
