### ISSUE TITLE
[Effect Suggestion] Nice Traffic

### ISSUE THREAD

**Issue by CronanDark** [gta-chaos-mod/ChaosModV#1298]
**Name of effect**
Nice Traffic

**Duration if timed effect (long or short timed?)**
2 minutes

**Effect Description**
only good cars on the road

**Comment by lZevex** [comment]
Already exists with Random Traffic

**Comment by Last0xygen** [comment]
Already requested, partly already available as „random traffic“

**Comment by CronanDark** [comment]
> Already requested, partly already available as „random traffic“

well it would be only good cars... no bad ones

**Comment by Last0xygen** [comment]
Like I said, duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/953
