### ISSUE TITLE
[Effect Suggestion] Bad Traffic

### ISSUE THREAD

**Issue by CronanDark** [gta-chaos-mod/ChaosModV#1299]
**Name of effect**
Bad Traffic

**Duration if timed effect (long or short timed?)**
2 minutes

**Effect Description**
only bad cars on the road

**Comment by Last0xygen** [comment]
Already requested, partly already available as „random traffic“

**Comment by CronanDark** [comment]
> Already requested, partly already available as „random traffic“

well it would be only bad cars... no good ones

**Comment by Last0xygen** [comment]
Like I said, duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/407
