### ISSUE TITLE
[Effect Suggestion] Spawn Random Playable Character

### ISSUE THREAD

**Issue by CronanDark** [gta-chaos-mod/ChaosModV#1301]
**Name of effect**
Spawn Random Playable Character

**Effect Description**
Teleports one of the playable characters to you. Not the one you are playing tho. Example: Teleport Michael to you while you are Trevor

**Comment by Last0xygen** [comment]
Already exists as random companion/enemy or spawn clone

**Comment by CronanDark** [comment]
> But switching characters should also switch to that teleported ped. Not a new ped that just looks like Michael for example.

this is what i was thinkin of... ud be able to switch to the character that tped to u and it would be right there
