### ISSUE TITLE
[Effect Suggestion] Everyone moves out of your way

### ISSUE THREAD

**Issue by CronanDark** [gta-chaos-mod/ChaosModV#1303]
**Name of effect**
Move B get out the way

**Duration if timed effect (long or short timed?)**
1 minute

**Effect Description**
everyone moves out of your way... wether it be walking/running/dodging away from you or driving to the other side of the road/to the sidewalk to avoid you.... similar to forcefield in no vehicles and peds near you but not destructive... also similar to peds fleeing but this involves vehicles and they dont leave the vehicles

**Comment by Last0xygen** [comment]
I don’t see how this would be different from forcefully except it not being that „powerful“ or „aggressive“
