### ISSUE TITLE
[Effect Suggestion] Bulldozer time!!

### ISSUE THREAD

**Issue by baromde** [gta-chaos-mod/ChaosModV#1305]
**Name of effect**
Bulldozer time!!

**Effect Description**
spawns heavily armored enemy with a shotgun.
alot of health, but not too much

**Comment by baromde** [comment]
this is the best effect sugestion i have seen

**Comment by pipecek** [comment]
> this is the best effect sugestion i have seen

Probably because you own it.

**Comment by baromde** [comment]
> > this is the best effect sugestion i have seen
> 
> Probably because you own it.
congrats you got the joke
