### ISSUE TITLE
[Effect Suggestion] Teleport into nearest flying vehicle

### ISSUE THREAD

**Issue by CronanDark** [gta-chaos-mod/ChaosModV#1306]
**Name of effect**
Teleport into nearest flying vehicle

**Effect Description**
Teleport the player into the nearest plane or helicopter

**Comment by Last0xygen** [comment]
Already exists as „set player into random seat/vehicle“

**Comment by CronanDark** [comment]
> Already exists as „set player into random seat/vehicle“

but this would only do flying vehicles
