### ISSUE TITLE
[Effect Suggestion] Super drunk

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#1313]
**Name of effect**
Super drunk

**Duration if timed effect (long or short timed?)**
2 minutes 

**Effect Description**
Sensitive touch and drunk affect at the same time mixed together

**Comment by Last0xygen** [comment]
would be too distracting. some "Random ragdolling" is already available with "I'm Tired"

**Comment by lZevex** [comment]
Would it be possible to have the drunk effect after going to a bar during hangouts? (Has a different screen effect)
