### ISSUE TITLE
[Meta Effect Suggestion] Broken Record

### ISSUE THREAD

**Issue by MrDrJohnny** [gta-chaos-mod/ChaosModV#1315]
Broken Record

Long

A meta effect that causes the last effect that happened to repeat every time an effect should happen. Like if rainbow weapons is selected then Broken Record begins every effect that happens will be Rainbow Weapons until Broken Record Expires.

**Comment by TheRealAyCe** [comment]
Duplicate, though I like the name :D https://github.com/gta-chaos-mod/ChaosModV/issues/520

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/520
