### ISSUE TITLE
[Effect Suggestion] Sucks and Blows All At Once

### ISSUE THREAD

**Issue by CRB9000** [gta-chaos-mod/ChaosModV#1323]
**Name of effect**
Sucks and Blows At Same Time
Sucks and Blows All At Once
I'm Attracted But Repelled

**Duration if timed effect (long or short timed?)**
Long.

**Effect Description**
I had Gravity Field follow Forcefield, it was a cool effect. So turn on both forcefield and gravity field at the same time for the duration.

**Comment by TheRealAyCe** [comment]
This? https://github.com/gta-chaos-mod/ChaosModV/issues/943

**Comment by CRB9000** [comment]
Kind of, but that isn't really described properly. Try this, go into effects and disable everything except gravity field and forcefield and then let the mod run so both will go into effect. You'll see what I mean.

**Comment by Last0xygen** [comment]
yeah, thats what https://github.com/gta-chaos-mod/ChaosModV/issues/943 is :)
