### ISSUE TITLE
[Effect Suggestion] Spawn Marvel/DC

### ISSUE THREAD

**Issue by Kemonoruv** [gta-chaos-mod/ChaosModV#1330]
**Name of effect**
Spawn Marvel/Dc
Its Hero Time!

**Effect Description**
It should spawn a character from Marvel or Dc Universe who will try to kill Matt with their abilities. For example-If Thanos is spawned, it will use the stones to mess with Matt and might click the fingers to kill Matt. If Hulk is spawned, he will jump on the vehicles and cause havoc destroying all cars and crushing Matt.

**Comment by turg-the-sad-cat** [comment]
1. This mod is not just for Matt, many other people use it and don’t even know Matt, 2. There is no marvel or dc models in the game

**Comment by Last0xygen** [comment]
Yes

**Comment by Kemonoruv** [comment]
> 1. This mod is not just for Matt, many other people use it and don’t even know Matt, 2. There is no marvel or dc models in the game

1. I did not know its for everyone. I apologise for that.
2. There are mods to make your game character one of the heroes. If that is not possible, no worries.

**Comment by Last0xygen** [comment]
We don’t implement custom models in this mod :)
