### ISSUE TITLE
[Bug] Some DLC cars aren't spawning/instantly despawns due to Rockstar preventing DLC cars on story mode

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1337]
**Describe the bug**
There's a measure in story mode where, some of new DLC cars cannot be spawned in story mode to prevent players testing it via mod menus. this bug can be seen on DarkViperAU's chaos mod episode 6 when his vehicle disappear after replace current vehicle (https://youtu.be/q7LvcbQ-APg?t=172) possible replacing Sabre Turbo into Tullip/Vamos/Impaler

**To Reproduce**
Spawning DLC Vehicle in Story Mode (i heard there's mod to fix it like modifying .dat files to allow these vehicle to spawn)
**Crash Dump (if a game crash)**
https://youtu.be/q7LvcbQ-APg?t=172
https://youtu.be/riFd668i8sE?t=5854

**Comment by Takasu96** [comment]
Chaos mod only works on vanilla game. It doesn't work on modified dat files since everyone has the original dat file by default so it won't work

**Comment by TheRealAyCe** [comment]
> 
> 
> This is known.
> we currently don't have a bypass for this online vehicle restriction by R*.
> if you want to use it -> use another mod that makes them persistent as i don't konw when we will be able to implement this

But then Online vehicles should be removed from the spawn lists by default, no?

**Comment by Last0xygen** [comment]
We don’t have a method to check if it has been bypassed either, so by disabling it we would disable it for players using a bypass too 😅

**Comment by TheRealAyCe** [comment]
Config setting ^^

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/wiki/Feature-Flags
.skipdlcs

**Comment by MoneyWasted** [comment]
> This is known.
> we currently don't have a bypass for this online vehicle restriction by R*.
> if you want to use it -> use another mod that makes them persistent as i don't konw when we will be able to implement this

Correction, I do have a bypass for this I’m working on adding it.
