### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Kemonoruv** [gta-chaos-mod/ChaosModV#1341]
**Name of effect**
Teleport to prison

**Effect Description**
Teleport the player to prison giving 5 stars

**Comment by TheRealAyCe** [comment]
Teleport to prison/jail was already suggested several times, just search for it.

**Comment by Kemonoruv** [comment]
> Teleport to prison/jail was already suggested several times, just search for it.

Oh okay. Thanks for telling.
