### ISSUE TITLE
GO OPPOSITE! 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1344]
**Name of effect**
GO OPPOSITE!!!  

**Duration if timed effect (long or short timed?)**
Long term 

**Effect Description**
This would invert the player's controls....for example, if someone clicks Forward (W on PC for instance)  he would go backward, if they click right, they would go left. 

Reply for more Details.

**Comment by Last0xygen** [comment]
Duplicate #17 #16 #1342
