### ISSUE TITLE
Fake Launch 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1345]
**Name of effect**
Fake Launch 

**Duration if timed effect (long or short timed?)**
Short 

**Effect Description**
Fake Launch 
Fake Launch
Fake Launch
Fake Launch
Fake Launch

**Comment by turg-the-sad-cat** [comment]
Wrong use for the effect description and “fake launch” could mean multiple things

**Comment by psych-s1** [comment]
> Wrong use for the effect description and “fake launch” could mean multiple things

Bruh, it literally means FAKE LAUNCH.

**Comment by pongo1231** [comment]
What kind of fake launch though? Fake launch player up? Fake launch effect? Fake launch into space? Could mean multiple things and you should elaborate further in the description (which is its whole purpose).

**Comment by turg-the-sad-cat** [comment]
It’s closed

**Comment by Last0xygen** [comment]
fake launching the web browser?
fake launching a nuclear rocket?
fake lauching all cars in the air?
fake launching the player forwards?

The structure of the effects are there to be used, to clarify.
If the description is saying nothing nobody can work on this

**Comment by psych-s1** [comment]
Ya I forgot, sorry, but I wanted a Fake Launch upwards, so it would look like a short quick teleport and within a second the character is in the original place.

**Comment by psych-s1** [comment]
Shall I Edit the issue or shall I open a new one?
