### ISSUE TITLE
Stop Hitting/Shooting 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1346]
**Name of effect**
Why are you attacking?, STOP ATTACKING

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
The hit key, like Left click and R2 etc.... Would be glitched, that means that the character would automatically start punching continuously  (if not equipped with weapon) or start shooting continuously  (if equipped).  

Reply for more clarifications.

**Comment by Last0xygen** [comment]
Already an effect ("Loose Triggers")

**Comment by TheRealAyCe** [comment]
> Already an effect ("Loose Triggers")

Having the character punch when no weapon is equipped in that effect would be a nice addition though.

**Comment by psych-s1** [comment]
> > Already an effect ("Loose Triggers")
> 
> Having the character punch when no weapon is equipped in that effect would be a nice addition though.

Thanks for considering, is there any hope that they can reopen this suggestion/issue?

**Comment by BitGhostYT** [comment]
> > Already an effect ("Loose Triggers")
> 
> Having the character punch when no weapon is equipped in that effect would be a nice addition though.

I’m pretty sure that’s also in “Loose Triggers”

**Comment by Last0xygen** [comment]
It is not

**Comment by BitGhostYT** [comment]
> It is not 

I remember in a Darkviperau chaos he couldn't switch weapons during loose triggers bc it kept making him punch but I don't have the clip

**Comment by BitGhostYT** [comment]
> > It is not 
> 
> I remember in a Darkviperau chaos he couldn't switch weapons during loose triggers bc it kept making him punch but I don't have the clip 

Found it, 26:00 on this vid https://youtu.be/mR7ADhOJYWo
