### ISSUE TITLE
Just Walk 

### ISSUE THREAD

**Issue by psych-s1** [gta-chaos-mod/ChaosModV#1349]
**Name of effect**
Just Walk,  Walking is good 

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
The character will only be stuck to Walking, cannot stop, cannot run.

**Comment by Last0xygen** [comment]
Please take a look at all existing effects :) 
This already exists as "No Sprint & No Jump"

**Comment by psych-s1** [comment]
> Please take a look at all existing effects :)
> This already exists as "No Sprint & No Jump"

Sure, but where do I see the list of existing effects?

**Comment by Last0xygen** [comment]
Either download the mod and look in the config app or the effects spreadsheet: https://docs.google.com/spreadsheets/d/1Q1jHwl3aj9Cla4af-gZHKxJhWZfP4bac8p7cY7MfeZc/edit#gid=1386834576

**Comment by psych-s1** [comment]
> Either download the mod and look in the config app or the effects spreadsheet: https://docs.google.com/spreadsheets/d/1Q1jHwl3aj9Cla4af-gZHKxJhWZfP4bac8p7cY7MfeZc/edit#gid=1386834576

Thank you :)
