### ISSUE TITLE
[Effect Suggestion] Random waypoints.

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#1356]
**Name of effect**
Random waypoint

**Effect Description**
I know confusing waypoints is already a suggestion.
But I think having the map place a random waypoint, would be much better.
Placing a random waypoint anywhere on the map, and hopefully confuse the player into thinking they have to drive to that location.
I hope it's different enough from confusing waypoints.

**Comment by turg-the-sad-cat** [comment]
There’s a bit of a problem, In the story, the waypoint is yellow and I don’t think you can move it, and if there is a random waypoint it’s kind of obvious if you look at the map and it changed directions

**Comment by turg-the-sad-cat** [comment]
And I’m pretty sure it’s been suggested before

**Comment by TitanY0MaMa** [comment]
I know the reason why this was suggested 😂

**Comment by Kibukaj** [comment]
Haha, I wanted to suggest the same thing! I guess you had the idea after DarkViperAU's video, didn't you?

**Comment by KatieDeForest** [comment]
Yup! DarkViperAU's video's are the best!
