### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Nghtmxre** [gta-chaos-mod/ChaosModV#1357]
**Name of effect**
Potential name(s) Jailed

**Duration if timed effect (long or short timed?)*
30 seconds.

**Effect Description**
Description of the effect; Put a cage on you for 30 seconds and teleport you in the jail.
Teleports you back wherever you were last.

**Comment by turg-the-sad-cat** [comment]
It’s not a good suggestion if it denies the player from playing

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/742

**Comment by Last0xygen** [comment]
Duplicate #742

**Comment by Nghtmxre** [comment]
> Duplicate #742

Get real my guy it didnt say teleport you to jail.

**Comment by turg-the-sad-cat** [comment]
Description of the effect; Put a cage on you for 30 seconds and teleport you in the jail.
Teleports you back wherever you were last.                                                     That’s what you said, you directly said teleport you in jail

**Comment by Nghtmxre** [comment]
Or you can just be teleported to prison, but its still not a duplicate clearly your not getting real ffs.
