### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by darkvigh** [gta-chaos-mod/ChaosModV#1358]
**Name of effect**
Random waypoint

**Effect Description**
puts a waypoint on a random mission or point on the map, inspired by darkviperau's latest twitch vs chaos video

**Comment by turg-the-sad-cat** [comment]
Already been suggested before

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1356
