### ISSUE TITLE
[Effect Suggestion] Ressurection (Meta)

### ISSUE THREAD

**Issue by Planita13** [gta-chaos-mod/ChaosModV#1362]
**Name of effect**
Nine Lives, Resurrection, Escaped the Reaper

**Effect Description**
Meta effect. If a player dies, there is a chance that they can be instantly revived, fully healed from all damage. Maybe 5% to 10% chance for each death.

**Comment by Last0xygen** [comment]
Already exists as "Invincible", i dont think theres a need for a meta version of this
