### ISSUE TITLE
[Effect Suggestion] Merryweather fleet's here, bro!

### ISSUE THREAD

**Issue by Kibukaj** [gta-chaos-mod/ChaosModV#1363]
**Name of effect**
Merryweather fleet's here, bro!

**Effect Description**
Trevor's voice, taken from mission "Derailed" plays: "Merryweather fleet's here bro!" 5 seconds after that, 2 buzzard helicopters with pilot, co-pilot and 2 machine gunners spawn near the player. The helicopters are able to use their mounted guns, and the machine gunner rifles, which would be MG's. At the same time, 3 merryweather off-road cars are spawned, each containing 4 MW mercenaries, armed with carabine rifles, 12 in total. All of the spawned NPC's are agressive towards player and use their weapons in attempt to kill the player. The effect isn't timed, the NPC's spawn only once.

**Comment by Last0xygen** [comment]
Already exists as „mercenaries“

**Comment by Kibukaj** [comment]
I know, however it would be slightly different. It could also replace the effect "Mercenaries".

**Comment by Last0xygen** [comment]
Mercenaries spawns a helicopter and military jeeps.
Playing trevors phrase is not possible.
-> I don’t see any advantage of your proposal of the current effect :)
