### ISSUE TITLE
[Suggestions + a small question] Remove liquids around the player, Spawn a ball of water, Randomize text and dialogue

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#137]
Remove liquids around the player: lasting effect, acts like Forcefield. Creates an area around the player where all the liquids (water) will be removed. Basically the player won't be able to enter the water and drive boats.

Spawn a ball of water: creates a ball of water on top of the player.

Randomize text and dialogue: every dialogue is random, and every on-screen text is random (for example, the current mission objective would be from another random mission to confuse the player or just something pointless (completely random)). Edit: you can also randomize something like sounds.

The question: is it better to write Chaos Mod suggestions here, or in Matt's (DarkViper's) Discord? Because I remember I suggested a lot of good stuff there (well, as I think), and only 1 or 2 things were added, while here I see most of people's suggestions get approved. Don't want to say everything I'm suggesting is 100% good and you need to add it, just maybe here it has a higher chance to be at least noticed, and even explained why something can't be added (seen a couple of times), and Discord lacks that opportunity.

**Comment by ProfessorBiddle** [comment]
Personally I don't know a way to change water except for sea level and wave intensity, and I have no idea how to randomize things like dialogue.

I don't think it matters where suggestions are posted, the reason some good ideas aren't done is because they aren't feasible with the tools we have, you can look through the scripthook methods here to see what's possible if you want: https://runtime.fivem.net/doc/natives/

**Comment by OHSHIET** [comment]
Well, there are effects Friendly and Unfriendly Neighborhood, I guess you can call them "dialogue randomization". Thanks for the link anyway.

**Comment by MoneyWasted** [comment]
> Personally I don't know a way to change water except for sea level and wave intensity, and I have no idea how to randomize things like dialogue.
> 
> 
> 
> I don't think it matters where suggestions are posted, the reason some good ideas aren't done is because they aren't feasible with the tools we have, you can look through the scripthook methods here to see what's possible if you want: https://runtime.fivem.net/doc/natives/

FiveM natives aren't the same as GTA V natives. While they do the same thing the syntax may be different due to the version differences and other anomaly's. Currently GTA 5 is on Patch 1.51 while FiveM is on patch 1.46.

**Comment by OHSHIET** [comment]
Ok, I've read through the docs and found some interesting stuff:

There is a function which creates a checkpoint. I guess in missions. There is also one which deletes it. Would be interesting, however there are some problems:
1. Even a long lasting effect wouldn't be long enough for this kind of effect. For usual Chaos without Twitch voting there is no chat trying to always kill you, so this effect would be useless most of the time.
2. If you aren't in a mission, you can't create checkpoints? Possible solution: create an "alternative hospital". Works like a hospital, just isn't a hospital, and you always respawn there if the "Create a Checkpoint" effect is active. Not sure you would be able to implement it though.

There are a lot of functions for setting text fonts, text colors, text shadows... Maybe an effect that randomizes styles of text using them?

Didn't find anything else interesting, but I still have a couple of suggestions:
1. Randomize player clothes could be lasting (changing clothes every second or so). As a separate effect, or just change the existing one. When it ends, clothes actually stay and don't change to what the player had before the effect (so the effect also kinda reminds us of the usual Randomize player clothes). And I also suggested randomizing peds clothes a while ago, if it's not possible, maybe you could just randomize peds models
2. All peds flee could be lasting too. I don't know why it's not, because you remade all the effects like this into lasting, and it worked well.
3. From the recent Matt's stream: Spawn Blue Sultan actually spawned a Red Sultan. Feature?
4. Repeat Current Dialogue. Didn't find anything about it in the docs, just again had an idea about messing with dialogues. There is a problem though, there isn't always dialogue playing.
5. Probably not the place to suggest it, but had an idea: bot commands on Twitch which tell you about Chaos effects. Not all at once, just the effect you want. If it's possible to do it so that the new effects will be automatically added.

Thanks for the correct site, by the way. I hope it's okay I wrote it here.

**Comment by ProfessorBiddle** [comment]
I'll have to play around with some of this, I'll update with some results
later.


I already tried continuously randomizing player clothes, but for some
reason the method only produces one combination of clothes/appearence per
game session. If anyone else can figure this out please do, I'm stumped.

As far as dialogue/cutscene randomization, its definetely possible but
dialogue/cut scenes can only be activated through a file name, if someone
has a good way of listing all of the cutscene files and creating an array
from them playing a random cutscene would be trivial, but I dont know of a
list and I'm a shit programmer and dont know how to get one lol

**Comment by pongo1231** [comment]
Modifying water in the ways you mentioned is simply not possible at runtime. The only ways water can be modified are by changing the water level and the wave intensity (IIRC).

Dialog randomization just really doesn't fit the mod as it's very situational. It's much more suited to a randomizer-style mod (like the Rainbomizer in SA, I have been doing some work on something in that style for V).

Ped models other than all the player and mp protagonist models barely have any clothing variety (or none for some models) so I don't think an effect for that would make sense.

The blue sultan in his streamed was red as "Red Traffic" was active.

Also I don't see why a bot command for information about specific effects makes sense when there's a [spreadsheet](https://docs.google.com/spreadsheets/d/1Q1jHwl3aj9Cla4af-gZHKxJhWZfP4bac8p7cY7MfeZc/edit?usp=sharing) containing (usually) every effect and with the ability to search for a specific effect.

**Comment by TheRealAyCe** [comment]
> The question: is it better to write Chaos Mod suggestions here, or in Matt's (DarkViper's) Discord? Because I remember I suggested a lot of good stuff there (well, as I think), and only 1 or 2 things were added, while here I see most of people's suggestions get approved. Don't want to say everything I'm suggesting is 100% good and you need to add it, just maybe here it has a higher chance to be at least noticed, and even explained why something can't be added (seen a couple of times), and Discord lacks that opportunity.

Github has a list of things todo - this one. Discord moves too fast for anything (older than a few days maybe?) to be remembered. If you want modders to look at your suggestions you should post them in the issues with [Suggestion]. Otherwise you are relying on someone who might actually implement an effect to see your short-lived suggestion on Discord.

That said, reporting bugs and suggesting things in Discord is still better than not doing that at all. Even better: Learn to implement them yourself. :P

**Comment by OHSHIET** [comment]
Well I can't really remember all my suggestions I posted there because I can't check the channel's previous messages... Pretty sure Pongo can, maybe some other mod contributors. If you're interested, you can look up my messages there. 

Actually, I always try to check what people suggest in Matt's Discord (and yes, it can be really difficult since you can't see the previous messages), and some people suggested the Matrix code vision effect https://www.youtube.com/watch?v=kqUR3KtWbTk
Some people suggested Agent Smiths attacking the player
And I think it'd nice to combine these two, so it'd be like Killer Clowns, with visual effects + enemies spawning. You can also change the player model. Since there is probably no Agent Smith/Neo model, you can just create some NPCs looking like them if possible (anyway you won't be able to recognise them with the code vision). Would be nice if the code vision didn't just pop up and appear on screen, but actually had transition between code vision and usual vision, and slowly moved down like it is seen in the video. The most difficult part is the visual effect, probably so difficult it's not even implementable, I just thought it was interesting.

Got another idea: 
Maybe there should be an effect which restricts you from using different types of vehicles for some time. Starting from just planes, helicopters, and ending with sedans, trucks. There definitely exists a function for checking the type of a vehicle or something, I think I've seen it. You can do 50/50 - you can't use 50% of the vehicles, or pick a random number each time of amount of vehicles you can't use (let's say 6 - you can't use 6 types of vehicles, then choose what types exactly). But it’d be better if the number was closer to 50%. If you’re in a vehicle you can't use, the player just exits the vehicle.

**Comment by TheRealAyCe** [comment]
Open one ticket per suggestion instead of adding suggestions here. :)

**Comment by OHSHIET** [comment]
Yeah, I already thought of it, but wasn't sure, thanks. I am just kinda new to GitHub and wasn't contributing here a lot.
I also often think some suggestions don't deserve their own issue, because they're too small. Maybe I should return to Discord, it'd easier :Р

**Comment by TheRealAyCe** [comment]
No problem. Suggestions don't have to be large, only good. The repository maintainers (-> pongo) will generally tell you if they consider your idea bad.

**Comment by OHSHIET** [comment]
Just realised you can easily create an "alternative hospital" for the "create a checkpoint" effect just by teleporting the player there when they respawn.

Should I rewrite those suggestions into new tickets btw?

**Comment by TheRealAyCe** [comment]
I was told to have one ticket for each suggestion, so I would guess you should have that. This one has 3 as far as I can tell, so maybe close this one and create 3 tickets and update their text? Dunno.
