### ISSUE TITLE
[Effect Suggestion] Fake Crash Revamp

### ISSUE THREAD

**Issue by itsdereklol** [gta-chaos-mod/ChaosModV#1372]
For the effect fake crash, I would like it to pull up the player’s home screen for a quick second, and then pull the game back up to make it even more believable.

**Comment by BitGhostYT** [comment]
How would they put that into the mod, unless they had something where when you load the mod it would screenshot your Home Screen, but I don’t think that’s possible

**Comment by kolyaventuri** [comment]
Closing as this is a duplicate of #1103
