### ISSUE TITLE
[Effect Suggestion] Spawn Ultimate Griffer Jesus

### ISSUE THREAD

**Issue by pokegustavor** [gta-chaos-mod/ChaosModV#1379]
**Name of effect**
Spawn Ultimate Griffer Jesus

**Effect Description**
Spawns a "normal" jesus, but if not killed quickly will use the obliterator to kill you

**Comment by kolyaventuri** [comment]
This is too similar to Spawn Extreme Griefer Jesus. Don't think we need more
