### ISSUE TITLE
[Effect Suggestion] Improvement for no ragdoll

### ISSUE THREAD

**Issue by lumpofcoal123** [gta-chaos-mod/ChaosModV#1383]
**Name of effect**
No Ragdoll

**Duration if timed effect (long or short timed?)**
Still the same

**Effect Description**
No ragdoll should prevent the player being thrown out the windshield

**Comment by Last0xygen** [comment]
It does already, doesn’t it?

**Comment by lumpofcoal123** [comment]
I believe you still shoot out the windshield, but just always land on your feet.

**Comment by Last0xygen** [comment]
This was already requested at some point and I testet if I can get knocked of a bike and I just couldn’t. Would be surprised if I instead get knocked out the windshield :D
