### ISSUE TITLE
[Effect Suggestion] Mommy Says I'm Special

### ISSUE THREAD

**Issue by iCeParadox64** [gta-chaos-mod/ChaosModV#1390]
**Name of effect**
I like the sound of _Mommy Says I'm Special_, but you could also just call it something like _Forced Special Ability_.

**Duration if timed effect (long or short timed?)**
Short seems most obvious, but I think it could work fine as a long effect.

**Effect Description**
The player's special ability is force enabled, and also has infinite charge so it doesn't run out, and can't be disabled until the effect ends.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/927
