### ISSUE TITLE
[Effect Suggestion] Teleport random protagonists to you

### ISSUE THREAD

**Issue by ato-gamecat** [gta-chaos-mod/ChaosModV#1391]
**Name of effect**
Potential name(s) for the effect
Teleport random protagonists to you

**Effect Description**
Description of the effect; what should it do?
It will teleport Michael or Trevor or Franklin to you. If you are playing as Franklin it won't teleport Franklin to you. (This will also go for if you're playing as Michael or Trevor)

**Comment by Last0xygen** [comment]
Same as „clone player“ or „spawn random enemy/companion“
