### ISSUE TITLE
[Effect Suggestion] ‘Split screen’ where the screen splits into 4 different views one being your player’s view and three others of random nearby NPC’s

### ISSUE THREAD

**Issue by ChaosSam** [gta-chaos-mod/ChaosModV#1392]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
Please use the template as described and don’t just put everything in the title 😅
But this can’t be done, so I’ll just close it instead
