### ISSUE TITLE
[Effect Suggestion] Acid Rain

### ISSUE THREAD

**Issue by ChaosSam** [gta-chaos-mod/ChaosModV#1395]
**Name of effect**
Acid Rain

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
It is a constant damage dealing rain that does same damage as bees but it is a constant damage meaning higher DPS but is avoidable by going under cover or being in an enclosed vehicle

**Comment by Last0xygen** [comment]
Already suggested
