### ISSUE TITLE
[Effect Suggestion] Hunting Party

### ISSUE THREAD

**Issue by J1rJ1r** [gta-chaos-mod/ChaosModV#1396]
**Name of effect**
Hunting Party

**Effect Description**
Spawns a small or large group of peds in a random location on the map that is far from the player. This group of peds will be using an APC hunt down the player untill killed or are directly responsible for the killing of the player. If successful, the peds and APC will despawn.

**Comment by J1rJ1r** [comment]
Not even sure if its possible to spawn functioning ai outside of the players area.

**Comment by TheRealAyCe** [comment]
Isn't this what Mercenaries do?

**Comment by J1rJ1r** [comment]
Was kind of thinking of one that was showing the fact and initially nothing happened until you happen to run into them so it's basically unexpected.

**Comment by Last0xygen** [comment]
Well that’s what mercenaries currently do. They spawn „far“ away and attack the player.
No random spawn anywhere on the map, but just far away enough.
