### ISSUE TITLE
[Effect Suggestion] Spawn Random Main Character

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1401]
**Spawn Random Main Character**

**Duration if timed effect (long or short timed?)**
One-time

**Effect Description**
Summons a randomly named character in GTA V. The weapons they got are completely random. However, if they’re a character’s alley, they’re a companion, and if they’re an antagonist or enemy (like Devin, Steve, Stretch, or Wei, etc.), he’s gonna be an enemy instead of a companion.

**Comment by Last0xygen** [comment]
This already exists as "Spawn Random Companion/Enemy". An extra effect for only "main" characters is not a good addition
