### ISSUE TITLE
[Effect Suggestion] Apathetic Citizen

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1402]
**Apathetic Citizen (or Blind Peds**

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
All peds are ignoring you and your crimes, even cops and enemies

**Comment by TheRealAyCe** [comment]
Brainless Peds?

**Comment by RosyMiranto18** [comment]
Nah nah. Brainless Peds means that they don't do anything. Apathetic Citizen means they goes on as normally they are, but they didn't retaliate or report on anything you did even against them directly.

**Comment by pipecek** [comment]
Never wanted.

**Comment by RosyMiranto18** [comment]
Uh... This also includes you attacking them, and they wouldn't flee too.

**Comment by Last0xygen** [comment]
Seems too close to „never wanted“ and „brainless peds“.
I don’t think there’s need for another „peds don’t react“-effect with no real difference
