### ISSUE TITLE
[Effect Suggestion] Melee Only

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1405]
**Melee Only**

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
All guns, bullets, explosives, fires, and vehicle contact doesn't deal damage (and this includes any Pistol-Whipping.) The only way to damage enemy is to use a melee weapon/fist.

**Comment by Da-Best** [comment]
Isnt this like Pacifist as iirc you can only melee in pacifist and gun shots will just kill the character

**Comment by RosyMiranto18** [comment]
No, there's a big difference. In Melee Only, everyone's guns are disabled (not just the player), and there's no death penalty for not complying, using guns only deals no damage.

**Comment by Last0xygen** [comment]
Any difference to „Remove weapons from everyone“? This seems like a timed version of that 🤔

**Comment by RosyMiranto18** [comment]
Yeah... now that you mention it, you're right about that. Damnit.
