### ISSUE TITLE
[Effect Suggestion] Spawn Piglin Brute

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1407]
**Spawn Piglin Brute**

**Duration if timed effect (long or short timed?)**
One-time

**Effect Description**
Summons a hostile NPC Pig/Boar carrying either a Battle Axe (but he’s very tanky), or a Stone Hatchet with the hatchet’s special ability permanently activated.

**Comment by Last0xygen** [comment]
Fixed https://github.com/gta-chaos-mod/ChaosModV/pull/1915
