### ISSUE TITLE
[Effect Suggestion] Cardinal gravity

### ISSUE THREAD

**Issue by J1rJ1r** [gta-chaos-mod/ChaosModV#1412]
**Name of effect**
Cardinal gravity

**Duration if timed effect (long or short timed?)**
30-45 seconds

**Effect Description**
Sets gravity to pull north, south, east, or west
Preferably made compatible with insane gravity and invert gravity.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/865
