### ISSUE TITLE
[Effect Suggestion] “How about I run this prick over with this thing?”

### ISSUE THREAD

**Issue by Jkw2021** [gta-chaos-mod/ChaosModV#1414]
**Name of effect**
“How about I run this prick over with this thing?”

**Effect Description**
A 5 second timer starts as if the effect has a duration. Then when the duration ends, you hear Trevor yell “How about I run this prick over with this thing?” and a large dock handler hits the player at supersonic speed killing them.

**Comment by DestroyerXyz** [comment]
"How about I run that prick over in this thing"

**Comment by pipecek** [comment]
So basically suicide...

**Comment by DestroyerXyz** [comment]
How about just spawning a dock handler?

**Comment by Jkw2021** [comment]
Just spawning one is fine but only if the voice line still plays.

**Comment by Last0xygen** [comment]
Then you can close it, as playing a specific line is not possible from what I know
