### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by ElijahFerris** [gta-chaos-mod/ChaosModV#1419]
tornado

long 

this is similar to gravity field but it pulls in a cirtain amount of objects (maybe 20 or so) that spin around the player almost like a forcefield hitting everything in its way. it should not pull in all objects since then the objects couldnt hit cars and peds etc. i dont think it should spin too fast since if i was the player, i would most likely want to see the objects hitting other objects as i go past them. maybe a rps of 4-5?

i think it should also (if possible. in not sure) maybe change the distance from the player. so it could start spinning from a radius of 1m from the player or the players car and then increase the radius to 5m after 10 seconds or so and then decrease back to 1m from the player.
it also could suck in more objects as it goes past. so by the end of the effect it could have 35- 50 objects spinning around the player

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/943 this

**Comment by Last0xygen** [comment]
Yup, seems like #943 😊
