### ISSUE TITLE
Consider adding velocity (or keep the velocity?) to the player when doing "Teleport to Heaven"

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#142]
Specifically this teleport targets a body of water and it can be annoying when your vehicle just sinks, especially if you are on a mission and fail. Provide some way to the players to save themselves, maybe by pushing them forward? What do you think?

I think velocity IS already being preserved, but sometimes you just don't have enough to reach land.

**Comment by pongo1231** [comment]
"Teleport To Heaven" might get changed to instead teleport the player to their current position at a much greater height instead

**Comment by TheRealAyCe** [comment]
A random place on the map but above land would probably also be fine. Otherwise it may become too similar to "Launch Player up"..?

**Comment by Last0xygen** [comment]
I guess adding a parachute and porting to a big height on the current position be the best change.
You‘d be „near heaven“ but always have a chance to survive with your parachute

**Comment by pongo1231** [comment]
Well true, but I feel more often than not it ends up with the player falling in the water and either dying or failing the mission by wrecking the vehicle they're in. Giving the player a parachute might also work but the player would need an indication they've received a parachute then.

**Comment by Last0xygen** [comment]
If the goal is to prevent the player from failing the mission by falling into water, then this may not be possible.
You could: 
- port with vehicle, if it’s a plane
- give parachute and port without car/bike/boat

But this would also potentially fail for any other mission triggers like follow missions or any distance checks.
So i don’t know if we can prevent all fail-triggers but this would prevent from a Safe Death by falling without a parachute and/or wrecking the car by falling into the sea

**Comment by MoneyWasted** [comment]
You could get all necessary mission entity's and teleport them to heaven with you. Would possibly help reduce the amount of fails due to distance.

**Comment by ProfessorBiddle** [comment]
You could also teleport the player below the map, that would cause them to fall for a while and (possibly) not fail the mission, but it would make the effect much less severe.

**Comment by MoneyWasted** [comment]
> You could also teleport the player below the map, that would cause them to fall for a while and (possibly) not fail the mission, but it would make the effect much less severe.
I think that would be better to call that "Teleport to Hell"

**Comment by MoneyWasted** [comment]
> You could also teleport the player below the map, that would cause them to fall for a while and (possibly) not fail the mission, but it would make the effect much less severe.

I think that should be called "Teleport to Hell"
