### ISSUE TITLE
[Effect Suggestion] Inverted controls

### ISSUE THREAD

**Issue by Shartist** [gta-chaos-mod/ChaosModV#1422]
**Name of effect**
Potential name(s) for the effect
Inverted controls, What is happening?

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Description of the effect; what should it do?
Invert the movement controls ex. Forward key would make u move backwards and vice versa, same could be applied to jump, which would change to stealth mode instead of jumping.

**Comment by Last0xygen** [comment]
Duplicate #16
