### ISSUE TITLE
[Effect Suggestion] Mat-o’s  fear

### ISSUE THREAD

**Issue by turtlebrowastaken** [gta-chaos-mod/ChaosModV#1425]
**Name of effect**
Mat-o’s fear
Mats nightmare 

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Spawn 100  Mountain lions

**Comment by turg-the-sad-cat** [comment]
This mod is not just for Matt, most people wouldn’t understand the reference and already been sort of suggested before

**Comment by Last0xygen** [comment]
* Not only for Matt 
* requested multiple times
* 100 spawns will crash the game
