### ISSUE TITLE
[Effect Suggestion] Teleport to Galileo Observatory

### ISSUE THREAD

**Issue by intermediocre** [gta-chaos-mod/ChaosModV#1427]
**name of effect**
Teleport to Galileo Observatory
Teleport to Daveyyy

**Duration Of Effect**
Teleport

**Effect Description**
Teleport to Galileo Observatory (Where the Daveyyyy thing is)

**Comment by kolyaventuri** [comment]
There's already quite a few teleport effects, so I'm not entirely sure what this adds to the mod

**Comment by SeanMirrsen** [comment]
> There's already quite a few teleport effects, so I'm not entirely sure what this adds to the mod

Another teleport location? Wasn't the whole point of the effect groups to enable us to add more of these kinds of things?

**Comment by kolyaventuri** [comment]
> > There's already quite a few teleport effects, so I'm not entirely sure what this adds to the mod
> 
> Another teleport location? Wasn't the whole point of the effect groups to enable us to add more of these kinds of things?

That's fair. I just wanna make sure we hit the happy-medium between fun effects and not _too_ many of the same effect.

**Comment by intermediocre** [comment]
I’m out of ideas I’m sowwy 🥺

**Comment by Last0xygen** [comment]
"Kind of" fulfilled with https://github.com/gta-chaos-mod/ChaosModV/pull/891 :)
