### ISSUE TITLE
[Effect Suggestion] Alt Strat

### ISSUE THREAD

**Issue by lumpofcoal123** [gta-chaos-mod/ChaosModV#1429]
**Name of effect**
Alt Strat

**Duration if timed effect (long or short timed?)**
short timed

**Effect Description**
Holds down the Alt button for you, the way DarkViperAU does in OHKO runs. The game is slow and it's hard to control your character.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1056

**Comment by pipecek** [comment]
Also, who's darkviperau???

**Comment by lumpofcoal123** [comment]
> Also, who's darkviperau???

Look him up. He does runs of GTA V trying not to take any damage, and Alt strat is significant part in it. He also plays chaos like every week.
