### ISSUE TITLE
[Effect Suggestion] Extreme Stalker Jesus

### ISSUE THREAD

**Issue by duckingducks** [gta-chaos-mod/ChaosModV#1431]
**Name of effect**
Extreme Stalker Jesus

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Spawn Jesus that follows you and tries to melee you. If he dies before timer is over, he gets revived at the end of the timer with super speed/strength and finds and melee you

**Comment by TheRealAyCe** [comment]
I mean, shouldn't Jesus get revived after a few ingame days anyway? :P

**Comment by DEATHCON1** [comment]
He should try to attack you when you have your back or camera turned.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
