### ISSUE TITLE
[Feature Suggestion] Explode every vehicle

### ISSUE THREAD

**Issue by Nextarity** [gta-chaos-mod/ChaosModV#1432]
**Name of effect**
Explode every vehicle

**Effect Description**
When your at the Maze bank you see car lights so there are cars everywhere on the map maybe you can make them explode?

(Yes I know it will cause lag)

**Comment by Last0xygen** [comment]
Already exists as "Explode All Nearby Vehicles"

**Comment by juhana** [comment]
The cars you see in the distance aren't actual vehicles, they're just a visual effect.
