### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#1436]
**Name of effect**
Gta 4 drunk

**Duration if timed effect (long or short timed?)**
1 minute

**Effect Description**
Description of the effect; what should it do?
The player will be drunk and it will be hard to walk,they will start to stumble like gta 4

**Comment by Last0xygen** [comment]
This is the "normal" drunk effect with the chance of falling over. "Porting" the GTA 4 drunk system is not possible, sorry
