### ISSUE TITLE
[Effect Suggestion] Spawn Chill Jesus

### ISSUE THREAD

**Issue by intermediocre** [gta-chaos-mod/ChaosModV#1438]
**Name of effect**
Spawn Chill Jesus
Spawn Dance Troop Jesus

**Effect Description**
It spawns Jesus doing the “In The Hood” dance with sunglasses on (it still plays the music though to scare the player)

**Comment by pipecek** [comment]
A) pretty useless and B) what music?

**Comment by TheRealAyCe** [comment]
Only real Dviper fans watch the livestreams instead of the highlights :P

**Comment by kolyaventuri** [comment]
Similar to #391 but I like the dancing aspect.

But the music is a no-go, that's not part of the mod. That's something DarkViperAU adds into the highlight reel in editing

**Comment by intermediocre** [comment]
I watch his full streams and the music is there, the “Our god is an awesome god?”

**Comment by turg-the-sad-cat** [comment]
It’s not there, you are watching his highlights episodes, he adds them in there, not in stream, not in the full chaos episode

**Comment by Last0xygen** [comment]
Yes, the music gets added by darkviper, not in the live stream.
Spawning „griefer Jesus“ that doesn’t attack you has already been requested several times.
Making him dance is not a great addition to this, sorry

**Comment by intermediocre** [comment]
Oh
