### ISSUE TITLE
[Effect Suggestion] The Birds

### ISSUE THREAD

**Issue by OrlandoSchaffer** [gta-chaos-mod/ChaosModV#1439]
-Effect Name:

The Birds/Attack Of The Birds/Hostile Birds

-Effect Duration:

120-180 Seconds 

-Effect Description:

Just like in the 1963 movie, “The Birds”, hostile birds will appear near the player to attack them and any NPC. They would deal fairly little damage since birds are not as strong as a larger animal. If you really want some laughs from people you could have them throw you out of your car just like if one were to have people throw the player out of the car when they have the “You’re Famous” effect.

**Comment by Last0xygen** [comment]
Getting hunted and hurt by peds exists via „all peds attack player“, via animals exists via „Bees“ ;P
Again seems like „All Peds Attack Player“ :/
