### ISSUE TITLE
[Effect Suggestion] Spawn Jesus and Brad

### ISSUE THREAD

**Issue by Plsstayfriendly** [gta-chaos-mod/ChaosModV#1440]
**Name of effect**
Spawn Jesus and Brad

**Effect Description**
Spawns Jesus and Brad in the getaway car from prolog. Jesus is driving and follows the player. Brad is in one of the back seats, shooting at the player. I think this would be really funny because in one of DarkViperAU's chaos runs (Link to the video: https://www.youtube.com/watch?v=7vxK8WD3xZM Timestamp: 6:40 and 8:20) Jesus took the wheel in prolog and beat the train. After the missonfail he kept driving around with Brad in the back seat. Later in the run the car literally got teleported to Los Santos by the effect "Teleport everything to player".

**Comment by turg-the-sad-cat** [comment]
People won’t understand that reference so I don’t think it’s a strong effect since it’s almost like Jesus take the wheel and spawn brad

**Comment by Plsstayfriendly** [comment]
But there is also the effect "can't tie my shoes" wich is kind of an insider too. And I think it would be really funny for those who do actually get the reference. I get your point tho. It would be similar to spawn blue sultan aswell.

**Comment by Last0xygen** [comment]
> But there is also the effect "can't tie my shoes" wich is kind of an insider too. And I think it would be really funny for those who do actually get the reference. I get your point tho. It would be similar to spawn blue sultan aswell.

For „can’t tie my shoes“ to „work“ you have to know exactly that, he can’t tie his shoes. This itself is a funny effect which does not need any background knowledge.
For your idea you have to know not only of darkviper and his chaos streams but this exact episode where this happened for a brief moment. The effect on its face value is kind of just an easier „Spawn Balla Squad“ or „Peds drive by shooting“, sorry.
