### ISSUE TITLE
[Effect Suggestion] 3D Universe Time

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1444]
**3D Universe Time**

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
The clock ticks twice as fast (Explanation: 1 IRL Second per in-game minute (or 24 minute per in-game day) instead of 2 IRL Second per in-game minute in IV and V)

**Comment by Last0xygen** [comment]
Already exists via „Timelapse“

**Comment by RosyMiranto18** [comment]
Timelapse is the speed up clock to the extreme while this one is only 2X as well. It's surely different, right?

**Comment by Last0xygen** [comment]
Yeah, the increase is different, but do we need another effect for a slower timelapse?

**Comment by RosyMiranto18** [comment]
Uh... Yeah, that is true.
