### ISSUE TITLE
[Effect Suggestion] Flip the Screen/The Mirror 

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1445]
**Flip Screen/The Mirror**

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Mirror the Screen Sideways, hopefully you realize to turn right to go left. Be careful when it’s paired with Turn Turtle.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/762
