### ISSUE TITLE
[Effect Suggestion] Mercenary (Tweak and Buff)

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1448]
**Mercenary (Tweak and Buff)**

**Duration if timed effect (long or short timed?)**
Buff

**Effect Description**
The Merryweather AI are now buffed to have an Aimbot Aim, constantly driving you using AP Pistol, if they exit the vehicle, they’re equipped with Assault Shotguns and Special Carbines. Their Mesas are now explosive proof (if not outright indestructible). There's another Helicopter chasing you as surveillance. They will rubberband in chasing you (i.e. you can’t shake them off normally) or they will chase you in packs.
Now you can get the true Merryweather Fleets Here Bro experience.

**Comment by Last0xygen** [comment]
The thing about the effect is not to easily kill the player all the time but for the layer to be hunted. If they get Aimbot and the carabine it’s not really a hunt but a safe death
