### ISSUE TITLE
[Effect Suggestion] Lag and Deja Vu (Tweaking)

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1449]
**Lag Tweaks and Deja Vu**

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
The Lag is tweaked to the old version where it’s just regular stuttering and rendering issue, while the current Lag is now renamed to Déjà vu.

**Comment by Last0xygen** [comment]
Slowing the game down/stuttering ist already a thing with „Consile experience“ which limits the game to 25 FPS 😅
