### ISSUE TITLE
Check "Vehicles explode on impact"

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#145]
This might not work reliably. Vehicles bump into things yet they don't explode. How hard do they need to impact?

**Comment by pongo1231** [comment]
Works perfectly fine locally on the newest game version.

**Comment by Last0xygen** [comment]
Working just fine on SocialClub and Epic

**Comment by TheRealAyCe** [comment]
¯\_(ツ)_/¯  I will post a video link with timestamps next time I see it happening.

**Comment by TheRealAyCe** [comment]
@pongo1231 @Last0xygen 
https://www.twitch.tv/videos/788445945?filter=archives&sort=time around 51:30

**Comment by pongo1231** [comment]
He likely still runs 1.7.5 since "Beyblades" also shows the old behavior (it doesn't affect parked vehicles for him, while it does on 1.7.5.1). The latest version fixed that effect not working on the newest game build.

**Comment by TheRealAyCe** [comment]
Ah, thanks for clearing that up! Someone tell him to upgrade! ;) Fixed then, right?

**Comment by pongo1231** [comment]
I'll reopen this if someone can confirm this effect not working for them on the latest game build
