### ISSUE TITLE
[Effect Suggestion] No Braking Allowed (Tweaks and Buff)

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1450]
**No Braking Allowed (Tweaks and Buff)**

**Duration if timed effect (long or short timed?)**
Buff

**Effect Description**
Now not only regular brakes won’t work, but the handbrake also didn’t work as well.

**Comment by Last0xygen** [comment]
Isn’t this already part of „no breaking allowed“?

**Comment by RosyMiranto18** [comment]
Wait, it is? I thought you can still use Handbrake on this effect. If it is, then you can close it down.

**Comment by Last0xygen** [comment]
Im 99.99% sure 😅
