### ISSUE TITLE
[Effect Suggestion] Fake Fake Fake Crash (Super Fake Crash)

### ISSUE THREAD

**Issue by Stanley40001** [gta-chaos-mod/ChaosModV#1452]
Fake Fake Fake Crash (Super Fake Crash)

It will first operate the same as the normal fake crash and show "fake crash" after the first crash ended, then the game will fake crash again and show "Fake Fake Fake Crash (Super Fake Crash)" after the second crash.

**Comment by Last0xygen** [comment]
This could go on several more levels.. one level is enough though ;)
