### ISSUE TITLE
[Effect Suggestion] Retribution

### ISSUE THREAD

**Issue by Stanley40001** [gta-chaos-mod/ChaosModV#1453]
Retribution (Heavenly hour)

**Duration if timed effect (long or short timed?)**
long ( Same as mercenaries)

It will work similar to mercenaries but with Jesus NPCs, they'll also be equipped with better weapons(maybe all railguns?) and vehicles, though with very poor accuracy.

**Comment by Last0xygen** [comment]
Spawning multiple Jesus has already been requested several times
