### ISSUE TITLE
[Effect Suggestion] The Ultimate Jesus

### ISSUE THREAD

**Issue by Spinni49** [gta-chaos-mod/ChaosModV#1456]
**Name of effect**
Ultimate Griefer Jesus

**Effect Description**
Spawn Jesus on a tractor (the rusty old one) with an explosive sawed of shotgun (you can change the weapon if you want)
And maybe give the tractor a better engine.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
