### ISSUE TITLE
[Effect Suggestion] Poseidon

### ISSUE THREAD

**Issue by CptnBrt** [gta-chaos-mod/ChaosModV#1458]
**Name of effect**
Poseidon

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
In a certain radius around the player, water should rise to a height of 5m (for example)
If impossible to code:
The whole sea level should rise (not in radius of the player) Just like in the tsunami mod

**Comment by juhana** [comment]
Water level can't be changed during the game. Already requested multiple times (#1238, #748, #729, #623, #622, #619)
