### ISSUE TITLE
Issue creation: Tell people how to look for duplicates

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#1461]
I see a lot of issues opened to suggest the same ideas. Maybe this is because people don't know how to look for duplicates? Maybe it would help to suggest to people to use the search before opening an issue and tell them how to do it?

**Comment by pipecek** [comment]
> I see a lot of issues opened to suggest the same ideas. Maybe this is because people don't know how to look for duplicates? Maybe it would help to suggest to people to use the search before opening an issue and tell them how to do it?

I agree a lot. If I had 1 dollar x the squared amount of cougar threads I'd have 256 dollars

**Comment by pongo1231** [comment]
#1506
