### ISSUE TITLE
[Effect Suggestion] No Cheating in PVP

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1466]
**Name of effect**
No Cheating in PVP

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
All damages received from Rockets, Grenades, Exploding Cars, Vehicle Weaponry (like Tank Cannons or Buzzard Machine Gun) and even Fire are nullified for everyone temporarily both players and enemies Don't be a noob spamming RPGs and get back to your bullets.

**Comment by Last0xygen** [comment]
Already exists as „everyone is invincible“
