### ISSUE TITLE
[Effect Suggestion] The voices told me to do it

### ISSUE THREAD

**Issue by neovidas** [gta-chaos-mod/ChaosModV#1478]
**Name of effect**
The voices told me to do it

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Takes random dialog lines and plays them making you feel like you got voices in your head (would be even better if they were aggresive telling you to kill someone or just funny ones

**Comment by Last0xygen** [comment]
Currently not possible, but requested already several times
