### ISSUE TITLE
Meta Effect 

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#1481]
**Name of effect**
Jesus Time

**Duration if timed effect (long or short timed?)**
3 to 4 minutes long

**Effect Description**
The only option people can pick from is Jesus options

**Comment by turg-the-sad-cat** [comment]
I don’t think it’s that unique to make a meta effect where you can only pick 3 options

**Comment by Last0xygen** [comment]
if someone wants to play like this, they can enable only those.
I don't think this is a good addition to the mod
