### ISSUE TITLE
[Effect Suggestion] Turn on the MP3 Player

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1487]
**Name of effect**
Turn on the MP3 Player

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
On foot, the Mobile Radio (feature from the Native Mod, etc.) will turn on at random Stations. If you're in a car, your radio station is only simply randomly changed. The radios can't be changed back or turned off (other than the Pause Menu) until the effect runs out. If you're a Streamer, beware of the Copyright.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/428
