### ISSUE TITLE
[Effect Suggestion] Replace All Nearby Vehicles

### ISSUE THREAD

**Issue by Aran8276** [gta-chaos-mod/ChaosModV#1488]
**Name of effect**
Replace All Nearby Vehicles

**Duration if timed effect (long or short timed?)**

**Effect Description**
Replace all vehicles with random vehicles, simply a random traffic but it replaces literally anything without timer

**Comment by Last0xygen** [comment]
So „Random Traffic“? 😅
The timer is just there to replace every vehicle in range as it can only replace some vehicles per cycle. Removing the timer is not a valid new effect imho
