### ISSUE TITLE
"Insane / Invert Gravity" crashes on newest game build

### ISSUE THREAD

**Issue by pongo1231** [gta-chaos-mod/ChaosModV#150]
Causes a mod (not game) crash, the signature they rely on might've changed in the newest build.

**Comment by Last0xygen** [comment]
It works just fine for me (Socialclub Edition).
You're using the steam-version, right?

**Comment by pongo1231** [comment]
Correct, I'm on the steam version. Anyone else with either the R* or Steam version able to confirm this?

**Comment by Last0xygen** [comment]
Just testet the EpicGames version, working there as well

**Comment by pongo1231** [comment]
@Last0xygen Are you able to test the changes on the fix-gravity branch? Works on Steam again now and I want to ensure I didn't break anything on the other versions.

**Comment by Last0xygen** [comment]
Will do

**Comment by Last0xygen** [comment]
Looks good. Working for SocialClub and Epic Version
