### ISSUE TITLE
[Effect Suggestion] Gang Attack

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1501]
**Name of effect**
Gang Attack

**Duration if timed effect (long or short timed?)**
 One-time

**Effect Description**
Spawn 10-30 random gang members as enemies in around 20 meters around you (from one of these groups: The Lost, Merryweather, Avery's Professionals, The Families, Vagos, The Armenians, Triads, and Marabunta) They are wielding random weapons of Handguns, Shotguns, SMGs, Rifles, and Projectile categories.

**Comment by Last0xygen** [comment]
Difference to „killer clowns“ is the ped model and weapon, not a real difference imo

**Comment by RosyMiranto18** [comment]
Well, there's some notable difference. I'm sure that Killer Clowns spawns one by one and they can despawn. Meanwhile Gang Attack reveals ALL of the Enemies at once, so you're easy to get surrounded if not carefully. Perhaps i should increase the weapon variety to everything other than Heavies (no rockets railguns) but Minigun have a very small chance to show up.

**Comment by Last0xygen** [comment]
Yes, it spawns clown by clown by design, as spawning multiple enemies at once (10-20) is a good start to crash the game. Spawning that many enemies is also just an instant kill every time.
Killer clowns were 5 clowns spawning at once, now they are spawning one by one ;)
