### ISSUE TITLE
[Effect Suggestion] Set Player Into Passing Aircraft

### ISSUE THREAD

**Issue by TheAmberArrow** [gta-chaos-mod/ChaosModV#1503]
**Name of effect**
Set Player Into Passing Aircraft or Set Player Into Overhead Aircraft

**Effect Description**
There’s lots of helicopters, blimps, fighter jets and passenger jets flying around on the map. A sudden switch into an aircraft could come with lots of creative uses.

**Comment by Last0xygen** [comment]
Already exists in "Set player Into Random Vehicle / Seat" :)
