### ISSUE TITLE
[Effect Suggestion] There are cougars in missions!

### ISSUE THREAD

**Issue by Rmn98** [gta-chaos-mod/ChaosModV#1505]
**Name of effect**
There are cougars in mission!

**Duration if timed effect (long or short timed?)**
not timed

**Effect Description**
If the player is in a mission, the effect spawns a cougar that will attack the player. It's a reference to a DarkViperAU meme that came about when Matt was doing OHKO and a cougar appeared in a mission that killed him and caused the run to die.

**Comment by kolyaventuri** [comment]
Already suggested multiple times, see #680, #343, or #1215.

**Comment by pipecek** [comment]
Might aswell start requesting "kill all cougars"
