### ISSUE TITLE
[Effect Suggestion] List of new suggestions (new enemies, new vehicles, new spawn locations, etc)

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1509]
**Spawn Bombushka**
Not timed
Spawn the largest and slowest plane in GTA, the RM-10 Bombushka
https://gta.fandom.com/wiki/RM-10_Bombushka

**Spawn FH-1 Hunter Attack Chopper**
Not timed
Spawn one of the more destructive helicopters in the game
https://gta.fandom.com/wiki/Hunter

**Spawn Random Plane**
Not timed
There are many, many cool planes in GTA online that could be spawned at random locations

**Spawn Random Fully Upgraded Arena Wars Vehicle**
Not timed
I think this would be fun as these vehicles have very neat features, like spikes, spinning side blades, front facing cannons, flame throwers, and the ability to shunt boost, knock most cars out of the way and etc.
There is a lot in this list, so I'm just going to leave a URL of all the vehicles:
https://gta.fandom.com/wiki/GTA_Online:_Arena_War#Vehicles

**Spawn Into Random Boat**
Not timed
The Cayo Perico heist added some new boat types, and it would be fun to be able to spawn the player into a random boat in the ocean or the Alamo sea to be stuck out there and have to get to land. Could also work as a fake teleport.

**Spawn Import/Export Special Vehicles**
Not timed
Spawn a random weaponized/"knock cars out of the way" vehicle from the Import/Export update.
These vehicles include:
- BF Ramp Buggy (type without spoiler only works on around 75 cars before it starts smoking, the one with the spoiler is unlimited)
- Brute Armored Boxville
- Coil Rocket Voltic
- Imponte Ruiner 2000
- Jobuilt Phantom Wedge
- Karin Technical Aqua
- Nagasaki Blazer Aqua

**Spawn Random Super Car and/or Sports Car**
Not timed
Again, there are hundreds of super and sports car planes in the online portion of the game and it would nice to see some of these added to Chaos mod

**Forced to Play Qu3bd or Other Arcade Game, If Fail Then Die**
30-120 seconds
Since the Casino heist, R* added a ton of arcade games, included Qu3bd from GTAIV, to the game. It would be funny for an arcade screen to open up, like the hacking module, and the player to be forced to play a random arcade game for 30-120 seconds and if they fail they die

**Spawn Bigfoot/Sasquatch (Enemy Type)**
Not Timed
The Sasquatch is found in default GTAV through a series of 100% completition. The Sasquatch is slow but has super punch and could be very tanky like Impotent Rage.
https://gta.fandom.com/wiki/Bigfoot

**Spawn Beast (Enemy Type)**
Not Timed
Like the Sasquatch, the beast is found in default GTAV through a series of Easter Eggs. He is very tanky and can super punch and super jump, as well as run very fast
https://gta.fandom.com/wiki/Beast

**Forced Take Ursula on a Date**
Not timed
This could be similar to the 'teleport to random mission' effect where you have to pick up Ursula and drive her all the way up to the North East side of the map.
https://gta.fandom.com/wiki/Ursula

**Spawn Into Altruist's Camp**
Not timed
The Altruists Camp is similar to being spawned into Fort Zancudo as all the enemies will agro onto the player and kill them. Could also work as a fake teleport.
https://gta.fandom.com/wiki/Altruist_Camp

**Spawn to Grove Street in a Police Car**
Not timed
Although it's been a long time since I've tested this, I believe if you show up on Grove street in a police car, all the enemies will start attacking the player because they think they're police. Can someone confirm if this still works?

**Spawn to North Yankton**
Not timed
Spawn the player into the North Yankton part of the map. This might require the placement of random grenades, sticky bombs, a car, or a helicopter otherwise the player would be stuck in NY. Although at some points the player can fall through the map into the ocean, it is a long swim back to shore. This could also work great as a fake Teleport.

**Spawn to Cayo Perico**
Not timed
I'm not sure if this is doable since it's an online only feature of the game, but it would be very cool to see players being spawned into this location. Again, would probably need some type of instrument to suicide or plane/helicopter/boat to leave the island.

**Spawn Onto Aircraft Carrier**
Not timed
The USS Luxington (ATT-16) is an aircraft carrier that spawns way out in the ocean where North Yankton is. The enemies will agro onto the player, but there are jets and I believe helicopters to get off the aircraft carrier. Could also work as a fake teleport.
https://gta.fandom.com/wiki/USS_Luxington_ATT-16

**Spawn Into Interior of Buildings (like Bahama Mamas, Tequila-la-la, etc)**
Not timed
This would require the mod Open All Interiors v5.1 mod for the game. There are many interiors of buildings that you can't usually access. With the Open All Interiors mod, the player can be spawned into all sorts of locations like police stations, night clubs, tattoo parlors and the other normally inaccessible parts of the interiors. I believe this mod will also let you leave through the door and not lock you in. Could also work as a fake teleport.
https://www.gta5-mods.com/scripts/open-all-interiors

Feel free to let me know your feedback on my suggestions. Thanks for taking the time to read through this, I spent weeks thinking long and hard about new effects that could be added, so I hope some of these make it into the new Chaos update script.
-pogue

**Comment by Thunderstorm64** [comment]
Effects shouldn't require outside mods like Open All Interiors. However I think a couple of these would be okay

**Comment by pogue** [comment]
Perhaps the Open All Interiors mod could be integrated into Chaos?

**Comment by TheRealAyCe** [comment]
You probably should close this ticket and open a separate ticket for every suggestion, like all others do it. This makes it easier and more convenient to respond to the suggestions and keeps discussions tighter.
I can already tell you that many of them will be rejected, since they have already been suggested (please use the search before posting). Some of them are still open, some of them (like use GTA Online content) were closed because it's not possible to do. So far no suggestion that includes integrating another mod was accepted.

**Comment by pogue** [comment]
Alright, I'll make a separate post for every single suggestion I made. I really don't like jumping through hoops just to come on here and make suggestions for a pretty casual project, but I'll do it if you think it'll help,

In order to spawn any GTA Online vehicle you also have to have a separate mod installed, btw.

**Comment by TheRealAyCe** [comment]
¯\_(ツ)_/¯ understandable, but you also have to keep in mind the sanity of the people actually doing the programming. If you don't like to do things by the rules of this project you could maybe post it in Discord and hope someone else will fill in the tickets here appropriately. As you can see we have ~700 open tickets, most of them suggestions, so I don't think anyone will beg for more to be posted.

**Comment by pogue** [comment]
Well, I reposted them all individually, so hopefully they will be reviewed or discussed. All of these suggestions are doable in the context of GTA Single Player and would enhance the fun of the mod. So, hopefully I'm not coming here just wasting everyone's time and I hope the programmers will consider my suggestions.
