### ISSUE TITLE
[Bug] Debug menu does not work for custom LUA effects

### ISSUE THREAD

**Issue by Goorakh** [gta-chaos-mod/ChaosModV#1516]
**Describe the bug**
If you have a custom LUA effect, you cannot activate it through the debug menu (CTRL+,)

**To Reproduce**
Have some custom LUA effect in the custom_scripts folder.
(re)Start the mod and/or game
Open the effects debug menu with CTRL+,
Find the custom LUA effect in the list
Attempt to start the effect

**Crash Dump (if a game crash)**
No crash

**Comment by SeanMirrsen** [comment]
Just to be sure, did you do a sanity check?

As in, deactivate all other effects and try running the game. Make sure your effect works in the first place, etc.

**Comment by Last0xygen** [comment]
Could you please attach the Luca script so I/we can check it ourself? 😊

**Comment by Goorakh** [comment]
> 
> 
> Just to be sure, did you do a sanity check?
> 
> As in, deactivate all other effects and try running the game. Make sure your effect works in the first place, etc.

Yes, I was still able to activate the custom effect by disabling every other effect and letting the timer reach the end. No error messages showed up in the mod's log either.

**Comment by Goorakh** [comment]
> 
> 
> Could you please attach the Luca script so I/we can check it ourself? 😊

I'm very sure it affects all LUA effects, I made a dummy one to confirm though. (Git doesn't support .lua files, so I have to send it as a txt)
[cant_be_activated.txt](https://github.com/gta-chaos-mod/ChaosModV/files/6642838/cant_be_activated.txt)

**Comment by Last0xygen** [comment]
Alright, found the error, i'll create a PR . Thanks for reporting
