### ISSUE TITLE
Mercenaries attacking each other?

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#152]
https://www.twitch.tv/videos/788445945?filter=archives&sort=time
at about 59:50

It's funny, but it probably should not happen, right?

**Comment by Last0xygen** [comment]
@TheRealAyCe as my last changes haven’t been released yet I would wait for that 😅 
But yeah, they shouldn’t attack each other ;)

**Comment by Last0xygen** [comment]
Hm, I took another look.
I guess we should add 
SET_BLOCKING_OF_NON_TEMPORARY_EVENTS
And reapply the task every few ticks.
I‘ll look into it again 😅

**Comment by juhana** [comment]
Mercenaries (and Killer Clowns) are still attacking each other.
