### ISSUE TITLE
[Effect Suggestion] Spawn Random Fully Upgraded Arena Wars Vehicle

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1524]
**Spawn Random Fully Upgraded Arena Wars Vehicle**
Not timed
I think this would be fun as these vehicles have very neat features, like spikes, spinning side blades, front facing cannons, flame throwers, and the ability to shunt boost, knock most cars out of the way and etc.
There is a lot in this list, so I'm just going to leave a URL of all the vehicles:
https://gta.fandom.com/wiki/GTA_Online:_Arena_War#Vehicles

**Comment by Last0xygen** [comment]
this should already work with "Spawn Random Vehicle". As Online vehicles despawn themselves if no other mod to persist them is present, they are often not really usable. There is already someone working on that though :)
