### ISSUE TITLE
[Effect Suggestion] Spawn Into Random Boat

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1525]
**Spawn Into Random Boat**
Not timed
The Cayo Perico heist added some new boat types, and it would be fun to be able to spawn the player into a random boat in the ocean or the Alamo sea to be stuck out there and have to get to land. Could also work as a fake teleport.

**Comment by Last0xygen** [comment]
already works with "Set Player Into Random Seat" or "Set Player into Random Vehicle".
