### ISSUE TITLE
[Effect Suggestion] Spawn Import/Export Special Vehicles

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1526]
**Spawn Import/Export Special Vehicles**
Not timed
Spawn a random weaponized/"knock cars out of the way" vehicle from the Import/Export update.
These vehicles include:
- BF Ramp Buggy (type without spoiler only works on around 75 cars before it starts smoking, the one with the spoiler is unlimited)
- Brute Armored Boxville
- Coil Rocket Voltic
- Imponte Ruiner 2000
- Jobuilt Phantom Wedge
- Karin Technical Aqua
- Nagasaki Blazer Aqua
https://gta.fandom.com/wiki/GTA_Online:_Import/Export#Vehicles

**Comment by Last0xygen** [comment]
Already possible with "Spawn Random Vehicle"

**Comment by pogue** [comment]
Yes, but my suggestion is to spawn these vehicles specifically as an option, not just spawn random vehicle. These vehicles are special and have special abilities, like boost, machine guns, missiles, etc. They are in a special class of vehicles and more than likely would not spawn with "spawn random vehicle". I have never seen it.
