### ISSUE TITLE
[Effect Suggestion] Spawn Random Super Car and/or Sports Car

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1527]
**Spawn Random Super Car and/or Sports Car**
Not timed
Again, there are hundreds of super and sports car planes in the online portion of the game and it would nice to see some of these added to Chaos mod

**Comment by Last0xygen** [comment]
Already possible with "Spawn Random Vehicle", but may require the implementation of https://github.com/gta-chaos-mod/ChaosModV/pull/1359
