### ISSUE TITLE
[Effect Suggestion] Spawn Bigfoot/Sasquatch (Enemy Type)

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1529]
**Spawn Bigfoot/Sasquatch (Enemy Type)**
Not Timed
The Sasquatch is found in default GTAV through a series of 100% completition. The Sasquatch is slow but has super punch and could be very tanky like Impotent Rage.
https://gta.fandom.com/wiki/Bigfoot

**Comment by DEATHCON1** [comment]
Diplicate of #1260
