### ISSUE TITLE
[Effect Suggestion] Spawn Into Altruist's Camp

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1532]
**Spawn Into Altruist's Camp**
Not timed
The Altruists Camp is similar to being spawned into Fort Zancudo as all the enemies will agro onto the player and kill them. Could also work as a fake teleport.
https://gta.fandom.com/wiki/Altruist_Camp

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/478
