### ISSUE TITLE
[Effect Suggestion] Spawn to North Yankton

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1534]
**Spawn to North Yankton**
Not timed
Spawn the player into the North Yankton part of the map. This might require the placement of random grenades, sticky bombs, a car, or a helicopter otherwise the player would be stuck in NY. Although at some points the player can fall through the map into the ocean, it is a long swim back to shore. This could also work great as a fake Teleport.

**Comment by Last0xygen** [comment]
North Yankton has to be loaded into memory for this to work, also you would just be stuck there 😓
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1162
