### ISSUE TITLE
[Effect Suggestion] Spawn to Cayo Perico

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1535]
**Spawn to Cayo Perico**
Not timed
I'm not sure if this is doable since it's an online only feature of the game, but it would be very cool to see players being spawned into this location. Again, would probably need some type of instrument to suicide or plane/helicopter/boat to leave the island.

**Comment by turg-the-sad-cat** [comment]
Already been suggested before, closed because it’s not possible

**Comment by pogue** [comment]
Ok, not a problem. Just a thought!
