### ISSUE TITLE
[Effect Suggestion] Spawn as RC car/Drone/Mini Tank

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1538]
**Spawn as RC car/Drone/Mini Tank**
Possibly not timed/possibly 60-120 seconds

You could spawn in as a drone, a mini RC car or mini tank. This would allow the player to become these vehicles, like in GTA online and drive/fly around in them. I'm not sure it would be a good idea to allow them to detonate, but the player could return out of one of these vehicles after 60-120 seconds or so.

**Comment by Last0xygen** [comment]
This should already be possible with "Spawn Random Vehicle" :)

**Comment by pogue** [comment]
No, these vehicles are in a special class. Random vehicle will only spawn regular street vehicles.

**Comment by Last0xygen** [comment]
"Spawn Random Vehicle" uses all possible vehicles and selects one at random, it is not limited to "street vehicles"

**Comment by pogue** [comment]
I don't want to get into an argument about this, but spawning into a drone is completely different than spawning into vehicle. It requires special access to get into the drones. The RC car and RC tank might spawn, but I've never seen it in a chaos stream and I've watched a lot of them.

**Comment by turg-the-sad-cat** [comment]
1. It’s closed, no reason to continue on, 2. You are arguing with someone that knows the ins and outs of the mod and knows a whole lot more about the mod than you

**Comment by Last0xygen** [comment]
> 1. It’s closed, no reason to continue on, 2. You are arguing with someone that knows the ins and outs of the mod and knows a whole lot more about the mod than you

No need to „defend“ me. He has all the rights to comment to question the reason.

As I Said, we use a method of loading all available vehicle types from memory. These should include all online and special vehicles.
If you never saw one it may be because there was no mod additionally present that enables said only vehicles

**Comment by turg-the-sad-cat** [comment]
I’m sorry
