### ISSUE TITLE
No radar does not work?

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#154]
https://www.twitch.tv/videos/788445945?filter=archives&sort=time
at about 2:18:25

Isn't the radar the minimap?

**Comment by Last0xygen** [comment]
Yup, can confirm, DISPLAY_RADAR doesn't seem to work anymore 🤔

**Comment by MoneyWasted** [comment]
It seems to be an issue with GTA it's self as in FiveM the native works perfectly fine (at least from my testing).

**Comment by ProfessorBiddle** [comment]
On my Epic Games client the radar seems to flicker and intermittently disable.

**Comment by TheRealAyCe** [comment]
Seems to work for "No HUD" though?
https://www.twitch.tv/videos/804409699 at ~2:31:15

**Comment by Last0xygen** [comment]
Yes, no hud works for me too, but that’s a broader effect than „no radar“ which also includes all other hud elements

**Comment by TheRealAyCe** [comment]
@Last0xygen 
https://youtu.be/riFd668i8sE?t=1360 Apparently it works again? You fixed it?

**Comment by Last0xygen** [comment]
I didn’t do anything 🤷‍♂️
maybe the new scripthook version fixed the native calls 😅

**Comment by pongo1231** [comment]
Well it's fixed now
