### ISSUE TITLE
[Effect Suggestion] Disguised Crash

### ISSUE THREAD

**Issue by LohenFeuer** [gta-chaos-mod/ChaosModV#1542]
**Name of effect**
Disguised Crash

**Effect Description**
It shall make the Fake Crash less obvious by adding other effects before it. For example: First Doomsday is activated (it's shown as an effect) --> Then Console Experience is activated after one or two seconds (it's not shown as an effect) --> After one or two seconds again Fake Crash is activated.
This way Matto will probably think that Doomsday caused the game to crash because too much happened. The first effect should always be something that is very chaotic like Doomsday, Teleport Everything To Player, Gravity Field, etc. The second one should indicate that the game has problems handling the first effect. A freeze or stuttering would be perfect. And finally there is the common Fake Crash. It's also important that the timings and effects should be random, else Matto will notice the pattern the second time it's occuring.

**Comment by Last0xygen** [comment]
Already suggested several times (also this mod ist not only for DarkViper ;) )

**Comment by pipecek** [comment]
Who's matto?

**Comment by jdefgh** [comment]
Matto-n deez nuts

**Comment by pipecek** [comment]
> 
> 
> Matto-n deez nuts

what?
