### ISSUE TITLE
[Effect Suggestion] Get Towed

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1543]
**Name of effect**
Get Towed

**Duration if timed effect (long or short timed?)**
One-Time

**Effect Description**
Attach your current car to the tow of a freshly spawned Towtruck in front of you (randomized between the Slamvan and Yankee Variant) whether you take the Tow Truck to deattach it or to drive it yourself it's up to you.

**Comment by DEATHCON1** [comment]
Should there be an npc driving the towtruck and should the npc follow a waypoint?

**Comment by SeanMirrsen** [comment]
I don't remember the name of the woman who has Franklin do towing missions, but it should probably be either Franklin or her.

I also don't have much faith in the ability of an NPC to follow a nav route with a towed car, but if they do follow one, I think it should be to the tow yard where the towing missions usually end. Sort of a differently themed Reposession effect.

**Comment by RosyMiranto18** [comment]
Franklin already did the Repossession gag, so the woman (Tonya) should do it. Actually, let's do it like this, the Slamvan version is spawned with nobody driving it while the Yankee version is spawned with Tonya driving.
