### ISSUE TITLE
[Bug] Deadeye does not work against peds in vehicles and with minigun

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#1545]
https://www.twitch.tv/videos/1055780849
~1:43:26

**Comment by Last0xygen** [comment]
Doesn’t work with any weapon against peds in vehicles sadly

**Comment by TheRealAyCe** [comment]
> 
> 
> Doesn’t work with any weapon against peds in vehicles sadly, I know

And minigun might suffer from the same problem as with rapid fire? Maybe that is fixable at least?

**Comment by Last0xygen** [comment]
i excluded minigun and hellbringer, just like with the rapidfire mod.
Something about the "powering up" with right click seems to make it not be able to shoot programmatically 🤷‍♂️
