### ISSUE TITLE
[Suggestion] Effect: Player leaves a trail of Proximity Mines

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#155]
The mines that explode when you walk on them, if I'm calling them right. 

Pretty self-explanatory. I don't really know though how long mines take to explode, so you might need to code them to take longer.

Yes, I guess it's somewhat similar to Help My W Key is Stuck, but slightly more difficult, and you won't be able to survive in all situations.

**Comment by MoneyWasted** [comment]
If one mine explodes all the other mines near it explode. This would practically be a suicide effect.

**Comment by ReiDaTecnologia** [comment]
Would be cooler if the mines was placed randomly around the player with a good enough distance so the player can try to avoid them (The effect would end after X time or if the player is killed by one of the proximity mines). Just a random idea that came into mind that i wanted to share, probably too complex or duplicated.

**Comment by MoneyWasted** [comment]
Yea who knows. If someone finds a better way to do it open another suggestion. This suggestion is over 2 years old anyway and its buried pretty deep.
