### ISSUE TITLE
[Effect Suggestion] Thermal Vision

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1552]
**Name of effect**
Thermal Vision

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Forces a Thermal Vision on you regardless of weapons in your hand. It may help you spot the enemies, but... just be careful when driving please.

**Comment by Last0xygen** [comment]
Already exists as „heat vision“

**Comment by RosyMiranto18** [comment]
Oh, i guess i really misread the actual effect's name. Sorry about that :D
