### ISSUE TITLE
[Feature Suggestion] Effect applies 1 frame after name appears so you can see which effect caused a crash

### ISSUE THREAD

**Issue by glibg10b** [gta-chaos-mod/ChaosModV#1558]
**Problem**
When the game crashes because of a chosen effect, you don't know which effect caused it

**Solution**
Either:
- Apply the effect 1 frame after its name appears
- Display the name 1 frame before the effect applies 

The effect's name will be on screen before the effect causes the game to crash, so we get to see which effect crashed the game when it is frozen.

**Comment by Last0xygen** [comment]
Theres a log file In the chaosmod folder logging all effects dispatched, you can look there after a crash :)
