### ISSUE TITLE
[Meta Effect Suggestion] Rigged Voting

### ISSUE THREAD

**Issue by Enderneer** [gta-chaos-mod/ChaosModV#1561]
**Name of effect**
Rigged Voting

**Duration if timed effect (long or short timed?)**
Long timed. Around a minute and 30 seconds.

**Effect Description**
If Twitch is controlling chaos while this meta effect is active, then the chaos effect that has the LOWEST votes will ALWAYS be chosen.

**Comment by BartWijshake** [comment]
This effect shouldn't be visible to chat though I feel otherwise they can manipulate the vote to more reliably pick options they want.

**Comment by TheRealAyCe** [comment]
I don't think that is a problem. The confusion of chat when they try to communicate to everyone that they now need to balance the votes AGAINST le funni teleport sounds like a good thing.

Not sure we should go with "always" though. Maybe eliminate all options by a likelihood based on vote count until only 1 option remains? (Reversal of likelihood. How else could you do that? Hmm...)

**Comment by SeanMirrsen** [comment]
> 
> 
> I don't think that is a problem. The confusion of chat when they try to communicate to everyone that they now need to balance the votes AGAINST le funni teleport sounds like a good thing.
> 
> Not sure we should go with "always" though. For determining the chosen effect, maybe eliminate all options by a likelihood based on vote count until only 1 option remains? (Just an idea for a "reversal" of the likelihood. How else could you do that? Hmm...)

I suggested a possible method back when I made the same metaeffect suggestion in #523 . :)

**Comment by Last0xygen** [comment]
Yeah, it’s a duplicate #523

**Comment by TheRealAyCe** [comment]
> I suggested a possible method back when I made the same metaeffect suggestion in #523 . :)

Yes, you did actually. Didn't even remember there was a ticket already. Funny that we came up with the same mechanic. :D
