### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by AlekB16** [gta-chaos-mod/ChaosModV#1562]
**Name of effect**
Potential name(s) for the effect
Random Waypoint

**Effect Description**
Description of the effect; what should it do?
It randomly put a Waypoint on the map

**Comment by TheRealAyCe** [comment]
Already done: https://github.com/gta-chaos-mod/ChaosModV/pull/1368

**Comment by Last0xygen** [comment]
Done #1368
