### ISSUE TITLE
Effect Suggestion: Judas

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#1563]
**Name of effect**
Spawn Companion Jesus but turns to Judas

**Duration if timed effect (long or short timed?)**
1 minute long

**Effect Description**
It spawns a Companion Jesus that help you out but when the timer runs out he will turn on you and start to shoot you. So it says Spawn Companion Jesus on the vote but when the timer runs out it will change and say Judas.

**Comment by aimlessB** [comment]
Very cool I like the Bible reference

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.

**Comment by EonYears** [comment]
I posted this ides 3 years ago. So why make a comment about it now.

**Comment by MoneyWasted** [comment]
> I posted this ides 3 years ago. So why make a comment about it now.

I’m currently reviewing the extensive list of open suggestions from the past four years. To ensure clarity and prevent any misunderstandings about why certain suggestions are being closed, I will leave a brief comment on each one giving the reasoning behind the decision.
