### ISSUE TITLE
[Effect Suggestion] Minecraft

### ISSUE THREAD

**Issue by AlekB16** [gta-chaos-mod/ChaosModV#1565]
**Name of effect**
Potential name(s) for the effect
Minecraft Moment/ Minecraft Steve/ Minecraft

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
1 minute and a half or 2 minutes 

**Effect Description**
Description of the effect; what should it do?
It transform the player in a cubicle form (like the characters in Minecraft

**Comment by Last0xygen** [comment]
Not possible, sorry
