### ISSUE TITLE
[Effect Suggestion] Acid Rain

### ISSUE THREAD

**Issue by MineDash1234** [gta-chaos-mod/ChaosModV#1567]
**Name of effect**
Acid Rain

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Causes the weather to change to rain and if the player is exposed to the sky, then they will take damage. They must be under shelter to not take damage. This affects all peds too and it would be cool if the rain was green colored.

**Comment by TheRealAyCe** [comment]
Duplicate, pls use search before posting
https://github.com/gta-chaos-mod/ChaosModV/issues?q=acid

https://github.com/gta-chaos-mod/ChaosModV/issues/1395
https://github.com/gta-chaos-mod/ChaosModV/issues/809
https://github.com/gta-chaos-mod/ChaosModV/issues/480
