### ISSUE TITLE
[Effect Suggestion] inverted keyboard 

### ISSUE THREAD

**Issue by AlekB16** [gta-chaos-mod/ChaosModV#1570]
**Name of effect**
Potential name(s) for the effect
Inverted keyboard

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
Short, like 15/20 seconds

**Effect Description**
Description of the effect; what should it do?
It just inverts the keyboard keys, for example the W will be S and S with W, etcetera (sorry for my bad English, hope u understood)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16
