### ISSUE TITLE
[Bug] Quick Sprunk stop not working

### ISSUE THREAD

**Issue by aimlessB** [gta-chaos-mod/ChaosModV#1575]
**Describe the bug**
You can't buy anything from the vending machine spawned in the effect "Quick sprunk stop". I don't know if this is a mistake or if you just can't make the vending machines working.

**To Reproduce**
Activate "Quick Sprunk stop" and try to buy something.

**Comment by Last0xygen** [comment]
It’s not a bug
https://github.com/gta-chaos-mod/ChaosModV/issues/894#issuecomment-808964383
it’s a „Feature“ 😅

**Comment by ProfessorBiddle** [comment]
Instead of making it function you could force the player to do the animation and give them full health or something. 

https://github.com/criminalist/Animations-list-GTA5-Fivem/blob/master/anim-list.txt

mini@sprunk

plyr_buy_drink_pt1
plyr_buy_drink_pt2
plyr_buy_drink_pt3

**Comment by Last0xygen** [comment]
And how should that work? Observing the player position all the time once a machine gets spawned and running animations then?
That’s why I didn’t do it, I would have to make it a timed effect then 😅

**Comment by ProfessorBiddle** [comment]
> And how should that work? Observing the player position all the time once a machine gets spawned and running animations then?

that's what I was thinking, but it might not be possible. I'll give it a shot later tonight.

**Comment by Last0xygen** [comment]
Yes that would be possible but not worth it imho

**Comment by ProfessorBiddle** [comment]
> Yes that would be possible but not worth it imho

Well, it does sort of work, but it's really clunky.  [I'll just wait for MoneyWasted to do his thing :)](https://github.com/gta-chaos-mod/ChaosModV/issues/894#issuecomment-809534215)

**Comment by Last0xygen** [comment]
Then we’ll wait 🤷‍♂️
