### ISSUE TITLE
Catto Guns

### ISSUE THREAD

**Issue by MarsTheBug** [gta-chaos-mod/ChaosModV#1576]
Catto Guns causes the game to crash if it's used with certain guns and in missions with a lot of NPCs
I think it might help to put a limit on how many cattos can spawn at a time and despawn older cattos
Maybe a limit of 250 would help prevent crashes

**Comment by Last0xygen** [comment]
Already done https://github.com/gta-chaos-mod/ChaosModV/pull/1550
