### ISSUE TITLE
Disingenuous dense motherfucker!

### ISSUE THREAD

**Issue by nicksours-design** [gta-chaos-mod/ChaosModV#1577]
**Name of effect**
Disingenuous Dense Motherfucker!

**Effect Description**
Spawn Michael dressed as DarkviperAU and have him roast the player saying "You disingenuous dense motherfucker, obviously you have to know something about something or you couldn't tie your shoes!"

**Comment by Last0xygen** [comment]
1. this mod is not only for DarkViper
2. There is no „Matt outfit“
3. There’s no way to let him say custom lines of dialog

**Comment by TheRealAyCe** [comment]
I've added part of that quote to the lines when you complete Hacking: https://github.com/gta-chaos-mod/ChaosModV/pull/1582/commits/1521890414ad0fb4cfb0701ac28c8171eb3e15a8

**Comment by turg-the-sad-cat** [comment]
@Stoneration once again, not everyone would understand the red and this mod is not just for Matt
