### ISSUE TITLE
Suggestion about the voting system

### ISSUE THREAD

**Issue by oreydaore** [gta-chaos-mod/ChaosModV#1578]
Hello, i've been using chaos mod for a while now, since. I want to suggest a feature to the mod.

I really want a YouTube chat system into the mod. Since some people do not like twitch (like me) and this would be really useful for most of the people that use YouTube!

**Comment by Last0xygen** [comment]
Hello 👋 
This has already been suggested: https://github.com/gta-chaos-mod/ChaosModV/issues/1050
