### ISSUE TITLE
[Effect Suggestion] minecraft caves

### ISSUE THREAD

**Issue by AlekB16** [gta-chaos-mod/ChaosModV#1579]
**Name of effect**
Potential name(s) for the effect
Minecraft surroundings/ minecraft cave sounds 

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
Long

**Effect Description**
Description of the effect; what should it do?
Plays random Minecraft cave sounds

**Comment by TheRealAyCe** [comment]
Stealing sounds from Minecraft? Think about it: Is that likely to happen?

**Comment by AlekB16** [comment]
> Stealing sounds from Minecraft? Think about it: Is that likely to happen?

I'm not talking about stealing...

**Comment by TheRealAyCe** [comment]
So how would we play the Minecraft sounds without stealing them?
