### ISSUE TITLE
[Effect Suggestion] GTA Bezos

### ISSUE THREAD

**Issue by Nextarity** [gta-chaos-mod/ChaosModV#1590]
**Name of effect**
GTA Bezos

**Effect Description**
GTA Bezos gives you 196.9 billion dollars as It is the net worth for Jeff Bezos.

**Comment by RosyMiranto18** [comment]
Uh... pretty sure that there's a max money cap in this game, the 32-bit number, 2,147,483,647. I think if you go past it, the money gone negative, but it may be just a rumor.

**Comment by MoneyWasted** [comment]
> Uh... pretty sure that there's a max money cap in this game, the 32-bit number, 2,147,483,647. I think if you go past it, the money gone negative, but it may be just a rumor.

that shows you how crazy rich that guy is
