### ISSUE TITLE
[Effect Suggestion] Birds are vicious

### ISSUE THREAD

**Issue by MineDash1234** [gta-chaos-mod/ChaosModV#1591]
**Name of effect**
Birds are vicious

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Birds will start flying down and attacking the player. They will swoop down, attack, and fly up, and repeat.

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1439

**Comment by Last0xygen** [comment]
Duplicate #1439
