### ISSUE TITLE
[Effect Suggestion] Broken Keyboard

### ISSUE THREAD

**Issue by nickchoeee** [gta-chaos-mod/ChaosModV#1593]
**Name of effect**
My keyboard is broken

**Duration if timed effect (long or short timed?)**
60

**Effect Description**
Every 5 sec. it will make random commands like:
-Pause Menu
-Open weapons (tab key)
-Open phone
-Sneak
-Get in a car
-ragdoll 
-walk forward for 1 sec
-walk backwards for 1 sec
-walk left for 1 sec
-walk right for 1 sec
-Take cover
AND MANY MORE!

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1560

**Comment by Last0xygen** [comment]
Duplicate #1560
