### ISSUE TITLE
[Effect Suggestion] Inversion

### ISSUE THREAD

**Issue by Onlyhereforchaos** [gta-chaos-mod/ChaosModV#1596]
**Name of effect**
Inversion

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
This effect will invert the player camera and keys (such that pressing W will go backwards, S forwards, etc etc)

**Comment by TheRealAyCe** [comment]
Duplicate? https://github.com/gta-chaos-mod/ChaosModV/issues/16

**Comment by Last0xygen** [comment]
Duplicate #16
