### ISSUE TITLE
[Effect Suggestion] Peyote Plant

### ISSUE THREAD

**Issue by Onlyhereforchaos** [gta-chaos-mod/ChaosModV#1597]
**Name of effect**
peyote plant

**Duration if timed effect (long or short timed?)**
short

**Effect Description**
Temporarily turns player into an animal, as seen upon eating the peyote plant

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues?q=peyote

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues?q=peyote
