### ISSUE TITLE
[Effect Suggestion] Cougar Town

### ISSUE THREAD

**Issue by LordRygar** [gta-chaos-mod/ChaosModV#1599]
**Name of effect**
Cougar Town
(referencing both a TV show, and an already well known meme)

**Duration if timed effect (long or short timed?)**
Instant/ Short

**Effect Description**
Replace all NPCs with Cougars.  NOT "HOSTILE" Cougars, just, "Cougars".  They'll act like normal NPCs, and only attack if they feel threatened by the player/ other NPCs.  Preferable if possible to not replace "Essential NPCs", like any of the Player Characters that are not currently being controlled, or other characters that could effect the story.

It would instantly transform them all, and potentially keep transforming all newly spawned NPCs for a short while.

I did have another idea for this. There is actually a place on the map that is a cul de sac that is quite well known since it is where the original San Andreas took place.   Could have it transform everyone there into cougars, but, this would end up being a useless chaos mod I think since it would end up being a one and done type effect.

**Comment by Last0xygen** [comment]
Changing ped models is currently not possible and could lead to softlocks and crashes

**Comment by LordRygar** [comment]
I see.  Aww. I'll try to keep that in mind for future ideas.

**Comment by LordRygar** [comment]
What about: All new NPCs that spawn could be cougars?  For a short or long duration.

**Comment by Last0xygen** [comment]
Thats the same thing
