### ISSUE TITLE
The Matrix

### ISSUE THREAD

**Issue by MarsTheBug** [gta-chaos-mod/ChaosModV#1604]
Effect Suggestion

The Matrix

Long Timed

Replaces all Peds with an FIB Agent to represent Agent Smith and they all attack the player
All agents only have a pistol

**Comment by TheRealAyCe** [comment]
Pls check for duplicates next time https://github.com/gta-chaos-mod/ChaosModV/issues?q=matrix

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/199
