### ISSUE TITLE
[Effect Suggestion] Pacifist Griefer Jesus

### ISSUE THREAD

**Issue by pieandcheese647** [gta-chaos-mod/ChaosModV#1622]
**Name of effect**
Inconvenience Jesus
Annoying Griefer Jesus
Pacifist Griefer Jesus

**Effect Description**
Griefer Jesus with an Up-n-Atomizer instead of a railgun, making it do knockback blasts with minimal damage.

**Comment by Last0xygen** [comment]
Already exists as the alien
