### ISSUE TITLE
[Effect Suggestion] Make GPS & Waypoint Disappear from Map

### ISSUE THREAD

**Issue by pogue** [gta-chaos-mod/ChaosModV#1623]
Make GPS & Waypoint Disappear from Map
30-60 seconds

Make the yellow line for the GPS and the ending waypoint disappear from the map. This will really show if the player knows where to go and their map knowledge.

**Comment by Last0xygen** [comment]
Already exists as „hide HUD“

**Comment by pogue** [comment]
Hide HUD doesn't make the yellow line from the GPS disappear from what I've seen, nor the waypoint or yellow marker.

**Comment by Last0xygen** [comment]
Either „hide hud“ or „hide radar“ itselfs hides the radar ;)

**Comment by pogue** [comment]
You're right, I was wrong. Hide HUD hides the GPS marker line.

**Comment by Last0xygen** [comment]
I don’t see any advantages of this over hide hud as it would be pretty situational

**Comment by pogue** [comment]
It just seems like it would leave the person in a confusing mess, where they can see the map, but can't see where to go.

Just an idea, anyway. If it's no good, I'm fine with that.
