### ISSUE TITLE
[Effect Suggestion] Spawn Fake Griefer Jesus

### ISSUE THREAD

**Issue by breadpilledbro** [gta-chaos-mod/ChaosModV#1630]
**Effect Description**
Spawns NPC that looks and acts like griefer jesus, but is actualy harmless, and after failing to kill you he just runs away/dies

**Comment by TheRealAyCe** [comment]
Pick your duplicate https://github.com/gta-chaos-mod/ChaosModV/issues?q=fake+griefer+jesus

**Comment by Last0xygen** [comment]
Yeah, requested several times
