### ISSUE TITLE
[Effect Suggestion] Stuttering

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1634]
**Name of effect**
Stuttering

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
The name explains it already, while the effect "Stuttering" is active, the game stutters.
During those 30 seconds the game is gonna drop lots of fps really frequently and at random times.

**Comment by Last0xygen** [comment]
Already exists as „console experience“
