### ISSUE TITLE
[Effect Suggestion] Fake Detonate Vehicle

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1635]
**Name of effect**
Before the beeping stops:"Detonate Vehicle" or "Detonate Current Vehicle" (basically the existing effect name) and after the beeping stops the real name'"Fake Detonate Vehicle" or etc... (you get the point)

**Effect Description**
The effects starts a beeping audio (the same as the existing "Detonate Vehicle" effect and after it finishes beeping the vehicle is not gonna explode and the real name is gonna be displayed.

**Comment by Last0xygen** [comment]
Already part of the mod
