### ISSUE TITLE
[Effect Suggestion] Fake Crash minimizes the game

### ISSUE THREAD

**Issue by noahthingholm** [gta-chaos-mod/ChaosModV#1638]
All my suggestion is, is just that whenever you get the effect "Fake Crash" the game minimizes after the "lag" which would make it even more believeable.

**Comment by TheRealAyCe** [comment]
pick your duplicate https://github.com/gta-chaos-mod/ChaosModV/issues?q=minimize

**Comment by Last0xygen** [comment]
Duplicate
