### ISSUE TITLE
[Feature Suggestion] Last Triathlon Changes

### ISSUE THREAD

**Issue by MineDash1234** [gta-chaos-mod/ChaosModV#1646]
**Is your feature request related to a problem? Please describe.**
I'm almost done with chaos 100%, but the last triathlon is pretty much impossible because it is 30 minutes long, and dying within that 30 mins is guaranteed.

**Describe the solution you'd like**
I think the mod should optimize the effects so that the ones that kill you or fail you are disabled, but it is still chaotic enough to where it's still hard. The things that kill you or fail you are the ones that take you too far from the race, spawn something that will kill you, or cause you to commit a crime.

**Comment by Last0xygen** [comment]
You can enable/disable/change propabilities for each effect as you wish :)
I don’t see how the mod should be acting different depending on the current mission

**Comment by anto4440** [comment]
*Chough Chough* #1021 *chough chough*
