### ISSUE TITLE
[Effect Suggestion] give player beard/matto

### ISSUE THREAD

**Issue by lemmini420** [gta-chaos-mod/ChaosModV#1653]
**Name of effect**
Give player beard/matto?

**Effect Description**
Found on YouTube. Theres a streamer that weekly plays chaos mod. This effect could be named after him but that is optinal. Gives the player a beard. Simple and easy (i hope)

**Comment by anto4440** [comment]
Yes, we all know dear old Matt. However, this effect is a dupe of #937

**Comment by Last0xygen** [comment]
> Yes, we all know dear old Matt. However, this effect is a dupe of #937

We don’t 🤪
But yeah, it’s a duplicate
