### ISSUE TITLE
[Effect Suggestion] Effect called fruitcake that would spawn in a copy of trevor, hostile or companion, whichever works.

### ISSUE THREAD

**Issue by Js46Designs** [gta-chaos-mod/ChaosModV#1655]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
Already an effect

**Comment by anto4440** [comment]
> Already an effect

No no no, you say: 'Duplicate of #XXX'. It was your thing man, what happened?

**Comment by Last0xygen** [comment]
Please no spam in closed prs 😏
It’s not a duplicate of a pr, but an already existing effect „clone player“

**Comment by anto4440** [comment]
I cant really see where i spammed...
