### ISSUE TITLE
[Effect Suggestion] Necronomicon

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1657]
**Name of effect**
Necronomicon

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Instantly deals 80% of the Peds base hp in damage (so that full health peds dont die)

**Comment by TheRealAyCe** [comment]
A boring version of Obliterate Nearby Peds that doesn't even obliterate, only weaken?

**Comment by anto4440** [comment]
I knew that i forgot some kind of 'kill all' effect.
