### ISSUE TITLE
[Effect Suggestion] Freeze!

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1659]
**Name of effect**
Freeze!

**Duration if timed effect (long or short timed?)**
Very short (10 Seconds)

**Effect Description**
Makes all Enemies (only enemies) freeze for duration of effect. They cannot move or shoot or perform any actions, but they can still take damage and die.

**Comment by Last0xygen** [comment]
Brainless peds?

**Comment by anto4440** [comment]
No, because it only affects enemies, they can still perform actions such as ragdolling and talking, and that it gives the player a bit of breathing time rather than hilarious situations
