### ISSUE TITLE
[Effect Suggestion] Polish Cow 

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#1661]
**Name of effect**
Polish Cow

**Effect Description**
Spawn a dancing cow from the one polish cow video meme thingy...

**Comment by turg-the-sad-cat** [comment]
Not possible, there is no dancing cow animation or whatever it’s called in the files

**Comment by Last0xygen** [comment]
If you mean the tv, those are prerendered
