### ISSUE TITLE
[Effect Suggestion] Paying a visit

### ISSUE THREAD

**Issue by lemmini420** [gta-chaos-mod/ChaosModV#1664]
**Name of effect**
Paying a visit

**Effect Description**
Teleports player to one of the three protagonists house.

**Comment by anto4440** [comment]
This is a dupe.

**Comment by lemmini420** [comment]
> This is a dupe.

Can i have the link if it is?

**Comment by anto4440** [comment]
> > This is a dupe.
> 
> Can i have the link if it is?

I know this seems counterintuitive, but i actually couldnt find it... But i swear in the name of all things holy, there was at least one 'teleport to safehouse' or something along those lines.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/644 and https://github.com/gta-chaos-mod/ChaosModV/issues/347

**Comment by anto4440** [comment]
Great, thanks matie
