### ISSUE TITLE
[Effect Suggestion] Double shot

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1665]
**Name of effect**
Double shot

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
When effect is active, every shot the player shoots will shot again shortly after

**Comment by Last0xygen** [comment]
Sooo rapidfire?

**Comment by anto4440** [comment]
> Sooo rapidfire?

No, Double shot, Not infinetouple shot ;)

**Comment by Last0xygen** [comment]
Rapidfire is Quad-Fire ;)

**Comment by anto4440** [comment]
I change it to split-shot

**Comment by Last0xygen** [comment]
Still just a slight variant to „rapidfire“
