### ISSUE TITLE
[Effect Suggestion] Randomise Movement Keybinds

### ISSUE THREAD

**Issue by DeluxHDx** [gta-chaos-mod/ChaosModV#1667]
Name of effect
Randomise Movement Keybinds

Duration if timed effect (long or short timed?)
Short

Effect Description
Randomises all movement keybind for 30 seconds. For example: W changes to D, A changes W, etc.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16
