### ISSUE TITLE
[Effect Suggestion] CJ's Style

### ISSUE THREAD

**Issue by DeluxHDx** [gta-chaos-mod/ChaosModV#1669]
Name of effect
CJ's Style

Duration if timed effect (long or short timed?)
insta

Effect Description
Changes players clothes to CJ's clothes.

**Comment by anto4440** [comment]
Thats an Instant effect, since it instantly changes players clothes

**Comment by Last0xygen** [comment]
And by „cjs clothes“ you mean the Tank top and Blue Jeans? Idk if that’s a good effect, sorry
