### ISSUE TITLE
[Effect Suggestion] Bomb shots

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1671]
**Name of effect**
Bomb shots/Exsplosive shots

**Duration if timed effect (long or short timed?)**
Short

**Effect Description* 
While effect is active, all successful shots from the player will summon a live grenade under the entity they hit. Only works when hitting entities

**Comment by SeanMirrsen** [comment]
"Explosive Combat" is already an effect. So this would end up being a little superfluous.

Also, as "Catto guns" shows in many a stream, having weapon fire generate physics objects is not very healthy for game stability.

**Comment by anto4440** [comment]
> "Explosive Combat" is already an effect. So this would end up being a little superfluous.
> 
> Also, as "Catto guns" shows in many a stream, having weapon fire generate physics objects is not very healthy for game stability.

But these are live grenades: they exsplode after a few seconds. However, exsplosive combat is a pretty similar effect (honestly think this one is more interesting though).
