### ISSUE TITLE
[Effect Suggestion] Weird Health

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1673]
**Name of effect**
Weird Health

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Make characters hp go up and down.

**Comment by Last0xygen** [comment]
Soooo OHKO with extra steps? 😅

**Comment by anto4440** [comment]
No, the health goes back up. But it’s pretty dumb since any damage is either gonna kill you or be invalidated.

Sendt fra min iPhone
