### ISSUE TITLE
[Metaeffect Suggestion] Chaotic Inputs

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1674]
**Name of effect**
(Metaeffect) Chaotic Inputs

**Duration if timed effect (long or short timed?)**
Very short (Five sec is *Generous*)

**Effect Description**
While effect is active, any input from the player will cause a random effect to drop.

**Comment by pipecek** [comment]
This will probably crash someone with a potato pc...

**Comment by anto4440** [comment]
> This will probably crash someone with a potato pc...

Chaos mod in a nutshell. Hell, if you even manage to run the *Base game* with a potato pc, i am impressed. Seriously though. How about comebo time, 5x timer speed, and even just a lot of the hevier effects?

**Comment by Last0xygen** [comment]
This would be just another „player can’t do anything“ effect

**Comment by anto4440** [comment]
> This would be just another „player can’t do anything“ effect

In that case, just make it so that the effect name doesnt pop up on screen. Problem solved.
