### ISSUE TITLE
[Effect Improvement Suggestion] Make the Screen rumble during effect Earthquake

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1675]
Make the screen rumble during the Earthquake effect. This can be achived by having a bunch of soundless exsplosions underground or something like that, you get the picture.

**Comment by TheRealAyCe** [comment]
Isn't the screen already rumbling enough from the physics being applied on the character or their vehicle?

**Comment by Last0xygen** [comment]
I think so too.
