### ISSUE TITLE
[Effect Suggestion] Hello

### ISSUE THREAD

**Issue by PrototypeRad** [gta-chaos-mod/ChaosModV#1676]
**Name of effect**
Hello

**Duration if timed effect (long or short timed?)**
The duration of 2 effects (2 purple lines)
**Effect Description**
This effect will work like the kifflom effect, but instead of saying "kifflom" it will say the line of franklin of him saying "hello"

**Comment by TheRealAyCe** [comment]
Isn't Friendly Neighbourhood already an effect that makes NPCs say "Hello"? Also, it has been mentioned before that playing specific soundfiles is not possible.

**Comment by Last0xygen** [comment]
That’s just „friendly neighborhood“
