### ISSUE TITLE
[Effect Suggestion] Cougar%

### ISSUE THREAD

**Issue by PrototypeRad** [gta-chaos-mod/ChaosModV#1677]
**Name of effect**
Cougar%

**Effect Description**
Turns every npc into a cougar

**Comment by turg-the-sad-cat** [comment]
1. Can soft lock the game and 2. Already been suggested before

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=cougar
