### ISSUE TITLE
[Effect Suggestion] Bluff

### ISSUE THREAD

**Issue by shawnweb** [gta-chaos-mod/ChaosModV#1678]
**Name of effect**
Bluff

**Duration if timed effect (long or short timed?)**
(Dependent On Effect But More Likely Then Not Short.)

**Effect Description**
Upon being chosen should be named a random effect (for example it could say flying vehicles, when it won't actually be that), matching the length of whatever effect is chosen (preferably not something instantly noticeable like invert gravity), and after 10 seconds should change back to the name bluff on the list of effects.

This should trick anyone who gets it (possibly including whoever's voting) into possibly going out of their way to attempt to activate the effect, or scare them into thinking an effect's going to kill them, when in reality it's the same as the "Nothing" effect. 

(If adding an effect like Detonate Vehicle to the list of fake vehicles, maybe make the vehicle beep but not explode, similar to the fake death detonate).

**Comment by TheRealAyCe** [comment]
In voting it would show up as "Bluff", no? Otherwise, how do you tell beforehand if something is a Bluff or not?

**Comment by shawnweb** [comment]
> In voting it would show up as "Bluff", no? Otherwise, how do you tell beforehand if something is a Bluff or not?

Of course, it would appear in voting as Bluff, but until the time passes, you have to guess if it's a bluff or not. Even a random effect could be a bluff, which could be hilariously confusing.

It takes full advantage of the proportional voting system.

**Comment by TheRealAyCe** [comment]
Since effects can apparently now change their displayed names after they were triggered, this suggestion seems doable.

**Comment by Last0xygen** [comment]
* Already been suggested (although I only found something similar)
* Fake detonation has already been made
* Most effects would be obvious „bluffs“, like earthquake, doomsday, randomize clothes, spawn any vehicle…
