### ISSUE TITLE
[Effect Suggestion] Different Types Of Game Speeds.

### ISSUE THREAD

**Issue by shawnweb** [gta-chaos-mod/ChaosModV#1679]
**Name of effect**
2x Gamespeed
Time-flow (or something cooler).

**Duration if timed effect (long or short timed?)**
Short - Medium

**Effect Description**
While the 2x gamespeed is pretty self explanatory, Time-flow would be time randomly slowing down and increasing for around 15 seconds (because anything more would be torture), and even if 2x gamespeed isn't possible due to game limitations, time-flow still sounds like it could work.

**Comment by Last0xygen** [comment]
* increasing game speed over 1x is not possible 
* „Dynamic Game speed“ already available as „superhot“
