### ISSUE TITLE
[Effect Suggestion] Spawn Anime Car

### ISSUE THREAD

**Issue by MC-88** [gta-chaos-mod/ChaosModV#1680]
**Name of effect**
Spawn Anime Car

**Effect Description**
Spawn a car with a livery themed after the in game anime. If possible, randomly select from all of the vehicles with these liveries.
Here is a list of all vehicles in the game with anime themed liveries. The names of the liveries will be included in parentheses for convenience. Due to their nature, the Scramjet and the Volatol have not been included in this list.
Sultan RS (Princess Robot Bubblegum)
Sentinel Classic (2D Relationship)
Futo (Itasha Drift)
Zion Classic (Waifu Wheels)
Sugoi (Wasabi Kitty)
Jugular (Shiny Wasabi Kitty)
Blista Kanjo (Shiny Wasabi Kitty)
Veto Modern (Princess Robot Bubblegum)

**Comment by pipecek** [comment]
The only one that could theoretically work is the futo because online cars get deleted by rockstar or something

**Comment by MC-88** [comment]
Really? That's a damn shame. I guess the effect could still work with that one car, it's just way more lame. That sucks!

**Comment by MC-88** [comment]
I don't think I'm gonna close the request though, just on the chance that you can actually get Online vehicles in SP (I swear I've seen the go cart spawn during Spawn Random Traffic)

**Comment by MC-88** [comment]
Could someone look into this once everyone's woken up? Thanks.

**Comment by Last0xygen** [comment]
> Could someone look into this once everyone's woken up? Thanks.

Please restrain from posting multiple own comments, it hinders maintainability/readability. :)

also please don’t pressure any contributors on here. We‘re all working unpaid in our free time on this Projekt :)

**Comment by MC-88** [comment]
Yeah, I've never done this before. Thanks for the guidance :)

**Comment by DEATHCON1** [comment]
This list needs to be updated...

**Comment by MC-88** [comment]
Yes, I'm aware. Also, we already determined that this effect won't work, so it doesn't even matter.
