### ISSUE TITLE
[Effect Suggestion] Summon Generic boss

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1683]
**Name of effect**
Summon generic boss

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Just summons an enemy with high health and a minigun. Why doesnt the mod have an effect this basic

**Comment by Last0xygen** [comment]
Already exists as juggernaut.
It doesnt contain enemy spawns that consistently and without a doubt kill the player, which is why the juggernaut has reduced accuracy

**Comment by anto4440** [comment]
> Already exists as juggernaut.
> It doesnt contain enemy spawns that consistently and without a doubt kill the player, which is why the juggernaut has reduced accuracy

Right, right. My bad.

**Comment by anto4440** [comment]
Changed it to #1688
