### ISSUE TITLE
[Effect Suggestion] Caged

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1690]
**Name of effect**
Caged

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Creates an invisible box around the player that cars and npc's cant move in or out of. Other entities (such as bullets, rockets and grenades) can freely move about. The size increases if player is in a vehicle.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/742

**Comment by anto4440** [comment]
> Duplicate #742


Nope, because its not permanent, and player can move around.

**Comment by Last0xygen** [comment]
„ This would be just as good as "Player Swap", freezing the player in place.“ 😊

**Comment by anto4440** [comment]
> „ This would be just as good as "Player Swap", freezing the player in place.“ 😊

" player can move around. "

**Comment by SeanMirrsen** [comment]
> 
> 
> „ This would be just as good as "Player Swap", freezing the player in place.“ blush

As far as I can tell this is actually a sort of proto-Forcefield. A box that collides with people and cars, but not weapons fire, centered on the player. An inverted "witness protection", as it were.

I'm not actually sure if this is technically possible. I don't think you can make a physics collider object that only respects peds and vehicles. But it could be neat as a concept.
