### ISSUE TITLE
[Effect Suggestion] Grandmas Computer

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1691]
**Name of effect**
"Grandmas Computer"

**Duration if timed effect (long or short timed?)**
Stays until ads are cleared or after 20 seconds

**Effect Description**
Will cause the ad popups from the lifeinvader mission to show on the players screen and will not go away until the effect ends or the player clear them

**Comment by anto4440** [comment]
Congrats on having your first effect that is actually good!

**Comment by pipecek** [comment]
This is actually good

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/869
