### ISSUE TITLE
[Effect Suggestion] Mentally Insane

### ISSUE THREAD

**Issue by Lavished** [gta-chaos-mod/ChaosModV#1693]
<!--
**********************
** 🛑 !! STOP !! 🛑 **
**********************

Before continuing, ensure that:

**Name of effect**
"Mentally Insane"

**Duration if timed effect**
30 seconds long

**Effect Description**
Will play echoed screams and other sound effects like the voices of Michael hearing himself in bury the hatchet and may even trip over the character.

**Comment by anto4440** [comment]
Why did you close this? its a great and fleshed out suggestion and the idea is interesting!

**Comment by Lavished** [comment]
> Why did you close this? its a great and fleshed out suggestion and the idea is interesting!

I thought it was broken but nevermind, its back up by the way, :)

**Comment by anto4440** [comment]
yes i see
