### ISSUE TITLE
[Effect Suggestion] "Freezer Burnt" or "Un-Fried"

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1703]
**Name of effect**
"Freezer Burnt" or "Un-Fried"

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
Should do the complete opposite of Deep-Fried so pretty much instead of extremely bright it becomes extremely dark but you would still be able to see

**Comment by anto4440** [comment]
Oh! Amazing! Your very first anti-contributer streak!

**Comment by anto4440** [comment]
Also, the effect blackout (i think thats what its called, im refferring to the one that kills all lights) does exactly this.

**Comment by Last0xygen** [comment]
Yeah, blackout ist pretty similar 🤔
If it’s about reducing visibility „I’m tired“ and „roll credits“ are your friends
