### ISSUE TITLE
[Effect Suggestion] Constant Ability 

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1708]
**Name of effect**
Constant Ability

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
Causes the players ability to be constantly active for 30 seconds and cannot be turned off until the time passes

**Comment by anto4440** [comment]
Im unsure if this is possible; maybe you can bruteforce the special effect to be always active, but i highly doubt it. even if it isnt, the effect could still work as much of the time as possible.

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1390

**Comment by Last0xygen** [comment]
Duplicate #1390
