### ISSUE TITLE
[Effect Suggestion] Peyote Addict

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1711]
**Name of effect**
Peyote Addict

**Duration if timed effect (long or short timed?)**
45 seconds

**Effect Description**
Transforms player into random peyote plant animal and will turn back to normal after effect ends

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=peyote duplicate, pls check existing suggestions before posting

**Comment by Last0xygen** [comment]
Duplicate
