### ISSUE TITLE
[Effect Suggestion] "Plane Rain

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1724]
**Name of effect**
Plain Rain

**Duration if timed effect (long or short timed?)**
45 seconds

**Effect Description**
Males plains fall from the sky and adds rainy weather while effect is on

**Comment by anto4440** [comment]
I think this was a thing at some point. Still though, it is covered by effect 'vehicle rain'

**Comment by pipecek** [comment]
Already suggested as "hallelujah it's raining men"

**Comment by Last0xygen** [comment]
Duplicate
