### ISSUE TITLE
[Effect Suggestion] GTA Online

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1725]
**Name of effect**
GTA Online

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
Causes half of the NPC's to be on oppressors then 20% in the futuristic tank (i dont remember the name) and the rest of the NPC's just driving recklessly

**Comment by anto4440** [comment]
This wont work for the same reasons as in #1388 #1020 #1090 and a bunch of earlier gta online suggestions. even i have made several.

**Comment by aimlessB** [comment]
What's the problem with #1020? It's just like Griefer Jesus

**Comment by Last0xygen** [comment]
duplicate

**Comment by anto4440** [comment]
> What's the problem with #1020? It's just like Griefer Jesus

Yeah my bad, if you'd done the thing it asks you to (check if the effect has occured before) youve noticed that there are A LOT of gta online effects.
