### ISSUE TITLE
[Effect Suggestion] Gives Everyone a Rocket Launcher

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#1727]
**Name of effect**
Gives Everyone a Rocket Launcher

**Duration if timed effect (long or short timed?)**
One-Time

**Effect Description**
Time for some true experience of Tryhard to Tryhard combat, isn't it?

**Comment by Last0xygen** [comment]
Already an effect

**Comment by RosyMiranto18** [comment]
Ah, sorry about that, i didn't read the fine print better. Surprisingly very quick response though.
