### ISSUE TITLE
[Effect Suggestion] Complications Jump

### ISSUE THREAD

**Issue by FuryChan** [gta-chaos-mod/ChaosModV#1730]
**Name of effect**
Complications Jump

**Duration if timed effect (long or short timed?)**

**Effect Description**
It puts you in an grey Obey Tailgater
and makes you jump out of it into micheal's house.

**Comment by pogue** [comment]
I'm worried we're going to get too many DarkViper memes in the script. We already have blimp strats and Witness Protection. Other players who have never heard of DV might not get these jokes.

**Comment by TheRealAyCe** [comment]
so... https://github.com/gta-chaos-mod/ChaosModV/issues/1607 duplicate?

**Comment by FuryChan** [comment]
> so... #1607 duplicate?

I Know it has been suggested before ones i have not seen too

**Comment by Last0xygen** [comment]
If you know it has been suggested before, why would you suggest it again??
