### ISSUE TITLE
Grove street, home

### ISSUE THREAD

**Issue by Moozy21** [gta-chaos-mod/ChaosModV#1733]
**Name of effect**
Grove street home

**Effect Description**
Teleport player to grove street in bmx 
Sound effect: "grove street home at least it was before i f*** everything up"

**Comment by juhana** [comment]
Duplicates: #715, #914

**Comment by JustTunerYT** [comment]
First of all, yes. It duplicates both these suggestions. Second, there is no sound effect you mentioned in GTA V. Chaos Mod Player have to create this sound effect by himself
