### ISSUE TITLE
[Effect Suggestion] Teleport to North Icon

### ISSUE THREAD

**Issue by Arysr** [gta-chaos-mod/ChaosModV#1736]
**Name of effect**
Teleport to North Icon

**Effect Description**
Teleports to North icon. The North icon is not an abstract part of the GUI, it genuinely is there on the map, much farther than you could hope to get to with the games coded effects to keep you from going out far into the ocean. Any type of vehicle whatsoever will break out there, and this effect is basically a death sentence.

**Comment by pogue** [comment]
I already suggested this. The player would have no way to escape the island unless they fall through the gground. And it's a long sewi back to shore.

**Comment by Last0xygen** [comment]
Duplicate
