### ISSUE TITLE
[Effect Suggestion] 1000 ping

### ISSUE THREAD

**Issue by samtbf** [gta-chaos-mod/ChaosModV#1751]
**Name of effect**
1000 ping

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Gives the player 1000 ping

**Comment by TheRealAyCe** [comment]
Delay inputs? That could actually be an infuriating effect...

**Comment by pogue** [comment]
What would this accomplish? Ping is only for online.

**Comment by pipecek** [comment]
> 
> 
> What would this accomplish? Ping is only for online.

it would make it pretty annoying to play, which is good. It was the name of the effect darling, he knows (afaik) that ping is for online, it's just made to delay inputs.

**Comment by LilCuteli** [comment]
This legit looks like a really but really infuriating effect, gonna love it.
I suggest you update the effect info and write:"Player inputs get delayed".
Also this could be a random effect every time, like sometimes 100 ping and sometimes 900 ping where the higher the ping the worse the input delay.

**Comment by juhana** [comment]
Suggested several times (#545, #767, #834)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/545
