### ISSUE TITLE
[Effect Suggestion] Loading

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1752]
**Name of effect**
Loading

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
Basically triggers the loading screen that comes up when you load the game or a mission replay or the simpler black screen loading when you're loading a part of the mission or when it's loading for respawning.

**Comment by Last0xygen** [comment]
Effects that just sets the player stuck or make them unable to play the game in any capacity are not what we are looking for :)
