### ISSUE TITLE
[Effect Suggestion] Chorus of Gas Gas Gas plays during Full Acceleration

### ISSUE THREAD

**Issue by Vandil-the-Rogue** [gta-chaos-mod/ChaosModV#1753]
**Name of effect**
Full Acceleration

**Effect Description**
This is a modification to Full Acceleration.  Having the chorus of Gas Gas Gas playing while FA is in effect would be a hilarious use of the meme.

**Comment by Last0xygen** [comment]
Sound effect can be added by anyone themselves
