### ISSUE TITLE
[Effect Suggestion] Let The Bodies Hit The Floor

### ISSUE THREAD

**Issue by PsycheOh** [gta-chaos-mod/ChaosModV#1759]
**Let The Bodies Hit The Floor**
Other possible names: Drowning Pool, Dead Peds, Death To All Peds. (I believe the original name suggestion would be funnier, still.)

**Short Duration**
It could also be argued that this would instantaneously kill all peds within a certain radius, and there be no resurrection for these peds. In which case, the effect would have no duration period. (Explained in **Effect Description**)

**Effect Description**
When voted for, all nearby peds drop to the floor, and any peds piloting or driving are dead in the air or behind the wheel. There would be a somewhat medium area affected/effected by this effect. I could see comic and chaotic potential for this being a duration effect, as well as instant. On one hand, if it's a timed effect, the peds are given life at the end of the timer, and get back to doing what they were doing originally. If not a timed effect, well, it's just death.

**Comment by SeanMirrsen** [comment]
There already are two effects that instantly kill everyone nearby. One explodes everybody, one ignites everybody. There's also an effect that briefly causes everyone to drop to the floor, and get up after several seconds.

While I do like the effect name, I'm afraid there's already many similar ones.

**Comment by PsycheOh** [comment]
Ah, you're right. It'd be cool if we could combine them all into one effect, but it might crash the game. Thanks for the look out, closing the issue.
