### ISSUE TITLE
[Effect Suggestion] Teleport to Merryweather Base

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1763]
**Name of effect**
Teleport to Merryweather Base

**Effect Description**
Teleports to the Merryweather Base.
If you don't know where it is, it's basically at the south of the entire map, west container docks (where you pick the submarine for the Merryweather Heist).
Or more simply, it's basically the place where you go with the semi-truck during "Scouting the Port".
Just spawn inside the base, not at the exit.
This should just be a "Teleport to Fort Zancudo" but less dangerous.

**Comment by pogue** [comment]
I also suggested being teleported to the [url=https://gta.fandom.com/wiki/Altruist_Cult]Altruist Cult[/url] where the players would be aggroed on and spawn on [url=https://github.com/gta-chaos-mod/ChaosModV/issues/1536#issuecomment-861688125]Aircraft Carrier[/ul] where the enemies also agro the player
https://github.com/gta-chaos-mod/ChaosModV/issues/1536#issuecomment-861688125

And spawn to the Altruist cult where there same thing could happen. Apparently these have already been suggested though.

**Comment by LilCuteli** [comment]
> I also suggested being teleported to the [url=https://gta.fandom.com/wiki/Altruist_Cult]Altruist Cult[/url] where the players would be aggroed on and spawn on [url=https://github.com/[/issues/1536](https://github.com/gta-chaos-mod/ChaosModV/issues/1536)#issuecomment-861688125]Aircraft Carrier[/ul] where the enemies also agro the player
> [#1536 (comment)](https://github.com/gta-chaos-mod/ChaosModV/issues/1536#issuecomment-861688125)
> 
> And spawn to the Altruist cult where there same thing could happen. Apparently these have already been suggested though.

Sorry, I keep forgetting about actually checking if what I'm suggesting has actually already been suggested.
