### ISSUE TITLE
[Effect Suggestion] Faulty Seatbelts

### ISSUE THREAD

**Issue by J1rJ1r** [gta-chaos-mod/ChaosModV#1766]
**Name of effect**
Faulty Seatbelts
Possible names, Ejector seat

**Duration if timed effect (long or short timed?)**
Long. 2:30-3:00 min

**Effect Description**
Any collision from the front or back of any applicable ground vehicle will cause the player and/or NPCs in the same vehicle to be flung through the windshield at low speed with no damage being dealt by the collision or the player/NPC flying through the windshield.

**Comment by Last0xygen** [comment]
Already suggested
