### ISSUE TITLE
busted

### ISSUE THREAD

**Issue by Pevetti** [gta-chaos-mod/ChaosModV#1768]
**Name of effect**
Busted
**Duration if timed effect 
no

**Effect Description**
player gets busted and loses the gun they are holding and all ammo. Spawns to the place where you spawn when you get busted (idk)

**Comment by Pevetti** [comment]
if they are in a mission they will fail

**Comment by Last0xygen** [comment]
Already worked on https://github.com/gta-chaos-mod/ChaosModV/pull/308
