### ISSUE TITLE
[Effect Suggestion] Long loading screen

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#1778]
**Name of effect**
Long load
Infinite Load
Long Loading Screen
Bugged Loading Screen

**Duration if timed effect (long or short timed?)**
short

**Effect Description**
Make it so you get that black loading screen with the rotating circle for a short period of time. Just to annoy the player, because they have to wait before continuing. Some missions are time based, and this could be a painful wait.

**Comment by Last0xygen** [comment]
Waiting / blocking effects are not an effect we’re looking for
