### ISSUE TITLE
[Effect Suggestion] Duster time

### ISSUE THREAD

**Issue by Pevetti** [gta-chaos-mod/ChaosModV#1781]
**Name of effect**
Duster time, Duster, Farm plane time

**Effect Description**
Teleports the player to a duster plane that is airborne right above the player. doesnt remove their current vehicle

**Comment by Last0xygen** [comment]
Please add the default description and modify it accordingly

**Comment by Pevetti** [comment]
hmm the description is not showing

**Comment by anto4440** [comment]
Dupelicate #819

**Comment by Last0xygen** [comment]
Duplicate
