### ISSUE TITLE
[Effect Suggestion] Mega Griefer Jesus

### ISSUE THREAD

**Issue by Booper18** [gta-chaos-mod/ChaosModV#1783]
**Name of effect**
Mega Griefer Jesus

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Pretty much Extreme Griefer Jesus but he spawns with the TM-02 Khanjali tank (with the railgun cannon)

**Comment by Last0xygen** [comment]
Already requested. Would always be an instant kill
