### ISSUE TITLE
[Effect Suggestion] Spawn Dozer/Lawnmower/Tractor

### ISSUE THREAD

**Issue by LilCuteli** [gta-chaos-mod/ChaosModV#1797]
**Name of effect**
Spawn Dozer/Lawnmower/Tractor

**Effect Description**
Basically adds these 3 vehicles to the precise spawn vehicle options.
Spawn Dozer.
Spawn Lawnmower.
Spawn Tractor.

So, it's basically https://github.com/gta-chaos-mod/ChaosModV/issues/972
Unfortunately it fell into the pit of "The Lost Suggestions".

**Comment by TheRealAyCe** [comment]
Why do you post something that was already suggested, even though you searched for it and found an existing ticket, that is not closed?
