### ISSUE TITLE
Find Jesus 

### ISSUE THREAD

**Issue by GreatdayJay** [gta-chaos-mod/ChaosModV#1799]
**Effect Description**
This effect will teleport the streamer to one of the churches and spawn Jesus. Not a griefer Jesus, just a normal one who wants to fight.

**Comment by FuryChan** [comment]
**Streamer** or **Player** bcuz all of the player playing the mod arent streamers like matt

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
