### ISSUE TITLE
GTA Online

### ISSUE THREAD

**Issue by GreatdayJay** [gta-chaos-mod/ChaosModV#1803]
**Effect Duration**
10-20 Seconds 
**Effect Description**
Just mods the crap out of the game. Money Rain, Ufos, Snowflakes, etc

**Comment by Last0xygen** [comment]
Yeah, that IS the chaos mod

**Comment by GreatdayJay** [comment]
> Basically Chaos Mod

Yes ,but all at once. Also turning streamers into Snowflakes qnd xmas trees aren't in Chaos mod

**Comment by Last0xygen** [comment]
That’s the beauty of chaos mod. There a several combinations that are really funny once they happen (like forcefield and explosive peds for example) but an additional effect which just enables multiple already existing effects is not a really „new“ effect
