### ISSUE TITLE
[Effect Improvement Suggestion] Improve "youre a wizard, Franklin"

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1806]
Improve "youre a wizard, Franklin" by making the vehicle a reskin of the Deluxo instead of an oppresor

**Comment by TheRealAyCe** [comment]
Not a chance, this is the only reliably way to get a working Oppressor in the mod. :D

**Comment by worm202** [comment]
I don't agree. With Deluxo you'll even have different sitting animation which is not suitable for broom as it is now

**Comment by anto4440** [comment]
> Not a chance, this is the only reliable way to get a working Oppressor in the mod. :D

I dont understand? Cant you just have normal oppresors?

**Comment by anto4440** [comment]
> I don't agree. With Deluxo you'll even have different sitting animation which is not suitable for broom

Yeah ok.
