### ISSUE TITLE
(Effect Suggestion) Chaos in the working hand

### ISSUE THREAD

**Issue by AryuSingh** [gta-chaos-mod/ChaosModV#1809]
**Name of effect** - Chaos in the working hand

**Duration if timed effect (long or short timed?)**
3 times
**Effect Description**
Player gets to decide which option they wants.

**Comment by Last0xygen** [comment]
What is this? I’m not getting what you’re suggesting

**Comment by TheRealAyCe** [comment]
Player can select one of the chaos option themselves instead of letting randomness/chat decide I think.

**Comment by AryuSingh** [comment]
> What is this? I’m not getting what you’re suggesting

so im saying is that for 3 turns, the players gets to decide which chaos gets accepted.

**Comment by Last0xygen** [comment]
Out of the 3 display choices (chat message, obs overlay and in game overlay) only the in game overlay shows the player what effects can be chosen.
So this won’t work
