### ISSUE TITLE
[Effect Suggestion] Resurrection

### ISSUE THREAD

**Issue by hakase420** [gta-chaos-mod/ChaosModV#1818]
Name of the effect: Resurrection
Effect description: If activated, it will stay until you die. When you die, Jesus will spawn and recurrect you (maybe with a cool animation)
Its simple but quite funny I think. Imagine Jesus pops up and resurrect you.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
