### ISSUE TITLE
Spawn Black Griefer Jesus

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#1821]
**Name of effect**
Spawn Black Griefer Jesus

**Effect Description**
This might sound bad but it's on Lamar in the Griefer Jesus outfit. The person who voices Lamar also plays Black Jesus. So that's where the idea comes from. I know it sounds racist but the idea.

**Comment by FuryChan** [comment]
and what does the effect do?

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
Also, you are unable to add clothing from one ped to another.
