### ISSUE TITLE
Vehicle rain

### ISSUE THREAD

**Issue by KindaChaotic69** [gta-chaos-mod/ChaosModV#1823]
**Duration if timed effect (long or short timed?)**
    long timed

**Effect Description**
   Basically straight vehicles raining from the sky from bikes, cars, trucks, buses to even helicopters, planes, boats, etc. Don't 
   forget about the tank tho. Pretty much like whale rain but vehicles.

**Comment by EonYears** [comment]
This is already a effect

**Comment by Last0xygen** [comment]
„Vehicle Rain“ already exists
