### ISSUE TITLE
[Effect Suggestion] Spammy camera

### ISSUE THREAD

**Issue by KindaChaotic69** [gta-chaos-mod/ChaosModV#1824]
**Name of effect**
Spammy camera

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
If it is even possible, it means quick camera change in a loop non stop on vehicle cam and also walk cam (if it has it idk) 
What he does in this video but always in order to create a cool looking effect (also disorienting)
https://www.youtube.com/watch?v=f2pywaRPM10

**Comment by anto4440** [comment]
this is the most comically ineffecient thing i have ever seen XD. Ima change it up:

Spams your camera change button.

**Comment by KindaChaotic69** [comment]
> this is the most comically ineffecient thing i have ever seen XD. Ima change it up:
> 
> Spams your camera change button.

**Comment by KindaChaotic69** [comment]
What do you mean "ineficient". You think is easy to try progress with that and also more mods and chat trying to kill him?
