### ISSUE TITLE
[Effect Suggestion] 1UP

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1825]
**Name of effect**
1Up / Extra life

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
The moment the effect is applied, an anchor for their coordinates gets created. Then. whenever the players health would reach zero, instead of dying they get full health and respawn at that point. The anchor is deleted  when effect ends.

**Comment by hakase420** [comment]
its basically my idea https://github.com/gta-chaos-mod/ChaosModV/issues/1818 but with a other name? xD

**Comment by anto4440** [comment]
oh, yeah, i see. Thats my bad for not writing my effect sooner (first thought of it a few weeks back). I thought yours was on the spot, while mine still teleports you back.
