### ISSUE TITLE
[Feature Suggestion] Improvement for realistic hacking

### ISSUE THREAD

**Issue by UjjwalJ-5107** [gta-chaos-mod/ChaosModV#1833]
-->

**Is your feature request related to a problem? Please describe.**
The effect realistic hacking could have better potential

**Describe the solution you'd like**
You should make it so that there is a random chance of every type of hacking minigame in GTA V and GTA Online

**Additional context**
It would have more variety and an actual impact on gameplay as some of the hacking is harder and easier than the one in the effect itself

**Comment by Last0xygen** [comment]
Duplicate
