### ISSUE TITLE
[Effect Suggestion] Spawn MikeViperAU

### ISSUE THREAD

**Issue by Delirious-Drama** [gta-chaos-mod/ChaosModV#1836]
**Name of effect**
Spawn MikeViperAU

**Effect Description**
Spawn Michael in a black tank top and black shorts, saying 'you disingenuous dense motherfucker obviously you have to know something about something or you couldn't tie your fucking shoes' and 'I've been in witness protection.' A zip folder is attached with both of them in as MP3 files.

[Spawn MikeViperAU.zip] (https://github.com/gta-chaos-mod/ChaosModV/files/6826520/Spawn.MikeViperAU.zip)

**Comment by turg-the-sad-cat** [comment]
This mod isn’t specifically for Matt and many people wouldn’t understand the reference

**Comment by Delirious-Drama** [comment]
it was worth a shot

**Comment by turg-the-sad-cat** [comment]
Still tho, why add something that people wouldn’t understand

**Comment by Delirious-Drama** [comment]
yeah, you're right, i'll delete this now
