### ISSUE TITLE
[Effect Suggestion] Spawn Chad

### ISSUE THREAD

**Issue by TheBrightFlag** [gta-chaos-mod/ChaosModV#1840]
**Name of effect**
Spawn Chad

**Effect Description**
It should spawn Chad Mulligan from the mission Eye In The Sky.
Best with the chad meme music playing in the background. (like for Griefer Jesus)
Can be a companion or an enemy

**Comment by Last0xygen** [comment]
Already part of „spawn random enemy/companion“
Playing a sound is something a streamer has to set up, the „griefer Jesus“ sound (if you’re referring to DarkVipers videos) has been added in post and is not Part of the mod

**Comment by TheBrightFlag** [comment]
Noted with thanks.
