### ISSUE TITLE
[Effect Suggestion] Teleport to random stunt jump location

### ISSUE THREAD

**Issue by ItzEricAn** [gta-chaos-mod/ChaosModV#1843]
Name of effect:
Teleport to random stunt jump

Effect Description:
It teleports the player in front of a random stunt jump location, letting the player complete that stunt jump, and then let the player rethink his life choices as he is miles away from his destination, but still proud since the player has completed the stunt jump.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1334
