### ISSUE TITLE
Merryweather fleets here bro

### ISSUE THREAD

**Issue by Gigabyte66** [gta-chaos-mod/ChaosModV#1844]
Plays the sound effect of Trevor screaming "MERRYWEATHER FLEETS HERE BRO"

**Comment by aoppenh** [comment]
Make it Trevor's face moving across the screen DvD logo style the same way Lester's face does for Pwned.  Just repeating the voice line over and over again.

**Comment by TheRealAyCe** [comment]
Already suggested several times, even initially in the Mercenaries effect. But it's apparently not possible to play voicelines like that.

**Comment by Last0xygen** [comment]
Already requested a ton of times
