### ISSUE TITLE
[Effect Suggestion] Reverse Time Travel

### ISSUE THREAD

**Issue by Noobula07** [gta-chaos-mod/ChaosModV#1845]
**Name of effect**
Reverse Time Travel, Time Travel, Back In Time

**Effect Description**
It would go back 5 seconds in Gta time, so if you did a jump 2 seconds ago, it would bring you back before you did the jump.

**Comment by TheRealAyCe** [comment]
This is only possible if it's a timed effect or blocks the mod when started, since in order to teleport we need to remember the position that all objects had.

We can't actually go back in time, if that's what you mean, revive peds and so on.

**Comment by Last0xygen** [comment]
Not possible, would require tracking of all props and their condition
