### ISSUE TITLE
[Effect Suggestion] Personal Jesus

### ISSUE THREAD

**Issue by Orlikowski** [gta-chaos-mod/ChaosModV#1846]
**Name of effect**
Personal Jesus

**Duration if timed effect (long or short timed?)**
no time

**Effect Description**
spawns in a companion Jesus with a rail gun to trick player to think Greifer Jesus has come to kill them

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=companion+jesus duplicate and apparently already in development https://github.com/gta-chaos-mod/ChaosModV/pulls?q=is%3Apr+is%3Aopen+jesus
