### ISSUE TITLE
[Suggestion] Effect Update: Explosive Zombies dive under your car

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#185]
Sometimes peds dive out of the way when you drive close to them, maybe you could implement that Explosive Zombies would intentionally dive under your car when you drive near them?

**Comment by TheRealAyCe** [comment]
I think it's sometimes hard enough NOT to hit zombies/near-missing them, having them do "unfair" things like that may not increase fun. The spawner already sometimes places them right in your way.

**Comment by OHSHIET** [comment]
Well, they spawn in stacks and almost always you just drive past them. It's hard to hit them when there's no other active effects affecting your driving or something, but maybe you're right.

**Comment by pongo1231** [comment]
I think that'd just be too annoying, dodging them can be hard already as is.
