### ISSUE TITLE
[Effect Suggestion] Spawn Blue Yoga Ball

### ISSUE THREAD

**Issue by Ryanthethird** [gta-chaos-mod/ChaosModV#1850]
**Name of effect**
Spawn Blue Yoga Ball

**Effect Description**
Spawns a Blue Yoga Ball (Reference to the Blue Yogaball in Micheals House)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1848
