### ISSUE TITLE
[Effect Suggestion] My New Meta Effect Idea

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/ChaosModV#1851]
**Name of effect**
Stop Effect Duration

**Duration if timed effect (long or short timed?)**
Normal

**Effect Description**
This effect will stop every other effects duration excluding this one, which means they will be active all time unless this one ends.
The effect should be Meta Effect, since of it's working.

**Comment by Last0xygen** [comment]
Already exists (partly) as „2x effect duration“ which almost fills the whole meta duration
