### ISSUE TITLE
[Effect Suggestion] Meta cancel effect

### ISSUE THREAD

**Issue by 22011** [gta-chaos-mod/ChaosModV#1852]
**Name of effect**
Cancel ongoing effect

**Effect Description**
This is a meta effect in which it cancels the most recent timed effect. 
If there is only 1 ongoing effect going for example Invert Gravity, the cancel ongoing effect woild well, cancel the effect. 
If for example there are 2 or more timed effects going from most recent. Immortality, peds drive by player and brake boosting. Then this effect would cancel the most recent effect which in this case is Immortality. 

Of course this effect will not cancel the one off effects like Griefer Jesus

**Comment by Last0xygen** [comment]
Wouldn’t do anything if no active timed effect available, otherwise it’s already part of „no chaos“
