### ISSUE TITLE
chaos effect; Blue balls

### ISSUE THREAD

**Issue by NeverGonna-GiveYouUp** [gta-chaos-mod/ChaosModV#1854]
spawns blue balls (the yoga ball in Michael's house) but multiple. 
![A2D8E9A5-A3FE-4901-BC1F-B7F2BB1D62AB](https://user-images.githubusercontent.com/81563663/126080643-f3c01902-79dc-4363-9edc-00150c444a92.png)
![E3DA82BE-7833-4FB7-B5B9-770ED851BC41](https://user-images.githubusercontent.com/81563663/126080645-be059c18-818c-4e13-9e71-83fa613e419a.jpeg) screenshots = idea and reference where comment came from (not my idea) [Blueballs%](https://youtu.be/FgzoWAeem1c)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1848

**Comment by NeverGonna-GiveYouUp** [comment]
👌
