### ISSUE TITLE
[Effect Suggestion] Complications Jump

### ISSUE THREAD

**Issue by GooseWaffe** [gta-chaos-mod/ChaosModV#1864]
Name of effect:
Complications Jump

Effect Description:
Similar to Blimp Strat, complications jump will teleport the player into the air around Michael's house where they will retain speed and hit the house.

Example: 
https://www.youtube.com/watch?v=cgDuuHvSTyw
Unsure if links are allowed but this is a link to DarkViperAU clips channel where he performs the complications jump

**Comment by ProfessorBiddle** [comment]
I like this, if we end up with more it could be a good effect group.

**Comment by TheRealAyCe** [comment]
Those are fancy teleports, no?

**Comment by juhana** [comment]
Duplicates: #1607, #1730

**Comment by Last0xygen** [comment]
Duplicate
