### ISSUE TITLE
[Effect Suggestion] $702 Big Mac

### ISSUE THREAD

**Issue by ajazzyjojo** [gta-chaos-mod/ChaosModV#1868]
**Name of effect**
Big Mac

**Effect Description**
Removes $702 from player and dents the rear right side of the current car if applicable and slightly heals player, as they've just eaten a very tasty Big Mac

**Comment by Last0xygen** [comment]
This mod is not only for DarkViper

**Comment by ajazzyjojo** [comment]
> This mod is not only for DarkViper

yes i know that but i thought it would be good as hes the one who *i think* publicised the mod the most and there is also ones such as witness pritection which i think relate to the meme of him ranting about witness protection

**Comment by Last0xygen** [comment]
As Said he’s not the only streamer/YouTuber playing this.
The „witness protection“ effect itself is a valid effect, you don’t need to know anything about him to get what the effect does.
This effect here on the other hand: $702? Big Mac? 
it’s just a weak version of poor boy and hesoyam.
