### ISSUE TITLE
[Effect Suggestion] eco friendly police

### ISSUE THREAD

**Issue by Road-Train** [gta-chaos-mod/ChaosModV#1873]
**Name of effect**
Eco friendly police

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Player gets the cops if they're driving any vehicle which isn't electric/hybrid or a bicycle, and the cops will use the police livery Karin dilletante (the Prius) and maybe bicycles. No boats no helicopters. Maybe also restrict weapons to only melee/ tazer/ alien weapons(because they are basically energy weapons which can be considered electric = more eco friendly?).

**Comment by Last0xygen** [comment]
Not a really good effect, as almost no car is electric and spawning cops would be almost like mercenaries
