### ISSUE TITLE
[Effect Suggestion] Add ¨Spawn Super Griefer Jesus¨

### ISSUE THREAD

**Issue by DamigamerMxUS** [gta-chaos-mod/ChaosModV#1876]
**Super Grifer Jesus**
Potential name(s) for the effect

**Effect Description**
This effect is like the popular Grifer Jesus that spawns in Chaos but this time is super, meaning its Greafer Jesus but instead of a railgun it has a Minigun with explosive bullets and possibly with aimbot, and yes it could be inmune to explosions like the original one.
If you add this there will be 4 incarnations of Jesus in ChaosMod for the DarkViperAU series Chaos. And that would be awesome!

**Comment by Last0xygen** [comment]
No it would be awesome. It would just be an instant death and possible „softlocks“

**Comment by DamigamerMxUS** [comment]
> No it wouldnt be awesome. It would just be an instant death and possible „softlocks“

At least you modders could test it

**Comment by Last0xygen** [comment]
This mod is not only for Matt….
It would not be a good effect as it would just be an instant death. We had those effects and they are not good
