### ISSUE TITLE
[Effect Suggestion] No Voting (Meta)

### ISSUE THREAD

**Issue by Nextarity** [gta-chaos-mod/ChaosModV#1877]
**Name of effect**
No Voting (Meta)

**Duration if timed effect (long or short timed?)**
Devs choice.

**Effect Description**
Switches to no Twitch Chaos (Disables voting). Effect does not exist in Chaos without voting.

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1707
