### ISSUE TITLE
[Effect Suggestion] Faulty Keyboard

### ISSUE THREAD

**Issue by gongasdd** [gta-chaos-mod/ChaosModV#1878]
**Name of effect**
Faulty Keyboard, Wish Keyboard or Broken Keyboard

**Duration if timed effect (long or short timed?)**
The effect is gonna last 1 minute and a half

**Effect Description**
The effect changes the basic keybindings
W->S
S->W
A->D
D->A

**Comment by kolyaventuri** [comment]
Already suggested numerous times (ex: #16, #1422, #1570, etc.)
