### ISSUE TITLE
[Effect Suggestion] STOP POSTING ABOUT GTA6

### ISSUE THREAD

**Issue by cass129** [gta-chaos-mod/ChaosModV#1880]
**Name of effect**
STOP POSTING ABOUT GTA6
When the Imperator is sus
Dead Body Reported

**Effect Description**
Plays horn sound in the rhythm of “Dead Body Reported”. That’s it. Maybe right after the effect kills the player to make it funnier.

**Comment by TheRealAyCe** [comment]
No

**Comment by Last0xygen** [comment]
Killing the player makes it not funny. Playing that melody is also not a good effect
