### ISSUE TITLE
[Effect Suggestion] Selfie before disaster

### ISSUE THREAD

**Issue by nyancatec** [gta-chaos-mod/ChaosModV#1884]
**Name of effect**
Selfie before disaster

**Effect Description**
Chaos mod spawn random NPC taking a selfie with player (player loses control over character and poses to selfie). After 3 seconds of losing control over character, selfie is done, and shows itself on entire screen. Durning that selfie there's something odd that wasn't in there before:
-Car just about to drive over player
-A piano (or any other prop) falling down on player
-Trevor on bike ready to throw sticky bomb (bomb explodes after 2 seconds after being thrown)
-Some random NPC executing a player (pistol to a head, player loses control and dies from headshot)
-Police car/helicopter seeing player (if car selfie shows 2 policeman leaving the car with weapons ready to use, if heli, sniper taking a shot to a head. If player somehow surives they have 3 star wanted level)
Effect may also give something good for player:
-Deluxo slowly hovering down to a player
-Merryweather dropping ammo (GTA Online function)
-NPC taking a selfie giving player money (from 1k to 10k)
-Limousine with bodyguards waiting for a player (Limo drives to a waypoint)
-Random Meta in streamer/players favour (0.5x timer speed, 0.5x duration time, etc.)

Everything must happen in less than 5 seconds after selfie, so it will indeed be "selfie before disaster"

**Comment by Last0xygen** [comment]
Wow, nice write up.
But as this is limited to the player being on foot walking and not in a vehicle, the air or water, I don’t see this working out.
It also needs to block player control which is something that we try to minimize.
I get what’s you’re suggesting and they sound funny, but I don’t think we can implement this into the chaos mod in a reliable and applicable way
