### ISSUE TITLE
[Effect Suggestion] The Second Coming 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#1885]
**Effect name**
The Second Coming

**Effect Description**
Basically a more epic Griefer Jesus. When this effect is chosen the weather changes to lightning and thunder and the Doomsday effect occurs for a short time (10 seconds). Jesus is spawned closeby but not too closeby like he usually is so the player doesn't see him until Jesus (enemy AI) shoots at them or decides to confront them. He has a minigun rather than a rail gun. Can be spawned in any vehicle as well as on foot (50/50 chance of either). Jesus ragdolls when shot. He "ressurects" after a minute rather than dies, fake dying basically. The only way he can stay dead is if he's shot in the head/killed by a hammer put in the player's inventory by the effect.

**Comment by Last0xygen** [comment]
We have enough Jesus effects :)
