### ISSUE TITLE
[Effect Suggestion] What If I Was Him All Along?

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#1886]
**Effect Name**
What If I Was Jesus All Along?

**Duration**
2 minutes

**Effect Description**
The player becomes Griefer Jesus basically, donning the Jesus model and only having a railgun in their inventory and teleported maybe a 50-75 metres away from where you as the player originally was. The player then is tasked with killing who you as the player was playing before he became Jesus (so either Michael, Franklin or Trevor). This means that the player's model will be wherever you were before you became Jesus, if a way point was set by you before becoming Jesus, your player model before becoming Jesus will continue to go there and if not, the player model maybe just stands where you were before becoming Jesus. In both cases though the player model shoots at you as Jesus now, and you have to kill him. Upon killing who you were playing before you became Jesus as Jesus you return back to the player model you were playing as and the effect ends. Time limit of 2 minutes to kill who you were wherever you were before you became Jesus as Jesus and if you fail in the time limit you explode and the effect ends. You have higher health than usual (same health as Griefer Jesus actually has) and if you are killed as Jesus by the player's previous model you explode and die and the effect ends also. 

Your previous player model is marked on the map by a way point btw so you as Jesus can locate them.

**Comment by Last0xygen** [comment]
Changing player models currently is not possible
