### ISSUE TITLE
[Feature Suggestion] Jesus Suggestion

### ISSUE THREAD

**Issue by Noobula07** [gta-chaos-mod/ChaosModV#1890]
**Is your feature request related to a problem? Please describe.**
So after jesus dies nothing happens.

**Describe the solution you'd like**
 After Jesus dies or gets killed, there should be a big thunder sound that happens.

**Describe alternatives you've considered**
Maybe after jesus dies his body starts on fire.

**Additional context**
N/A

**Comment by TheRealAyCe** [comment]
Maybe Jesus should be revived after some ingame days? Lol

I don't think anything like that is feasible, this seems like logic that needs to run constantly to check if Jesus died, and effects don't do that.

**Comment by Last0xygen** [comment]
Exactly
