### ISSUE TITLE
[Effect Suggestion] There Aren't Cougars at Random Times!!

### ISSUE THREAD

**Issue by FuryChan** [gta-chaos-mod/ChaosModV#1891]
**Name of effect**
There Aren't Cougars at Random Times!!

**Effect Description**
It Teleports You Where in the Mission **Mr.Philips** you have to kill the bikers and it puts you behind trevor's car and it gives you a sniper and it spawn a cougar that immediately kills you.

**Comment by VolvoFH16007** [comment]
this mod isnt only for darkviper

(not a mod)

**Comment by FuryChan** [comment]
Sorry if the title is wrong but the right name is under **Name of effect**

**Comment by FuryChan** [comment]
No i just think its a good effect idea

**Comment by Last0xygen** [comment]
It already has been suggested 822562 times

**Comment by FuryChan** [comment]
POG
