### ISSUE TITLE
[Effect Suggestion] Invasion!

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#1893]
**Effect Name**
Invasion!

**Effect Description**
Spawns three aliens with each alien in their own vehicle Cletus gifts Trevor (the Back to The Future type one) that chase after the player. The aliens have weapons that range from Up N Atomizers to laser guns to the railgun and try kill the player. Simple effect and may be very similar to Spawn Alien but thought it would be pretty cool espiecally with them in that vehicle and with different weapons.

**Comment by Last0xygen** [comment]
Too similar to spawn alien
