### ISSUE TITLE
[Feature Suggestion] Universal Healthcare 

### ISSUE THREAD

**Issue by AgentV12** [gta-chaos-mod/ChaosModV#1894]
A simple effect that spawns Ambulance and medical teams on top of every ped that proceed to do CPR on said ped.
Could cause possible framerate issues because it may double the amount of entities in a given area, and possibly even crash.

**Comment by Last0xygen** [comment]
An effect that possibly crashes the game 🤔
I don’t think this would be a Good Addition. It’s mostly spawning a lot of vehicles and peds, failing missions and again, most likely crashing the game
