### ISSUE TITLE
[Effect Suggestion] Buffering

### ISSUE THREAD

**Issue by yarnie13** [gta-chaos-mod/ChaosModV#1900]
**Name of effect**
Buffering

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Freeze game and show buffering symbol for a short period of time

**Comment by Last0xygen** [comment]
Effect that only block the player from playing the game will be avoided from implementing

**Comment by TheRealAyCe** [comment]
Or just freeze the view, but let the game continue, so that the player has to do actions from memory and predictions?
