### ISSUE TITLE
[Effect Suggestion] Clutch Kick

### ISSUE THREAD

**Issue by Gorlix1337** [gta-chaos-mod/ChaosModV#1902]
**Name of effect**
Clutch Kick
Too Much RPM

**Effect Description**
As in drifting, if possible, the vehicle engine RPM goes very fast and gives angular velocity to car to the side where the wheels are pointing at (if they are pointing forward, multiply the existing angular speed).
im not sure if you can actually change the RPM.

**Comment by Last0xygen** [comment]
Difference to „Slippery vehicles“?

**Comment by juhana** [comment]
Sounds more like "10x Engine Speed" which behaves just as described.

**Comment by Gorlix1337** [comment]
> Difference to „Slippery vehicles“?

all of this is works with a timer, the clutch kick occurs only one time

**Comment by Last0xygen** [comment]
That’s exactly what the „ Duration if timed effect (long or short timed?)“ part would tell us but you deleted it from the request ;)

But as it’s just a timed effect happening once I don’t think this would be a good addition, sorry
