### ISSUE TITLE
[Feature Suggestion] Teleport to Random Mission Change

### ISSUE THREAD

**Issue by FuryChan** [gta-chaos-mod/ChaosModV#1907]
I Know People Have Said This Before But When Teleport to Random Mission Comes and You are in a mission it should put you in another mission bcuz alot of people play the whole story with chaos mod

**IT SHOULD PUT YOU IN SIDE MISSIONS BECAUSE THEY ARE KINDA USELESS** like me

**Comment by Last0xygen** [comment]
Teleport to random mission does exactly what it says. Teleport you to a random (possible) mission.
If you’re already on one, you can’t just change the current mission.
If there would be other missions available on the map the player would get teleported.
Teleport to random mission does teleport you to side missions but not to location specific and random encounters
