### ISSUE TITLE
[Effect Suggestion] Can't Resist The Funk

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#1913]
**Duration**
15 seconds 

**Effect Description**
Its like Hand's Up but instead of that animation, this effect traps the player in any dancing animation.

**Comment by Last0xygen** [comment]
Blocking the player from playing the game is not something we’re looking for

**Comment by TerrizX** [comment]
> Blocking the player from playing the game is not something we’re looking for

But Hands Up and Stop and Stare do essentially this too??

**Comment by ProfessorBiddle** [comment]
> But Hands Up and Stop and Stare do essentially this too?? Duration can be shortened to how long the animation is.

hands up only lasts for a few seconds, and stop and stare is a single event so the player can continue immediately.

**Comment by TerrizX** [comment]
> > But Hands Up and Stop and Stare do essentially this too?? Duration can be shortened to how long the animation is.
> 
> hands up only lasts for a few seconds, and stop and stare is a single event so the player can continue immediately.

I guess. But Hands Up still traps the player in an anim blocking them from playing still even if it's for a couple seconds, that's why I was confused that this suggestion was closed for that reason.

**Comment by Last0xygen** [comment]
Hands up will be changed imo to not block anything but even if it stays that way: rules for new effect don’t always reflect the current effects

**Comment by juhana** [comment]
The difference is that Hands Up is an instant effect triggering a built-in method that lasts a few seconds. The same is not possible for the dancing effects, they need to be kept active on each frame. Which means that the minimum time that the dancing effect could be in effect is the Short effect duration which is 30 seconds by default. So the Hands Up effect is a special case that needs to be pretty much exactly what it is now, you can't make new effects based on it by just replacing the animation.

**Comment by TerrizX** [comment]
> The difference is that Hands Up is an instant effect triggering a built-in method that lasts a few seconds. The same is not possible for the dancing effects, they need to be kept active on each frame. Which means that the minimum time that the dancing effect could be in effect is the Short effect duration which is 30 seconds by default. So the Hands Up effect is a special case that needs to be pretty much exactly what it is now, you can't make new effects based on it by just replacing the animation.

Ah ok, thanks for this, fair enough then. And fair enough for what you said LastOxygen, I didnt know that initially.
