### ISSUE TITLE
[Effect Suggestion] Spawn greifing jesus

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#1917]
**Name of effect**
Spawn greifing jesus

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Spawns one out of the following possibilities (you can add your own in the comments):

1: Greifer jesus squad. Spawns one of the vehicles that have a machine gun mounted on them, with one jesus driving, and another shooting with the mg at the player.

2: Ramp jesus. Spawns a ramp buggy with jesus in it. Jesus will then keep driving into the player.

3: Tow truck Jesus. A tow truck that has both rear tires popped spawns with jesus in it. Jesus will then hook the player and drive to the destination (if there is none, just make him drive to somewhere thats a long way away from the players current posision. 

4: Cargo Jesus. A lot like Tow truck Jesus, but this time he is in a cargobob. He flies as high as possible, then goes to your destination, and drops you down to it from the heavens

Note: when there are live jesus's from this effect, if possible please make it so that player randomly will be called by jesus, with him saying a single voice line insult, and then hanging up.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
