### ISSUE TITLE
[Effect Suggestion] The good ol' driving (GTA 4 Vehicle Handling)

### ISSUE THREAD

**Issue by Numi43** [gta-chaos-mod/ChaosModV#1923]
**Name of effect**
The good ol' driving

**Duration if timed effect (long or short timed?)**
Preferably long or even meta effect

**Effect Description**
Changes the vehicle handling to resemble driving in GTA 4 (somewhat wonky, with vehicles having higher chance to roll over etc.)
Basically the same as this mod by A.Blade, just included in Chaos: https://gtaforums.com/topic/796441-classic-handling/
The handling.meta file is there on page 4 too.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/793
