### ISSUE TITLE
[Effect Suggestion] Teleport to North Yankton

### ISSUE THREAD

**Issue by ProNick12** [gta-chaos-mod/ChaosModV#1939]
Effect Description
Description of the effect; what should it do? 
Teleports you to North Yankton

**Comment by turg-the-sad-cat** [comment]
Already been suggested multiple times before, please search up suggestions before making one

**Comment by Last0xygen** [comment]
Duplicate

**Comment by ProNick12** [comment]
> Duplicate

My bad, did not look in closed suggestions
