### ISSUE TITLE
[Effect Suggestion] No full auto in buildings

### ISSUE THREAD

**Issue by ttarso** [gta-chaos-mod/ChaosModV#1942]
Effect description:
Makes players guns shoot very fast

Duration: 30s

**Comment by Last0xygen** [comment]
Already exists, „rapid fire“

**Comment by TheRealAyCe** [comment]
> 
> 
> Already exists, „rapid fire“

To actually address the title of the effect, how about removing the ability for full-auto fire? Click for every shot only.
