### ISSUE TITLE
[Effect Suggestion] console experience also lowers the resolution to something like 720p or whatever u think is good.

### ISSUE THREAD

**Issue by coolharry830** [gta-chaos-mod/ChaosModV#1943]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
Wrong request Lay-out.
Also don’t work, requested already
