### ISSUE TITLE
[Effect Suggestion] Can't Skip Cutscenes

### ISSUE THREAD

**Issue by TBHYv2** [gta-chaos-mod/ChaosModV#1947]
**Name of effect**
Can't Skip Cutscenes

**Duration if timed effect (long or short timed?)**
2 minutes

**Effect Description**
Cutscenes will play until finished, and cannot be skipped

**Comment by RosyMiranto18** [comment]
I have an alternate idea for this. Instead, you are forced to view a random scene from any random Missions/Strangers and Freaks, but luckily, you aren't actually teleported there, but your character will be a practical sitting duck against the reality during the cutscene's playing

**Comment by TBHYv2** [comment]
Like a radom cutscene plays, thats unskippable?

**Comment by RosyMiranto18** [comment]
Yep, that's what i meant

**Comment by Last0xygen** [comment]
That hd already been requested https://github.com/gta-chaos-mod/ChaosModV/issues/1928

and forcing the player to watch a current running cutscene would be SO situational. As the effect would have to trigger at the exact moment the player wants to skip, as he either skips it right away, waits a few seconds or wants to watch it anyways
