### ISSUE TITLE
[Effect Suggestion] remove all effects(Meta)

### ISSUE THREAD

**Issue by coolharry830** [gta-chaos-mod/ChaosModV#1955]
**Name of effect**
Remove chaos(meta)

**Duration if timed effect (long or short timed?)**

**Effect Description**
randomly (like without the 4 selections, like the no chaos , 2x timer speed , you get it) removes all ongoing timers of effects

**Comment by Last0xygen** [comment]
So just „no Chaos“

**Comment by Numi43** [comment]
Almost, but not quite. It just deletes ongoing effects.

**Comment by turg-the-sad-cat** [comment]
But all meta affects are timed, what you’re saying is add a non timed no chaos basically

**Comment by coolharry830** [comment]
no like remove all effects , it dosent have a duration
