### ISSUE TITLE
[Effect Suggestion] Explosive Whale Rain

### ISSUE THREAD

**Issue by BavnoopD** [gta-chaos-mod/ChaosModV#1956]
**Name of effect**
Spawn Explosive Whales
Explosive Whale Rain

**Duration if timed effect (long or short timed?)**
Short (or as long as whale rain)

**Effect Description**
The same as normal whale rain but they’re explosive when they hit the ground :)

**Comment by Last0xygen** [comment]
Already „exists“ as „Airstrike“ 🤪
