### ISSUE TITLE
[Effect Suggestion] Is that a Creeper?

### ISSUE THREAD

**Issue by FrayPipo** [gta-chaos-mod/ChaosModV#1958]
**Name of effect**
Is that a Creeper?, Creepers aren't in this game, Copied Enemy

**Effect Description**
A pedestrian dressed in green color runs towards the player, and explodes once he is near him

**Comment by Last0xygen** [comment]
Already exists as „explosive zombies“

**Comment by pipecek** [comment]
what is a creeper?
