### ISSUE TITLE
[Effect Suggestion] Matto Mode

### ISSUE THREAD

**Issue by VikZick** [gta-chaos-mod/ChaosModV#1959]
**Name of effect**
Matto Mode

**Duration if timed effect (long or short timed?)**
long/90sec

**Effect Description**
Char in control wears a (black) tank top, shorts, sandals, long hair and a beard. In addition the char will scream/shout angrily.

E.g. Franklin 
  -  Bitch-ass bullshit.
  -  Man, screw this.
  -  Man, fuck this shit.
  -  What the fuck?
  -  Fuck.

**Comment by pipecek** [comment]
What's Matto?

**Comment by Last0xygen** [comment]
Already a thing of „randomize player clothes“
