### ISSUE TITLE
[Effect Suggestion] game re-dub

### ISSUE THREAD

**Issue by begoade** [gta-chaos-mod/ChaosModV#1966]
All main characters have their voices replaced by people in the community reading the game script and dubbing it themselves

**Comment by juhana** [comment]
This is something that should be a separate mod if anything. It would also be a *massive* project – each main character has tens of thousands of voice lines.

**Comment by kolyaventuri** [comment]
While im sure this may be _technically_ doable, the undertaking is WAY out of scope for the mod, on too of how much sheer data that would be to download.
