### ISSUE TITLE
[Effect Suggestion] Forced stunt jump

### ISSUE THREAD

**Issue by Theduck404** [gta-chaos-mod/ChaosModV#1970]
**Name of effect**
Stunt jump, Forced stunt jump

**Duration if timed effect (long or short timed?)**
Short 

**Effect Description**
Teleports player to random stunt jump in a random vehicle(or current) if you fail the stunt jump the car explodes, Teleports player back to original location on successful jump.

**Comment by Last0xygen** [comment]
Already requested several times…
