### ISSUE TITLE
[Effect Suggestion] Delay every Input

### ISSUE THREAD

**Issue by Thierry2021** [gta-chaos-mod/ChaosModV#1972]
**Name of effect**
Could be something like
- Mars Rover (since there is a delay for transmission of data)
or simply 
- Delayed input

**Duration if timed effect (long or short timed?)**
Since the effect doesn't hinder the player from continuing the game, it can be quite long (for example 30-60sec)

**Effect Description**
The effect delays every input my the player for a fixed amount of time (maybe 2-3 seconds).
So if a player for example presses "W" the player begins to move only after those 2 seconds the same thing when the button is not being pressed anymore..

Sort of like a moon/mars rover where manual control has a delay.

**Comment by pipecek** [comment]
Suggested multiple times

**Comment by Last0xygen** [comment]
Yes, suggested multiple times
