### ISSUE TITLE
[Effect Suggestion] You're Driving A Tank

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#1976]
Car = Tank
It's a tank, not a car
You're Driving A Tank

Long timed

This effect makes your car invulnerable, able to push anyone without speed reduction and blow up cars on impact.
Objects, peds, vehicles - anything that can be pushed will be pushed with the same speed.

**Comment by Last0xygen** [comment]
Already possible with forcefield

**Comment by JustTunerYT** [comment]
@Last0xygen You didn't get the idea. Not just push them with "magic force", EXACTLY with the car, because forcefield for first don't make your car invulnerable and player can still be killed. AND forcefield explodes cars only if they are pushed to the wall or flew far too high. So it's not really a "Forcefield"

**Comment by JustTunerYT** [comment]
If you didn't understand, i was relying on GTA:SA Cheat Code, that does so as i described it
