### ISSUE TITLE
[Effect Suggestion] Passive Mode

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#1978]
ez no re
Griefer Dodging

Long timed

When active, disable weapon selector (or make player's damage to 0 (player cannot hurt anyone)), make player invincible to anyone (nor make him ghost to any bullets, rockets and vehicles). If player is in vehicle, vehicle is ghost to anything except world and invulnerable too.

**Comment by pipecek** [comment]
suggested already

**Comment by JustTunerYT** [comment]
> suggested already

Can you tag the suggestion?

**Comment by pipecek** [comment]
#983

**Comment by Last0xygen** [comment]
Duplicate #983
