### ISSUE TITLE
[Effect Suggestion] Prop Hunt

### ISSUE THREAD

**Issue by Bilalhamid2** [gta-chaos-mod/ChaosModV#1983]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

> Name: prop hunt
Duration: 1 minute
Description: Gives the player a gun and when he shoots he becoms the object/person he shoots

**Comment by TheRealAyCe** [comment]
That would mean changing the player model, and, so far, all suggestions containg this requirement have been rejected, since it may cause crashes.
