### ISSUE TITLE
[Effect Suggestion] Make it so fake crash shows a picture of Matt's desktop wall paper

### ISSUE THREAD

**Issue by Pineyapple** [gta-chaos-mod/ChaosModV#1984]
**Name of effect**
Fake Crash

**Effect Description**
The usual fake crash but to make it more realistic, it can sometimes show matto's desktop background

**Comment by kolyaventuri** [comment]
This mod is not only for DarkViperAU. Also, this has already been suggested. ex: #1103, #335
