### ISSUE TITLE
[Effect Suggestion] Twitter

### ISSUE THREAD

**Issue by M0ntherload** [gta-chaos-mod/ChaosModV#1988]
**Name of effect**
Twitter

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Everyone becomes verbally aggressive to each other (no one actually fights), possibly replace NPC's with clown models
NPC's in cars show the finger

**Comment by TheRealAyCe** [comment]
So Unfriendly Neighbourhood?

**Comment by Last0xygen** [comment]
Already exists as „ Unfriendly Neighbourhood“
