### ISSUE TITLE
[Effect Suggestion] Fake donation

### ISSUE THREAD

**Issue by Theduck404** [gta-chaos-mod/ChaosModV#1995]
**Name of effect**
Fake donation, Troll donation 

**Duration if timed effect (long or short timed?)**
8 seconds
**Effect Description**
Creates the hell yeah sound effect(or the current donation effect he is using) and a donation message of 1000,100,10 appears randomly with these potential messages, (Matt you forgot to turn off alerts), (Take my money), (i don't need the money have it all) (You got jebaited). Effect should not appear on effect list until after.

**Comment by Theduck404** [comment]
Hope this hasn't been done before

**Comment by Last0xygen** [comment]
you do realise that this mod is not done exclusively for DarkViper? :)
