### ISSUE TITLE
[Effect Suggestion] God Of War 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#1999]
**Duration if timed effect (long or short timed?)**
Medium 

**Effect Description**
The player only has a stone hatchet in which if the player hits an NPC, thunder is heard and the NPC is sent flying back. The hatchet insta kills them too.

**Comment by Last0xygen** [comment]
I don’t think there is a Stone hatchet in gta

**Comment by Pvi05** [comment]
There is, available in GTA Online. Prop is surely findable in the game files. 
Here is the wiki page : https://gta.fandom.com/wiki/Stone_Hatchet

**Comment by TerrizX** [comment]
> There is, available in GTA Online. Prop is surely findable in the game files.
> Here is the wiki page : https://gta.fandom.com/wiki/Stone_Hatchet

Even better, I suggested an updated version with just a regular hatchet, nice to know that stone hatchet is actually in the game.
