### ISSUE TITLE
[Effect Suggestion] Spawn Friendly Jesus/Extreme Friendly Jesus

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2002]
**Effect Description**
Friendly Jesus spawns Jesus equipped with a railgun and same features (not prone to explosions etc) like his opposite and is a companion to the player. Extreme Friendly Jesus is a seperate effect but spawns a companion (to the player) Jesus that has an Oppressor, equipped with a railgun also if he is knocked off the Oppressor (also with same features as his opposite). And just for the hell of it  (and some differentiation) if the Extreme Friendly Jesus dies, he explodes.

**Comment by turg-the-sad-cat** [comment]
Already been suggested multiple times

**Comment by Last0xygen** [comment]
Yup, already requested a lot of times, still not interesting
