### ISSUE TITLE
[Effect Suggestion] Teleport to Random Online Interior

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2005]
**Effect Description**
What it says in the title. The player teleports to any of the Online interiors in Online, like the bunker, apartment etc whatever.  Apparently Online Interiors exist under the map in places even in SP so it's possible to go there. Plus would just be a cool effect.

Edit: To get out the interior - some people playing may just know to jump into the edge of the interior and glitch through but the player is given an explosive in their inventory.

**Comment by turg-the-sad-cat** [comment]
But players will get stuck and what will happen if they don’t have explosives

**Comment by TerrizX** [comment]
> But players will get stuck and what will happen if they don’t have explosives

Damn you right. Maybe it's a timed effect then? You stay there for 30 seconds (medium duration I guess) and are teleported back?

**Comment by turg-the-sad-cat** [comment]
Sadly it has also been suggested before

**Comment by TerrizX** [comment]
> Sadly it has also been suggested before

It hasn't. People have suggested teleporting to random interiors in general. Not Online interiors tho I've checked.

**Comment by kolyaventuri** [comment]
To be fair, it's not explicitly stated but it's implied in #1537 w/ the "Open All Interiors" mod having online interiors available. Additionally, I agree with the fact that this is soft-lock prone if you're put in a building you can't get out of easily. A "teleport out after 30 seconds" option also doesn't make for a good effect if that's the failsafe.
