### ISSUE TITLE
[Effect Suggestion] Russian traffic

### ISSUE THREAD

**Issue by Resenak** [gta-chaos-mod/ChaosModV#2010]
/**Name of effect**
-"Russia mode"
-"GTA russia"
-"Russia time!"

/**Duration if timed effect (long or short timed?)**
-IDK ... hmm a couple seconds 30 or 1 minute 

/**Effect Description**
-SO.... basically Russia traffic at its best.
Peds drive completely erratic, ignoring Traffic lights, going VERY fast, crashing,driving over the sidewalk..etc you get the idea..
maybe with hardbass in the background, like when jesus appear,

**Comment by Last0xygen** [comment]
Sound effect/music is not part of the mod and has t be set by the player.
Traffic running into the player is already a thing with „traffic magnet“
