### ISSUE TITLE
[Effect Suggestion] who keeps hitting me or John cena 

### ISSUE THREAD

**Issue by Slothboi42** [gta-chaos-mod/ChaosModV#2011]
**Name of effect**
Who keeps hitting me. John cena maybe?

**Effect Description**
Description of the effect; what should it do?
Spawns in one invisible enemy with no weapons who will try and punch u to death.

**Comment by TerrizX** [comment]
This has already basically been suggested #1912

**Comment by Last0xygen** [comment]
Yes, duplicate
