### ISSUE TITLE
[Effect Suggestion] Mission Fail but for the wrong reason(s)

### ISSUE THREAD

**Issue by ViktorL77** [gta-chaos-mod/ChaosModV#2013]
**Name of effect**
Something Wrong?

**Effect Description**
1) When in mission: This effect would instant mission fail the player and under the typical "Mission Failed" message the player would get a random message from another mission.
For instance - let's say you (the player) play "Pulling Favors" and you drive the tow truck with Tonya around the city. When this effect happens the "Mission Fail" bar appears and under that it would say "Not enough sticky bombs remaining" (a fail message from the mission "Friends Reunited").

2) When the player is not in a mission: This effect would teleport the player to a random mission (while displaying the name of the effect as "Teleport to Random Mission"), start a countdown of ~30 seconds or more (taking into account the possibility that the player might watch the cutscene) then fail the mission and display the random message.

3) Now HOW will this effect actually fail the mission? I suggest by either killing the player (which in a visual way might create more confusion for the player) or either by killing an important character (since most of the missions have at least a 2nd character)

**Comment by Last0xygen** [comment]
Most Players won’t even read those messages

**Comment by TheRealAyCe** [comment]
Wasn't there an effect "Gustavo died" once?

**Comment by Last0xygen** [comment]
> Wasn't there an effect "Gustavo died" once?

There was maybe a request like that, but never an effect
