### ISSUE TITLE
[Effect Suggestion] Mission Replay

### ISSUE THREAD

**Issue by ViktorL77** [gta-chaos-mod/ChaosModV#2014]
**Name of effect**
This seems familiar

**Effect Description**
I was thinking that you guys might be able to access the "mission replay" option from the game and force start a random mission that was already done by the player.
Or if the last part is impossible then just force start the first mission in the game

**Comment by Last0xygen** [comment]
Already exists as „teleport to random mission“.
Replaying older missions is not an effect we try to create
