### ISSUE TITLE
[Effect Suggestion] Fake "Fake Crash"

### ISSUE THREAD

**Issue by ViktorL77** [gta-chaos-mod/ChaosModV#2015]
**Name of effect**
The Real Fake Crash
Fake Crash 2.0
I love you, streamer
Brace Yourselves

**Effect Description**
It displays the "Fake Crash" option on the screen while it freezes the game for exactly one second then it force closes the game

**Comment by Last0xygen** [comment]
Crashing the game is not a good effect

**Comment by TheRealAyCe** [comment]
More like an unpleasant side-effect :P
