### ISSUE TITLE
[Effect Suggestion] The 4th Way

### ISSUE THREAD

**Issue by ViktorL77** [gta-chaos-mod/ChaosModV#2016]
**Name of effect**
The 4th Way

**Effect Description**
Puts the player in the Devin Weston's car (from the end of the game) and teleports the player on the cliff from the end of the game. The car is locked (so the player can't get out) and is slowly going to the edge of the cliff where you can watch Strech, Steve Haines, Wei Cheng and Devin Weston dancing. The car then falls on the rocks, explodes and when all this is happening the ending credits roll on the screen.

**Comment by TerrizX** [comment]
Would be better if Michael, Trevor and Franklin were there behind the car dancing rather than Devin, Wei and Steve. Even better, maybe they could be shooting at the car and making it roll/explode. The vehicle is locked so the player wouldn't be able to get out unless an effect comes on in time that un-locks the player. May be too restrictive tho

**Comment by ViktorL77** [comment]
> Would be better if Michael, Trevor and Franklin were there behind the car dancing rather than Devin, Wei and Steve.

This defies the original idea. In the "3rd way" mission you need to kill these guys and you can't play with Franklin, Trevor or Michael and have a copy of them shooting at themselves, it doesn't make any chance. I suggested this effect as to make Strech, Steve, Cheng, and Devin take revenge on one of the characters

**Comment by TerrizX** [comment]
> > Would be better if Michael, Trevor and Franklin were there behind the car dancing rather than Devin, Wei and Steve.
> 
> This defies the original idea. In the "3rd way" mission you need to kill these guys and you can't play with Franklin, Trevor or Michael and have a copy of them shooting at themselves, it doesn't make any sense. I suggested this effect as to make Strech, Steve, Cheng, and Devin take revenge on one of the characters

True, fair enough then.

**Comment by Last0xygen** [comment]
An effect that elaborate just blocks the player from playing. Also, if it ends with always killing the player this is not a Good effect
