### ISSUE TITLE
[Effect Suggestion] Stunt double 

### ISSUE THREAD

**Issue by Hours09** [gta-chaos-mod/ChaosModV#2022]
Stunt double
Teleport 
The effect should be teleporting the player to the mountain where the car drives off of a mountain, and make the player the driver of the vehicle.

**Comment by juhana** [comment]
This already happens with "Teleport To Mount Chiliad" if the player is in a car.

**Comment by Last0xygen** [comment]
> This already happens with "Teleport To Mount Chiliad" if the player is in a car.

True
