### ISSUE TITLE
[Effect Suggestion] Strike me down Zeus

### ISSUE THREAD

**Issue by Evoction** [gta-chaos-mod/ChaosModV#2028]
Name of effect
Strike me down Zeus

Duration if timed effect (long or short timed?)
Instant

Effect Description
When the effect pops up on stream,let matto have 3 seconds of peace before you "strike him down".You can use a explosion that would look like a thunderbolt or a thunderbolt itself (if it even exists)

**Comment by Last0xygen** [comment]
This mod is not exclusive to „Matto“
The effect itself is „suicid“, „ragdoll player“ or something familiar and therefore not a good suggestion
