### ISSUE TITLE
[Effect Suggestion] Equip Low-Grip Tyres On All Vehicles

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#2033]
**Name of effect**
Equip Low-Grip Tyres On All Vehicles

**Effect Description**
Every currently spawned vehicle gets equipped with Low-Grip Tyres.

**Comment by TheRealAyCe** [comment]
Would this be the "GTA 4 driving" people have been asking before, then? :D

**Comment by juhana** [comment]
"Slippery Vehicles" already exists

**Comment by DEATHCON1** [comment]
> "Slippery Vehicles" already exists

Right, ok, but this'll make your car a permanent slippery vehicle...

**Comment by Last0xygen** [comment]
So it’s slippery vehicles but permanent? Too similar
