### ISSUE TITLE
[Effect Suggestion] Just Give Me The Mission Objective Already!

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#2035]
**Name of effect**
Just Give Me The Mission Objective Already!

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
The game plays random voice lines from KDJ and Sessanta when they both talk to you on the phone at the same time. Just the ones where they flirt with each other.

**Comment by Last0xygen** [comment]
Playing random voice lines is not an effect idea we’re looking for
