### ISSUE TITLE
[Effect Suggestion] Canonball!

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2038]
**Effect Description**
Player is positioned sideways, with arms by their side (if possible but if not just have the player be in the position they're in when still but tilted 45 degrees) and "shot" out into the sky (like a canon, so not directly upwards but at an angle like said above). Player is shot VERY far and very fast like a canon. Player should end up after being launched on the other side of the map. If the player has a parachute they can counter this eventually but if not, they'll probably just die unless they hit something that dont kill them.

**Comment by Last0xygen** [comment]
Would instantly kill the player if in a building or under / near any building.
„Fling player“ alsrwady exists though not that extreme
