### ISSUE TITLE
[Feature Suggestion] Fake Crash showing that Olibrate all Peds etc

### ISSUE THREAD

**Issue by Coolbombe** [gta-chaos-mod/ChaosModV#2039]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Coolbombe** [comment]
That new feature should show that if Fake Crash got chossen then that up right it shows a random Effect which can Crash the Game like olibrate all peds or Bus Bois

**Comment by Last0xygen** [comment]
Already requested several times
