### ISSUE TITLE
[Effect Suggestion] ''No speeding law''

### ISSUE THREAD

**Issue by Dan777cz** [gta-chaos-mod/ChaosModV#2040]
If you drive faster than 72 mph you gain a wanted level. that's it lol

**Comment by pipecek** [comment]
All you had to do was follow the damn Format Dan. Anyhow, sounds pretty good.

**Comment by Last0xygen** [comment]
After „innocence is illegal“ and „30 mph limit“ I don’t think we have to have another effect like this
