### ISSUE TITLE
[Effect Suggestion] Prison Break

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2041]
**Effect Description**
Teleports the player to the yard in the prison. 5 of the prisoners are now your companions, and follow you and will shoot for you. You also have a 5 star wanted level.

**Comment by Last0xygen** [comment]
„Prisons“ effect have already been requested

**Comment by TerrizX** [comment]
> „Prisons“ effect have already been requested

People have mainly requested Teleport to Prisons and that's it though? Maybe I guess you'd get a wanted level edgeways even with a typical teleport.
