### ISSUE TITLE
Thanos Effect (remake)

### ISSUE THREAD

**Issue by ImCringe** [gta-chaos-mod/ChaosModV#2050]
**Name of effect**
Thanos Has Arrived

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Wipes out half of the player's health, armor and special ability bar. Then gives the player purple skin. Also, if possible, wipes out half NPCs (but not vital to the mission)

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=thanos duplicate

**Comment by Last0xygen** [comment]
Yup, duplicate
