### ISSUE TITLE
[Effect Suggestion] I’m Batman…..

### ISSUE THREAD

**Issue by thegamingsoul56** [gta-chaos-mod/ChaosModV#2051]
**Name of effect**
I’m Batman 

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Causes NPC’s to ragdoll and scream when their hp is low, but they cannot be killed and will stand back up when effect is over. 

**EDIT**
Also remove players guns (or ability to fire), but keep melee weapons and throwables (return on effect completion if possible)

**Comment by turg-the-sad-cat** [comment]
But isn’t that just ragdoll everyone with one extra step?
