### ISSUE TITLE
[Effect Suggestion] It's high noon

### ISSUE THREAD

**Issue by Enginefailed** [gta-chaos-mod/ChaosModV#2054]
**Name of effect**
It's high noon

**Effect Description**
Spawn an enemy ped with a revolver and aimbot

**Comment by Last0xygen** [comment]
Spawn random enemy already is a thing.
Spawning an enemy and giving him the power to easily kill the player is not a good effect idea

**Comment by SeanMirrsen** [comment]
> 
> 
> Spawn random enemy already is a thing.
> Spawning an enemy and giving him the power to easily kill the player is not a good effect idea

Honestly, I'd beg to differ. Spawning a random enemy and forcing the player to kill them in a short time window or else the enemy kills them, is a pretty decent effect idea. Most of the random enemy spawns are easily ignored. Like anytime you're in a moving vehicle, even Griefer Jesus is mostly unable to harm you as by the time he's jumped out and able to shoot you, you're already out of range.

Granted, this specific idea may not be that much good in that regard. Hold a sec while I think up something better.
