### ISSUE TITLE
[Effect Suggestion] Free Chicken Nuggets Apocalpys

### ISSUE THREAD

**Issue by D3DH4CK3R** [gta-chaos-mod/ChaosModV#2055]
Everyone comes at you to offer free chicken nuggets

**Comment by Malatype** [comment]
So basically peds riot?

**Comment by Last0xygen** [comment]
Either peds riot or you are famous

**Comment by D3DH4CK3R** [comment]
Nah it means everyone ask you if you want free chicken nuggets
