### ISSUE TITLE
[Feature Suggestion] Change for Blimp Strats

### ISSUE THREAD

**Issue by Rolypolyoly1877** [gta-chaos-mod/ChaosModV#2064]
**Describe the solution you'd like**
Having the Blimp Strats effect teleport the player to a random mission instead of to the observatory every time.

**Comment by TheRealAyCe** [comment]
The beauty of Blimp Strats is that it spawns the player/blimp precisely so they land in the "Davey" spot. Just teleporting it randomly would mean that for every mission such a spot has to be found, otherwise the blimp is just going to blow up and kill the player. Besides, "Teleport to random mission" already exists.

**Comment by Rolypolyoly1877** [comment]
True. I suggested the feature to make the effect more usable in different scenarios however that would remove some of the chaos aspect of it (where chaos is kinda necessary for a chaos mod to work).
On second thought, it acts the same way as "Teleport to (location)". Is it on the list of fake teleports?

**Comment by Road-Train** [comment]
> **Describe the solution you'd like**
> Having the Blimp Strats effect teleport the player to a random mission instead of to the observatory every time.

Blimp strats refers to a speedrun strategy which is only used in dead man walking. I don't think making this trigger on other missions would make sense. Also some missions start in interiors making it impossible to 'blimp strat' to them anyway.

**Comment by Last0xygen** [comment]
> True. I suggested the feature to make the effect more usable in different scenarios however that would remove some of the chaos aspect of it (where chaos is kinda necessary for a chaos mod to work).
> On second thought, it acts the same way as "Teleport to (location)". Is it on the list of fake teleports?

It is not on the fake teleport list.
You could open a new Request for it :) 
This one is closed
