### ISSUE TITLE
Kickflip not strong enough

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#207]
https://youtu.be/o8OScme2T3E?t=4676

Maybe stop car in  place and then kickflip? Or make kickflip a scripted motion so that the car always does a full flip.

**Comment by ProfessorBiddle** [comment]
playing around with different driving conditions this doesn't seem to be a problem anymore. Not sure what changed.

**Comment by Last0xygen** [comment]
Nothing changed 🤪

**Comment by ProfessorBiddle** [comment]
> Nothing changed 🤪

I didn't think so, but I can't seem to replicate the video anyway. Might have been a fluke.
