### ISSUE TITLE
[Effect Suggestion] CJ's Garage

### ISSUE THREAD

**Issue by Numi43** [gta-chaos-mod/ChaosModV#2070]
**Name of effect**
CJ's Garage (or, alternatively, Retro Parade)

**Duration if timed effect (long or short timed?)**
Preferably long or even meta

**Effect Description**
The only vehicles to be spawned are those resembling vehicles made in or before 90s. (Basically all Sports Classics, most of Muscle Cars and few more from other categories).

*Not sure if Native Trainer disables Online cars despawning. If it doesn't disable it, Simple Trainer or Rainbomizer might be needed for the effect to happen.

**Comment by Last0xygen** [comment]
already requested as an addition to ls noire

**Comment by Numi43** [comment]
Alright, interesting.
