### ISSUE TITLE
[Effect Suggestion] Freefall Speed Limit for Teleport to Heaven

### ISSUE THREAD

**Issue by Arhammahra** [gta-chaos-mod/ChaosModV#2075]
**Teleport to Heaven**

**Effect Description**
Everything as before, but the character just falls slowly. Usually the speed goes upto ~430Km/h when falling, but it would be hilarious if you just keep on falling for a solid minute.

**Comment by Last0xygen** [comment]
Would block the player from playing unnecessarily long

**Comment by Arhammahra** [comment]
Well I was wrong about the freefall speed being 430km/h. That can only be achievable using a glitch on old patches, actual fall speed without a parachute is 197km/h and it already takes 44 seconds to reach the ground.
