### ISSUE TITLE
[Effect Suggestion] Millions to One

### ISSUE THREAD

**Issue by MrJayGamerTTV** [gta-chaos-mod/ChaosModV#2076]
Name of effect:
- Millions to One

Effect Description:
- As DarkViperAU himself said, it is Millions to One... This effect would spawn a cougar behind the player, and that cougar would then attack the player and likely kill them. Much like Jesus, this effect would bring joy to us all (except the ones who play the Chaos mod), as "There aren't cougars in missions, it is millions to one"... Sounds fun?

**Comment by Last0xygen** [comment]
Already requested thousands of times…
This mod is not a mod just for darkviper
