### ISSUE TITLE
[Effect Suggestion] Violent Gravity Smashing, GraviSmash

### ISSUE THREAD

**Issue by Lulu50k** [gta-chaos-mod/ChaosModV#2078]
**Name of effect**
GraviSmash

**Duration if timed effect (long or short timed?)**
30-60sec
**Effect Description**
You are thrown up into the air and immediately thrown back down to the ground hard repeatedly until the effect ends. Probably in quarter second intervals. “2 smashes to the ground per second”

**Comment by YEETERSD** [comment]
Isn't this just earthquake?

**Comment by Last0xygen** [comment]
Alread excited as „earthquake“ and/or „doomsday“
