### ISSUE TITLE
[Effect Suggestion] Mute everyone

### ISSUE THREAD

**Issue by Evoction** [gta-chaos-mod/ChaosModV#2080]
**Name of effect**
Mute everyone or mute all pedestrians

**Duration if timed effect (long or short timed?)**
Lasts 1 minute

**Effect Description**
Mutes everyone around the player

**Comment by worm202** [comment]
Might potentially break mission progression?
Since some missions require dialogue to complete

**Comment by Evoction** [comment]
> Might potentially break mission progression?
> Since some missions require dialogue to complete
We could make it so it lowers the game volume to zero so that way the game countinues while we can't hear anything

**Comment by TheRealAyCe** [comment]
You mean this effect? https://github.com/gta-chaos-mod/ChaosModV/issues/339 :D

**Comment by Last0xygen** [comment]
Duplicate #339
