### ISSUE TITLE
[Effect Suggestion] Back to the past 

### ISSUE THREAD

**Issue by NotGrieferJesus** [gta-chaos-mod/ChaosModV#2081]
**Name of effect**
Back to the past

**Duration if timed effect (long or short timed?)**
-

**Effect Description**
Has to complete prologue to continue and the time does not progress. If this effect is active in the mission prologue you have to complete the mission again then will be control in the session where prologue is playing.

**Comment by Last0xygen** [comment]
Not a good effect, huge time waster 😅

**Comment by NotGrieferJesus** [comment]
> Not a good effect, huge time waster 😅

isnt that what is chaos supposed to be?

**Comment by Numi43** [comment]
It´s meant to experience the game in a new way. Not to make you repeat one lengthy mission over and over again, my dude.
