### ISSUE TITLE
[Effect Suggestion] Masturbate 

### ISSUE THREAD

**Issue by Arhammahra** [gta-chaos-mod/ChaosModV#2083]
**Effect Name**
Quick Fap

**Duration if timed effect (long or short timed?)**
10s? if not possible however long Trevor's masturbation animation lasts

**Effect Description**
Stop everything and start masturbating, not just for Trevor but for all characters if his animation can be applied to all characters. If the character is in a vehicle, he gets out and start masturbating. Would be so fking hilarious if this gets added.

**Comment by Numi43** [comment]
Uhhhhh no (and even if it ever gets added, needs to be disabled by default)

**Comment by Last0xygen** [comment]
this is not a good effect :|
