### ISSUE TITLE
[Effect Suggestion] Spawn Corrupt Cop

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2085]
**Effect Description**
Spawns a companion cop. He helps the player out, and greets members of all gangs there is LS if near them. If the player shoots at any gang members or a large number of police, the cop turns on the player and becomes your enemy. If the player shoots at one-two policemen, the corrupt cop wont do anything.

**Comment by Last0xygen** [comment]
With these specifics it would have to be a timed effect which does not fit to a „spawn …“ effect. There’s now way to prematurely stop a timed effect

**Comment by TerrizX** [comment]
> With these specifics it would have to be a timed effect which does not fit to a „spawn …“ effect. There’s now way to prematurely stop a timed effect

Updated it to make it simpler in #2087
