### ISSUE TITLE
[Effect Suggestion] Spawn Corrupt Cop (Updated)

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2087]
**Effect Description**
Spawns a companion cop that greets every gang member in LS (if in the vicinity of course).

**Comment by Last0xygen** [comment]
Would be a minor addition to a „spawn random companion“, most plsyers wouldn’t even realize that. Also „greeting a gang member“ is not something that can be set once, would still require a timed effect

**Comment by TerrizX** [comment]
> Would be a minor addition to a „spawn random companion“, most plsyers wouldn’t even realize that. Also „greeting a gang member“ is not something that can be set once, would still require a timed effect, sorry

Damn, aight then
