### ISSUE TITLE
[Effect Suggestion] Richard Hammond Mode

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#2093]
**Name of effect**
No steering
Richard Hammond mode

**Duration if timed effect (long or short timed?)**
30 seconds

**Effect Description**
Makes it so you can't turn left or right, this is a parody on the Richard Hammond rimac crash.

**Comment by Last0xygen** [comment]
Disable random direction is already an effect

**Comment by pipecek** [comment]
> Disable random direction is already an effect

It only disables a random direction afaik. This disables both left and right steering and not W/A/S or D

**Comment by kolyaventuri** [comment]
FWIW, disable Left / Right (or Forward / Backward for that matter) actually already used to exist. It was upgraded to disable random direction

**Comment by TheRealAyCe** [comment]
Because disabling W&S or A&D essentially was just a "stop playing the game for a while" effect when you had to drive.
