### ISSUE TITLE
[Effect Suggestion] Skyfall but with Jesus

### ISSUE THREAD

**Issue by NotGrieferJesus** [gta-chaos-mod/ChaosModV#2094]
**Name of effect**
Skyfall but with Jesus

**Effect Description**
Should do basically the same thing as the cheat skyfall but with a twist extreme griever Jesus spawns with you but he has a oppressor mk 2 hostile towards the player.

**Comment by Last0xygen** [comment]
Skyfall has already been requested and griefer Jesus is already a thing
