### ISSUE TITLE
extreme vehicle damage & teleport to North Yankton

### ISSUE THREAD

**Issue by bloodyframe2019** [gta-chaos-mod/ChaosModV#2097]
i made a suggestion before and it got deleted because it was too close to vehicles explode on impact but it wasn't

extreme vehicle damage: add extreme vehicle damage but once the vehicle is damaged it is still driveable and will not explode if you crash multiple times. basically like gta 4's vehicle damage

teleport to North Yankton: teleports player to North Yankton with the map loaded in but instead it has a 50/50 chance of being a timer or you stay permantly till you die. (the map vanishes when dead or the timer runs out)

**Comment by TerrizX** [comment]
Teleport to North Yankton has been requested gazillion times, just saying.

**Comment by TerrizX** [comment]
> ok and the vehicle damage?

May have been requested before too but idk, just gotta wait for LastOxygen to say something

**Comment by bloodyframe2019** [comment]
ok i hope it makes it otherwise i have to think about something else

**Comment by Last0xygen** [comment]
> > ok and the vehicle damage?
> 
> May have been requested before too but idk, just gotta wait for LastOxygen to say something

Something

;)
North Yankton has been requested a lot of times but simply put it would not be a good effect (search for closed requests and you’ll find more elaborate explanations :) )
The other effect sounds like „crumbling vehicles“ but „only visual“, am I understanding this correctly?
If so, I think crumbling vehicle and actual damage is enough, iirc gta 4 had a more „advanced“ damage model that gta 5, so idk if it would even be that interesting here

**Comment by Last0xygen** [comment]
The developer? Rockstar? 😂😂
Yeah, no, that won’t work

**Comment by bloodyframe2019** [comment]
i got another idea if this isn't working. bad A.I like GTA III, GTA: Vice City and GTA: San Andreas. bad A.I drive fast and emergancy vehicles will drive on the target like the previous games. another one is worst A.I (makes vehicles target people walking on streets not just the player.

**Comment by Last0xygen** [comment]
> i got another idea if this isn't working. bad A.I like GTA III, GTA: Vice City and GTA: San Andreas. bad A.I drive fast and emergancy vehicles will drive on the target like the previous games. another one is worst A.I (makes vehicles target people walking on streets not just the player.

Single requests for each idea please.
But in this case you can save it. Making emergency units drive wild is a „mild“ version of „traffic magnet“ for example
