### ISSUE TITLE
[Effect Suggestion]  Change or ad Waypoint 

### ISSUE THREAD

**Issue by HOG-RIIIIIIDER** [gta-chaos-mod/ChaosModV#2099]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by turg-the-sad-cat** [comment]
Already been suggested before

**Comment by Last0xygen** [comment]
Please use the template for requesting an effect.
But yes, this also was requested several times
