### ISSUE TITLE
added Effect "Floor is lava" burning floor after  3 seconds timer 

### ISSUE THREAD

**Issue by HOG-RIIIIIIDER** [gta-chaos-mod/ChaosModV#2100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Last0xygen** [comment]
Pleeeeeease use and edit the template and don’t just write everything into the title..
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/444
