### ISSUE TITLE
bad A.I and worst A.I [my last idea for 2 effects]

### ISSUE THREAD

**Issue by bloodyframe2019** [gta-chaos-mod/ChaosModV#2101]
bad A.I is like GTA III, GTA: Vice City and GTA: San Andreas. bad A.I drive fast and emergancy vehicles will drive on the target like the previous games. another one is worst A.I (makes vehicles target people walking on streets not just the player. they will continue driving on the target till they die. almost like traffic magnet but peds are effected too on street)

**Comment by Last0xygen** [comment]
Like I told you in the other request: this is „traffic magnet“

**Comment by bloodyframe2019** [comment]
for peds. ok i am done this github forum or whatever sucks.

**Comment by bloodyframe2019** [comment]
no i mean drivers drive over peds until they die not you're famous

**Comment by bloodyframe2019** [comment]
drivers can stay in the car and still target peds when they are famous. you're famous only effect peds on street not roads (drivers)

**Comment by bloodyframe2019** [comment]
i just got an original idea sort of what about you're famous but people steal cars and try to ran you over

**Comment by bloodyframe2019** [comment]
otherwise i don't see much of an a original choice. maybe tornado? vehicles, peds and objects spin around till the timer runs out

**Comment by TheRealAyCe** [comment]
This is not Discord, just edit your last post instead of posting 4 times in a row.

**Comment by bloodyframe2019** [comment]
i do not use discord lol
