### ISSUE TITLE
[Effect Suggestion] Spawn killer squad

### ISSUE THREAD

**Issue by LordPhoenix11** [gta-chaos-mod/ChaosModV#2106]
**Name of effect**
-Spawn killer squad
-Is this the Suicide Squad?

**Effect Description**
Spawns Griefer Jesus, Space Ranger, Angry Alien and Impotent Rage BUT each one at 1 HP

**Comment by Last0xygen** [comment]
Not a good effect idea, would be spawnkilled instantly
