### ISSUE TITLE
[Suggestion] Effect: Randomize Player's Surroundings

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#211]
Lasting, splits the ground around the player into equal squares (like chunks in Minecraft) and then randomizes their position, so player's surroundings would be completely random.

The one problem that may happen is "holes" between those chunks where you can fall, caused by the differences in altitude (if speaking about mountainous terrain, for example). Idk, maybe that's exactly the point of this effect, but if you want and if this is possible, I guess you can fill these holes with some random walls.

![image](https://user-images.githubusercontent.com/51336396/100927861-82716200-34f6-11eb-911a-fd75145703d2.png)

**Comment by ProfessorBiddle** [comment]
This is a really cool idea, but sadly I don't think it's possible with scripting.

**Comment by MoneyWasted** [comment]
Modifying terrain during runtime (while the game is running) the way you are suggesting is impossible with out heavy modifications to the games core. The closest we could do is spawning different parts of the map more specifically the LOD (low render distance) models around the player to give the illusion that they are in a different place.
