### ISSUE TITLE
[Suggestion] Effect: Spawn 10 Buffalos

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#212]
So, i remembered the glitch in race event, that Matt (aka DarkViperAU) loved, which spawns buffalo every time player repeats race after fail (https://www.youtube.com/watch?v=RpmkZ2d1tbw). I thought of it and decided to suggest spawning these 10 times. Color: White. Upgrades: None

**Comment by TheRealAyCe** [comment]
Alternative names:
Buffalo Stampede
Car Herder

**Comment by ProfessorBiddle** [comment]
Alternately spawning a buffalo every time the player interacts with something (using phone, entering vehicle, starting mission, reaching checkpoint) would be interesting,

**Comment by JustTunerYT** [comment]
I think negative, because if it will affect shooting too, game would crash

**Comment by ProfessorBiddle** [comment]
Good point, maybe have a timed effect that spawns a buffalo every few
seconds?

**Comment by JustTunerYT** [comment]
But, what about this one? I thought, that it would be exactly 10 buffalos and it will be one timed effect

**Comment by JustTunerYT** [comment]
Oh, nvm. Had to press "more" button.
Closed
