### ISSUE TITLE
[Effect Suggestion] Spawn Tryhard

### ISSUE THREAD

**Issue by Ruhto** [gta-chaos-mod/ChaosModV#2122]
**Name of effect**
Potential name(s) for the effect

Spawn Tryhard.

**Effect Description**
Description of the effect; what should it do?

it spawns an npc that has an tryhard outfit and he has heavy sniper mk2 with explosive bullets. it would spawn a little far away from the player so the player cant easily kill him. so the tryhard then snipes the player.

**Comment by Ruhto** [comment]
i forgot an one thing. It has aimbot too

**Comment by Rolypolyoly1877** [comment]
Isn't this essentially just a reskinned Griefer Jesus?

**Comment by Ruhto** [comment]
> Isn't this essentially just a reskinned Griefer Jesus?

No different gun and doesnt spawn right next to the player

**Comment by Last0xygen** [comment]
Duplicate of https://github.com/gta-chaos-mod/ChaosModV/issues/1093 and #1020
