### ISSUE TITLE
[Effect Suggestion] You, Guilty!

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2123]
**Duration if timed effect (long or short timed?)**
Medium 

**Effect Description**
Sets the player and their vehicle aflame but the player still operates as normal. Player clothes become more punk-ish (like Ghost Rider, this effect is pretty much just the player becoming Ghost Rider). If the player looks at a ped, the ped goes aflame. Their vehicles leave a fire trail too.

**Comment by Last0xygen** [comment]
Already part of „hot traffic“
