### ISSUE TITLE
[Feature Suggestion] fake crash shows random effect when frozen

### ISSUE THREAD

**Issue by YEETERSD** [gta-chaos-mod/ChaosModV#2128]
**Is your feature request related to a problem? Please describe.**
 Oftentimes when fake crash happens it's easy to tell it's fake because it occurs when the purple line reaches the end, where with a normal crash you would be able to see the name of the effect that caused it

**Describe the solution you'd like**
When fake crash is picked, display a random effect that isn't a fake effect or a meta effect
**Describe alternatives you've considered**
Minimize GTA 5 so that the player might think it crashed

**Additional context**

**Comment by Last0xygen** [comment]
Already requested several times
