### ISSUE TITLE
[Effect Improvement Suggestion] The Blade Hungers is too forgiving

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#2143]
The time to kill has been increased 2.5x, which seems to be too much time - the effect barely activates twice when you do nothing. Considers balancing it out by not completely resetting the effect on kill (need multiple kills for full reset) or reducig the duration again.

**Comment by OnlyRealNubs** [comment]
This isn't a bug. Please label it with the "Effect Suggestion" label.

**Comment by TheRealAyCe** [comment]
Only contributors can do that.

**Comment by pongo1231** [comment]
Effect isn't part of the mod anymore
