### ISSUE TITLE
Suggestion for Chaos Mod (Oppressor MKII)

### ISSUE THREAD

**Issue by Leon-Playz53** [gta-chaos-mod/ChaosModV#2147]
Hello there (Yes its a Star Wars Meme)
So i had an idea for The Choas Mod How about "Spawn Oppressor MKII" Like the flying Bike in "Exreme Griefer Jesus".

~Leon-Playz53

**Comment by Last0xygen** [comment]
Hello Leon,
this is already a thing as the Oppressor will spawn with the effect "You're A Wizard, Franklin", although invisible and as a broom
