### ISSUE TITLE
[Effect Suggestion] Flying (Press insert key here)

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2148]
**Duration if timed effect (long or short timed?)**
Long 

**Effect Description**
Allows the player to fly. Maybe a centralized Invert Gravity to the player of which the player can actually navigate themselves and descend.

**Comment by TheRealAyCe** [comment]
Similar to this: https://github.com/gta-chaos-mod/ChaosModV/issues/243

**Comment by TerrizX** [comment]
> Similar to this: #243

bro yall should add that effect even. Or even a Noclip type thing. I'll close this issue.

**Comment by TheRealAyCe** [comment]
What gets added completely depends on the people actually writing code. All these posts are just suggestions. They can still implement whatever they want.

**Comment by TerrizX** [comment]
> What gets added completely depends on the people actually writing code. All these posts are just suggestions. They can still implement whatever they want.

ye I know, didnt mean that as a command or anything, just more like a really good idea that should be implemented.
