### ISSUE TITLE
[Effect Suggestion] Tenfold Bullets

### ISSUE THREAD

**Issue by cheesecakeHunter** [gta-chaos-mod/ChaosModV#2149]
**Duration if timed effect (long or short timed?)**
Long timed

**Effect Description**
This already exists in some mod menus: Enables the player to shoot more bullets in more than one direction, like a rifle with shotgun effect.

**Comment by Last0xygen** [comment]
Its called „rapidfire“ and is already an effect

**Comment by cheesecakeHunter** [comment]
Rapidfire means something different, and I'm pretty sure I've never seen my suggested effect in any of the streams...

**Comment by Last0xygen** [comment]
I created the rapid fire effect for chaos mod. It fires 2 additional shots every frame it can fire. This does create a spread for shotguns, rifles, pistoles and so on.
You probably never saw it because, for some reason, no streamer shoots with this effect active, idk why
