### ISSUE TITLE
[Effect Suggestion] GTAGuessr

### ISSUE THREAD

**Issue by Aq1fZA** [gta-chaos-mod/ChaosModV#2150]
**Name of effect**
GTAGuessr

**Effect Description**
Makes the player play a round of GTA V Geo Guesser and gives them a certain amount of time to guess the location and depending on their amount of points they can survive or die.

This idea was created by a youtube channel name
Amar Raza

**Comment by Last0xygen** [comment]
This has nothing to do with chaos mod.
I can’t even imagine how this should work, sorry

**Comment by Aq1fZA** [comment]
Man i literally make a github account just for submit this. But its kinda okay tho
