### ISSUE TITLE
[Effect Suggestion] AMOGUS

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2152]
**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
- Spawns 5 companions with the player. These companions are the weirdest models in the game like the space ranger, alien, clown etc so it's harder to tell expressions. They help the player as normal. However, one of the companions is the impostor. When not looking at the companions, the impostor will kill one of the companions following behind the player, each of the 5 companions are killed by the impostor corresponding with every fifth of the how long the long-time duration is so the impostor does kill most of them (maybe just have the sound of a ingame gunshot play and the companion die behind them, doesnt have to actually happen). 

- To make it harder for the player to guess who it is, all the companions have the same weapons and they are always holding their guns. If the companion is killed then like how Simeon says is you'll be alerted that one of your companions died. 

 - The player has to vote off the impostor companion by aiming their gun at who he thinks is the impostor. If he does this with someone who isnt an impostor, the person voted is flung extremely far like a canonball (to reflect being ejected from the ship) and the player is told they're wrong (like Simeon says). 

- If impostor is guessed correctly, like the Simeon says banner thing itll say you're right and the impostor will be flung very far also (like a canonball) and the effect will end.
  
 - If the player doesn't guess the impostor and the effect is close to ending with some companions left, the impostor shoots the player with a rocket launcher lol to which the effect should end shortly after and all companions are despawned.

The player can never be killed by the impostor unless left alone with the impostor.

**Comment by Last0xygen** [comment]
Thanks for taking the time to write this out.
But sadly this won’t be a good effect. About 99.99% of the time the player is playing a mission or getting to a mission. So the player will either ignore them or kill them

**Comment by TerrizX** [comment]
> Thanks for taking the time to write this out.
> But sadly this won’t be a good effect. About 99.99% of the time the player is playing a mission or getting to a mission. So the player will either ignore them or kill them

Yeah I realised overtime that this wouldn't work. Just wanted to find a way to make an Among Us type effect, sadly dont think it's possible.
