### ISSUE TITLE
[Effect Suggestion] That funny gun with screen mounted on it

### ISSUE THREAD

**Issue by M0ntherload** [gta-chaos-mod/ChaosModV#2153]
**Name of effect**
Utility Firearm, That gun with the mounted screen

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Give player a revolver that does not do damage but instead copies the shot object\ped

**Comment by ReVxNova** [comment]
I think you are referring to the Tool Gun from GMod.

**Comment by TheRealAyCe** [comment]
Duplicate? https://github.com/gta-chaos-mod/ChaosModV/issues/506

**Comment by Last0xygen** [comment]
Duplicate

**Comment by M0ntherload** [comment]
> I think you are referring to the Tool Gun from GMod.

shhh copyright
