### ISSUE TITLE
[Effect Suggestion] Here We Go Again

### ISSUE THREAD

**Issue by ReVxNova** [gta-chaos-mod/ChaosModV#2156]
**Name of effect**
Here We Go Again

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
The effect will put the player character (preferably Franklin) on a bicycle and give him a blue jeans and a white tank top
(and if possible teleport him into an alleyway near grovestreet)

Credit for the idea goes out to u/theYorkist01

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/715
