### ISSUE TITLE
[Effect Suggestion] Left 4 Dead

### ISSUE THREAD

**Issue by ChimiDios** [gta-chaos-mod/ChaosModV#2158]
**Name of effect**
Left 4 Dead/ Left for Dead

**Duration if timed effect (long or short timed?)**
Long, around 90 seconds

**Effect Description**
Spawn a massive horde of zombies around (a block away from the player or so) that will attack the player and also any NPC. Zombies will keep spawning in his surroundings as the player moves. Optional: Spawn 3 companions with shotguns

**Comment by Ruhto** [comment]
there is already an effect that spawns zombies

**Comment by Last0xygen** [comment]
> there is already an effect that spawns zombies

Exactly

**Comment by ChimiDios** [comment]
Yeah I know, but I thought in this by giving it a more normal zombie meaning, in hordes and without exploding, plus attacking NPCs too.

**Comment by ChimiDios** [comment]
> > there is already an effect that spawns zombies
> 
> Exactly

Yeah I know, but I thought in this by giving it a more normal zombie meaning, in hordes and without exploding, plus attacking NPCs too.
