### ISSUE TITLE
[Effect Suggestion] Is there someone behind me?

### ISSUE THREAD

**Issue by LordPhoenix11** [gta-chaos-mod/ChaosModV#2159]
**Name of effect**
Is there someone behind me?
Look back

**Duration if timed effect (long or short timed?)**
20-30s

**Effect Description**
Activates the Look-back-camera

**Comment by TheRealAyCe** [comment]
Duplicate? https://github.com/gta-chaos-mod/ChaosModV/issues/2136

**Comment by LordPhoenix11** [comment]
> Duplicate? #2136

You are right, I am sorry for not seeing this
