### ISSUE TITLE
Suggestion: Add AI blips to spawned entities

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#216]
Only to spawned enemies/companions, not vehicles/whales etc. It isn't hard to implement, just looking for you guys' thoughts before I do.

**Comment by MoneyWasted** [comment]
I'll get this implemented.

**Comment by pongo1231** [comment]
IMO the uncertainty of the spawned enemies' whereabouts adds to the fun. Very unlikely to be implemented.
