### ISSUE TITLE
[Effect Suggestion] WAYPOINT

### ISSUE THREAD

**Issue by LordPhoenix11** [gta-chaos-mod/ChaosModV#2160]
**Name of effect**
WAYPOINT
Set waypoint

**Effect Description**
Puts the waypoint to a random location

**Comment by pipecek** [comment]
did you read this? 

I doubt it, this is a copy of #1368

**Comment by Ruhto** [comment]
kinda useless

**Comment by LordPhoenix11** [comment]
> did you read this? 
> 
> 
> I doubt it, this is a copy of #1368

I read it but didn't find anything, I'm very sorry
