### ISSUE TITLE
[Effect Suggestion] The Purge

### ISSUE THREAD

**Issue by ChimiDios** [gta-chaos-mod/ChaosModV#2166]
**Name of effect**
The Purge

**Duration if timed effect (long or short timed?)**
Long, around 90 seconds.

**Effect Description**
All NPCs become aggresive and start fighting each other, stealing cars, driving at high speed, mass shooting and any type of criminal activity. If the player has a wanted level, it is supressed. No police cars, ambulances or fire fighters exist during this effect, unless they had already spawn.

**Comment by TerrizX** [comment]
Peds Riot is basically this and is already in the mod

**Comment by Last0xygen** [comment]
Yes, Thats peds riot
