### ISSUE TITLE
[Effect Suggestion] Matto

### ISSUE THREAD

**Issue by laczz** [gta-chaos-mod/ChaosModV#2168]
**Matto**
Potential name(s) for the effect

**Effect Description**
It would spawn a model of Matto based on Michael's model, his voicelines would be Matto iconic voicelines such as "There are no cougars in missions!" or "Micheal was never in witness protection" and it would be characterized as an companion for the player.

**Comment by kolyaventuri** [comment]
This mod is not only for DarkViperAU.

**Comment by laczz** [comment]
> This mod is not only for DarkViperAU.

I know, that's why I closed it
