### ISSUE TITLE
[Effect Suggestion] Spawn Companion Davey

### ISSUE THREAD

**Issue by grungemachine** [gta-chaos-mod/ChaosModV#2178]
NAME OF EFFECT:

Spawn Companion Davey

EFFECT DESCRIPTION:

Spawn FIB Agent Dave Norton (Davey). He shall be a friendly NPC that will follow and help the player in combat.

**Comment by durillon** [comment]
daveyyyyyyyyyyyy how you doin

**Comment by Last0xygen** [comment]
Already part of „spawn random companion“, doesn’t need a separate effect
