### ISSUE TITLE
[Effect Suggestion] Yee Yee Ass haircut.  

### ISSUE THREAD

**Issue by PhotoNegativeMickey** [gta-chaos-mod/ChaosModV#2180]
**Name of effect**
Yee Yee Ass Haircut

**Effect Description**
Randomise player haircut and facial hair

**Comment by Last0xygen** [comment]
This is already part of "Randomize Player Clothes"

**Comment by Eventhzd** [comment]
How about he cannot hire a prostitute while this effect is active
