### ISSUE TITLE
choose sound effect for every effect

### ISSUE THREAD

**Issue by bloodyframe2019** [gta-chaos-mod/ChaosModV#2185]
customize random effect sounds. replace the current sound to something else with MP3 or WAV but choose a effect that the sound is gonna play. hard to explain but make it so the sound the effects makes customizable. custom sound effects for effects.

**Comment by bloodyframe2019** [comment]
like a custom sound effect for greifer jesus (our god is an awsome god) like darkviper makes but modify chaos game sounds instead of editing in a video

**Comment by kolyaventuri** [comment]
This already exists in the mod

![image](https://user-images.githubusercontent.com/972446/130369954-b2e5f871-bcb1-4109-ba93-396a271bdbed.png)
