### ISSUE TITLE
[Effect Suggestion] Highway to hell

### ISSUE THREAD

**Issue by Eventhzd** [gta-chaos-mod/ChaosModV#2191]
**Name of effect**
Highway to hell

**Duration if timed effect (long or short timed?)**
20 seconds

**Effect Description**
Everything is now on fire for 20 seconds. When the world ignites, only player and his vehicle are safe.

**Comment by TerrizX** [comment]
Similar to #2133

**Comment by Last0xygen** [comment]
Duplicate #2133
