### ISSUE TITLE
[Effect Suggestion] Replacing peds with Cougars

### ISSUE THREAD

**Issue by AyushRohilla007** [gta-chaos-mod/ChaosModV#2195]
**Name of effect**
All peds are Cougars

**Effect Description**
This effect should replace all the currently spawned peds with Cougars which will attack player

**Comment by turg-the-sad-cat** [comment]
Already been suggested a bunch of times before and it won’t happen because changing ped models will break the game

**Comment by Last0xygen** [comment]
already replaced 102384523 times ;)
