### ISSUE TITLE
[Effect Suggestion] Eye of the Tire

### ISSUE THREAD

**Issue by MichaelMotorcycl** [gta-chaos-mod/ChaosModV#2198]
**Name of effect**
Eye of the Tire

**Duration, if timed effect (long or short-timed?)**
As long as "Now this is some Tire Poppin'".

**Effect Description**
Simply put, this effect would be the same exact effect as "Now this is some Tire Poppin'", except in the rhythm of Eye of the Tiger. Hence the name, the Eye of the Tire

**Comment by Last0xygen** [comment]
wont work + not a real improvement to the existing effect
