### ISSUE TITLE
[Effect Suggestion] No violence

### ISSUE THREAD

**Issue by M0ntherload** [gta-chaos-mod/ChaosModV#2202]
**Name of effect**
Kid friendly, No violence

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Peds can't fight, player can't deal damage

**Comment by turg-the-sad-cat** [comment]
So pacifist with an extra step?

**Comment by Last0xygen** [comment]
already exists as part of "minimal damage" or "pacifist"
