### ISSUE TITLE
[Feature Suggestion] Add Sounds Before"Fake Crash" Effect

### ISSUE THREAD

**Issue by Planita13** [gta-chaos-mod/ChaosModV#2204]
Some streamers can guess when the Fake Crash effect occurs, so I propose to make it extra convincing by making it seem a crazy event caused the game to crash. For example there can be sudden explosion effect a split second before the actual Fake Crash effect occurs, to make it look like an explosion effect crashed the game.

**Comment by kolyaventuri** [comment]
Already suggested. ex: #1969.
