### ISSUE TITLE
[Effect Suggestion] GTA Online Phone's

### ISSUE THREAD

**Issue by Lavished** [gta-chaos-mod/ChaosModV#2224]
**Other Name's of the effect**
Online Phone's
Bad Credit
Online Marketing
**Duration if timed effect (long or short timed?)**
Long (90 Seconds)

**Effect Description**
You'll get an email, phone call, or text in between 5-10 seconds
The texts, emails, and phone calls will be the annoying ones you get if you start gta online from the start

Hey it's Pa-

**Comment by Last0xygen** [comment]
already requested several times
