### ISSUE TITLE
[Effect Suggestion] No Texture's

### ISSUE THREAD

**Issue by Lavished** [gta-chaos-mod/ChaosModV#2226]
**Name(s) of effect**
Missing Texture's
No Texture's

**Duration if timed effect (long or short timed?)**
2 minutes

**Effect Description**
 removes textures from the game

**Comment by Last0xygen** [comment]
So „where’s everything gone“ but not that much?

**Comment by Lavished** [comment]
> So „where’s everything gone“ but not that much?

yeah, sort of

**Comment by pongo1231** [comment]
In the mod now
