### ISSUE TITLE
[Effect Suggestion] Peyote Plant

### ISSUE THREAD

**Issue by literallyrice** [gta-chaos-mod/ChaosModV#2230]
**Name of effect**
Peyote Plant, Animal Transformation, Animal

**Duration if timed effect (long or short timed?)**
Relatively short, maybe 20-25 seconds long

**Effect Description**
Utilizes the peyote plants to turn player into one of the randomized animals. If in helicopter turn into bird, if in car turn into dog or cow or something. You get the idea.

**Comment by Last0xygen** [comment]
Already requested several times
