### ISSUE TITLE
[Effect Suggestion] World War III

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2239]
**Duration if timed effect (long or short timed?)**
Long 

**Effect Description**
LS becomes a warzone. Military spawn in shooting other military. Jets spawn in shooting rockets randomly. Tanks spawn in shooting at the enemies too. Streets are filled with barracks and military jeeps. LS essentially looks like a warzone.

**Comment by Last0xygen** [comment]
Duplicate
