### ISSUE TITLE
[Effect Suggestion] Happy Birthday

### ISSUE THREAD

**Issue by PinballGH** [gta-chaos-mod/ChaosModV#2243]
**Name of effect**
Happy Birthday
Funny Clown
Circus Party

**Duration if timed effect (long or short timed?)**
Short timed, 10-15 seconds

**Effect Description**

Teleports inside a Circus Van, driven around by a clown who loves to honk
Player cannot leave until effect ends (Maybe give him a costume too ? :))

**Comment by Last0xygen** [comment]
Getting the player "stuck" is not a good effect. The ones the mod already has is currently enough :)
