### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by OHMiku** [gta-chaos-mod/ChaosModV#2249]
**Name of effect**
Ped controls Player

**Duration if timed effect (long or short timed?)**
Short (one purple line)

**Description of effect**
Remove player controll and replace it with a standard ped ai. For example running from gunshots

**Comment by Last0xygen** [comment]
„Autopilot“ is already an effect

**Comment by OHMiku** [comment]
> „Autopilot“ is already an effect

Ah sorry
