### ISSUE TITLE
[Effect Suggestion] Millions To One

### ISSUE THREAD

**Issue by Gunmoon80** [gta-chaos-mod/ChaosModV#2250]
**Name of effect**
Potential name(s) for the effect
Millions To One
Spawn Cougar

**Effect Description**
Description of the effect; what should it do?
Spawn a hostile cougar targeting the player, and the effect shouldn't show in the list of current effects until the player dies or the cougar is killed.

**Comment by Last0xygen** [comment]
Ja already been requested thousand of times, please use the search
