### ISSUE TITLE
[Effect Suggestion] Realistic Fake Crash

### ISSUE THREAD

**Issue by D1vid3dS0ul** [gta-chaos-mod/ChaosModV#2251]
**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by pipecek** [comment]
STICK.TO.THE.FORMAT

**Comment by Last0xygen** [comment]
No description -> close

**Comment by SeanMirrsen** [comment]
> 
> 
> STICK.TO.THE.FORMAT

What?

> STICK TO THE **FUCKING** FORMAT!
