### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kardiolohtipos07** [gta-chaos-mod/ChaosModV#2252]
I play on the epic games version and i have noticed that when a vehicle touches me without any force i immediatly die even if i have the invicible cheat of menyoo's mod menu.Could you please help**

**To Reproduce**
Steps to reproduce the behavior

**Crash Dump (if a game crash)**
Attach the latest .dmp file (names are Year-Month-Day-Hour-Minute.dmp) located in chaosmod/crashes/, ignore if bug doesn't cause a game crash

**Comment by OnlyRealNubs** [comment]
This doesn't seem to be an issue caused by the mod according to the description you provided. If you can provide a more clear description. I could maybe help you.

**Comment by MoneyWasted** [comment]
This is an issue with another mod, not the Chaosmod.
