### ISSUE TITLE
[Effect Suggestion]  Facts and Glitches/Out of Bounds

### ISSUE THREAD

**Issue by Conemanepico** [gta-chaos-mod/ChaosModV#2255]
Facts and Glitches/Out of Bounds

Short effect, teleport

The effect will Teleport you to either a location that DarkViperAU has covered in his Facts and glitches series or to an out of bounds location (chosen at random)

**Comment by JeunessesValeurs** [comment]
Nearest OOB would be better imo + It'll take a lot of time to add all the locations. But I like the idea anyway :)

**Comment by JustTunerYT** [comment]
This mod is not only for content creator. Players may not be aware of those places as they never watched DarkViperAU

**Comment by Last0xygen** [comment]
Nice find @JustTunerYT, this must have slipped through.
