### ISSUE TITLE
[Effect Suggestion] Family Therapy

### ISSUE THREAD

**Issue by Aethelkoet** [gta-chaos-mod/ChaosModV#2256]
Name:

**Family Therapy**

Description: 

This effect spawns Jealous Jimmy, Tantrum Tracy, & Amoral Amanda (im not good with names) and spawns them with a mid tier but not overly overpowered weapon. - They will attack on sight.

This could be expanded to spawn characters based on the character being played, or just keep it with the main three.

**Comment by RosyMiranto18** [comment]
Let's see... How about this. Jimmy had the Carbine Rifle. Tracy had the Broken Bottle and Molotov, and Amanda have a Stun Gun. It's not OP individualy, but it may be deadly combined.

**Comment by kolyaventuri** [comment]
This has the potential to, more often than not, kill the player immediately and impede progress. Not the kind of effects we're looking for.
