### ISSUE TITLE
[Effect Suggestion] Spawn Mugger

### ISSUE THREAD

**Issue by rollschuh2282** [gta-chaos-mod/ChaosModV#2261]
**Name of effect**
Spawn Mugger

**Effect Description**
spawn a NPC similiar to the mugger in GTAO which throws you to the ground and runs away.
but for the effect let the mugger take away all the weapons, and money.
and you have to chase the mugger down on foot and kill him to get your weapons and money back.
and to not make him be on the map and findable forever, just let him despawn after like 100 meters.
that way if the player doesn´t kill him and he escapes, the weapons and money will stay gone.

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues?q=mugger
