### ISSUE TITLE
[My Super Cool Effect Idea

### ISSUE THREAD

**Issue by BigMan6901** [gta-chaos-mod/ChaosModV#2263]
**Name of effect** Alt Strat
Potential name(s) for the effect
not sure 
**Duration if timed effect (long or short timed?)** 30 seconds
If not a timed effect, remove this section

**Effect Description** when chosen it is forced to hold down the alt key to have the character swap showing and making things extremely slow
Description of the effect; what should it do? when chosen it is forced to hold down the alt key to have the character swap showing and making things extremely slow

**Comment by Last0xygen** [comment]
Duplicate
