### ISSUE TITLE
[Effect Suggestion] combine console experience and lag

### ISSUE THREAD

**Issue by YEETERSD** [gta-chaos-mod/ChaosModV#2268]
Currently console experience and lag are two separate effects, even though they are both simulating lag,
Combining the effects of
A)reverting the game to a previous state
B)lowering the frame rate
C)simulating input lag
Into one effect would help with consistencies in effects,
Currently what we have now is two different ways of simulating lag.

**Comment by Last0xygen** [comment]
„Console experience“ and „lag“ are different effects with different behaviors.
„Input lag“ has already been requested several times but still would be a separate effect then.
I don’t see a reason why we should combine them
