### ISSUE TITLE
[Effect Suggestion] Swap Player Model

### ISSUE THREAD

**Issue by KarimFauzy** [gta-chaos-mod/ChaosModV#2292]
For example If you are playing Michael You get swapped to Instead player with Lester Or devin weston , it could be randomized to any model in the game (but you have to be careful of the fully Naked Model thats in the Game) 
i believe it would be best as a Non Time limited Effect Only or something it would make it really cool , unless it softlocks the game

**Comment by TheRealAyCe** [comment]
Changing the player model is not possible
