### ISSUE TITLE
[Griefer jesus can walk on water and can regenerate health] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by chamoflag** [gta-chaos-mod/ChaosModV#2293]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
This has already been requested
