### ISSUE TITLE
[Effect Suggestion] The Last Supper 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2296]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Jesus and 12 random male peds in different eating animations near the player. With Jesus drinking wine also.

**Comment by Last0xygen** [comment]
Already requested

**Comment by TerrizX** [comment]
I checked tho, someone requested this and it was closed? They wanted Jesus spawned in with 12 bodyguards or something? Someone requested what I have exactly?

**Comment by Last0xygen** [comment]
I.e. https://github.com/gta-chaos-mod/ChaosModV/issues/561
adding animations still doesn’t make this request unique and and a Good Addition imho, sorry
