### ISSUE TITLE
[Effect Suggestion] Junkies

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2299]
**Duration**
 Long

**Effect Description**
Makes player model invisible and fills the player with small-medium size props which stick onto them. The player's shape should be able to be seen or at least for the most part. Same for if the player is with story characters.

**Comment by kolyaventuri** [comment]
Spawning this many objects and tracking them onto player movement has the potential to cause a lot of performance issues, unfortunately.
