### ISSUE TITLE
[Feature Suggestion] Add Tumble Down Mount Chiliad (Name: Fall From Mount Chiliad)

### ISSUE THREAD

**Issue by MostlyOwen** [gta-chaos-mod/ChaosModV#2306]
I would like this feature to happen like this:
The player gets teleported right off the nearest edge of mount chiliad and ragdoll is on.
I hope you think this also sounds cool.

- Owen
- Discord Owen Darling#7967

**Comment by Last0xygen** [comment]
this is not a "Feature" but an "effect".
There already is a tp to mount chiliad effect though ;P
