### ISSUE TITLE
[Effect Improvement] No Phone

### ISSUE THREAD

**Issue by rollschuh2282** [gta-chaos-mod/ChaosModV#2312]
in 2015-2016 R* had implemented a anti piracy meassure which prevented you from recieving calls while still being able to use the phone.
it even showed a unique text message.
[screenshot of message](https://cdn.discordapp.com/attachments/424790839793942549/886139042058625084/mhiALX.png)

so maybe this is something that can be a change that can be done for the existing no phone effect.
Can be enabled from a script by doing this:
```ruby
DECOR_SET_BOOL(PLAYER_PED_ID(), "Synched", false); // true/false doesn't matter
```
and disabled:
```ruby
DECOR_REMOVE(PLAYER_PED_ID(), "Synched");
```

**Comment by TheRealAyCe** [comment]
Out of interest, where did you get this from?

**Comment by rollschuh2282** [comment]
someone that messes around with the game code a lot found it yesterday, and told me about it.
that meassure was removed in 2015-2016 from the DRM code so it doesn´t call that code anymore.
but the feature still exists

**Comment by TheRealAyCe** [comment]
neat

**Comment by Last0xygen** [comment]
No phone is already an effect :)

**Comment by rollschuh2282** [comment]
> No phone is already an effect :)

yeah i know.
i just meant maybe this can be done as a improvement for the existing effect.
no priority, just thought i share it
