### ISSUE TITLE
[Effect Suggestion] VERY long loading screen

### ISSUE THREAD

**Issue by TMCAtom** [gta-chaos-mod/ChaosModV#2315]
VERY long loading screen

- [x] Long
- [ ] Short
- [ ] No duration

Once you fail a mission/die while the effect is active, the game takes longer to load.

**Comment by kolyaventuri** [comment]
Effects that just completely prevent the player from doing anything aren't what we're looking for. They tend to not be very fun.

**Comment by TMCAtom** [comment]
ill think of something more "interesting"

**Comment by RosyMiranto18** [comment]
i have an alternative idea. Rename the effect into "Fake Reload Save" by showing just one picture of the Loading Screen when you boot up the game, and then after that we back to the game. Sure, the lack of actual Reload Save Effect may make it too obvious after the first hit, but it can be pretty funny.
