### ISSUE TITLE
[Effect Suggestion] Bounty On Yo Head

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2318]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [] No duration

**Effect Description**
Gangs all over LS actively seek out the player in droves and try kill him (driving all the way from where they are to where the player is etc).

**Comment by Last0xygen** [comment]
Too similar to „peds attack player“ or „spawn balls squad“
