### ISSUE TITLE
[Effect Suggestion] Spawn Prostitute

### ISSUE THREAD

**Issue by oaxxe** [gta-chaos-mod/ChaosModV#2334]
**Name of effect**
Spawn Prostitute

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a Prostitute next to you

**Comment by Last0xygen** [comment]
Can already happen with „spawn random enemy/companion“, not unique enough to be a separate effect
