### ISSUE TITLE
Ultimate god

### ISSUE THREAD

**Issue by shahar654** [gta-chaos-mod/ChaosModV#2336]
-->

**Name of effect**
The ultimate god

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X] No duration

**Effect Description**
Spawns griefer jesus, extreme griefer jesus and jesus takes the wheel

**Comment by Last0xygen** [comment]
has already been requested several times, still not a good effect, sorry
