### ISSUE TITLE
[Effect Suggestion] Spawn KDJ

### ISSUE THREAD

**Issue by imadethisforchaosmodsuggestion** [gta-chaos-mod/ChaosModV#2337]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
-  x No duration

**Effect Description**
This effect would spawn KDJ/Moodymann and his annoying ass “mothafuckas”

**Comment by Last0xygen** [comment]
Can already happen with „spawn random enemy“, not unique enough to be a separate effect
