### ISSUE TITLE
[Effect Suggestion] Fake crash 2.0

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2338]
**Name of effect**
Fake crash 2.0

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x ] Short
- [ ] No duration

**Effect Description**
This is an upgrade to the fake crash effect in ,instead of the fake crash only having the game freeze for a couple of moments,the effect will also display darkviperau’s desktop background

**Comment by Last0xygen** [comment]
No… this not a mod for a single streamer…

**Comment by Hazemkaid** [comment]
Oh ok
