### ISSUE TITLE
[Effect Suggestion]Expanded and enhanced 

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2339]
**Name of effect**
Expanded and enhanced 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description”
Makes license plates for every vehicle yellow

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2335 ….

**Comment by Hazemkaid** [comment]
What do you mean duplicate

**Comment by Hazemkaid** [comment]
Oh

**Comment by Last0xygen** [comment]
That this issue has already been requested

**Comment by Hazemkaid** [comment]
Didn’t know someone had the same idea

**Comment by Hazemkaid** [comment]
Sorry
