### ISSUE TITLE
[Effect Suggestion] Fake invert gravity 

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2340]
**Name of effect**
Fake invert gravity

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ x] Short
- [ ] No duration

**Effect Description**
You will be be pulled to the sky like normal invert gravity for 6 seconds and then teleported back to the ground

**Comment by Last0xygen** [comment]
Mission fails woll already have happened at this point. And teleporting ALL peds/objects/vehicles back is a really extensive task
