### ISSUE TITLE
[Effect Suggestion] Mad Michael

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2341]
**Name of effect**
Mad Michael 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x ] No duration

**Effect Description**
Micheal spawns with a golf club and beats the player with it

**Comment by Last0xygen** [comment]
Can already happen with „spawn random enemy“, not unique enough to be a separate effect
