### ISSUE TITLE
[Effect Suggestion] Daveeeey!

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2342]
**Name of effect**
Daveeey

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x ] No duration

**Effect Description**
Dave spawns with lots of health and starts beating the crap out of of the player

**Comment by Last0xygen** [comment]
Can already happen with „spawn random enemy“, not unique enough to be a separate effect

**Comment by Hazemkaid** [comment]
Is this Better
