### ISSUE TITLE
[Effect Suggestion] You're A Virus!

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2344]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
If the player touches any ped, that ped T-Poses or becomes low render versions of themselves, same for props and cars.

**Comment by Last0xygen** [comment]
Is already a thing in „low render distance“, I don’t think this need so be „easier“ 😅

**Comment by TerrizX** [comment]
Lol I was thinking you would say this. Yeah fair enough 

> Is already a thing in „low render distance“, I don’t think this need so be „easier“ 😅

Yeah I was thinking you'd say this. Fair enough just an idea I had. Was thinking of a zombie effect with this instead but you cant change peds so
