### ISSUE TITLE
[Effect Suggestion] Gives Everyone Assault Shotguns

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2352]
**Name of effect**
Gives Everyone Assault Shotgun

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The favorite weapon for the close ranges, one of the most powerful non-heavy weapons in the game. Prepare to avoid being shredded in seconds though, but at least they can't touch you since they can't drive-by with it.

**Comment by Last0xygen** [comment]
„Give every ped a random weapon“ is already an effect. Shotguns would be too overkill imho
