### ISSUE TITLE
[Effect Suggestion] It's not a lake. It's an ocean

### ISSUE THREAD

**Issue by NotGamingShark** [gta-chaos-mod/ChaosModV#2355]
**Name of effect**
It's not a lake. It's an ocean

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The effect teleports player to the very end of the map, where it takes you a significant amount of time to go back to land

**Comment by Last0xygen** [comment]
Already suggested several times
