### ISSUE TITLE
[META Effect Suggestion] Rigged (Meta)

### ISSUE THREAD

**Issue by PapaAquchala** [gta-chaos-mod/ChaosModV#2357]
Duration (choose one and replace the corresponding "[ ]" with "[X]")
- [x] Long
- [ ] Short
- [ ] No Duration

Effect Description:
Meta effect (like 5x timer speed, 0.5x effect duration, etc.)
For the next 5 votes, have the mod pick between the second least voted effect
Ex. You have Pacifist 13%, Blade Hungers 29%, Blimp Strats 15%, and Random Effect 43%. The mod will pick Blimp Strats due to it holding the second lowest number of votes, 15%

**Comment by Last0xygen** [comment]
So… it would be just „normal proportional voting“ behavior? 😅
