### ISSUE TITLE
[Effect Suggestion] Return To Monkey

### ISSUE THREAD

**Issue by RezzScape** [gta-chaos-mod/ChaosModV#2362]
**Name of effect**
Potential name(s) for the effect
Grand Theft Monkey
Monkey Simulator

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X] No duration

**Effect Description**
Description of the effect; what should it do?
Replaces the Player Model with a Monkey Model.

**Comment by Last0xygen** [comment]
Already been requested several times
