### ISSUE TITLE
[Effect Suggestion] Niko it's roman

### ISSUE THREAD

**Issue by JustCosmic** [gta-chaos-mod/ChaosModV#2366]
Niko it's roman

let's go bowling

- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**

Opens a mini-game like the hacking mini-game where the person has to bowl (and maybe you can be against roman so if you lose you blow up if you win you get to resume gameplay)

**Comment by turg-the-sad-cat** [comment]
There’s no bowling in gta 5, with realistic hacking that’s in the game but bowling, hope

**Comment by Last0xygen** [comment]
There is no bowling minigame in gta 5
