### ISSUE TITLE
[Feature Suggestion] My Neat Feature

### ISSUE THREAD

**Issue by 6doesgames** [gta-chaos-mod/ChaosModV#2368]
Feature: You get a janitor that mops then it pulls out a gun and just slowly kills you, 1 shot per second and he gets half of normal HP.
Feature 2: You go to a random mission cut scene, Lets say you're doing the raid on the FIB, And then you get teleported to the cut scene of when lamar goes, You aint gonna get no bitches on yo dick with that yee yee ass hair cut, no no word'aaaa.
Feature 3: Fake death effect. Make a mountin lion come out of no where and it will eat you alive then you get revived and the Mtlion goes away.
Feature 4: You should add a one that sticks a random object to you're body for until the next effect comes.

**Comment by TheRealAyCe** [comment]
Those are effect suggestions not features. All are either bad or duplicates.

**Comment by Last0xygen** [comment]
Either duplicate or not a suitable effect

**Comment by 6doesgames** [comment]
Im butt ass naked and spanking my dick rn

**Comment by 6doesgames** [comment]
That nigga Noah Moonsong is a bitch for reacting with the sob emoji to my comment, ill come over there and spank you like a bad bad boy you are fuck ass nigga.

**Comment by 6doesgames** [comment]
Good boy..

**Comment by 6doesgames** [comment]
who wanna makeout with me im spicy asl

**Comment by 6doesgames** [comment]
gta-chaoss-mod is a fatass nigga update ur mod once in a while you cunt

**Comment by 6doesgames** [comment]
quit deleting my comment ill squirt on u

**Comment by 6doesgames** [comment]
noah can you queef in my mouth and let me inhale it
asking for a friend

**Comment by 6doesgames** [comment]
:smallkappa:
nigger

**Comment by 6doesgames** [comment]
last oxygen is a fatass he needs a diet too

**Comment by 6doesgames** [comment]
yo noah moonsong i heard u got ptsd

BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB

**Comment by 6doesgames** [comment]
quit deleting my discord messages you fatass retard get a diet instead and diet mountain dew doesnt count as a diet nigga

**Comment by 6doesgames** [comment]
![image](https://github.com/user-attachments/assets/a0bcc8e4-d477-4e31-a2fb-a5f37aaec52c)

**Comment by 6doesgames** [comment]
call me daddy before you delete my discord message

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
dont say hi to me bitch nigga say hi to my dick
<@476507259783086101>

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
<@476507259783086101>

**Comment by 6doesgames** [comment]
yo noah moonsong i heard u got ptsd

BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB

**Comment by 6doesgames** [comment]
yo noah moonsong i heard u got ptsd

BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB

**Comment by 6doesgames** [comment]
yo noah moonsong i heard u got ptsd

BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB

**Comment by 6doesgames** [comment]
yo noah moonsong i heard u got ptsd

BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB BOMB

**Comment by 6doesgames** [comment]
whoever is deleting my messages in git activity i will find u and doxx ur ass i am a pro backer i code in .batch i am a skid nigga
