### ISSUE TITLE
[Effect Suggestion] Force Special Ability

### ISSUE THREAD

**Issue by MostlyOwen** [gta-chaos-mod/ChaosModV#2373]
Forcing the special ability for player (Include T,M,F)

**Duration**
- [ ] Long
- [ X] Short
- [ ] No duration

**Effect Description**
Effect should make your special ability run until there's no more.
(I know this is close to no special ability)

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/927

**Comment by Last0xygen** [comment]
Duplicate
