### ISSUE TITLE
[Effect Suggestion] WW3

### ISSUE THREAD

**Issue by Gabrielzin0** [gta-chaos-mod/ChaosModV#2374]
**Name of effect**
WW3

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Use the same coding of mercenaries but are 4 military guys on foot and jesus in a tank, they are hostile to everyone one but them

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.) or effects that contain "Jesus".
