### ISSUE TITLE
[Effect Suggestion] Become Jesus

### ISSUE THREAD

**Issue by JustCat141** [gta-chaos-mod/ChaosModV#2376]
**Name of effect**
(Griefer) Jesus takes the control / Turn into (Griefer) Jesus | (idk im not creative)

**Duration**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
With this effect, you'd become the well-known (Griefer) Jesus. You would get his abilities, like:
- Have a railgun with infinite ammo (player would only have this gun)
- Explosions wouldn't damage you
- No wanted level
- ? Get an Oppressor MK II if player is on foot
- Player model would change to Jesuses

(Maybe this effect could be similar to Blade Hungers, but you'd have to explode vehicles (or you'd be just stronger than regular))

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
Also changing the players model breaks a lot of things.
