### ISSUE TITLE
[Effect Suggestion] Teleport to Mineshaft

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2378]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports the player inside the abandoned mine shaft.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/425
