### ISSUE TITLE
[Effect Suggestion] Fake Mission Passed

### ISSUE THREAD

**Issue by BenHilling** [gta-chaos-mod/ChaosModV#2381]
Name of effect
Fake Mission Passed

Duration 
- [ ] Long
- [ ] Short
- [X] No duration

Effect Description
It should pop up with the mission passed screen so it would make the player think the mission was completed

**Comment by TheRealAyCe** [comment]
You already suggested that https://github.com/gta-chaos-mod/ChaosModV/issues/2372 ?

**Comment by Last0xygen** [comment]
Duplicate #2372

**Comment by BenHilling** [comment]
Sorry I re suggested it because I didn't format it properly
