### ISSUE TITLE
[Effect Suggestion] Jesus ACTUALLY takes the wheel

### ISSUE THREAD

**Issue by Dico1337** [gta-chaos-mod/ChaosModV#2382]
**Jesus ACTUALLY takes the wheel**

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Jesus spawns in passenger seat of current vehicle, and then bails out (possibly with a steering wheel in hand) - Disabling left/right movement

Or alternatively

**Jesus ACTUALLY takes the wheels**
Jesus spawns in passenger seat of current vehicle, and then bails out (removing wheels from vehicle) - Disabling left/right movement

**Comment by Kaboom62** [comment]
or removing the ability to drive at all.

**Comment by TheRealAyCe** [comment]
Sort of a duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/107

**Comment by Last0xygen** [comment]
Duplicate #107
