### ISSUE TITLE
[Effect Suggestion] Load a Save

### ISSUE THREAD

**Issue by Kaboom62** [gta-chaos-mod/ChaosModV#2384]
**Name of effect**
Load a Save

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Load a random save while playing the game.

**Comment by TheRealAyCe** [comment]
That's just evil.

**Comment by Last0xygen** [comment]
Already requested
