### ISSUE TITLE
[Effect Suggestion] Drive-Thru

### ISSUE THREAD

**Issue by Kaboom62** [gta-chaos-mod/ChaosModV#2389]
**Name of effect**
Potential name(s) for the effect
Drive-Thru
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Recreate the famous drive-thru scene where Big Smoke order's his large meal from GTA San Andreas turning it into an unskipable cutscene with the original audio and cutscene animations(if possible) and at the end of the cutscene there will be some ballas in a car but instead chasing them in the original they chase you and shoots at you instead. The cutscene should start when the fast food worker said "Can I take your order please" until when Sweet said "Drive-by!"

**Comment by Last0xygen** [comment]
Blocking the player to mimic a cutscene is not a good effect
