### ISSUE TITLE
[Effect Suggestion] Jumpscare

### ISSUE THREAD

**Issue by MarkowitzThe2nd** [gta-chaos-mod/ChaosModV#2390]
**Name of effect**
- Jumpscare

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- No duration/short duration (this can be randomized at times)

**Effect Description**
The 'Jumpscare' Effect simply scares the player, therefore catching them off-guard as they wait for the purple line to reach its end. Of course, the scares can be randomized, so that there is variety. The only rule of this is that they must be GTA-related.

**Comment by Last0xygen** [comment]
Duplicate
