### ISSUE TITLE
[Effect Suggestion] Movie Scene 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2391]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Camera cuts to different more cinematic angles viewing the player at times, like an automatic Cinematic Camera albeit with different actual cinematic views. Sometimes the camera may do an extreme close up, or be tilted or an over the shoulder shot etc.

**Comment by Last0xygen** [comment]
I don’t think we need another „cinematic camera“ effect
