### ISSUE TITLE
[Effect Suggestion] Davey!

### ISSUE THREAD

**Issue by TMCAtom** [gta-chaos-mod/ChaosModV#2392]
-->

Name:
Davey!

Duration
- [ ] Long
- [ ] Short
- [x] No duration

Spawns a hostile Dave with his North Yankton outfit and a sniper rifle

**Comment by TheRealAyCe** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1624 https://github.com/gta-chaos-mod/ChaosModV/issues/1492

**Comment by Last0xygen** [comment]
Yes, duplicate
