### ISSUE TITLE
[Effect Suggestion] set time to mourning

### ISSUE THREAD

**Issue by Shapito03** [gta-chaos-mod/ChaosModV#2395]
**Name of effect**
Set time to mourning

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Set weather to rain, and change all vehicles to hearses. Possibly change character outfit to a suit?

**Comment by Last0xygen** [comment]
„set weather to rain“, „ls noire“ and „ Where's The Funeral?“ are already effects

**Comment by TheRealAyCe** [comment]
But I do like the pun.
