### ISSUE TITLE
[Effect Suggestion] Online AI

### ISSUE THREAD

**Issue by ScompFol** [gta-chaos-mod/ChaosModV#2396]
**Name of effect**
Online AI

**Duration**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
As the name says, This will make cars ram into you while driving just like how it does in GTA Online.

**Comment by kolyaventuri** [comment]
This was previous an effect, and is now `Traffic Magnet` which is effectively the same idea

The name change happened here -> https://github.com/gta-chaos-mod/ChaosModV/commit/8a417721f3032fc9d5a4367feb324855a0e7e2e6#diff-20a505663650f8d670428c5cc69320da3c7967fd0c837599efbfc5d037e049efL398
