### ISSUE TITLE
[Effect Suggestion] World is on Fire

### ISSUE THREAD

**Issue by rollschuh2282** [gta-chaos-mod/ChaosModV#2397]
**Name of effect**
World is on Fire

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
makes the screen red like from the blade hungers effect and puts the player into the firefighter outfit.
it would work bc even Trevor has one in the files even though he never appears in the bureau raid.
maybe setting some peds randomly on fire could be a extra part of the effect

**Comment by Last0xygen** [comment]
Setting peds on Fire is already an effect
