### ISSUE TITLE
[Effect Suggestion] 8-bit//Retro (Vision

### ISSUE THREAD

**Issue by VDKA-Deado** [gta-chaos-mod/ChaosModV#2399]
**Potential names of effect**
8-Bit, Retro, Retro Vision, etc

**Duration**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Essentially applies a filter to the game (similar to the visual effect of Virtual Reality, LSD, Deep Fried, etc.) Which makes everything all pixilated, similar to that of an 8-bit/Retro game. Also applies a similar 8-bit/Retro style to the audio (if it's possible to bit-crush audio real-time).

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1016
