### ISSUE TITLE
[Effect Suggestion] Who the f*ck is Gustavo

### ISSUE THREAD

**Issue by DillyBar01** [gta-chaos-mod/ChaosModV#2401]
**Name of effect**
Who The F*ck is Gustavo?!

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn Gustavo Mota as an ally, who will attack all NPCs for 30 seconds, then die showing a fake "Mission failed" screen with the text "Gustavo Mota died" or something more creative lol

**Comment by Last0xygen** [comment]
Duplicate
