### ISSUE TITLE
[Effect Suggestion] It Follows

### ISSUE THREAD

**Issue by MarkowitzThe2nd** [gta-chaos-mod/ChaosModV#2402]
**Name of effect**
- It Follows

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- Long

**Effect Description**
Once the effect is spawned, a supernatural entity incessantly pursues the player at a walking pace. If it touches the player, the player dies immediately. There is also no way to kill it. The entity could be of an assortment of GTA characters.

**Comment by kolyaventuri** [comment]
While this sounds neat, we're not looking for an effect that is basically just suicide. Yes you could outpace it, but not having a way to kill it and you die immediately just sounds like the suicide effect with extra steps.

**Comment by MarkowitzThe2nd** [comment]
How do you suggest we improve it then? Maybe the entity is killable?
