### ISSUE TITLE
[Effect Suggestion] You have aimbot

### ISSUE THREAD

**Issue by MatthewMcEwen** [gta-chaos-mod/ChaosModV#2403]
**Name of effect**
You have aimbot

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Causes you to aim at enemies automatically, instantly and perfectly accurately

**Comment by TheRealAyCe** [comment]
Already exists

**Comment by kolyaventuri** [comment]
Already exists in the mod
