### ISSUE TITLE
[Effect Suggestion] Peds Drive By Player

### ISSUE THREAD

**Issue by RADIS370** [gta-chaos-mod/ChaosModV#2405]
Peds Drive By Player

- [60 Seconds] Long
- [X ] Short
- [X ] No duration

Peds drive by the players car movement (For example if the player drives foward all nearby peds in the car drive foward too)

**Comment by TheRealAyCe** [comment]
Already in the mod, wtf?

**Comment by RADIS370** [comment]
Read the example. Its not in the mod yet
