### ISSUE TITLE
[Effect Suggestion] Randomize Keybinds

### ISSUE THREAD

**Issue by JuliusFalck1** [gta-chaos-mod/ChaosModV#2409]
**Name of effect**
Potential name(s) for the effect
Randomize Keybinds

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
Randomize all keybinds, when effect is done, controls reset back to which they were before.

**Comment by Last0xygen** [comment]
Already requested several times
