### ISSUE TITLE
[Effect Suggestion] spawn companion chad

### ISSUE THREAD

**Issue by TanMan2601** [gta-chaos-mod/ChaosModV#2412]
**Name of effect**
Potential name(s) for the effect
spawn companion chad
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by TanMan2601** [comment]
so like you spawn companion brad you can spawn a companion chad that has a body builder model.

**Comment by TheRealAyCe** [comment]
Not Chad Mulligan?
