### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by TanMan2601** [gta-chaos-mod/ChaosModV#2413]
**Name of effect**
Potential name(s) for the effect
spawn companion chad
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by TanMan2601** [comment]
like when you spawn companion brad you can spawn companion chad that is a body buider model

**Comment by Last0xygen** [comment]
Already part of „spawn random companion“, no need for a specific spawn effect for this
