### ISSUE TITLE
[Effect Suggestion] (meta) 2x effect power 

### ISSUE THREAD

**Issue by Fireslinger35** [gta-chaos-mod/ChaosModV#2417]
**2x effect power**
Potential name(s) for the effect
2x effect strength

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
the effect with durations get the effect empowered so earthquake would be aggressive or pasifcts being that you can't hold any weapon

**Comment by Last0xygen** [comment]
This would require every effect to be update, every future effect to be considered wirkt his in mind and some effects getting weakened because it would crash otherwise

**Comment by SeanMirrsen** [comment]
> 
> 
> This would require every effect to be update, every future effect to be considered wirkt his in mind and some effects getting weakened because it would crash otherwise

All that said, there *is* already a PR for it. :P #2257

**Comment by Last0xygen** [comment]
Yes, which also points out my points 
https://github.com/gta-chaos-mod/ChaosModV/pull/2257#issuecomment-912117214
