### ISSUE TITLE
Millions To One!!! 

### ISSUE THREAD

**Issue by GalaxyGaming629** [gta-chaos-mod/ChaosModV#2419]
**Name of effect**
Millions To One!!!
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It spawns a cougar and makes the player 1hp

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues?q=cougar wtf man

**Comment by GalaxyGaming629** [comment]
Why'd you close it

**Comment by kolyaventuri** [comment]
@GalaxyGaming629 This has been suggested numerous times. We also try to avoid effects that are specific to a content creator, such as DarkViperAU, as this isn't just a mod for specific people.

**Comment by GalaxyGaming629** [comment]
I'm sorry I didn't know that

**Comment by TheRealAyCe** [comment]
> @GalaxyGaming629 This has been suggested numerous times. We also try to avoid effects that are specific to a content creator, such as DarkViperAU, as this isn't just a mod for specific people.

Can we add "No DarkViperAU references, no cougars, no jesus, no fake fake death, no instadeath, no spawn NPC xyz, no change player to model xyz and so on" to the suggestion template? The "search before you post" thing is ignored. Well, maybe listing concrete effects in addition will be ignored too, but it might be worth a try.
