### ISSUE TITLE
[Effect Suggestion] Teleport all peds to player

### ISSUE THREAD

**Issue by Santiago-Alvizar** [gta-chaos-mod/ChaosModV#2422]
**Teleport all peds to player**

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Teleport all peds that are in range to the player**

**Comment by Last0xygen** [comment]
Here’s already an „teleport everything to player“ effect

**Comment by Santiago-Alvizar** [comment]
ik that, but instead just teleports the peds that have an AI, so that the player doesnt dies because of 10 cars teleported to them, instead teleports all the people and doesnt die to an explosion
