### ISSUE TITLE
[Effect Suggestion] 6-Star Wanted Level

### ISSUE THREAD

**Issue by MarkowitzThe2nd** [gta-chaos-mod/ChaosModV#2427]
**Name of effect**
6-Star Wanted Level

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- Dependent on the player's ability to lose them.

**Effect Description**
The effect spawns weaponized Jesus's that come after the player. They will also retain their normal health status, making them harder to kill.

**Comment by Last0xygen** [comment]
We don’t need several new Jesus effects 😅
