### ISSUE TITLE
[Effect Suggestion] pacifist

### ISSUE THREAD

**Issue by Hazemkaid** [gta-chaos-mod/ChaosModV#2435]
**Name of effect**
Pacifist

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
The player can't punch or use weapons for 10 seconds

**Comment by VDKA-Deado** [comment]
The pacifist effect already exists...

**Comment by Hazemkaid** [comment]
> The pacifist effect already exists...

Oh well dang thought I could add the effect seems someone beat me to it

**Comment by turg-the-sad-cat** [comment]
But it’s been in the mod since like the first 3 months

**Comment by Hazemkaid** [comment]
> But it’s been in the mod since like the first 3 months 

Oh ok
