### ISSUE TITLE
[Effect Suggestion] Turn current vehicle into bmx

### ISSUE THREAD

**Issue by iampof** [gta-chaos-mod/ChaosModV#2437]
**Name of effect**
Potential name(s) for the effect
Bike boys

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
Should turn the players current vehicle into a bmx, and kick any passengers out

**Comment by turg-the-sad-cat** [comment]
Isn’t that just spawn BMX

**Comment by Last0xygen** [comment]
It is, but without forcing all other peds out.
In itself not that unique, sorry
