### ISSUE TITLE
[Effect Suggestion] K-9 Unit 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2438]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Spawns a bunch of dogs of which if the player is attacked by enemies, the dogs will attack said enemies until the effect's over. Even they are abandoned they'll always find a way back to the player to assist

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/940
Please use the search before posting :)
