### ISSUE TITLE
[Suggestion] Effect: Limit FPS

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#244]
Lock the framerate to 15 fps for a while

**Comment by PiotrKowalski** [comment]
I would call it "Console POV" instead of "Limit FPS"

**Comment by AxmPlays** [comment]
> I would call it "Console POV" instead of "Limit FPS"

console fps is 30

**Comment by PiotrKowalski** [comment]
> > 
> 
> console fps is 30
That was a joke. You know. That consoles run poorly.
