### ISSUE TITLE
[Effect Suggestion] Peloton

### ISSUE THREAD

**Issue by SeanMirrsen** [gta-chaos-mod/ChaosModV#2440]
**Name of effect**
Peloton

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The player's vehicle is turned into a random bicycle (or they are put on a random spawned bicycle). Any NPCs in player's faction, plus any NPCs within a short range of the player, are also put on bicycles, and made to follow the player.

(While writing this I realized it's sort of a copy of Scooter Brothers, but slightly different in that the player vehicle also changes. I think it can still work in the mod, as most other effects of this kind (with buses or tanks) are extremely disruptive.)

**Comment by turg-the-sad-cat** [comment]
Changing the players model doesn’t work

**Comment by SeanMirrsen** [comment]
> 
> 
> Changing the players model doesn’t work

Uh, yes, it does not. That is entirely true. And? :P

**Comment by turg-the-sad-cat** [comment]
Once again it might be too close to spawn bmx

**Comment by SeanMirrsen** [comment]
This suggestion was inspired by the other one about bmx, I'm not the same guy. :P 
It's actually a little too close to "scooter brothers", but I thought the slight bit of difference in both changing the player's vehicle into a bicycle, and also putting nearby NPCs on bicycles, would be interesting. Sometimes if you're driving along on a mission and Scooter Brothers comes up, your mission buddies are just ejected out on their scooters, and you have to go collect them. And if you get a random vehicle that doesn't have enough seats, they're also left behind. With this one, you get a single-seat vehicle, but so does everyone else, and they'd follow you (hence the name Peloton, a group of racing cyclists banding together for speed), so you could try to keep going.

**Comment by usget** [comment]
I suggested something similar a few days ago - prefer your effect name though  --> https://github.com/gta-chaos-mod/ChaosModV/issues/2414

**Comment by SeanMirrsen** [comment]
Ooh, so you did. I thought I was following the submissions well enough through the discord bot, so didn't do a search. Apparently my memory failed me. I'll close this one then, it's basically a carbon copy.
