### ISSUE TITLE
[Effect Suggestion] Why did let the monkey drive?

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#2442]
**Why did let the monkey drive?**
Potential name(s) for the effect

**Duration**
- [x] No duration

**Effect Description**
Description of the effect; what should it do?
Put the monkey in the wheel

This idea come from Meltdown (a gta movie)
---------
Zavarski The Novakid give me the idea

**Comment by TheBatmanReal** [comment]
MONKE

**Comment by Last0xygen** [comment]
Spawn companion monkey is already an effect
