### ISSUE TITLE
[Effect Suggestion] Tweak to all Jesus effects

### ISSUE THREAD

**Issue by LifeTimeGamerYT** [gta-chaos-mod/ChaosModV#2444]
Have this https://www.youtube.com/watch?v=Wdo4Eyw4DqM built into the Jesus effects to add more value to the effect.

**Comment by Goorakh** [comment]
You can already do this with the effect trigger sounds, if you want the song to play in-game, save it to an mp3 file in the chaosmod/sounds folder with the name "spawn_grieferjesus", "spawn_grieferjesus2", or "veh_jesustakethewheel".

**Comment by Last0xygen** [comment]
Every player can modify that themselves, we won’t provide a standard sound
