### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Naofumi856** [gta-chaos-mod/ChaosModV#2448]
**Name of effect**
RNGesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X ] No duration

**Effect Description**
A fifty percent chance to spawn enemy griefer Jesus, and a fifty percent chance to spawn companion griefer Jesus.

**Comment by Last0xygen** [comment]
Correct
