### ISSUE TITLE
[Effect Suggestion] Fake Jesus

### ISSUE THREAD

**Issue by Santiago-Alvizar** [gta-chaos-mod/ChaosModV#2449]
Fake Jesus

- [ ] Long
- [ ] Short
- [X] No duration

The effect will show to the player as Spawn Extreme Griefer Jesus, the "Our God is an awsome God!" song will play but after some seconds the player can see the real effect and song will stop (pretty much the same as fake dead or fake teleport)

**Comment by VDKA-Deado** [comment]
I'm pretty sure that they don't want any new Jesus effects.
Plus using music that isn't from the game would likely be complicated - involving a using an audio file that isn't already in GTA and also using audio which would require permission and other awkward dealings. 
Those last 2 might not be true but I know the first point is.

**Comment by kolyaventuri** [comment]
Correct, we don't want any more Jesus effects. It's also already been suggested (see #396 or #1366).

As for playing "Our God is an Awesome God," that's not something that's part of the mod. That's something DarkViperAU edits in, in the chaos mod highlights. There are no intentions to add that song as part of the effect.
