### ISSUE TITLE
[Suggestion] Effect: Fake Mission Fail

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#245]
So, after "Fake Death" effect update, you will be ragdolled/blown with "Wasted" screen about to show up and then be restored, as it was fake. But first version just did "Wasted" screen, none more. What if this version will be now "Fake Mission Fail", which does exactly as the first version of "Fake Death", but Fail Description would be "You've been jebaited"?

**Comment by pongo1231** [comment]
Would only be applicable to missions and even then it will likely just have the same effect "Fake Death" has (it's randomized as to if it's playing the death / explosion animation or not). I don't think it's a good fit for the mod.
