### ISSUE TITLE
[Millions to One!] Spawns a cougar and doesn’t show the effect name until player is dead or the cougar is dead.

### ISSUE THREAD

**Issue by Chipsy101** [gta-chaos-mod/ChaosModV#2451]
**Millions To One!**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X] No duration

**Effect Description**
It spawns a cougar and doesn’t show the effect name until the player dies from the cougar or the cougar gets killed.

**Comment by kolyaventuri** [comment]
Suggested numerous times already

See #2250, or #1215 two name two
