### ISSUE TITLE
[Effect Suggestion] Lost Glasses / Everything is blurry

### ISSUE THREAD

**Issue by PinballGH** [gta-chaos-mod/ChaosModV#2452]
**Name of effect**
Lost Glasses
Everything is blurry
(Something similar?)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long (30 seconds)

**Effect Description**
Makes everything really blurry for 30 seconds, including minimap/HUD. It'll be hard to drive without hitting anything, see where you gotta go on the minimap, select the correct weapon, see your health and shoot accurately at enemies. As simple as that !

**Comment by SeanMirrsen** [comment]
"I need glasses" is already an effect.

We really need that official catch-all issue so that at least the people that search up their suggestion can find it if it's already in the mod.

**Comment by kolyaventuri** [comment]
Correct, already an effect.

**Comment by PinballGH** [comment]
> 
> 
> "I need glasses" is already an effect.
> 
> We really need that official catch-all issue so that at least the people that search up their suggestion can find it if it's already in the mod.

I searched it, I checked for glasses / blurry / blind didn't found anything :/

**Comment by kolyaventuri** [comment]
You won't find an issue for it, since it's already an existing effect in the mod. A master list that is easier to search is a good idea though

**Comment by PinballGH** [comment]
> 
> 
> Correct, already an effect.

My bad then!

**Comment by SeanMirrsen** [comment]
> 
> 
> > "I need glasses" is already an effect.
> > We really need that official catch-all issue so that at least the people that search up their suggestion can find it if it's already in the mod.
> 
> I searched it, I checked for glasses / blurry / blind (each one by one obviously) didn't found anything :/

Yeah, but it's an effect already in the game, so you wouldn't have found it. We need that open issue with a list of existing effects, and commonly suggested (and rejected) ones.
