### ISSUE TITLE
[Effect Suggestion] CP1

### ISSUE THREAD

**Issue by mmmoo123** [gta-chaos-mod/ChaosModV#2454]
**Name of effect**
CP1

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Effect inspired by YouTuber DGR. The effect would revers player progress on mission to first or previous checkpoint.

**Comment by TerrizX** [comment]
This is way too evil

**Comment by Last0xygen** [comment]
This has also already been requested
