### ISSUE TITLE
[Effect Suggestion] There aren’t cougar on the game… or are there

### ISSUE THREAD

**Issue by Damianyo11** [gta-chaos-mod/ChaosModV#2456]
**There aren’t cougar on the game… or are there**

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ X] Long

**Description**
Make the controlled player a cougar and make them attack lots of Trevor’s

**Comment by pipecek** [comment]
Cougars were requested so... many.... fricking times

**Comment by Damianyo11** [comment]
> Cougars were requested so... many.... fricking times

Oh my bad I searched cougar and nothing popped up
