### ISSUE TITLE
[Effect Suggestion] animal party

### ISSUE THREAD

**Issue by Mikiboy123** [gta-chaos-mod/ChaosModV#2460]
**Name of effect**
animal party

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn 5 random animals near the player including: cougar, deer, dog etc.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/712
