### ISSUE TITLE
[Effect Enhancement Suggestion] Fake Crash

### ISSUE THREAD

**Issue by GTAHewlett** [gta-chaos-mod/ChaosModV#2463]
Current Effect: Fake Crash.

Change: Minimise the window for 2 seconds after suspending the thread so the player believes it to be a real crash, as an alternative maybe use this as an additional effect such as Super Fake Crash.

How? Use the following windows functions found in "WinUser.h"
ShowWindow(); https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
FindWindowA(); https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindowa

Use arguments SW_MINIMISE and SW_RESTORE to minimise and restore the window to the original state and size.

You could also use this to add other effects built upon this such as "Windowed Mode", "Switch Window" caused sometimes by SW_HIDE. Not many possibilities but the major one is making fake crashes less fake lol. 

I could also code and implement this myself as it's not too difficult but I'm currently busy, if no ones done it in a month I will.

**Comment by kolyaventuri** [comment]
Duplicate, see #2171 or #1103. As well, I've explored using the WinApi bindings to achieve this before, to no avail. Thought I had the hwnd of the GTAV.exe process, but no dice. You're more than welcome to have a go at implementing it you feel comfortable!
