### ISSUE TITLE
[Effect Suggestion] change language

### ISSUE THREAD

**Issue by lonecoder1011** [gta-chaos-mod/ChaosModV#2465]
**Name of effect**
Potential name(s) for the effect
change language
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
 temporarily changes to a random language

**Comment by VDKA-Deado** [comment]
Great idea, though I'm pretty sure this has [already been suggested](https://github.com/gta-chaos-mod/ChaosModV/issues/1131).

**Comment by Last0xygen** [comment]
Duplicate
