### ISSUE TITLE
[Effect Suggestion] Spawn Oppressor and Oppressor Mk 2

### ISSUE THREAD

**Issue by GalaxyGaming629** [gta-chaos-mod/ChaosModV#2468]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; it will spawn the first oppressor and the oppressor MK2 but they will be separate effects

**Comment by Last0xygen** [comment]
Theres already „you’re a wizard franklin“, which spawns the mk2. Spawning the first one can already be done via „spawn random vehicle“.
A separate effect only for that is not unique enough, sorry

**Comment by GalaxyGaming629** [comment]
Ok I'll try to think of a unique effect
