### ISSUE TITLE
[Effect Suggestion] Player stats go down to 0

### ISSUE THREAD

**Issue by Mikiboy123** [gta-chaos-mod/ChaosModV#2471]
**Name of effect**
Decrease all player stats

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
All the player stats go down to 0 including: stamina,shooting,driving etc

**Comment by Last0xygen** [comment]
Too similar to https://github.com/gta-chaos-mod/ChaosModV/issues/1193 or #1633
