### ISSUE TITLE
[Effect Suggestion] "5"-Bit

### ISSUE THREAD

**Issue by Aq1fZA** [gta-chaos-mod/ChaosModV#2477]
- [x] Long
- [ ] Short
- [ ] No duration

[Effect description]
Makes your screen becomes 8-bit or became a 8-bit game!

**Comment by Aq1fZA** [comment]
I know this wont be accepted

**Comment by Last0xygen** [comment]
Then why post it 🤪
Jokes aside, this is (currently) not possible
