### ISSUE TITLE
[Effect Suggestion] Ms Bakers phone call

### ISSUE THREAD

**Issue by Aq1fZA** [gta-chaos-mod/ChaosModV#2478]
**Name of effect**
Ms Bakers Casino Phone Call

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Make Ms Bakers calls you when you are doing a random mission or everyday!

**Comment by Last0xygen** [comment]
Fake phone calls have already been requested

**Comment by Aq1fZA** [comment]
i forgot about that😅 sorry
