### ISSUE TITLE
[Effect Suggestion] Avengers

### ISSUE THREAD

**Issue by Rolypolyoly1877** [gta-chaos-mod/ChaosModV#2480]
**Name of effect**
Avengers, Avengers Assemble, anything with the word Avenger

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Replaces current vehicle with, or spawns player into an Avenger.
Spawns Impotent Rage nearby, Space Ranger, npc in a Blue Jock Cranley suit, maybe the Pogo Space Monkey, and maybe Brad. They are friendly towards the player similar to Companion Brad and will help fight nearby enemies.

**Comment by Last0xygen** [comment]
Basically the same as https://github.com/gta-chaos-mod/ChaosModV/issues/392
Or other suggestions. Multiple ped spawn effects are not a good „new effect“
