### ISSUE TITLE
[Effect Suggestion] Ultimate Griefer Jesus

### ISSUE THREAD

**Issue by Hatsch1** [gta-chaos-mod/ChaosModV#2481]
**Name of effect**
Ultimate Griefer Jesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- X No duration

**Effect Description**
Player gets killed by orbital cannon with the message "Jesus obliterated you"; "message from heaven" or something like that. Optional: player receives an SMS from jesus "1-0 lzzzzzzzz" or, if SMS sender can't be customized;
 "1-0 lzzzzzzzzzz
-Jesus"

**Comment by 5harpness** [comment]
isn't that a bit too extreme? good idea but for ex. have jesus strike the player's current position, so matt at least has a chance to survive. so if hes standing still he dies but if hes moving in a fast car he wont

**Comment by Last0xygen** [comment]
Insta killing the player is not a good effect
