### ISSUE TITLE
[Effect Suggestion] N.O.E.

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2484]
**Name of effect**
N.O.E.

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
An Altitude Meter will show up on the radar at your screen, works similarly like Minor Turbulence. However, this Meter is not only responding when you're in an aircraft, but also when on the ground on foot or driving a car. As soon as your altitude goes past the upper limit, two enemies in a Lazer will show up and finish you off. So be careful and Nap On the Earth, especially if you got effects such as Low Gravity, Send X to Space, Teleport to Heaven, etc.

**Comment by Last0xygen** [comment]
Im sure this has already been requested.
But as this won’t do anything of the User is on foot, swimming or driving, I don’t think this is a good effect. It won’t do anything 98% of the time

**Comment by RosyMiranto18** [comment]
But... But this one suggestion is MEANT to also work on foot and driving land vehicles too, not just aircraft. Unless if you can't put the Altitude Meter on anything other than air vehciles.

**Comment by RosyMiranto18** [comment]
That's a really great idea to improve it on. Thank you for your wise words here, Sean. Both of your suggested names also work really good too.

**Comment by TheRealAyCe** [comment]
Open a new ticket with the revised suggestion? Edit this one and have it reopened? What does Last0xygen think?

**Comment by Last0xygen** [comment]
If then for sure a new suggestion. But I’m still not really convinced how this should work (technically and visually)
