### ISSUE TITLE
[Effect Suggestion] Spawn Chernobog

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2485]
**Name of effect**
Spawn Chernobog

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn the Slavic Black God of a Surface to Air Missile Launcher Vehicle. Self-explanatory. Enemy driver driving the vehicle is optional upon spawning.

**Comment by Last0xygen** [comment]
Already part of „spawn random vehicle“
