### ISSUE TITLE
[Effect Suggestion] Spawn Doomsday (Griefer) Jesus

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2486]
**Name of effect**
Spawn Doomsday (Griefer) Jesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn Our Lord and Savior Griefer Jesus, fresh from fighting the End of Time, the Apocalypse. He still carries his trusty Railgun, but instead of riding the Oppressor Mk. II, he's in a Khanjali with a Railgun Cannon and a Galaxy Livery.

**Comment by Last0xygen** [comment]
Duplicate has already been requested
