### ISSUE TITLE
[Effect Suggestion] Spawn Pet Rock

### ISSUE THREAD

**Issue by 5harpness** [gta-chaos-mod/ChaosModV#2488]
**Name of the Effect**
Spawn Pet Rock

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No Duration

**Effect Description**
Spawns a rock. The size is random, from a small pebble to a boulder half the player’s size. This effect would be quite funny to see since it would either do nothing or potentially crash someone’s airplane. Whether the rock can be bigger really depends on your preference last0xygen, since I know you’re the only one who reads these.

**Comment by Last0xygen** [comment]
😂 nice one.
But seriously though, meteor shower is already an effect

**Comment by RosyMiranto18** [comment]
I think this can work somewhat. Meteor's drop velocity is pretty slow, so maybe this one effect's drop velocity will be a lot higher, at least five times.

**Comment by 5harpness** [comment]
> 😂 nice one. But seriously though, meteor shower is already an effect

The rock would spawn on a player, and it would be just one, its kinda different but ig
