### ISSUE TITLE
[Effect Suggestion] Special Combo Time

### ISSUE THREAD

**Issue by aenon83** [gta-chaos-mod/ChaosModV#2493]
**Name of effect**
Combo Time (X)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**

- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Instead of the actual Combo Time effect, where (at least for the Twitch version) it uses the next three options for voting, make different Combo Time options for voting that are predefined combos. For example:

- Combo Time (Directedy by Michael Bay): uses explosive peds, explosive zombies, explosive combat and vehicles explode on impact.
- Combo Time (Puke Rainbows): uses rainbow weapons, rainbow lights and rainbow cars.
- Combo Time (I can't see sh*t or I can't see anything): invisible vehicles and everyone is a ghost.
- Combo Time (Frozen): snow, snowy weather and slippery vehicles.
- Combo Time (Honk Honk): all vehicles honk and honk boosting, I don't know if this would result in the same as full acceleration.
- Combo Time (Wanted: Dead or Alive): spawns griefer Jesus, jealous Jimmy, Juggernaut, Deadly Agent, all (or just a few) of the enemies that can be spawned nearby, not just near the player, just enough that he will be finding them while he is moving.
- Combo Time (Let me clean your screen): no hud, no radar and no phone.

The time effect for each option would depend on the time effect of the options that it uses.

**Comment by Last0xygen** [comment]
Similar requests already exist. The problem with that is that this would require additional work and maintenance for every effect AND their depending effects. If one change is odone is has to be evaluated with all depending effects.
If a new effects get submitted it has to be cross referenced with all existing ones if there’s a combination
