### ISSUE TITLE
[Effect Suggestion] Improved Fake Teleport

### ISSUE THREAD

**Issue by 5harpness** [gta-chaos-mod/ChaosModV#2494]
**Name of effect**
Fake Teleport

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Another idea for Fake Teleport, basically it teleports you like 15m from your waypoint, then teleports you back. The distance is there so the mission doesn't end/trigger to keep it a FAKE teleport.

**Comment by turg-the-sad-cat** [comment]
Already been suggested before
