### ISSUE TITLE
[Effect Suggestion] this is why we cant have nice things

### ISSUE THREAD

**Issue by andrew21521** [gta-chaos-mod/ChaosModV#2504]
**Name of effect**
Potential name(s) for the effect

this is why we can't have nice things
no more nice things

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
get rid of everything, guns, cars, money, etc.

**Comment by Last0xygen** [comment]
„bad luck“ effects have already been requested
