### ISSUE TITLE
[Effect Suggestion] Add an effect called orange which freeze the screen and change it into just the colour orange

### ISSUE THREAD

**Issue by Francoorthatxqcperson** [gta-chaos-mod/ChaosModV#2505]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
Not a good effect
