### ISSUE TITLE
[Effect Suggestion] To become an NPC

### ISSUE THREAD

**Issue by Mikiboy123** [gta-chaos-mod/ChaosModV#2511]
**Name of effect**
Become a nearby NPC

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
You control the Nearest NPC while your main character becomes an NPC,when the effect ends you control back your main character

**Comment by Last0xygen** [comment]
Yes
