### ISSUE TITLE
[Effect Suggestion] Flash Mob

### ISSUE THREAD

**Issue by EonYears** [gta-chaos-mod/ChaosModV#2524]
**Name of effect**
Flash Mob

**Effect Description**
Maybe a huge flash appeares on the screen or not. It spawns maybe 10 to 20 people that are just dancing. They will just dance and nothing unless killed. It's a true flash mob then.

**Comment by Last0xygen** [comment]
Spawning lots of peds is generally not a good effect. Making peds dance is already available as „in the hood“
