### ISSUE TITLE
[Bug] My Nasty Bug

### ISSUE THREAD

**Issue by GalaxyGaming629** [gta-chaos-mod/ChaosModV#2529]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Crash Dump (if a game crash)**
Attach the latest .dmp file (names are Year-Month-Day-Hour-Minute.dmp) located in chaosmod/crashes/, ignore if bug doesn't cause a game crash

Make it able to drink from the vending machine from 'Quick Sprunk Stop'

**Comment by GalaxyGaming629** [comment]
I was thinking about it but then I realized it's kind of a bug

**Comment by Last0xygen** [comment]
It is not though. Spawning a vending machine does not add all the code to make it „usable“.
This has also been requested but it’s just not really feasible to add that as it’s much work for little payoff
