### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by JuliusFalck1** [gta-chaos-mod/ChaosModV#2535]
**Name of effect**
Potential name(s) for the effect:
Expanded & Enhanced

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?:
Make every license plate yellow, because that's what came in Expanded & Enhanced

**Comment by Last0xygen** [comment]
Duplicate
