### ISSUE TITLE
[Effect Suggestion] Pool Party

### ISSUE THREAD

**Issue by InvoicingKarma** [gta-chaos-mod/ChaosModV#2537]
**Name of effect**
Pool Party!

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports player and any peds in a radius into Michael's Pool

**Comment by Last0xygen** [comment]
Well it’s more a combination of teleport everything to player and that other suggestion, I don’t think it needs its own
