### ISSUE TITLE
[Effect Suggestion] All Cars Are Deleted

### ISSUE THREAD

**Issue by D3DH4CK3R** [gta-chaos-mod/ChaosModV#2540]
**Name of effect**
All Cars Is Deleted

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Every Car Is Deleted Even Peds Cars And Players Car

**Comment by Last0xygen** [comment]
So „no Traffic“ with „remove current vehicle“
„No traffic“ alone is sufficient imho
