### ISSUE TITLE
[Effect Suggestion] The Noob Tube

### ISSUE THREAD

**Issue by TBloemink** [gta-chaos-mod/ChaosModV#2545]
The Noob Tube

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

Might haven’t searched right but couldn’t find it

spawns clone of Lester with an RPG that attacks player much like Griefer Jesus

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
