### ISSUE TITLE
[Effect Suggestion] Death by arrival

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2555]
**Name of effect**
Death by arrival 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Kill player when he is 30 meters from his waypoint or a mission

**Comment by FAR95d** [comment]
> No difference to suicide

Ah but it hides the effect until you reach a mission or waypoint or destination... Then if you are within 30 metres of it you die... So its suicide with extra steps..

**Comment by Last0xygen** [comment]
Yes, suicide with extra steps
