### ISSUE TITLE
[Suggestion] Fake Death can be more fake

### ISSUE THREAD

**Issue by AxmPlays** [gta-chaos-mod/ChaosModV#256]
When fake death is selected randomly or twitch voted it, fake death doesn't show up after the fake death has happened which can be remembered to know when fake death happened but for suicide and explode current vehicle it shows up straight away when it is selected. So for fake death if the player isn't in a vehicle it will say suicide and then after the fake death is done then it would say fake death and for fake death in a vehicle it will say explode current vehicle and then after the fake death is done then it would say fake death in the recent selected options.

**Comment by Last0xygen** [comment]
in progress https://github.com/gta-chaos-mod/ChaosModV/pull/325
