### ISSUE TITLE
[Effect Suggestion] Copyright

### ISSUE THREAD

**Issue by andrew21521** [gta-chaos-mod/ChaosModV#2562]
**Name of effect**
Potential name(s) for the effect
get copyrighted, time for licensed music
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
play a copyrighted song that it has like Feel Good Inc. or Radio Ga Ga

**Comment by Last0xygen** [comment]
Not a good effect
