### ISSUE TITLE
[Suggestion] Effect: Spawn Troll Jesus

### ISSUE THREAD

**Issue by SeanMirrsen** [gta-chaos-mod/ChaosModV#257]
Amid the litany of fakeout effects, it may be neat to have a fakeout where one is even less expected.

A "Troll Jesus" is exactly like the Griefer Jesus, with several important differences.

He has a gun, but can only aim, not shoot.
He is completely invincible, but despawns after a short period.
Anyone who shoots him, dies - like the Pacifist effect.
Any vehicle that collides with him, explodes.

I think it'd be a pretty good representation of a troll - an ineffectual but impossible to get rid of a-hole that only harms you if you engage with him. :P

**Comment by Last0xygen** [comment]
No need for another Jesus effect
