### ISSUE TITLE
[Effect Suggestion] Spawn Companion Doctor 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2584]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Dr. Dre as a companion.

**Comment by TerrizX** [comment]
> Already part of „spawn random companion“

But there are options to spawn specific peds like Brad tho?

**Comment by Last0xygen** [comment]
Yes, and they are enough :)
