### ISSUE TITLE
[Effect Suggestion] Just As The Founding Fathers Intended

### ISSUE THREAD

**Issue by Ricwc34** [gta-chaos-mod/ChaosModV#2586]
**Just As The Founding Fathers Intended**
Potential name: 
JATFFI
Founding Fathers Intended
WTFFI- (what the founding fathers intended)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
When chosen all "modern" weapons are stripped from the player and they are given a musket and marksman pistol. Hostile, neutral, and passive AI are not affected by this effect. The players outfit could be changed to look more "colonial".

**Comment by Last0xygen** [comment]
There already is a „musket“ effect suggestion
