### ISSUE TITLE
[Effect Suggestion] Human guns

### ISSUE THREAD

**Issue by vihtro** [gta-chaos-mod/ChaosModV#2590]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Effect similar to Catto guns but with humans, not cattos. If human will survive then it will attack player with baseball bat.

**Comment by vihtro** [comment]
F... Wrong category. Sorry 😐

**Comment by anto4440** [comment]
Well i already have suggested 'Improvised weanponry', which can make you fire humans. Also the ragdolls would cause horrible lag.

**Comment by MoneyWasted** [comment]
Too similar to Improvised weanponry
