### ISSUE TITLE
[Effect Suggestion] Mario Kart

### ISSUE THREAD

**Issue by KindaChaotic69** [gta-chaos-mod/ChaosModV#2593]
Replace current vehicle (or if he isn't in a vehicle do it anyways) with a random kart vehicle.
Idk how much you can change about the game but it would be cool adding some powerups too that he can use when the mod is on.

**Comment by MoneyWasted** [comment]
Sounds like a cool idea but it is too similar to replace current vehicle. Also, Nintendo probably won't like us using "Mario Kart".
