### ISSUE TITLE
"millions to one" where it spawns in a cougar and shows the affect after 

### ISSUE THREAD

**Issue by bronzedelta0** [gta-chaos-mod/ChaosModV#2594]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ ] No duration

**Effect Description
 It spawns in a cougar and shows the affect after the player or cougar is killed.

**Comment by turg-the-sad-cat** [comment]
Already been suggested multiple times
