### ISSUE TITLE
[Effect Suggestion] Jesus take the wheel v2

### ISSUE THREAD

**Issue by RastaGrzywa** [gta-chaos-mod/ChaosModV#2596]
**Name of effect**
Jesus take the wheel v2

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
So currently Jesus takes the steering wheel. It could be fun if Jesus would take randomly one of 5 wheels in a car (1 steering & 4 normal). When steering wheel chosed then effect stays same as original, otherwise pop one random tire.

**Comment by MoneyWasted** [comment]
Has already been suggested and is actively being worked on.
