### ISSUE TITLE
[Effect Suggestion] The Expendables

### ISSUE THREAD

**Issue by Fluffx** [gta-chaos-mod/ChaosModV#2597]
**Name of effect**
The Expendables

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a group of 9 muscular military men (or just muscular if needed). They're treated as companions or followers with powerful weapons.

**Comment by MoneyWasted** [comment]
Sounds like a cool effect but we currently don't need any more spawning ped effects.
