### ISSUE TITLE
[Effect Suggestion] Play A Random Meme

### ISSUE THREAD

**Issue by JerezFIN** [gta-chaos-mod/ChaosModV#2598]
**Name of effect**
Play a random meme
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Plays a random meme sound effect :D example: Bruh,follow that goddamn train CJ, ah shit here we go again
Description of the effect; what should it do?

**Comment by MoneyWasted** [comment]
Can be done by each user individually as an effect sound. Also, there are other issues with this, but I can't explain them all here.
