### ISSUE TITLE
[Effect Suggestion] Can"t have shit in Los Santos

### ISSUE THREAD

**Issue by UjjwalJ-5107** [gta-chaos-mod/ChaosModV#2599]
**Name of effect**
Fuckers stole my tire, tire gone, chaos take the wheel

**Effect Description**
Description of the effect; what should it do?
It should pick off a tire of the players vehicle.

**Comment by turg-the-sad-cat** [comment]
Already been suggested before

**Comment by casperge** [comment]
Would like to code something like this, but don't think there is a method known that could remove wheels.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/107
