### ISSUE TITLE
[Effect Suggestion] Seizure

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2600]
**Name of effect**
Seizure

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Ragdoll and fling in one place

**Comment by FAR95d** [comment]
I mean ragdoll and fling in a 1 meter radius simultaneously

**Comment by MoneyWasted** [comment]
Too similar to ragdoll.
