### ISSUE TITLE
Meta Effect (the chosen one)

### ISSUE THREAD

**Issue by Agentcool** [gta-chaos-mod/ChaosModV#2604]
**the chosen one **
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X ] Long
- [ ] Short
- [ ] No duration

**its a meta effect it would work whit the effect of proportional voting of matt and just make it so its the most voted effect insted of proportional so it would be the chosen one and it would be for 2min **
Description of the effect; what should it do?

**Comment by Last0xygen** [comment]
No
* no effects for single streamers
* has been requested already
