### ISSUE TITLE
[Bug]some of the commands dont work

### ISSUE THREAD

**Issue by CouchPotatoJ** [gta-chaos-mod/ChaosModV#2606]
For example, Ctrl + L, and - work but Ctrl +, and . don't work and those are the ones for the mod menu and pause 
I didn't even do anything for this to happen, when I downloaded the mod and tried out the commands these two just didn't work.

**Comment by Last0xygen** [comment]
Did you enable them in the config app? OtherwiE they won’t work

**Comment by CouchPotatoJ** [comment]
> Did you enable them in the config app? Otherwise they won’t work

yeah I did, I also tried deleting and redownloading the mod

**Comment by MoneyWasted** [comment]
This is user issue and has little to do with the mod. Also hasn't had a response in over 2 months. Closing...
