### ISSUE TITLE
[Effect Suggestion] Melodic Bullets

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2607]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Bullets shoot in rhythm to different iconic songs of your choice (ones that most people would be able to recognise).

**Comment by Last0xygen** [comment]
Too situational
Would require he player to shoot full Auto for a long period, pistol shotgun or snipers won’t be heard.
Also Framerate dependent
