### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by RetroStance** [gta-chaos-mod/ChaosModV#2608]
**Name of effect**
Did somebody’s say yoga?

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
When chosen, the effect will cause the yoga mini-game to pop up on the screen. The player will then have to complete one of these mini-games to advance.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/648
Also, hi Reddit 🤪
