### ISSUE TITLE
[Effect Suggestion] Nintendo Switch Experience

### ISSUE THREAD

**Issue by HenBasket** [gta-chaos-mod/ChaosModV#2610]
**Nintendo Switch Experience**
Potential name(s) for the effect:
Switch Experience, Nintendo Switch Port, Switch Port

**Duration**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Effect would be a combination of Console Experience, Low Render Distance, and optionally lag. Basically, an exaggerated example of how a rushed switch port would feel

**Comment by MoneyWasted** [comment]
Effects to mimic this already exist and it seems unnecessary.
