### ISSUE TITLE
[Effect Suggestion] Eye Guns

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2612]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Looking at a ped causes bullets to be shot at them.

**Comment by JustTunerYT** [comment]
That's "Deadly Aim"

**Comment by Last0xygen** [comment]
Yes
