### ISSUE TITLE
[Effect Suggestion] 

### ISSUE THREAD

**Issue by CANDICEDICK** [gta-chaos-mod/ChaosModV#2613]
Welcome to the jungle

Monke rain
Monkey rain

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x ] Long
- [ ] Short
- [ ] No duration

monkeys start to rain and start fighting with guns ( small light brown moneys vs. big dark brown monkeys)
some have miniguns some have assault riffles

**Comment by KindaChaotic69** [comment]
i can see the crash already lol

**Comment by MoneyWasted** [comment]
Can cause to many issues with stability.
