### ISSUE TITLE
[Effect Suggestion] RNGesus

### ISSUE THREAD

**Issue by shahar654** [gta-chaos-mod/ChaosModV#2614]
-->

**Name of effect**
RNGesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X ] No duration

**Effect Description**
Will spawn random Jesus figure. It could be: Jesus takes the wheel, Griefer Jesus, Extreme Griefer Jesus and one extra, ally Jesus.

**Comment by Last0xygen** [comment]
Already has been requested
