### ISSUE TITLE
[Effect Suggestion] Extreme Inaccuracy

### ISSUE THREAD

**Issue by Complectogram** [gta-chaos-mod/ChaosModV#2615]
**Name of effect**
Extreme Inaccuracy
Inaccurate Weapons

**Duration**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
All bullets/rockets are fired with a 30° spread, or just ones from the player if you think that would be better.

**Comment by AussieEevee** [comment]
I think this would probably be better if it was a short duration to prevent it being too annoying.

**Comment by anto4440** [comment]
Nope. I have played games with a 30* deviation. its unplayable. half the time you just kill yourself by hitting the floor. 5* or 10* are plenty enough. Still a good effect though

**Comment by MoneyWasted** [comment]
Effect already exists as Heavy Recoil
