### ISSUE TITLE
[Effect Suggestion] Teleport to LS customs

### ISSUE THREAD

**Issue by Lampoff** [gta-chaos-mod/ChaosModV#2617]
**Name of effect** Teleport to LS customs
Potential name(s) for the effect 
What’d you do to her now?

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?
Should teleport the player to the nearest LS customs

**Comment by AussieEevee** [comment]
I suggest making it a random LS customs.

**Comment by MoneyWasted** [comment]
We currently don't need any more teleporting effects. I'll keep this in mind if we do want to add any more of them.
