### ISSUE TITLE
[Effect Suggestion] China

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2618]
**Name of effect**
China

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Makes everyone chinese and makes everything work crappy and break every 20 seconds such as vehicles, gps and make random stuff explode... And airplanes, choppers and blimps start to crash

**Comment by FAR95d** [comment]
Oh yeah and everyone would suddenly be talking as if they have been insulted like "I'm frightened!"

**Comment by FAR95d** [comment]
And the sky will be red so will the sun and it would play red sun rising constantly... And everyone will be holding either coffee or chinese food

**Comment by Last0xygen** [comment]
Yeeeeah no, Breaking Cars is already a thing though
