### ISSUE TITLE
[Effect Suggestion] millions to one

### ISSUE THREAD

**Issue by GnarlyRaccoon32** [gta-chaos-mod/ChaosModV#2619]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?
It will spawn a cougar that will instant kill you

**Comment by turg-the-sad-cat** [comment]
Been suggested at least 10 times

**Comment by Da-Best** [comment]
> Been suggested at least 10 times

to be exact 21 times
