### ISSUE TITLE
[Effect Suggestion] LGBTQ+

### ISSUE THREAD

**Issue by GnarlyRaccoon32** [gta-chaos-mod/ChaosModV#2620]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
Make everyone wear rainbow

**Comment by coolman6** [comment]
No controversial effects please.

**Comment by Last0xygen** [comment]
Not a good effect idea. Rainbow cars /weapons should be enough
