### ISSUE TITLE
[Effect Suggestion] Spawn TVA

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2622]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Spawns two suited peds near the player that walk from a door (random door spawned near the player) with laser guns. They're enemies of the player.

**Comment by Last0xygen** [comment]
No real difference to „spawn space ranger“
