### ISSUE TITLE
[Effect Suggestion] GTA IV

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2623]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Niko, Gay Tony, Patrick and Johnny as companions of the player.

**Comment by MoneyWasted** [comment]
Currently not possible to add character from other GTA games.

**Comment by TerrizX** [comment]
> Currently not possible to add character from other GTA games.

These models are in the game.
