### ISSUE TITLE
[Effect Suggestion] Zootopia

### ISSUE THREAD

**Issue by hugowiffen** [gta-chaos-mod/ChaosModV#2624]
**Zootopia**
Cursed Animals

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
This effect swaps the models of all npc's + player with random animal models and swaps all animal models with random NPC models.

**Comment by Last0xygen** [comment]
This has already been requested
