### ISSUE TITLE
[Effect Suggestion] Zap yourself

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#2626]
Also can be named as "Stunned"
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

It might be close to effect "Ragdoll", but it's a bit more logical than that one. Add a shock effect to any player model's spot like being shot by someone with stun gun

**Comment by anto4440** [comment]
Nah, its definitly too close to 'ragdoll'

Instead, maybe try to make an effect improvement to 'ragdoll', where its a 50/50 chance of a regular ragdoll or 'stunned'

**Comment by MoneyWasted** [comment]
Too similar to ragdoll
