### ISSUE TITLE
[Effect Suggestion] Armour Satchel

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2631]
**Name of effect**
Armour Satchel

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Gives player 3x max armour. This stacks (though i highly doubt it will matter, it would be pretty rare to get that several times before losing it)

**Comment by MoneyWasted** [comment]
Don't see the point of this effect. Seems very similar to the Give Player Max Armor and won't change much in terms of gameplay.
