### ISSUE TITLE
[Effect Suggestion] High, Very High Gravity

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/ChaosModV#2633]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ X for High Gravity] Long
- [X for Very High Gravity ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
High Gravity and Very High Gravity will be completely opposite to Low Gravity and Very Low Gravity

**Comment by VDKA-Deado** [comment]
Doesn't extreme gravity already exist?
I guess a _normal_ high grav could be interesting tho...

**Comment by Kristof-30** [comment]
Insane Gravity may have set 100X Gravity since it's insane
and Very High Gravity would have probably like 5-10X (depends how much value Very Low Gravity has because it's supposed to be completely inverted)

**Comment by MoneyWasted** [comment]
Too similar to the other effects and we don't want 10 different effects that do the same thing.
