### ISSUE TITLE
[Effect Suggestion] Spawn Angry Dave

### ISSUE THREAD

**Issue by YTQAlpha** [gta-chaos-mod/ChaosModV#2634]
**Name of effect**
Davey how are you?

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Spawns Dave with a minigun

**Comment by MoneyWasted** [comment]
We don't currently need anymore "angry" peds.
