### ISSUE TITLE
[Effect Suggestion] Rigged

### ISSUE THREAD

**Issue by Hemulius** [gta-chaos-mod/ChaosModV#2635]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
While this effect is active only good effects can happen by random effect or voted effect (so there will only be good/helpful effect avaiable for voting)

**Comment by Last0xygen** [comment]
Already requested
