### ISSUE TITLE
[Bug] Game freezes and crashes while playing GTA V Chaos Mod

### ISSUE THREAD

**Issue by Derps456** [gta-chaos-mod/ChaosModV#2636]
I put everything the game needs for the chaos mod, unfortunately the game freezes and crashes when I open it up and loaded the story mode. I am using the game from the Epic Games Store.

**Comment by MoneyWasted** [comment]
We need more information to be able to assist you. Can you upload your log files that are generated in your game folder by the mod?

**Comment by MoneyWasted** [comment]
Closed due to no response.
