### ISSUE TITLE
[Effect Suggestion] Jesus our Lord and saviour, and RNGesus

### ISSUE THREAD

**Issue by gkid64** [gta-chaos-mod/ChaosModV#2637]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; Jesus our Lord and saviour is essentially just griefer Jesus but he helps the player by shooting enemies of the player. RNGesus will spawn in Jesus with the rail gun but you won't know which Jesus he will be for a few seconds (if he's Jesus take the wheel he'll just hop into a nearby vechile)

**Comment by turg-the-sad-cat** [comment]
It’s been both suggested before (also with two suggestions, you should’ve made two separate ones)

**Comment by MoneyWasted** [comment]
We don't need any more Jesus based effects currently.
