### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Hello-MuFKR** [gta-chaos-mod/ChaosModV#2638]
**Name of effect**
Potential name(s) for the effect
America's Most Blunted

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
 
Gives player the weed effect and makes it very hard to drive, adds screen shake and effects.

**Comment by MoneyWasted** [comment]
Too similar to the drunk effect
