### ISSUE TITLE
[Effect Suggestion] Mr. Stark, I Don't feel so good

### ISSUE THREAD

**Issue by Pattyxe** [gta-chaos-mod/ChaosModV#2642]
**Name of effect**
Mr. Stark, I Don't feel so good

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
The effect is basically the Thanos snap, the player and the peds have a 50% of disintegrating.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1650 and #501
