### ISSUE TITLE
[Effect Suggestion] Big Smoke

### ISSUE THREAD

**Issue by Chrisis247** [gta-chaos-mod/ChaosModV#2647]
**Name of effect**
Big Smoke

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ X ] Long
- [ ] Short
- [ ] No duration

**Effect Description**
You get teleported behind the Train on a Motorbike with Big Smoke on your rear, yelling at you to follow the train, while he shoots 6 vagos on top of it. If you cant efficiently follow the train, the bike blows up and Big Smoke stands over you and yells the famous Line.

**Comment by UjjwalJ-5107** [comment]
that is literally the most impossible to recreate suggestion i have ever seen. Can't detect the train. No big smoke model in GTA V. and no dialogue for big smoke in the game too. although i get you may not know but still, not possible

**Comment by Last0xygen** [comment]
Yea, that’s not possible
