### ISSUE TITLE
[Bug] "Teleport To Random Location" destroys aircrafts

### ISSUE THREAD

**Issue by MoDerPo** [gta-chaos-mod/ChaosModV#2661]
**Describe the bug**
The effect 'Teleport to random location' teleports the player to the ground level, even if they are in an aircraft which destroys it.

**Steps To Reproduce**
- press `ctrl`+`.` to pause the mod
- get in an aircraft
- press `ctrl`+`,` and search for "Teleport To Random Location"
- press `enter`
- kaboom

**Location (roughly)**
``ChaosMod/Effects/db/Player/PlayerTpController.cpp:204`` < there needs to be some check here.

**Comment by pongo1231** [comment]
Already fixed; flying vehicles retain their current height when teleporting
