### ISSUE TITLE
[Effect Suggestion] Table

### ISSUE THREAD

**Issue by CANDICEDICK** [gta-chaos-mod/ChaosModV#2664]
**Name of effect**
Potential name(s) for the effect

Table

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**

- [ x] No duration

**Effect Description**
It spawns a table infront of the player

**Comment by Last0xygen** [comment]
This does not seem like a funny effect. „Quick Sprunk stop“ seems to do something similar though
