### ISSUE TITLE
[Effect Suggestion] Oh No, Our Table

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2665]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
A table drops directly onto the player and deals a great deal of damage. Coded in a way where the table will always hit the player. Only effects the player if outside or on a motorbike (maybe a car) but would be funny imo.

**Comment by Last0xygen** [comment]
So it’s 100% like quick sprunk stop? Lol
Duplicate effect then

**Comment by TerrizX** [comment]
> So it’s 100% like quick sprunk stop? Lol
> Duplicate effect then 

It ain't like sprunk stop at all wdym

**Comment by Last0xygen** [comment]
Ok then it’s like the blue balls effect (in progress)
Also, just meme effects for specific content creators without any additional (funny) turns are not something we’re looking for.
