### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by bhavin2707** [gta-chaos-mod/ChaosModV#2668]
Effect Name : 
**Merryweather Fleet's here bro**

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
This effect will spawn Merryweather fleet around the player or can just turn every ped into Merryweather Fleet. This will be fun as players will have to fight them or flee before they kill the player.

**Comment by Last0xygen** [comment]
Mercenaries is already an effect

**Comment by bhavin2707** [comment]
ohh okay, I am so sorry. My Bad. I will delete this suggestion.
