### ISSUE TITLE
Teleport player a few meters 

### ISSUE THREAD

**Issue by fruitcaketrevor** [gta-chaos-mod/ChaosModV#267]
Turn the effect into a 30 second effect so it teleports the player Every 3 seconds

**Comment by kolyaventuri** [comment]
This could probably be turned into a "Lag Switch" effect. Sorta just. Keep teleporting the player in their direction of movement. Seems less destructive than randomly teleporting the player every few seconds?

**Comment by pongo1231** [comment]
Similar to Teleporter Malfunction or Lag which are already in the mod
