### ISSUE TITLE
[Effect Suggestion] Chad Jesus

### ISSUE THREAD

**Issue by idk-what-name** [gta-chaos-mod/ChaosModV#2670]
**Name of effect**
Chad Jesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns in Jesus with a Railgun/AP Pistol that kills any nearby enemies or anyone you attack

**Comment by Last0xygen** [comment]
Duplicate
