### ISSUE TITLE
[Effect Suggestion] Take Aim

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2671]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description
All peds in player vicinity follow the player with a random gun aimed at the player.

**Comment by Last0xygen** [comment]
Seems like „you’re famous“ with peds aiming at you. I don’t see a real benefit of that or it being a good separate effect, sorry

**Comment by TerrizX** [comment]
> Seems like „you’re famous“ with peds aiming at you. I don’t see a real benefit of that or it being a good separate effect, sorry 

it would look cool and be funny is the benefit pretty much but agree to disagree
