### ISSUE TITLE
[Effect Suggestion] Glitched world

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2673]
**Name of effect**
Glitched world

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Randomises weather, time of day, cars, peds and their behaviour and textures and clothes and if they're animals or not and the colour of the sky, moon, sun. All that nonsense

**Comment by Last0xygen** [comment]
Sounds like the rainbomizer mod lol
