### ISSUE TITLE
[Effect Suggestion] Why Am I Hearing Boss Music?

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2674]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spanws a random enemy with explosive punch, fast run, super jump, max armor and health cheat.

**Comment by Last0xygen** [comment]
Duplicate
