### ISSUE TITLE
[Effect Suggestion] 3 2 1 Go!

### ISSUE THREAD

**Issue by KurgerBing69420** [gta-chaos-mod/ChaosModV#2676]
**Effect Name**
3 2 1 Go!

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Spawn 7 cars in front of player and a crowd of people and if a player is in a vehicle the race will spawn and they keep their car but if they dont it gives them any car in the game

**Comment by Last0xygen** [comment]
This sounds way too complex and doesn’t do anything if the palyer is already in a mission
