### ISSUE TITLE
[Effect Suggestion] Vacation 

### ISSUE THREAD

**Issue by lazyRares** [gta-chaos-mod/ChaosModV#2677]
**Name of effect**
Potential name(s) for the effect
- Vacation

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ]Short
- [ ] No duration

**Effect Description**
the effect would play the cutscene shown when flying to Cayo Perico, then place the player at the Cayo Perico airstrip. After that the player is left to wander until the effect stops.

**Comment by Last0xygen** [comment]
Duplicate.
