### ISSUE TITLE
[Effect Suggestion] RIGGED

### ISSUE THREAD

**Issue by Mafiapug** [gta-chaos-mod/ChaosModV#2678]
**Name of effect**
Rigged, RIGGED,

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Rigged/RIGGED is a new meta effect that lasts for a short period, the voting is continued as normal but the lowest picked option is always applied regardless of percentage. an example being: 
the highest percent voted for is griefer Jesus and the lowest voted is teleport to random location, rigged would the pick random location.

**Comment by Last0xygen** [comment]
Duplicate
