### ISSUE TITLE
[Effect Suggestion] Fake Deep Fried

### ISSUE THREAD

**Issue by Bwazza94** [gta-chaos-mod/ChaosModV#2679]
**Name of effect**
Fake Deep Fried

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
We all love the fake effects so why not fake deep fried, blind us until our eyes adjust then revert it

**Comment by Last0xygen** [comment]
This is basically the effect, isn’t it? 😅

**Comment by Bwazza94** [comment]
It is but it's reversed back

**Comment by kolyaventuri** [comment]
> It is but it's reversed back

Deep-fried is already reverted though. This just sounds like "short deep-fried" which isn't that interesting on its own

**Comment by Bwazza94** [comment]
Fair, thanks regardless
