### ISSUE TITLE
[Effect Suggestion] Flash Steps

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2680]
**Name of effect**
Flash Steps

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Your character (and your vehicle) will constantly teleported forward by a few meters continuously.
This is a double edged sword however. Sometime it can help you in a pinch of avoid getting stuck and move without any input. Most of the time, you have no control to avoid crashing and it might got you into Out of Bonds if you're not careful.

**Comment by Last0xygen** [comment]
„Teleporter malfunction“ has been created. A „force move forward effect“ hast already been implemented in many other ways though
