### ISSUE TITLE
[Effect Suggestion] I Lied (Meta)

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2681]
**Name of effect**
I Lied (Meta)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
For a period of time, all effects shows with different names in the Chaos Player's screen, but it still shows the actual names in the Voting system so people can still vote on the effect. The False name is split into the three pools of Long, Short, and No Duration to make it more convincing to the Chaos Player. Whether the Chaos Player is told that I Lied is active or not is optional, both options are possible.

**Comment by Last0xygen** [comment]
Too similar to „what’s happening“
