### ISSUE TITLE
[Effect Suggestion] Advanced Darkness

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2682]
**Name of effect**
Advanced Darkness

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Pretty much the Anti-thesis of Fullbright. This effect reduced your Brightness, Contrast, and Saturation Settings to 0, creating effect as if the screen is almost completely blank. Hope you can still see things even in this condition.

**Comment by Last0xygen** [comment]
Too similar to „I’m tired“

**Comment by RosyMiranto18** [comment]
Really? But i'm tired leaves some room to see things while this one's effect is more severe.

**Comment by Last0xygen** [comment]
We had some „I’m blind“ effect back then but it kept the player from playing for the full duration of the effect, hence it not being a good effect after all

**Comment by RosyMiranto18** [comment]
Ah, i see, i see. Even though this is not a complete blank like that one, it probably just end up like that too.
