### ISSUE TITLE
[Effect Suggestion] Chop Vision

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2693]
**Name of effect**
Chop Vision

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X]Long
- [ ] Short
- [ ] No duration

**Effect Description**
Puts the player into the perspective of chop just like in the missions. First person, green filter, and most importantly, a very low camera height. You're pretty much in a bumper camera if you're in a vehicle.

**Comment by Last0xygen** [comment]
„Chop vision“ already was an effect which has been removed

**Comment by RosyMiranto18** [comment]
Hm... I see. But can i asked why this effect was removed in the first place?

**Comment by Last0xygen** [comment]
Because it was a „plain boring vision effect“.
Tinting the screen a little green was not a good effect by itself 😅

**Comment by RosyMiranto18** [comment]
Ah okay then, fair enough
