### ISSUE TITLE
[Effect Suggestion] Raining Tacos

### ISSUE THREAD

**Issue by D3DH4CK3R** [gta-chaos-mod/ChaosModV#2700]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Its Raining Tacos

**Comment by Last0xygen** [comment]
Sorry, doesn't sound like a good effect idea, doesn't do anything :/

**Comment by bloodyframe2018** [comment]
he is referencing the raining tacos song from a while back. that became annoying and more and more people started hating it. like rick roll but different
