### ISSUE TITLE
[Effect Suggestion] Teleport To Random Activity

### ISSUE THREAD

**Issue by johndoe717** [gta-chaos-mod/ChaosModV#2710]
**Name of effect**
Teleport To Random Activity

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Similar to Teleport To Random Mission, but teleports the player to a random activity (tennis, golf, yoga, strip club, ect.).

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/871
Please use the search before Creating an new Issue :)
