### ISSUE TITLE
[Effect Suggestion] All Vehicles are Invulnerable

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2712]
**Name of effect**
All Vehicles are Invulnerable

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
You can't blow them up, you can't shoot them,  you can't damage them at all, you can't even shoot the windows and tires, if you want to chase someone, you have to hijack them out of a car. I can't believe nobody thinks of this yet.

**Comment by Last0xygen** [comment]
This already is an effect
