### ISSUE TITLE
[Effect Suggestion] Now This Is Some Tire Poppin' (Remix)

### ISSUE THREAD

**Issue by ReiDaTecnologia** [gta-chaos-mod/ChaosModV#2715]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration
**Effect Description**
Description of the effect; what should it do?
As Now This Is Some Tire Poppin' has a cool beat, i was thinking of a variation (or even change the effect itself) that loop a beat for it
would be cool to hear that :)

**Comment by Last0xygen** [comment]
Requested several times.
Because of pc timing differences this is not something you can easily do, also you’d have to time every pop to be right on the note, which is a lot of work
