### ISSUE TITLE
[Effect Suggestion] random key bind effect 

### ISSUE THREAD

**Issue by Pianoautumn** [gta-chaos-mod/ChaosModV#2718]
**Name of effect**
Potential name(s) for the effect: what's my keybinds again?

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ x] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do? it will randomize the the people key binds for 30 seconds and the person will have to figure out what their keybinds are.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16
