### ISSUE TITLE
[Effect Suggestion] Remove a random wheel

### ISSUE THREAD

**Issue by zndrmn** [gta-chaos-mod/ChaosModV#2719]
**Name of effect**
Potential name(s) for the effect

Remove wheel
Remove random wheel
Remove random wheel from current vehicle
Remove all wheels
Remove all wheels from all vehicles

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; 

This effect should remove one tire from either the current vehicle or from all vehicles. 
A rare version of this effect could remove all wheels off of every vehicle. 
Also "Remove some wheels" could remove a random number of wheels off of all vehicles spawned.

**Comment by anto4440** [comment]
And as such, the legacy continues
