### ISSUE TITLE
Extreme bouncy vehicles

### ISSUE THREAD

**Issue by CANDICEDICK** [gta-chaos-mod/ChaosModV#2720]
**Name of effect**
Potential name(s) for the effect

Xtreme bouncy vehicles

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x ] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

its the bouncy vehicle effect but its launches the player more

**Comment by Last0xygen** [comment]
I think the bouncy vehicle effect is strong enough, as it can launch you over half the map in some situations.
If you need a stronger one you can change it :)
