### ISSUE TITLE
[Effect Suggestion] Ratman

### ISSUE THREAD

**Issue by DBWhale** [gta-chaos-mod/ChaosModV#2723]
**Name of effect**
•Ratman
•I Am Ratman

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Remember that old GTA urban legend of a "Ratman" in the sewers of the game. Let's bring it back. 
This effect spawns a couple of rat NPCs (im thinking maybe 10 or so) which follow the player and act as allies. (They attack those who attack the player). 
The effect ends when all the rats inevitably die.

**Comment by Last0xygen** [comment]
Actually no, never heard of it 😐
I don’t know if there’s a rat NPC, but spawning 10 companions itself is not a good effect idea, sorry

**Comment by DBWhale** [comment]
Danger thought it was a really cool idea. Cool callback too

**Comment by DBWhale** [comment]
Dang*

**Comment by DBWhale** [comment]
You can find out what Ratman is by just looking it up. There are 100s if not 1000s of cringe clickbait YouTube videos on it. 

There are rat NPCs. You can find them in the sewers and I think behind some buildings. 

Heck, spawning 20 of them would be even better. This is Chaos we are talking about things need to get chaotic. 

It would be a bit weird seeing their model morph to accommodate humanoid punching and kicking animations but that makes it better. More chaotic.
