### ISSUE TITLE
[Suggestion] Effect: Nailguns

### ISSUE THREAD

**Issue by kolyaventuri** [gta-chaos-mod/ChaosModV#273]
Bullet hits temporarily freeze the player or pedestrian in place. Much like the former `Time For A Break` effect (see [PlayerBreak.cpp](https://github.com/gta-chaos-mod/ChaosModV/blob/63d8479fd1881a055faa192288ef3a9bbe3386f4/ChaosMod/Effects/db/Player/PlayerBreak.cpp) from f2e1638)

**Comment by TheRealAyCe** [comment]
Maybe same for peds that the player shoots at?

**Comment by kolyaventuri** [comment]
Yeah that's what i was thinking as well, just maybe didn't communicate that clearly 😂

**Comment by TheRealAyCe** [comment]
Oh, you are right, I must have skipped that mentally

**Comment by MoneyWasted** [comment]
I was thinking having the player shoot actual nails and we could also place the [nail gun object](https://forge.plebmasters.de/objects/prop_tool_nailgun?d=eyJzZWFyY2giOiIiLCJwYWdlIjoxLCJmaWx0ZXIiOnsidGFncyI6e30sImRsYyI6W10sInNpemUiOltdLCJjYXRlZ29yeSI6MH0sImNhdGVnb3J5IjowfQ%3D%3D) in the players hand

**Comment by JustTunerYT** [comment]
What i read and think it will do, as you say, is they won't die until effect is passed, like "Peds Are Brainless", but they will freeze in place. And, if someone hits player, he'll also not die until effect passes. You'll still have injuries, so if HP during effect will be below zero, player will be "alive" until effect passes, and only then player will die with "Wasted" screen. I wonder, what will be about explosive weapons...

**Comment by kolyaventuri** [comment]
> I was thinking having the player shoot actual nails and we could also place the [nail gun object](https://forge.plebmasters.de/objects/prop_tool_nailgun?d=eyJzZWFyY2giOiIiLCJwYWdlIjoxLCJmaWx0ZXIiOnsidGFncyI6e30sImRsYyI6W10sInNpemUiOltdLCJjYXRlZ29yeSI6MH0sImNhdGVnb3J5IjowfQ%3D%3D) in the players hand

Oh that's fun, didn't know this was in the game.

> What i read and think it will do, as you say, is they won't die until effect is passed, like "Peds Are Brainless", but they will freeze in place. And, if someone hits player, he'll also not die until effect passes. You'll still have injuries, so if HP during effect will be below zero, player will be "alive" until effect passes, and only then player will die with "Wasted" screen. I wonder, what will be about explosive weapons...

That would be neat, but I was thinking more like, you (or any peds you shoot) are just stuck in place? "Nailed" to the ground until the effect ends.
