### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Aron25746** [gta-chaos-mod/ChaosModV#2732]
**Name of effect**
Fake Fake Teleport

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It’s like fake teleport but after the fake teleports you back to the original location you get sent back to the “fake” teleport location.

**Comment by Last0xygen** [comment]
Duplicate
