### ISSUE TITLE
[Effect Suggestion] 'Teleport to heaven' includes spawning jesus

### ISSUE THREAD

**Issue by Hugo-ejj** [gta-chaos-mod/ChaosModV#2734]
**Name of effect**
'Teleport to heaven' includes spawning jesus (change of existing effect)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The existing effect 'Teleport to heaven' should include spawning jesus (in vehicle if applicable).

**Comment by MoneyWasted** [comment]
Although this aligns with the effect, we are not incorporating any new effects related to "Jesus" at this time, nor are we modifying existing effects to include him.
