### ISSUE TITLE
[Suggestion] Effect: Clear all other active effects.

### ISSUE THREAD

**Issue by Simber1** [gta-chaos-mod/ChaosModV#274]
Was thinking it would be kinda cool to have an effect that clears all other currently active effects.

**Comment by OHSHIET** [comment]
I think that sounds nice as a metaeffect #236

**Comment by Simber1** [comment]
Yeah It'd probably fit there quite nicely.

**Comment by Last0xygen** [comment]
Already implemented as "No Chaos" Meta-Effect
