### ISSUE TITLE
[Effect Suggestion] Pop right tires

### ISSUE THREAD

**Issue by IamNotProgrammer** [gta-chaos-mod/ChaosModV#2740]
Pop right tires

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Pops tires on the right side of the vehicle

**Comment by Last0xygen** [comment]
Already part of „random tire popping“, imo no need for a separate effect
