### ISSUE TITLE
[Effect Suggestion] Addition to Jesus Takes the Wheel

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2743]
**Name of effect**
Addition to Jesus Takes the Wheel 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
In addition to a Panto, Jesus could also spawn taking the Vamos if you aren't driving a vehicle. Why that car specifcially? Because it has a tendency to steer on its own upon any contact with bumps and kerbs. It will be quite peculiar sight to see.

**Comment by DEATHCON1** [comment]
I reckon it should be a fully upraded Deluxo or Speedo Custom. Because they're cars that are favoured by griefers and Jesus is one...

**Comment by RosyMiranto18** [comment]
Dude, Oppressor Mk. Ii is already the car that is favored by Griefer and Extreme Griefer Jesus already use it.

**Comment by DEATHCON1** [comment]
The Oppressor MkII is not eligible for 'Jesus Take The Wheel' because it's a one seater...

**Comment by RosyMiranto18** [comment]
Okay, that one is a good point. You got me.

**Comment by MoneyWasted** [comment]
We are currently not making modifications to any "Jesus" themed effects. Except for bug fixes.
