### ISSUE TITLE
[Effect Suggestion] Automated Voting

### ISSUE THREAD

**Issue by Lavished** [gta-chaos-mod/ChaosModV#2745]
**Name of the effect**
Automated Voting

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
(For Twitch Streams) Viewers will lose the ability to vote, and instead a robot will do it

**Comment by Last0xygen** [comment]
Duplicate
