### ISSUE TITLE
[Effect Suggestion] You have prayed

### ISSUE THREAD

**Issue by shahar654** [gta-chaos-mod/ChaosModV#2748]
-->

**Name of effect**
You have prayed/ Nice jesus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X ] No duration

**Effect Description**
Spawns Jesus as a companion and will shoot enemies. Instead of a railgun, he will be given a carbine rifle because a railgun is too OP.

**Comment by Last0xygen** [comment]
Duplicate
