### ISSUE TITLE
Suggestion: Gustavo

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#275]
Putting this here so I don't forget to add it.

Display a mission failed screen similar to Fake Death, but the reason is 'Gustavo Mota died' and actually fail the mission/kill the player. Reference to DVAU's ohko and pacifist issues on Raiding the Bureau with Gustavo dying

**Comment by TheRealAyCe** [comment]
I think it's fine as a "Fake Death" message instead of "Keep Playing", while not actually failing the player. But it may be too niche of a reference anyway.

**Comment by ProfessorBiddle** [comment]
You're probably right. Making it a possible message in 'Fake Death' would work great.

**Comment by Last0xygen** [comment]
Already available via "Fake Death", adding "Gustavo Mota died" doesn't really add anything
