### ISSUE TITLE
[Effect Suggestion] Teleport to Church

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2750]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports player outside the church with a very thin to almost impssible chance everytime this effect is chosen that Griefer Jesus spawns too at the church (not stated in the effect title obviously).

**Comment by ReiDaTecnologia** [comment]
Or you could "Teleport To Jesus" ¯\_(ツ)_/¯
(Jesus spawn at Del Perro Pier)

**Comment by Taylor3621** [comment]
> Or you could "Teleport To Jesus" ¯_(ツ)_/¯ (Jesus spawn at Del Perro Pier)

Now that's a fun idea. Besides, the pier would provide a teleport point that's not inconvenient, and a fair distance away from the existing points.

**Comment by MoneyWasted** [comment]
We are currently not adding "player teleportation" effects. (We have enough already.)
