### ISSUE TITLE
[Effect Suggestion] Jesus Saves

### ISSUE THREAD

**Issue by CrimsonTemplar** [gta-chaos-mod/ChaosModV#2751]
**Name of effect**
Jesus Saves (U Save)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
(Apolgies if duplicate. I went through everything Jesus related and couldn't find this).

Saves the game or gives player the option to save their game. A reference to the early top down GTA series.

**Comment by Last0xygen** [comment]
This wouldn’t really work. During missions you can’t save at any point and the save before the mission is already set.
I don’t see, what this effect would accomplish, if autosave is on
