### ISSUE TITLE
[Effect Suggestion] Whale Gun

### ISSUE THREAD

**Issue by DBWhale** [gta-chaos-mod/ChaosModV#2755]
**Name of effect**
•Whale Gun
•Whalo Gun

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Similar to the catto gun effect but more chaotic with the aid of larger mammals.

**Comment by MoneyWasted** [comment]
Too many issues would arise from using large peds.
