### ISSUE TITLE
[Effect Suggestion] Bonzi Buddy 

### ISSUE THREAD

**Issue by rayford79** [gta-chaos-mod/ChaosModV#2756]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect;           Bonzi Buddy will appear on screen and try to annoy the player by swinging in and grabbing stuff on the screen and moving it somewhere random on screen such as the hud, ui or maybe even vehicles or players. Bonzi Buddy should also occasionally make the player pull over to listen to a dumb knock knock joke.

**Comment by Last0xygen** [comment]
This is a separate program and should not be part of the chaos mod
