### ISSUE TITLE
[Effect Suggestion] Hacks

### ISSUE THREAD

**Issue by Mikiboy123** [gta-chaos-mod/ChaosModV#2764]
**Name of effect**
Obtain hacks

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Phase through obstacles ,that's about it

**Comment by Last0xygen** [comment]
duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/243
