### ISSUE TITLE
[Effect Suggestion] Repel All

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#2770]
**Name of effect**
Repel All

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
All the damages you influcted. Punch, runovers, guns, you will be one receiving the damage instead of the intended target... And perhaps the same can also work with the enemies.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/404
