### ISSUE TITLE
[Effect Suggestion] Better safe then sorry

### ISSUE THREAD

**Issue by DrFl4m1ng0** [gta-chaos-mod/ChaosModV#2776]
**Name of effect**
Better safe then sorry

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Forces the player to do a quick save

**Comment by Last0xygen** [comment]
Duplicate 
https://github.com/gta-chaos-mod/ChaosModV/issues/792
