### ISSUE TITLE
[Feature Suggestion] Addition to Simeon Says/addition to more simeon says sayings 

### ISSUE THREAD

**Issue by Pianoautumn** [gta-chaos-mod/ChaosModV#2783]
**Is your feature request related to a problem? Please describe.**
not exactly 

**Describe the solution you'd like**
so in Addition to Simeon Says  make one say simeon says press f or press f to make someone leave their vehicle 

**Describe alternatives you've considered**
ive considered making suggestion a new affect player leaves vehicle but that already exists so i feel like this would be more funny 

**Additional context**
sorry if this is already a suggestion or a bad idea i did some searching and couldnt find anything

**Comment by Last0xygen** [comment]
The problem is that keybinds can be remapped, it doesn’t have to be „f“ (I.e. using a controller).
Naming it so it would be universally understood would be a big challenge and not easy to read quick
