### ISSUE TITLE
[Effect Suggestion] who's there?

### ISSUE THREAD

**Issue by bloodyframe2018** [gta-chaos-mod/ChaosModV#2784]
add the classic convincing knocking sound effects to the game if possible and make it so the effect name appears a couple of seconds later after convincing knocking sound effects played one time.

**Comment by MoneyWasted** [comment]
Effects that only play sounds should be avoided. Especially ones that require custom audios. This is more of an effect that should be handled by the user themselves using custom sound triggers.
