### ISSUE TITLE
[Effect Suggestion] Ye-Ye Ass Haircut

### ISSUE THREAD

**Issue by Col598** [gta-chaos-mod/ChaosModV#2788]
**Name of effect**
Potential name(s) for the effect
Ye-Ye Ass Haircut
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
This effect will randomize what the player's hairuct is.

**Comment by Last0xygen** [comment]
Already part of „randomize player clothes“
