### ISSUE TITLE
[Feature Suggestion] Modification to Fake Crash

### ISSUE THREAD

**Issue by BoBogus** [gta-chaos-mod/ChaosModV#2792]
**Is your feature request related to a problem? Please describe.**
One thing that seems to give away fake crashes is the fact that no effect name appears at all.  In reality (like on several of DarkViperAU's streams), some other effect happens and immediately locks the game up (after the correct effect name is shown) and then the game crashes.

**Describe the solution you'd like**
What I would recommend is some other effect name to appear just as the screen freezes, before changing to "Fake Crash" as the screen unfreezes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Last0xygen** [comment]
Already suggested several times
