### ISSUE TITLE
[Effect Suggestion] Anger Management 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2800]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Player character punches any ped near them.

**Comment by Last0xygen** [comment]
I don’t get it..? So the player loses control why the character starts punching peds? Sounds like an aggressive version of „Autopilot“, I don’t think this is something we’re looking for
