### ISSUE TITLE
[Effect Suggestion] Spawn Random Casino Game

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#2801]
**Name of effect**
Spawn Random Casino Game

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns either a random Slot Machine, a BlackJack Table with a random table worker npc working it or a Three Card Poker Table with a random table worker npc working it next to the player. Instead of chips, you'll use in-game money amounts equivalent to the amount of chips you can use on them.

**Comment by OnlyRealNubs** [comment]
Tbh, this sounds more like a full on standalone mod. It would be a lot of work to remake casino games for an effect. It would probably be better to just make it spawn the table and the npc, with no actual games or betting involved. 

If your are looking for casino recreated for single player, I recommend checking out this mod: https://www.gta5-mods.com/scripts/diamond-casino-resort-business
