### ISSUE TITLE
[Effect Suggestion] Everyone is a monkey

### ISSUE THREAD

**Issue by CANDICEDICK** [gta-chaos-mod/ChaosModV#2803]
**Everyone is monkey**
Potential name(s) for the effect
reverse evolution

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Turns everyone into a monkey

**Comment by OnlyRealNubs** [comment]
This could be possible for peds other than the player. But like Last0xygene [said](https://github.com/gta-chaos-mod/ChaosModV/issues/2772#issuecomment-1073062984). Replacing the player ped is to error prone.
