### ISSUE TITLE
[Effect Suggestion] Animal%

### ISSUE THREAD

**Issue by JesusofNazareth69** [gta-chaos-mod/ChaosModV#2804]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

An effect called animal% wildlife% or Zootopia or something like that idk that would transform everyone (player and peds) into a random animal (whale, dog, bird, etc)

**Comment by Last0xygen** [comment]
Duplicate
