### ISSUE TITLE
[Effect Suggestion] It's raining peds

### ISSUE THREAD

**Issue by kjsdafbreh** [gta-chaos-mod/ChaosModV#2820]
**Its raining peds**

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Random peds spawn in the air above the player and fall to the ground. Similar to whale rain, but the peds should survive the fall.
Especially funny when combined with effects such as peds attack player, explosive peds or all peds are cops.

**Comment by Last0xygen** [comment]
Duplicate
