### ISSUE TITLE
[Bug] Using the mouse nullifies 'Disable Random Direction'

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2822]
**Describe the bug**
When 'Disable Random Direction' is applied, holding down M1 and turning with the mouse nullifies it. I can move any direction using a mouse.

**To Reproduce**
Have 'Disable Random Direction' applied. 
Find out what direction is disabled.
Hold down your primary mouse button and keep on enjoying life.

**Comment by Last0xygen** [comment]
Can't reproduce. I keep firing but explode instantly for failing Simeon

**Comment by anto4440** [comment]
> Can't reproduce. I keep firing but explode instantly for failing Simeon

What??? Simeon is not a part of this. how can it be more obvious that im reffering to 'Disable Random Direction?'

**Comment by Last0xygen** [comment]
Ok, misread lol

**Comment by Last0xygen** [comment]
And now that im using 'Disable Random Direction' i still can't reproduce it.
If left is disabled and i hold my left mouse button i still can't walk left

**Comment by ReiDaTecnologia** [comment]
Strange, i just tested it and i can turn left with left disabled when the option "Default Mouse Driving Control" is set to "Camera" and i hold Left mouse button and move my mouse to left.
