### ISSUE TITLE
[Feature Suggestion] Enabled/Total number of effects in config app

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#2827]
I decided to complete story mode with one random effect chosen by AI. The problem is that i have to count effects by myself, which is painful

Add counter of enabled effects and total number of effects. Same for all categories.

Example of how it should look like. 
![exmp](https://user-images.githubusercontent.com/63610557/162757156-3fce0c1a-887f-4d1e-9a10-64db41d71793.png)

**Comment by JustTunerYT** [comment]
This probably exists in GTA:SA Chaos Mod, if i remember right

**Comment by JustTunerYT** [comment]
Found it. Yeah, it should something like this 
![image](https://user-images.githubusercontent.com/63610557/162757854-03c62416-bf21-4213-94e1-666d6d4126dc.png)

**Comment by OnlyRealNubs** [comment]
I think this could be a useful feature. Just to show how many effects. Wait to see what others think.
