### ISSUE TITLE
[Bug]? Peds are way too accurate when "Peds drive-by player"

### ISSUE THREAD

**Issue by pavlvs327** [gta-chaos-mod/ChaosModV#283]
I think it ruins a lot of the fun of the "peds drive-by player" effect that peds have essentially perfect aim and end up killing the player very fast. It would be more dramatic for there to be a constant hail of bullets from all directions than a few bullets perfectly hitting the player and killing them quickly.

**Comment by pongo1231** [comment]
That is true. Was afraid the effect would be too harmless so I gave the peds really high accuracy when I originally created it and simply never touched it again. Will adjust it in the next update.
