### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Pianoautumn** [gta-chaos-mod/ChaosModV#2831]
**Name of effect** time for a break
Potential name(s) for the effect
break time 
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
this effect has existed idk if it still is but it makes it so the player cant move aka break time idk if that kinda relates to Simeon says but seems like it was a good effect

**Comment by OnlyRealNubs** [comment]
Can you please provide a more detailed description of the effect? And please make sure to fill in the missing fields.

**Comment by Last0xygen** [comment]
it was called "Take a break" or something and was removed as it just stops the player from interacting at all which is not an effect idea we're looking for
