### ISSUE TITLE
[Effect Suggestion] I Am But A Host

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2836]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Player model is autopiloted and kills one ped closest to them with only the weapon the player has at the time the effect is chosen. If done before the effect is over, the player remains still.

**Comment by OnlyRealNubs** [comment]
We already have effects like `Aimbot` which do practically the same thing.

**Comment by TerrizX** [comment]
> We already have effects like `Aimbot` which do practically the same

Doesn't Aimbot make you shoot peds with 100% accuracy? That's different, maybe you could say what I suggested is basically what Autopilot does, sure but I thought this effect would be unique in that the player doesn't just kill enemies but any one person next to them, whether thats a random ped or a story character.
