### ISSUE TITLE
[Bug] Nerf Gravity Sphere and Doomsday

### ISSUE THREAD

**Issue by Powercube7** [gta-chaos-mod/ChaosModV#2839]
**Describe the bug**
Gravity Sphere and Doomsday often crash my game due to the abundance of objects on screen 

**To Reproduce**
Lowest possible graphics settings and an average system (1050Ti and intel core i5 8th gen)

**Crash Dump (if a game crash)**
[crashes.zip](https://github.com/gta-chaos-mod/ChaosModV/files/8489129/crashes.zip)

**Further Notes**
The effects don't crash the game every time (doomsday at least), they just do it very often

**Comment by pongo1231** [comment]
Already fixed by 173d6b0b4ac944f839174fd3f77d89722693ece9

**Comment by OnlyRealNubs** [comment]
It's neither. It will be included in the next beta release. If you want it now, you can clone the repository, and build it. More instructions can be found [here](https://github.com/gta-chaos-mod/ChaosModV/blob/master/README.md).
