### ISSUE TITLE
[Effect Suggestion] Teleport to WADEpoint

### ISSUE THREAD

**Issue by partoftheworlD** [gta-chaos-mod/ChaosModV#2843]
**Name of effect**
Teleport to WADEpoint

- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Teleport a player to Wade if exists, or create Wade at a random location and teleport the player to it.

**Comment by OnlyRealNubs** [comment]
Please give more details.

**Comment by anto4440** [comment]
> Please give more details.

If a ped with the Wade character model exists, teleport player to Wade (this likely will do basically nothing, as Wade is rarely loaded in and when he is, he is close to the player), or if no Wade exists, spawn one at a random location (as widely possible), and teleport the player to him.

**Comment by MoneyWasted** [comment]
Would only make sense in a very small number of cases. Otherwise, this would just become another teleport/ped  spawn effect.
