### ISSUE TITLE
[Effect Suggestion] Fake FAKE Death

### ISSUE THREAD

**Issue by AnimaSo1a** [gta-chaos-mod/ChaosModV#2844]
**Name of effect**
Fake FAKE Death

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It'll play the normal fake death/suicide effect, tricking the player then maybe 5 seconds later, the vehicle will actually explode or the character will really commit suicide.

**Comment by Last0xygen** [comment]
Already requested several times
