### ISSUE TITLE
[Effect Suggestion] Wrestling Match

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2847]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
All peds lunge themselves towards each other and fight each other bare fists only till the effect is over.

**Comment by OnlyRealNubs** [comment]
There is an effect called « All peds riot » Which is the same thing.

**Comment by TerrizX** [comment]
> There is an effect called « All peds riot » Which is the same thing.

fair nuff
