### ISSUE TITLE
[Effect Suggestion] Fake mission pass

### ISSUE THREAD

**Issue by SimonDiamond** [gta-chaos-mod/ChaosModV#2853]
**Fake Mission Pass**
Potential name(s) for the effect

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Similar to the Fake Mission Pass in the San Andreas Chaos Mod, when this effect gets activated, the mission gets cancelled and with it comes a mission pass screen, but, when you re enter the mission, the same mission that was supposedly passed gets started again. (Here is the SA version of it in action: https://youtu.be/HdAeLYERAw8?t=87)

Although, to actually trick people into believing it, you might also implement a real mission pass to it.

**Comment by OnlyRealNubs** [comment]
What if the player isn’t in a mission?

**Comment by SimonDiamond** [comment]
Then either replace it with Nothing or make it so that it only appears in a mission

**Comment by Last0xygen** [comment]
Im pretty certain „mission pass“ and „fake mission pass“ have already been suggested
