### ISSUE TITLE
[Effect Suggestion] Updated Fake crash

### ISSUE THREAD

**Issue by begoade** [gta-chaos-mod/ChaosModV#2854]
when a fake crash occurs, have a fake effect play; that is likely to crash the game, for a few seconds, before actually fake crashing to make a fake crash more believable

**Comment by ReiDaTecnologia** [comment]
https://github.com/gta-chaos-mod/ChaosModV/pull/2850
it is already being enhanced :p

**Comment by Last0xygen** [comment]
Yup, also duplicate
