### ISSUE TITLE
[Feature Suggestion] My Neat Feature

### ISSUE THREAD

**Issue by Viktor02334** [gta-chaos-mod/ChaosModV#2855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Viktor02334** [comment]
Discord can control effects like twitch,it would be awesome if my friends could control it without steaming it on twitch! :)

**Comment by Last0xygen** [comment]
Please use the first post to show what you want, not as an additional comment.

also this is already possible. Just use the streamvoting but show your game on discord. Your friends can vote via your twitch chat without you going live.
Voting via discord has already been requested several times and is already been worked on
