### ISSUE TITLE
[Effect Suggestion] Drone

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2858]
**Name of effect**
Drone

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Does multiple things:
1: Fully heals the player and give full armor. The armour should be multiplied by x3 for balance reasons.
2: The player becomes unable to use any weapons or move around: He will just become stuck in place. 
3: A ped with an assount rifle will spawn at an elevated height, and this peds X and Z coordinates is directly changed by the WASD keys. The ped a an ally to the player, and will hopefully shoot at enemies while the player has to position him. He is invulnurable. 

**Notes**
If the player is in a car while the effect is chosen, the same thing will happen but with a four person car filled with NPC's, that have 'micro smg'. The car and the NPC's are still invulnurable, although the vehicle the player is in does not get repaired or recieve extra hitpoints.

**Comment by OnlyRealNubs** [comment]
This is just another instance where we just take away control from the player (which isn't what we are looking for). It also spawns an enemy to attack the player, when the player is defense less.
