### ISSUE TITLE
[Effect Suggestion] Lodestone

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2863]
**Name of effect**
Lodestone / Magnetizing Tears

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Any vehicle or Ped the player hit with a ranged weapon will have a HIGLY WEAKENED force field effect attached. The player is unaffected by the magnets. The effect does not stack.

**Comment by Last0xygen** [comment]
tbh this would be pretty intense on the pc, if you have to check dozens of entities and apply hundreds of gravity forces :/ sorry

**Comment by anto4440** [comment]
> tbh this would be pretty intense on the pc, if you have to check dozens of entities and apply hundreds of gravity forces :/ sorry

Then buy a better PC, the poor man should not be interfering with my life (this is a joke, I totally get that)
