### ISSUE TITLE
[Effect Suggestion] Spawn Justice League

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2865]
**Name of effect**
Spawns justice league 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Spawn a black van with Griefer Jesus, Space Ranger, Angry Alien and Deadly Agent. Once they get close enough they will exit the van and would attack the player

**Comment by anto4440** [comment]
How about you make this one of the SUVs with two mountes guns attached? Then they are more of an active threat

**Comment by Last0xygen** [comment]
Similar effects have already been requested several times
