### ISSUE TITLE
[Effect Suggestion] Limited bullets

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2867]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
When effect is applied, a random number between 1 and 100 is pulled. This number is then shown on screen. During the effect, the player is not able to fire any more bullets than the number drawn. Ammo is unaffected.

**Comment by Last0xygen** [comment]
IMHO "One Bullet Magazines" is a sufficient version of this kind of effect
