### ISSUE TITLE
[Effect Suggestion] Equality (again)

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2869]
**Name of effect**
Equality

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Makes all entities WEIGH the same.

**Comment by Last0xygen** [comment]
Too little of an effect, which hasn’t already been set by „low gravity“, „very low gravity“ or „invert gravity“
