### ISSUE TITLE
[Effect Suggestion] Turn of events

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2870]
**Name of effect**
Turn of events

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Completely flips the players position in relationship to the waypoint (objective if there is no waypoint)

**Comment by Last0xygen** [comment]
So tp To the other side of the WP?
This would often result in teleports on top of buildings, water/ocean or no teleport at all if no waypoint/objective

**Comment by anto4440** [comment]
So? I mean, it has happened before. Its still unpredicatble.
