### ISSUE TITLE
[Effect Suggestion] Deaths List

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2871]
**Name of effect**
Deaths List

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
A random NPC (if enemies are loaded in, it will be enemies, allies can never be affected) will be 'marked for death', his blip on the map will be made larger and so will his character model. When killed, the player will heal 50% HP and get a full clip, this does not deplete ammo supply. When the marked for death NPC dies, a new one will be marked.

**Note**
If the player kills someone who is not MFD, the mark disappears for five seconds.

**Comment by Last0xygen** [comment]
Something similar has already been requested

**Comment by anto4440** [comment]
> Something similar has already been requested

Do please show me the duplicate :-)

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/194
