### ISSUE TITLE
[Effect Suggestion] Midas Shot

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#2872]
**Name of effect**
Midas Shot

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Does the 'Midas Touch' effect to any entitity that gets shot (by player)
All weapons get goldified

**Comment by OnlyRealNubs** [comment]
Like you said, very similar to the "Midas Touch" effect. There would be no reason to add it as an additional effect. It would make more sense to add it to the already existing "Midas Touch" effect.

**Comment by Last0xygen** [comment]
> Like you said, very similar to the "Midas Touch" effect. There would be no reason to add it as an additional effect. It would make more sense to add it to the already existing "Midas Touch" effect.

but it doesn't make "sense" to add it as thats not how "midas touch" works 😅 
But i do agree on the other stuff
