### ISSUE TITLE
kamikaze

### ISSUE THREAD

**Issue by lawand69** [gta-chaos-mod/ChaosModV#2879]
**Name of effect**
kamikaze

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
makes jets fall from the sky at a certain angle near the player (you can also make a bonus by adding cannon firing while they are nose-diving)

**Comment by AshtonGoBoom** [comment]
Reminds me of the Airstrike effect and I think this is a good idea, but I think it would be hard to make the planes land near the player

**Comment by gaseet** [comment]
Maybe replicate the vehicle rain but only with jets?

**Comment by casperge** [comment]
https://github.com/gta-chaos-mod/ChaosModV/pull/2550
