### ISSUE TITLE
[Effect Suggestion] Teleport to Mount Gordo/Ghost

### ISSUE THREAD

**Issue by AshtonGoBoom** [gta-chaos-mod/ChaosModV#2881]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

Effect Description
Teleports the Player to the location where Jolene Cranley-Evans spawns on Mount Gordo and maybe even change the time to when She spawns (between 23:00 and 00:00)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2408
Please use the search before creating new suggestions
