### ISSUE TITLE
[Effect Suggestion] Allow Griefer Jesus to Walk on Water

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#2882]
Ive seen Griefer Jesus get spawned while the player is in the ocean a lot and hes pretty much useless when he does 

And thought it might be worth allowing him to walk on water to make him more annoying and, well it def suits him lol

**Comment by Last0xygen** [comment]
Duplicate 
https://github.com/gta-chaos-mod/ChaosModV/issues/1311
#2293 
#823
