### ISSUE TITLE
[Effect Suggestion] Propped 

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#2885]
**Name of effect**
Prophunt

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
 Makes everyone invisible and it would place a random prop making it so the player looks like a prop

**Comment by FAR95d** [comment]
Dont worry the player still moves we already have an effect for it (Its time for a break) but basically it makes the player a prop

**Comment by Last0xygen** [comment]
„Replacing“ all peds with props is already an effect
https://github.com/gta-chaos-mod/ChaosModV/pull/2274
„it’s time for a break“ has been removed for a long time 😅

**Comment by FAR95d** [comment]
And to make it maybe more chaotic. Make it so that the props can clip. That would mean the player sometimes can't move into tight spaces. But would be able to if the prop was tiny

**Comment by FAR95d** [comment]
> „Replacing“ all peds with props is already an effect
> https://github.com/gta-chaos-mod/ChaosModV/pull/2274
> „it’s time for a break“ has been removed for a long time 😅

Ah but this one may also "turn" the player into a mobile prop
