### ISSUE TITLE
[Effect Suggestion] Spawn Angry Fan Cats 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2891]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Maybe a very slim chance that when Spawn Fan Cats is picked that it spawns cats with cougar behaviours that immediately attack the player.

**Comment by Numi43** [comment]
Better would be if Spawn Fan Cats had a slim chance of spawning 3 cougars. And they attack player. Afterall, cougars ARE (big) cats.

**Comment by TerrizX** [comment]
True, its just that seeing a cat attacking them like a cougar would really mess with the player
