### ISSUE TITLE
[Effect Suggestion] Super Jump x10 / Fast Run x10

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#2892]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Player runs way faster and jumps alot higher (like crazzyy high) with fast run and super jump cheats. The player is invincible too to counterract them dying when they jump in open air.

**Comment by MoneyWasted** [comment]
Both of these already exist as effects. Wouldn't make sense to combine them to make another effect.
