### ISSUE TITLE
[Effect Suggestion] Solid props

### ISSUE THREAD

**Issue by Kristof-30** [gta-chaos-mod/ChaosModV#2895]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X ] Long
- [ ] Short
- [ ] No duration

**Effect Description**
All fences, street lights etc. that can be easily destroyed by driving at high speed to and any other means, will be heavy as wall and undestroyable.

**Comment by ReiDaTecnologia** [comment]
hey that is a pretty unique suggestion!
_LaxyOxygen procedes to say this is a duplicate_ xD

**Comment by Last0xygen** [comment]
Sounds like https://github.com/gta-chaos-mod/ChaosModV/issues/581 🤔
