### ISSUE TITLE
[Effect Suggestion] Hacker

### ISSUE THREAD

**Issue by Hulk3421** [gta-chaos-mod/ChaosModV#290]
**Name of effect**
Hacker

**Effect Description**
Player has no Control of his Character, until he solves a Hack. 
There are quite a few different Hacking minigames in the Game, the effect could choose one randomly, so the player has to do a different Hack everytime.

**Comment by JustTunerYT** [comment]
The hacks are from GTAO heist missions, i suppose?

**Comment by Hulk3421** [comment]
Not only (but mostly) heists from GTAO. There are some other events where hacks occur (in SP too, i think). But basically Yes.

**Comment by pongo1231** [comment]
Already exists (effect name is `Realistic Hacking`). Currently it's always the same hack but adding more to it should be possible in the future.
