### ISSUE TITLE
[Feature Suggestion] If the Twitch popular vote loses, the dice should be rolled a second time

### ISSUE THREAD

**Issue by Fireheart318** [gta-chaos-mod/ChaosModV#2905]
Problem - With Twitch voting integration, it can be quite frustrating to have a 99% vote lose to a 1% vote randomly.

Solution - If the most popular vote loses, the dice should be re-rolled once before selecting an effect, effectively doubling the popular vote’s chance at winning.
This should be an option in the settings, not just this or no proportional voting.

**Comment by OnlyRealNubs** [comment]
There are 2 different modes for voting: Proportional and Majority.

#### Proportional:
Votes have % chance of happening when % of people vote for that effect

#### Majority:
Votes are decide by which effect has the most % of people that voted for it.

**Comment by Last0xygen** [comment]
I don’t think this would be a good change.
Where do you draw the line?
26 vs 25 vs 25 vs 24 too?
Every effect has a chance to be picked, „get over it“ lol.
If the streamer doesn’t want the „popular vote“ to lose all he has to do is disable proportional voting.
Yeah, CAN be „frustrating“ for viewers but also be more surprising / fulfilling if it happens then ;P
