### ISSUE TITLE
[Effect Suggestion] Full screen mini map

### ISSUE THREAD

**Issue by NinBendo1** [gta-chaos-mod/ChaosModV#2908]
An effect where the mini map becomes the entire screen and you can only exclusively see the mini map, so you have to navigate via that alone. 

No idea if the mini map would stay low resolution and/or be stretched to fill the screen. Also, the effect should be 30 seconds long

**Comment by MoneyWasted** [comment]
According to @Goorakh this will be able to be added. I'll approved so that one of the contributors can work on at some point.

**Comment by NinBendo1** [comment]
Thank you so much for adding my suggestion!!
