### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by elcryptix** [gta-chaos-mod/ChaosModV#2909]
**Name of effect**
extreme fake crash

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
same as fake crash but it also minimises the game

**Comment by OnlyRealNubs** [comment]
Already suggested/implemented.

**Comment by Last0xygen** [comment]
Duplicate
