### ISSUE TITLE
[Effect Suggestion] Randomize Controll

### ISSUE THREAD

**Issue by Hulk3421** [gta-chaos-mod/ChaosModV#291]
**Name of effect**
Randomized Control

**Duration**
1 Minute?

**Effect Description**
Randomly change W, A, S, D and  Spacebar (maybe even multiple times during the effect, like every 20 seconds?)

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16

**Comment by Hulk3421** [comment]
Kinda, but I think its different enough, to be its own effect

**Comment by Terrain2** [comment]
so kinda like "Drunk" but much worse? Make it also fuck with your phone and enter UIs (like a shop) and spend money (so, also randomize arrow keys, enter, backspace, E, F, Q, pretty much all controls except for pause game i'd say) and reduce the time to short
