### ISSUE TITLE
[Effect Suggestion] Fake Crash V2

### ISSUE THREAD

**Issue by LelandDev** [gta-chaos-mod/ChaosModV#2910]
**Fake Crash**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X ] No duration

**Effect Description**
When Fake Crash is applied, freeze screen for a few seconds, then minimize the window. Would be impossible to tell apart from a real crash

**Comment by Last0xygen** [comment]
Everything has been already suggested, please use the search before creating a suggestion
