### ISSUE TITLE
[Effect Suggestion] Random Language

### ISSUE THREAD

**Issue by proffissionalgamer** [gta-chaos-mod/ChaosModV#2913]
This effect will switch the game to a random language (There are 13 of them in total: English, German, French, Italian, Korean, Spanish - Spain, Simplified Chinese, Traditional Chinese, Russian, Japanese, Polish, Portuguese, Spanish - Latin America

After the effect is finished, the game automatically switches to the language you previously played

Long Effect

(I know that this effect is probably meaningless)

**Comment by OnlyRealNubs** [comment]
I like this. I had plans of doing something like this, but never got around to it.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2465

**Comment by proffissionalgamer** [comment]
> Duplicate #2465

So will this effect be in game?

**Comment by OnlyRealNubs** [comment]
> > Duplicate #2465
> 
> So will this effect be in game?

That just means that this effect has already be suggested. Please be sure to check for duplicates next time.

**Comment by Last0xygen** [comment]
Maybe at some point, if someone takes it and developes it :)
If you want to contribute you’re more than welcome to code it and create a PR :)
