### ISSUE TITLE
[Effect Suggestion] Teleport Everyone Else Into Random Vehicle

### ISSUE THREAD

**Issue by MicaLovesKPOP** [gta-chaos-mod/ChaosModV#2981]
**Name of effect**
Teleport Everyone Else Into Random Vehicle

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports everyone but the player into random pre-existing vehicle seats. Peds already in vehicle seats get teleported into different vehicles/seats as well. Includes friends&foes.

If possible/feasible, try to keep mission peds somewhat close due to fail conditions in missions.

**Comment by Last0xygen** [comment]
i don't think this would be a necessary or good addition to the current randomize vehicle seat effect
