### ISSUE TITLE
[Feature Suggestion] Jesus can't swim, walks on water

### ISSUE THREAD

**Issue by MicaLovesKPOP** [gta-chaos-mod/ChaosModV#2982]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For realism sake, I want the Jesus ped model to never swim, but instead walk on water. This would work for all Jesus effects, as well as naturally spawning Jesus ped models.

**Describe alternatives you've considered**
N/A

**Additional context**
I don't know for sure if this isn't the case already, but was unable to find it mentioned anywhere.

**Comment by Last0xygen** [comment]
Duplicate
* https://github.com/gta-chaos-mod/ChaosModV/issues/2882
* https://github.com/gta-chaos-mod/ChaosModV/issues/1311
* #2293 
* #823
* ...
