### ISSUE TITLE
[Effect Suggestion] Red Light District

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3002]
**Name of effect**
Traffic Light District

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Turn all traffic lights to be stuck at either red or green. If it's stuck on right, go past it and you get +1 Wanted Level each.

**Comment by OnlyRealNubs** [comment]
#2582 duplicate
