### ISSUE TITLE
[Feature Suggestion] Killing Jesus gives wanted level

### ISSUE THREAD

**Issue by IamNotProgrammer** [gta-chaos-mod/ChaosModV#3017]
Whenever either Griefer Jesus or Jesus take the wheel is spawned player can kill our Lord and Savior without any consequences. I think it would be interesting to give player some wanted level for such sin and gives Jesus possibility to screw player even after death

**Comment by MoneyWasted** [comment]
We are currently not making modifications to any "Jesus" themed effects. Except for bug fixes.
