### ISSUE TITLE
[Meta-Effect Suggestion] Effects are [[Amount of times]] stronger

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#3026]
- [ ] Long
- [X] Short
- [ ] No duration

Effects, like "Invert Current Velocity", "Speed boost", "Forcefield" and "I'm too tired" have multiplied force, chance and maybe duration.
Let me bring up some examples. 
"Beyblades": When originally they spin horisontally, with this meta they will spin vertically and faster
"I'm too tired":Player will ragdoll more often and the eyes closing effects is faster, ragdoll is longer
"Whose phone is ringing?":More ringtones at once for a pedestrian, player's calling tones are longer
"On-Demand TV":More screens at once and different apart

**Comment by Last0xygen** [comment]
Basically https://github.com/gta-chaos-mod/ChaosModV/pull/2257
But has been requested several times already

**Comment by JustTunerYT** [comment]
@Last0xygen that cannot be right. I looked through searching, none was similar to this one

**Comment by OnlyRealNubs** [comment]
> @Last0xygen that cannot be right. I looked through searching, none was similar to this one

He literally just linked it.

**Comment by JustTunerYT** [comment]
> > @Last0xygen that cannot be right. I looked through searching, none was similar to this one
> 
> He literally just linked it.

That i saw, yeah. I'm referring to the amount of requests

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/2417 at least, but there were others 🤔
