### ISSUE TITLE
[Effect Suggestion] Get Helicopter'd/Jesus Stole My Boat

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3036]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [] Long
- [ ] Short
- [X] No duration

**Effect Description**
Two seperate effects, basically Jesus Take The Wheel but Jesus spawns in a heliocpter and a boat too.

**Comment by MoneyWasted** [comment]
We are currently not adding or modifying any "Jesus" themed effects.
