### ISSUE TITLE
[Effect Suggestion] Spawn Car Crash 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3049]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Spawns two cars that collide at high speeds in front of the player.

**Comment by Last0xygen** [comment]
Happens all the time already 🤪 seriously though, would be a huge problem in building or something, don’t know how to tackle this there.
Thanks for suggesting anyways
