### ISSUE TITLE
[Bug] Mod Crash On SHV Reload (SC Only)

### ISSUE THREAD

**Issue by OnlyRealNubs** [gta-chaos-mod/ChaosModV#3052]
**Describe the bug**
ChaosMod crashes when `scriptUnregister` is called on SocialClub versions. 

**To Reproduce**
- Have the SocialClub version of the game.
- Have the latest version of ChaosMod. From gta5-mods.com or a build from the repo.
- Put “ScriptHookV.dev” in the game directory.
- Press CTRL-R to Hot-Reload ScriptHookV.
- Press it again to see that ChaosMod doesn’t reload.

#
As far as I know, this only happens on the SC version of the game.

**Comment by pongo1231** [comment]
I am going to assume this doesn't happen anymore, otherwise feel free to reopen

**Comment by OnlyRealNubs** [comment]
This still occurs even a few months later. It only appears to happen on the RGL version of the game. It doesn’t really « crash ». It just fails to unload properly when you hit CTRL + R. Resulting in it not loading back up. When you close the game Scripthook gives you an error dialog. I will try and find a screen shot.

**Comment by OnlyRealNubs** [comment]
After further looking, im going to rule out the possibility that it is the SHV for MinGW that is causing the issues. I made a build environnent similar to ChaosModV. Only difference is the SHV for MinGW. They both start fine, put ChaosModV fails when scripUnregister is called. While the second environment doesn't. Indicating that this could be an issue with the SHV for MinGw.

Correct me if I'm wrong anywhere.
