### ISSUE TITLE
[Feature Suggestion] Discord Voting via Bot

### ISSUE THREAD

**Issue by eXpLethora** [gta-chaos-mod/ChaosModV#3053]
I would like to see the possibility to integrate a voting system that can occur in private Discords, streaming the game while in a discord with friends voting for what screws you over would be fun without having to publically stream to have the same affect.

I am not sure how easy that would be or how it works with Discord bot integrations but would be a cool feature that would make it more accessible to people who just want to have fun behind closed doors with friends.

**Comment by Last0xygen** [comment]
You kind of can already.
Start with twitch voting but don’t stream to twitch but discord. Your friends can vote via twitch chat but you don’t have to go live :)

**Comment by OnlyRealNubs** [comment]
I made something like this, but I believe to to complications and too many merge conflicts I closed the PR. It also relies on Koly’s Abstraction Voting layer which is still a W.I.P. So we will have to wait and see. But until then what Last0xygen said is a good substitute.

**Comment by pongo1231** [comment]
Implemented in 8ab4a761d7d2fa29c5d27177f4977fe02c9801ef
