### ISSUE TITLE
[Effect Suggestion] Spawn Angry Farmer 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3058]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a farmer in a tractor who will try run over the player. They'll only exit if you pull them out.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped driving vehicle" effects. (We have enough already.)
