### ISSUE TITLE
[Effect Suggestion] All Props are Trees

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3070]
**Name of effect**
All Props are Trees

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Turn all destructible props in the game into Solid Object. Even a single light pole can be dangerously impactful now.

**Comment by Reguas** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/pull/2918
