### ISSUE TITLE
[Effect Suggestion] Seven deadly sins

### ISSUE THREAD

**Issue by Spooditt** [gta-chaos-mod/ChaosModV#3091]
**Name of effect**
Potential name(s) for the effect
Seven deadly sins. If you remove an enemy, you could call it sinister six. 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
This effect will spawn 7 enemies. 
1. Griefer Jesus
2. Extreme griefer Jesus
3. Jealous Jimmy 
4. Space ranger
5. Juggernaut 
6. Impotent rage
7. Spawn random enemy (unless there's a better enemy to choose)

**Comment by ThatWardrobeGuy** [comment]
This is pure evil

**Comment by SeanMirrsen** [comment]
"Seven deadly sins" should spawn seven hostile, but comparatively nonlethal NPCs. For the most part they'd be unarmed or armed with melee weapons.

The NPCs would be story-mode NPCs that correspond to the deadly sins. Something like -

Greed - Devin Weston, probably.
Envy - Lamarr? I think it works.
Pride - Steve Haines?
Lust - Samantha?
Sloth - Jimmy? Don't know if there's better characters for this.
Gluttony - don't really know. Maybe Jimmy? But then someone else for Sloth.
Wrath - technically Trevor works, but it's probably better not to use player characters. Maybe Madrazzo?

Whoever is Sloth and Gluttony should probably start out neutral, Wrath, Lust, and Envy are hostile, Pride and Greed should be either random or the 'cops' faction.

**Comment by Last0xygen** [comment]
Love the creativity but spawning multiple enemies itself is not a good effect idea, sorry
