### ISSUE TITLE
[Effect Suggestion] Meta random effects.

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#3094]
**Name of effect**
(Meta) Random effects

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
No matter what people vote, or pick. It's always gonna be picking random effects while the timer is ongoing.

**Comment by OnlyRealNubs** [comment]
Without Voting = Normal Chaos Mod

**Comment by OnlyRealNubs** [comment]
My point is why only add something, if only a select people can use it.

**Comment by KatieDeForest** [comment]
Oh, I didn't think about it that way. I see. 
I have never tried the chaos mod, without twitch voting. 
So forgot that some played it without.

**Comment by KatieDeForest** [comment]
Perhaps add so there's only casual effects, such as change weather, etc. For a perioded time
