### ISSUE TITLE
[Effect Suggestion] Sporty type

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#3096]
**Name of effect**
Sporty type
Only super cars
Super mode

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Only spawn super cars, no matter what area you're in. Until times up.

**Comment by ReiDaTecnologia** [comment]
Another name could be "Everyone is Rich", in homage to GTA SA's "Sports Cars" cheat.

**Comment by KatieDeForest** [comment]
That's a good one, haven't played the other GTA's. So thank you :D

**Comment by Last0xygen** [comment]
Duplicate, sorry
