### ISSUE TITLE
[Effect Suggestion] too fast, too furious

### ISSUE THREAD

**Issue by LordAero05** [gta-chaos-mod/ChaosModV#3097]
**Name of effect**
Too fast, Too furious

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Pedestrians with vehicle will aggressively try to run over the player 
(Note: the peds have to slam the gas hard while the effect is going on)

**Comment by ReiDaTecnologia** [comment]
Aren't that effect just "All Peds Attack Player" and "Vehicle Magnet"?
