### ISSUE TITLE
[Suggestion] Loose gun (or Loose Cannon)

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#31]
Weapons perma-shoot with infinite ammo. Either all peds or only player.
Maybe also lock current weapon, so that you can't switch to unarmed?

**Comment by pongo1231** [comment]
If this were to be implemented, probably could be merged with the "No Weapon Switching" effect

**Comment by pongo1231** [comment]
Implemented with #77

**Comment by TheRealAyCe** [comment]
@pongo1231 @Last0xygen  This should probably switch to a gun if you are currently unarmed. The effect name also does not make the lack of weapon switching apparent, which may become less of a problem when the mod makes sure that the player always has something to shoot with.
