### ISSUE TITLE
[Effect Suggestion] Mower Guy

### ISSUE THREAD

**Issue by Execoote** [gta-chaos-mod/ChaosModV#3107]
**Name of effect**
Mower Guy

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The same as Bus Bois and Scooter Brother, but Lawnmower.
Spawn a character Carlos (which michael's grass guy)

**Comment by OnlyRealNubs** [comment]
#1241 duplicate
