### ISSUE TITLE
[Effect Suggestion] Rigged! (Meta)

### ISSUE THREAD

**Issue by bruhidksmhlol** [gta-chaos-mod/ChaosModV#3113]
**Rigged! (Meta)**

**Duration**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
I feel like this new meta effect has plenty of potential, whilst being easy to code(?). Essentially , this meta would automatically choose the least voted effect for Twitch voting for about 2-3 cycles. Viewers must vote for a different effect if they want their desires effect to be chosen. (I come from DarkViperAU’s fanbase :trollface:)

**Comment by Taylor3621** [comment]
I guess you could say this opportunity is
_millions to one_


I'll see myself out

**Comment by Last0xygen** [comment]
Duplicate
