### ISSUE TITLE
[Effect Suggestion] Rigged [meta]

### ISSUE THREAD

**Issue by Juliasmatius** [gta-chaos-mod/ChaosModV#3115]
Rigged [meta effect]
onlynfor twitxh voting
- [ ] Long
- [x] Short
- [ ] No duration

When active the effect with the lowest amount of votes will be picked

**Comment by Juliasmatius** [comment]
sorry for spelling mistake here is what i ment
only for twitch voting

**Comment by OnlyRealNubs** [comment]
Duplicate
