### ISSUE TITLE
[Effect Suggestion] RIGGED (meta)

### ISSUE THREAD

**Issue by Viktorkozh** [gta-chaos-mod/ChaosModV#3116]
**Name of effect**
RIGGED (meta)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
For 3 purple lines chaos will choose the effect with the lowest percentage of votes.

**Comment by Last0xygen** [comment]
Still duplicate 😅
