### ISSUE TITLE
[Effect Suggestion] Unroastable

### ISSUE THREAD

**Issue by bruhidksmhlol** [gta-chaos-mod/ChaosModV#3118]
**Unroastable**

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The effect is a fun one to have that will not interrupt the player’s experience. This effect would:
-Give the player a random new haircut
-Spawn Tanisha as a companion
-Spawn a doctor ped that would explode after 1 second (does not damage player)
-Spawn Lamar that would get spooked

**Comment by bruhidksmhlol** [comment]
wait i accidently pressed enter 💀

**Comment by Last0xygen** [comment]
Like the idea, but I don’t think this would be a good effect by its own. Explosions would also scare other pedestrians -> could fail a mission.
