### ISSUE TITLE
[Effect Suggestion] Double Draw

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3123]
**Name of effect**
Double Draw (or Pot of Greed)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
All effects that have no duration will trigger twice, in which the second trigger happened around 10-15 seconds after the first one

**Comment by Last0xygen** [comment]
Duplicate
