### ISSUE TITLE
[Effect Suggestion] Hello, This is Agatha.

### ISSUE THREAD

**Issue by katnitro** [gta-chaos-mod/ChaosModV#3126]
**Name of effect**
Hello, This is Agatha.
This is Agatha.
Mrs. Baker

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x ] No duration

**Effect Description**
To celebrate matt finally ridding his GTA Online experience from the spam of Agatha's phone calls, we should reward him with a chaos effect that simulates the iconic phone call from Mrs Baker. This phone call would obviously be the classic phone call we've heard many times on Matto's Online streams but completely unskippable and unable to hang up on so he has no choice but to listen to the entire phone call.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2902
