### ISSUE TITLE
[Effect Suggestion] Add Agatha Baker's phone call

### ISSUE THREAD

**Issue by ParthNaik14** [gta-chaos-mod/ChaosModV#3127]
**Name of effect**
Agatha strikes again

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ ] No duration

**Effect Description**
This phone call is a running joke in whole of GTA 5 community. Sure, this became so famous as it is because of DarkViperAU, but it's not gonna cater to just one specific streamer's audience. The whole community in is annoyed by this phone call and makes fun of it. It'll be one of the best effects ever. There's no loss in adding the effect, it's a win-win situation. You anyways give the option to opt out of effects by manipulating the .ini file.

**Comment by Last0xygen** [comment]
> It will become an instant meme.

It already is, isn’t it? ;)

> There's absolutely no reason why not to put this effect. 

You‘re more than welcome to open a PR and I’ll review it.
But I think it is prone to blocking mission / cutscenes, so that could be a problem

> It'll be one of the best effects ever

ok
