### ISSUE TITLE
[Effect Suggestion] Mr.Baker Phone call

### ISSUE THREAD

**Issue by Troi4839** [gta-chaos-mod/ChaosModV#3128]
**Name of effect**
Potential name(s) for the effect
Mr.Baker Call

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
It should start the Agatha Baker phone call and it should be unskippable

**Comment by Last0xygen** [comment]
Duplicate nr 6
