### ISSUE TITLE
[Effect Suggestion] Wrong Names

### ISSUE THREAD

**Issue by MistKane2** [gta-chaos-mod/ChaosModV#3129]
**Name of effect**
Wrong Names

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; Incorrectly labels the chosen/current effects as different effects to confuse the player

**Comment by Last0xygen** [comment]
Kind of exists already as „what’s happening“
