### ISSUE TITLE
[Effect Suggestion] Teleport to End of Map

### ISSUE THREAD

**Issue by Hellenaaa** [gta-chaos-mod/ChaosModV#3130]
**Name of effect**
Teleport to End of Map

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
This effect should teleport the Player to the small grouping of islands just north of Paleto Bay (which I think is the furthest point of the map).

This effect can also be a variant of Fake Teleport.

**Comment by Hellenaaa** [comment]
I wrote this suggestion on Matt (DarkViperAU)'s subreddit a very long time ago. I finally figured out you can directly suggest stuff here.

**Comment by ReiDaTecnologia** [comment]
This would be a good addition imo. Unless it is a duplicate xD

**Comment by RosyMiranto18** [comment]
I agree with this one too.

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/400
https://github.com/gta-chaos-mod/ChaosModV/issues/1042
https://github.com/gta-chaos-mod/ChaosModV/issues/2375
