### ISSUE TITLE
[Effect Suggestion] Spawn Pirates

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3131]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a tugboat with enemies on it

**Comment by MoneyWasted** [comment]
We are not currently adding "ped driving vehicle" effects. (We have enough already.)
Also, this would only work in very specific instances. (Being in the water)
