### ISSUE TITLE
[Effect Suggestion] Random Weapon

### ISSUE THREAD

**Issue by MistKane2** [gta-chaos-mod/ChaosModV#3134]
**Name of effect**
Random Weapon 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X ] No duration

**Effect Description**
Description of the effect; Gives the player a random weapon, can be Mk. II, and/or with random attachments

**Comment by Last0xygen** [comment]
„Give Everyone A Random Weapon“ is already an effect
