### ISSUE TITLE
[Effect Suggestion] Called by Ms. Baker

### ISSUE THREAD

**Issue by TrayXCooper** [gta-chaos-mod/ChaosModV#3135]
**Name of effect**
Called by Ms. Baker

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Have Ms. Baker from gta online call you about The Duggans. 
Try to make this call so u can't hang up so you need to hear her annoying voice the entire way through the call lol

**Comment by OnlyRealNubs** [comment]
Duplicate.
