### ISSUE TITLE
[Effect Suggestion] Unskippable Phone calls from online

### ISSUE THREAD

**Issue by TrayXCooper** [gta-chaos-mod/ChaosModV#3136]
**Name of effect**
Ring Ring 

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Have any random call u would get from gta online and make the calls unskippable

**Comment by pongo1231** [comment]
Duplicate of #1119
