### ISSUE TITLE
[Effect Suggestion] Why did I move here?

### ISSUE THREAD

**Issue by IamNotProgrammer** [gta-chaos-mod/ChaosModV#3144]
**Name of effect**
Why did I move here? / other, I'm not creative with names

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Rapidly changes weather conditions like rainy, snowy, fog etc.

**Comment by Last0xygen** [comment]
Was already an effect back in the day called „modded stop changing the weather“ or something. Was removed for being too chaotic, gave players/viewers headaches

**Comment by IamNotProgrammer** [comment]
Damn, I can't have original idea
