### ISSUE TITLE
[Effect Suggestion] Nap time

### ISSUE THREAD

**Issue by Coolguyag1217** [gta-chaos-mod/ChaosModV#3147]
**Name of effect**
Nap time

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Everybody falls and stays down for a short period of time and you lose control of your character during that period.

**Comment by MistKane2** [comment]
Already exists as "Make everyone ragdoll" I think

**Comment by Taylor3621** [comment]
Too similar to what happens during Insane Gravity IMO
