### ISSUE TITLE
[Bug] Simeon doesn't let you react

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#3150]
https://clips.twitch.tv/MistyPlayfulPandaYouWHY-3zMtnhXu9uDnVnro
For some reason, without any restrictions/orders given, Simeon just blows up player without any delay for reaction

**Comment by OnlyRealNubs** [comment]
This is a common issue with FiveM and this effect.

**Comment by JustTunerYT** [comment]
Wait, really?

**Comment by JustTunerYT** [comment]
Not sure if it's fixed (Hopefully is), but since it's a common bug, guess i don't need this issue open anymore
