### ISSUE TITLE
[Effect Suggestion] Mrs. Baker Calls You Again

### ISSUE THREAD

**Issue by WeirdPov** [gta-chaos-mod/ChaosModV#3153]
**Name of effect**
Mrs. Baker Calls You Again

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
_"If its existed already, i'll remove this as planned"_
From DarkViperAU's video about agatha, on top comment says 
"I really want this to be an unskippable phone call effect in chaos."
By: TotalHydration (On top comment)
Video: https://www.youtube.com/watch?v=ttPmvX0LIKE

**Comment by OnlyRealNubs** [comment]
Duplicate of [#Call Spam](https://github.com/gta-chaos-mod/ChaosModV/issues/1119) . For the love of god, look for duplicates.

**Comment by WeirdPov** [comment]
> Duplicate of [#1119](https://github.com/gta-chaos-mod/ChaosModV/issues/1119) . For the love of god, look for duplicates.

Yea i know!! i put there as ""If its existed already, i'll remove this as planned"" GAD DAMMIT

**Comment by OnlyRealNubs** [comment]
> > Duplicate of [#1119](https://github.com/gta-chaos-mod/ChaosModV/issues/1119) . For the love of god, look for duplicates.
> 
> Yea i know!! i put there as ""If its existed already, i'll remove this as planned"" GAD DAMMIT

Maybe check before hand we wouldn't be here. 🙃
