### ISSUE TITLE
[Effect Suggestion] T Pose Time

### ISSUE THREAD

**Issue by AscariGTA** [gta-chaos-mod/ChaosModV#3154]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

Makes The Characters around All go into a t pose animation for 45 seconds, everything works fine but everyone is t posing

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1170
