### ISSUE TITLE
[Effect Suggestion] Spawn Stoned Tonya

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3156]
**Name of effect**
Potential name(s) for the effect
Spawn Stoned Tonya

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn an enemy Tonya NPC spamming you with endless barrage of Machine Gun bullets albeit with less than stellar accuracy of being in a permanent LSD state but her defense is bolstered with permanent Bullshark Testosterone too.

**Comment by OnlyRealNubs** [comment]
So Jealous Jimmy, but high?

**Comment by RosyMiranto18** [comment]
Hm... I guess so. And she's practically invincible too to make up for poor accuracy .

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
