### ISSUE TITLE
[Effect Suggestion] Spawn Jobless Janitor 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3157]
Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Enemy Janitor with a baseball bat reskinned as the broom prop

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
