### ISSUE TITLE
[Improvement] Fake player swap is too long

### ISSUE THREAD

**Issue by kolyaventuri** [gta-chaos-mod/ChaosModV#316]
**Describe the improvement**
With fake player swap using `OnStart` and `OnStop` (see [PlayerFakePlayerSwap.cpp](https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Effects/db/Player/PlayerFakePlayerSwap.cpp)), it seems far too long. If we can make this to be about the same length as a normal player swap, that would be ideal

**To Reproduce**
- Will add a link if I can find a timestamp in a video (probably a DarkViperAU video, I'm watching his stream as I write this up)
- Just run `Player Swap` effect to experience it

**Comment by pongo1231** [comment]
Effect is not a part of the mod anymore
