### ISSUE TITLE
[Effect Suggestion] Side Angle Camera 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3162]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Locks the camera at 180 degrees of the player

**Comment by OnlyRealNubs** [comment]
On what axis? 🧐

**Comment by TerrizX** [comment]
> On what axis? 🧐

X axis

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/3082
