### ISSUE TITLE
For the Fake Crash effect you should make it 2 seconds longer, so the panic always kicks in.

### ISSUE THREAD

**Issue by Pecske21** [gta-chaos-mod/ChaosModV#3170]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by pongo1231** [comment]
It's good as it is IMO
