### ISSUE TITLE
[Effect Suggestion] (Car Bomb)

### ISSUE THREAD

**Issue by rollschuh2282** [gta-chaos-mod/ChaosModV#3171]
**Name of effect**
Fake Vehicle or Car Bomb

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Basically a fake "spawn vehicle" effect.
but when entering it blows up and changes the effect name to Car Bomb for example.
example: it spawns for example a Adder and shows the effect text for "Spawn Adder", but when the player enters the car, it instantly blows up and the effect text changes to the intended name.

can result in funny moments of a streamer for example being happy about the car and then getting a unexpected surprise

**Comment by OnlyRealNubs** [comment]
You want this to have no duration, but logic after the effect dispatches?

**Comment by ReiDaTecnologia** [comment]
Honestly would be funny a fake _spawn vehicle_ (The several effects that spawn vehicles) where the vehicle despawn after some time xD

**Comment by rollschuh2282** [comment]
> You want this to have no duration, but logic after the effect dispatches?

iirc the spawned vehicles don´t despawn usually.
so i just thought maybe it would be possible to have it similar, just with a check that if it blows up, that the text changes.
if that isn´t possible, then maybe the idea can be utilized similar.

**Comment by OnlyRealNubs** [comment]
> > You want this to have no duration, but logic after the effect dispatches?
> 
> iirc the spawned vehicles don´t despawn usually. so i just thought maybe it would be possible to have it similar, just with a check that if it blows up, that the text changes. if that isn´t possible, then maybe the idea can be utilized similar.

When the effect starts it calls code that is called once and returns when the effect is dispatched. So there is no way to check after the initial start function is called, atleast with no duration.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2012
