### ISSUE TITLE
[Feature Suggestion] a new feature that I think would be neat is when an effect has been applied to the game and it shows up on the side of the screen, next to it should say the percentage of people who voted for it.

### ISSUE THREAD

**Issue by Dingusplays** [gta-chaos-mod/ChaosModV#3172]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/270
Also, please use the normal layout :)

**Comment by Dingusplays** [comment]
I honestly don't know how I was meant to search for that, and also I've
never used this site before so there was no need to correct me on format
usage. There were a lot of hoops to jump through to even get here maybe you
should think of doing this in a way that's more simple and has less
barriers to entry. Thanks for replying, and sorry for repeating a
suggestion.
