### ISSUE TITLE
[Feature Suggestion] Show effect name before applying it.

### ISSUE THREAD

**Issue by Nuker299** [gta-chaos-mod/ChaosModV#3177]
**Is your feature request related to a problem? Please describe.**
Sometimes the game crashes when effect is applied, but we can't be sure what effect crashed it due to the randomness.

**Describe the solution you'd like**
Show the effect name in the list before applying it, i think few frames should be enough to show it on the frozen screen.

**Comment by GalaxyGaming629** [comment]
You can check the chaoslog in the chaosmod folder to see what effect happened before the game crashed

**Comment by Last0xygen** [comment]
There already is the effectslog in your chaosmod folder for that 👍
