### ISSUE TITLE
Drive-By!

### ISSUE THREAD

**Issue by 810CK-A1D** [gta-chaos-mod/ChaosModV#3181]
**Name of effect**
Drive-By!

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x ] No duration

**Effect Description**
Spawns a pink voodoo. Like in the drive thru San Andreas mission, it’ll spawn two ballas member in a voodoo attempting to shoot the player

**Comment by PinballGH** [comment]
Isnt this what you meant ? If yes, its already included in the mod :)

> https://github.com/gta-chaos-mod/ChaosModV/issues/104

**Comment by JustTunerYT** [comment]
First of all, pink voodoo already exists as "Balla Squad". Second, there's also "Peds Drive-by Player" effect.
