### ISSUE TITLE
[Effect Suggestion] Midnight Swim by Brock Berrigan

### ISSUE THREAD

**Issue by RMJStrikeCat** [gta-chaos-mod/ChaosModV#3185]
**Name of effect**
Potential name(s) for the effect

Play Midnight Swim
-OR-
Midnight Swim

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- X Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

Play the song Midnight Swim 
-OR-
Set time to midnight and spawn the player in the ocean while playing the song

If possible, this should only occur on the mission “Minor Turbulence” because DarkViperAU, a YouTuber and Twitch Streamer, has had some…experiences with it…

**Comment by Last0xygen** [comment]
Imbedding a song is not something we’re looking for.
Also this seems very streamer specific
