### ISSUE TITLE
[Effect Suggestion] Teleport to Random Minigame 

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3196]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports the player to a random activity, so a race, tennis court game etc.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/871
