### ISSUE TITLE
[Effect Suggestion] Griefer Jesus *Companion*

### ISSUE THREAD

**Issue by Groofle** [gta-chaos-mod/ChaosModV#3201]
**[Effect Suggestion]** Griefer Jesus *Companion*

- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Spawns the exact copy of Jesus with a railgun, however as a companion, but make the text where it says 'Companion' really small if possible. Friendly fire activated if possible so people could be baited into killing a powerful companion.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2563
