### ISSUE TITLE
[Effect Suggestion] Out of This World

### ISSUE THREAD

**Issue by GarbageHacks** [gta-chaos-mod/ChaosModV#3206]
**Name of effect**
Out of This World

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleports the player as high as possible and as far out of the map as possible leaving them stranded in the middle of the ocean at height limit.

**Comment by ReiDaTecnologia** [comment]
I feel like the devs will not like this effect...

**Comment by Last0xygen** [comment]
> I feel like the devs will not like this effect...

😏

nah tbh, we have several requests for variations of „teleport to heaven“ and „teleport to ocean“ basically, so I’ll close this as a duplicate.
Thanks for the suggestion though 😊
