### ISSUE TITLE
[Effect Suggestion] Everyone's Blessed

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3207]
**Name of effect**
Everyone's Blessed

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Replace all peds that are spawned and those that will spawn with the model of Jesse/Griefer Jesus

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
Also, it is not possible to "hot swap" models like this. (Trust me I have spent hours trying to.)
