### ISSUE TITLE
[Effect Suggestion] BONUS STAGE!!!

### ISSUE THREAD

**Issue by Taylor3621** [gta-chaos-mod/ChaosModV#3209]
**Name of effect**
BONUS STAGE!!!

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
For the duration, the player can't gain a wanted level, and all cars turn golden. While the effect is active, hitting cars and pedestrians gives the player money. (Perhaps $50 or $100?)

**Comment by SRG27** [comment]
Midas Touch is a very similar effect.

**Comment by Taylor3621** [comment]
I will not lie to you
I forgot that was an effect because I basically never see it XD
