### ISSUE TITLE
[Effect Suggestion] fake fake teleport

### ISSUE THREAD

**Issue by Swagi-REDACTED** [gta-chaos-mod/ChaosModV#3211]
**Name of effect**
Potential name(s) for the effect
Real fake teleport, fake fake teleport, double fake teleport
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; it should teleport to somewhere just like regular teleport then teleport back like fake teleport then back to where they got teleported too

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1218
