### ISSUE TITLE
[uno damage ] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by lordofthehams** [gta-chaos-mod/ChaosModV#3212]
**uno**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [y ] Short
- [ ] No duration

**Effect Description**
all damage the player makes on the enemy(npc) is put one the player  
Description of the effect; what should it do?
reverse damage. if you do 20hp damage to an npc you will get that back

(i guess the npc could have the same effect ? so they get hurt if they shoot you)

**Comment by ReiDaTecnologia** [comment]
I'm pretty sure this is a duplicate
Did i guess it right Oxygen-san? :flushed:

**Comment by lordofthehams** [comment]
> 
Oxygen-san? 
i looked it up and saw noting. but if it is a dup did not know :) was just told to put a suggenst here

**Comment by Last0xygen** [comment]
Sounds similar to https://github.com/gta-chaos-mod/ChaosModV/issues/404
There has been similar requests, yes :)

**Comment by lordofthehams** [comment]
> 

ah thank you! i did not see them. did a bad job at looking. thank tho :)

**Comment by Last0xygen** [comment]
> ah thank you! i did not see them. did a bad job at looking. thank tho :)

No worries, it’s not always that easy to find 😅
Thanks for the suggestion though :)

**Comment by lordofthehams** [comment]
> > ah thank you! i did not see them. did a bad job at looking. thank tho :)
> 
> No worries, it’s not always that easy to find 😅 Thanks for the suggestion though :)

thanks for letting me know :) hope you have a goodie day !
