### ISSUE TITLE
[Effect Suggestion] Invisible Timer (Meta)

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3214]
**Name of effect**
Invisible Timer (Meta)

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Temporarily renders the Purple Line to be invisible especially to the Streamers. Particularly dangerous when Fake Crash is close by.

**Comment by ReiDaTecnologia** [comment]
Aren't that part of the "What's happening?" Meta?

**Comment by RosyMiranto18** [comment]
No, it's not the same. What's Happening is the Effect themselves are invisible. In this case, it's the timer.

**Comment by Speedyxx** [comment]
> No, it's not the same. What's Happening is the Effect themselves are invisible. In this case, it's the timer.

But "What's Happening" also hides the timer.

**Comment by RosyMiranto18** [comment]
Oh... I didn't know that. Oops.

**Comment by ReiDaTecnologia** [comment]
bruh that what i said in my first comment...

**Comment by RosyMiranto18** [comment]
Sorry. I just thoight that What's Happening doesn't have the timer invisible too.
