### ISSUE TITLE
[Effect Suggestion] No Bitches

### ISSUE THREAD

**Issue by AyushRohilla007** [gta-chaos-mod/ChaosModV#3218]
**Name of effect**
No Bitches

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Despawn all the female peds during the effect

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/3077
