### ISSUE TITLE
[Effect Suggestion] Random, Random effect (meta)

### ISSUE THREAD

**Issue by Signedinto** [gta-chaos-mod/ChaosModV#3220]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

a meta effect where it would do a random effect every 30 seconds for 2 or 3 minutes. Along with the voted chaos effects.

**Comment by PapaAquchala** [comment]
If I'm understanding correctly, this is already a thing

Random Effect (Meta) will pick two random effects to apply alongside whatever is voted for

**Comment by Last0xygen** [comment]
Yea, that’s „combo time“ 😅
