### ISSUE TITLE
[Feature Suggestion] Anti-cheating method against streamers

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#3223]
I have no issues, if skipping a mission or doing something that is not right to do while completing mission in story mode with chaos mod was an agreement by everyone, no problem.
But, using cheat codes to spawn a car, skipping even because streamer completed whole mission and got crashed/softlocked without agreement, restarting mod because he got stuck (again, without public opinion). My opinion is those actions is unrightful things to do. So i came up with the idea to fight those cheaters. Of course, this ability has to be given to those, who knows, how the game works, how the mod works and don't have reasons to abuse the command
So, i think there should be a command, which can either: 1 - force invoke all effects at once; 2 - force 5x timer speed meta effect until the game crashes.

The reason i made this option is because streamer's actions are getting ridiculous now and we have to do something about it.
If you think that we could come up with another method to make streamers play fair and not use any other ways to complete story line, that includes actions mention above, comments are open, write the down if you want to. So far i think this is the best method yet.

**Comment by JustTunerYT** [comment]
My final piece of being a good guy has ran out when i got timed out for thinking, that streamer shouldn't cheat. That was it

**Comment by JustTunerYT** [comment]
> This is a mod where the entire point is to have fun and make playing the game a different experience, yet you're concerned that people aren't having fun your way? If you don't want to use mod menus when you play that's fine, but literally asking the devs of a mod to stop other people from using other mods is probably the dumbest suggestion I've seen since I've come here. And that's saying a lot considering people have literally suggested crashing the game as an effect.

You see, these people, who stream chaos mod, challenged themselves to complete the game with the mod. Doing this way isn't fun for anyone. If they are just chilling around, not doing missions, then they can do whatever they want and they can use anything if in any means neccesary, but doing their way isn't fun either. It's not challenging enough, when you get buzzard through cheat code, if instead you could just look around and find a vehicle, when you reset mod because "it's too hard", if this mod already has failsafe if player keeps mission failing, or skip, avoiding redoing mission for another challenge, if they just could go for another round, have more fun while trying to complete this mission yet again. If streamer didn't like, that he was softlocked/crashed/his car died/he died/can't complete mission, he can just ask some people to be more nice to him. It works for the most cases, at least those were the cases.

**Comment by Taylor3621** [comment]
🗿

**Comment by Speedyxx** [comment]
bruh if you dont like how someone plays the game, then either watch another streamer or play the game yourself.
