### ISSUE TITLE
[Effect Suggestion] Can we update "realistic hacking"?

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#3227]
Considering "Realstic hacking" being an old effect with only one way to hack, i think it's time to freshen it up by adding more hack programs/tools.

Duration option not included as this effect already exists

In my opinion, there should be somewhere around 5 new realistic hacks
1st is a well know fingerprint hack from cayo perico island heist. It can contain up to 4 fingers to hack, but since we don't want to make it very long, one is enough. [Video on YouTube](https://youtu.be/_6H_CZGaajA)
2nd is (as far as i can tell) also known, same fingerprint scan hack, but from casino heist. Same as above. [Video on YouTube](https://youtu.be/EoUc-fWBkKo)
3rd is IP Address hack, which is used almost EVERYWHERE in single player story heists (at least 100% sure about The Bureau Raid). [Video on YouTube](https://youtu.be/KWMtkjJastA)
4th is that hack programm, where you have to hit enter/click at good timing to line up coloumns (not sure how i can call it, nor does it have a name)
And 5th is a hack also from GTAO, the Doomsday heist, where you need to destroy packets (blue cores) and keep alive firewalls (red cores). [Video on YouTube](https://youtu.be/XaKuFH71UjM)

At least 1, 3 and 4 are doable, i think. Not sure about the rest tho

**Comment by JustTunerYT** [comment]
And i also remembered, that's there's a Fleeca Job hack too [link](https://youtu.be/XZVi1ScyjuI)
I think this one is doable as well

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/993
https://github.com/gta-chaos-mod/ChaosModV/issues/1833
