### ISSUE TITLE
[Effect Suggestion] No Ragdoll

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#3232]
**Name of effect**
Unable to ragdoll
No ragdoll
I'm a pole
Iron man
Rock hard

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
I've searched in the issues, and I'm surprised I haven't seen this one yet.
It would be great to have a no ragdoll effect, so vehicles push you around or you can't trip.
It's basically the opposite of "Tie your shoes". It's included in a lot of mod menu's I've fucked around with in SP.
Would be great to see!

**Comment by ReiDaTecnologia** [comment]
My guess it is too minimal to consider adding it

**Comment by Last0xygen** [comment]
My guess would be that it’s already an existing effect ;)
https://github.com/gta-chaos-mod/ChaosModV/blob/bb04d3e3edee494ebe6df3e95cd14c31a8d8074e/ChaosMod/Effects/db/Peds/PedsNoRagdoll.cpp

**Comment by KatieDeForest** [comment]
Weird, I've never gotten that effect before.

**Comment by SeanMirrsen** [comment]
> My guess would be that it’s already an existing effect ;) 

<_<
