### ISSUE TITLE
[Effect Suggestion] Stare of Death

### ISSUE THREAD

**Issue by TerrizX** [gta-chaos-mod/ChaosModV#3237]
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
If the player looks at a ped the ped dies immediately

**Comment by Last0xygen** [comment]
Basically „deadly Aim“
https://github.com/gta-chaos-mod/ChaosModV/blob/d94207ab4454e1347d0326ac3008fe1f0cd36af3/ChaosMod/Effects/db/Player/PlayerPoof.cpp
