### ISSUE TITLE
[Effect Suggestion] Corrupt Save File (0.01%)

### ISSUE THREAD

**Issue by GamingRonReed** [gta-chaos-mod/ChaosModV#3245]
**Name of effect**
Corrupt Save File
Millions to One
Gamble

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
There is a 0.01% chance that, once triggered, this effect will corrupt the save file, essentially forcing you to restart the story.

**Comment by ReiDaTecnologia** [comment]
I don't think this is a good idea even with an extremely low % and is it even possible tho?

**Comment by Last0xygen** [comment]
This is not something we want for chaos mod
