### ISSUE TITLE
[Effect Suggestion] MILLIONS TO ONE

### ISSUE THREAD

**Issue by 65tuvalu** [gta-chaos-mod/ChaosModV#3250]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?
Spawns a mountain lion behind you

**Comment by Last0xygen** [comment]
Already an effect called „hot cougars in your area“
