### ISSUE TITLE
[Effect Suggestion] Fake Fake Teleport

### ISSUE THREAD

**Issue by GamingRonReed** [gta-chaos-mod/ChaosModV#3257]
**Name of effect**
Fake Fake Teleport

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Similar to fake teleport, the player will be teleported to a random location and then teleported back after a few seconds. However, once they have gotten their hopes up again, this effect just teleports them again.

**Comment by Last0xygen** [comment]
Duplicate
