### ISSUE TITLE
[Effect Suggestion] This will hurt me more...

### ISSUE THREAD

**Issue by CRB9000** [gta-chaos-mod/ChaosModV#3262]
This will hurt me more...
This will hurt me more than you

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Damage inflicted in reverse. The character inflicts damage on themselves when fighting others. Conversely, NPC's receive damage when attacking the player.

**Comment by anto4440** [comment]
i have one thing to say. #404 #405 #776 #2770 #3212
