### ISSUE TITLE
[Effect Suggestion] Jesus' blessing

### ISSUE THREAD

**Issue by Kylerr98** [gta-chaos-mod/ChaosModV#3269]
Anytime a Jesus is spawned whether it's griefer or take the wheel the last chaos effect will be removed 
Wouldn't have a time limit

**Comment by NeverKnowDev** [comment]
So an effect that would only do something when a few other effects get activated? Also a removing the last chaos effect is impossible for some and super time consuming and difficult for others.

**Comment by Kylerr98** [comment]
Ok it was just a suggestion

**Comment by NeverKnowDev** [comment]
And I was just responding and bringing out the details. Are we not allowed to give feedback on suggestions ?

**Comment by Kylerr98** [comment]
I know ...you are and I wasn't angry

**Comment by SRG27** [comment]
> Also removing the last chaos effect is impossible for some and super time consuming and difficult for others. 

It *is* possible to remove the last chaos effect, it's already used in the failsafe. (After three mission fails)

**Comment by NeverKnowDev** [comment]
@SRG27 Oh yes, your right. My bad

**Comment by anikun2k10** [comment]
This would probably be better as a meta effect

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
