### ISSUE TITLE
[Effect Suggestion] Jesus Take the Flying Lesson

### ISSUE THREAD

**Issue by Execoote** [gta-chaos-mod/ChaosModV#3271]
**Name of effect**
Jesus Take the Flying Lesson

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Jesus with flying random **PLANE** or a **CHOPPER** and teleport's players to a plane _(Which player does teleport to Passenger/Co-Pilot seat, and Jesus takes control of a PLANE/CHOPPER)_.
Spawn coordinate: **Same height as the "Teleport to Heaven" but not specific place where it teleports to heaven**
Spawn Plane or Chopper: **Random**

**Comment by Mirandawws** [comment]
Jesus controls planes and choppers very poorly. With choppers he just hovers still without moving to any direction.
With planes he doesn't control it at all. He just accelerates. Meaning he will just fly in a single direction.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
