### ISSUE TITLE
[Effect Suggestion] Spawn Fourteen Paiges

### ISSUE THREAD

**Issue by WeirdPov** [gta-chaos-mod/ChaosModV#3273]
**Name of effect**
Spawn Fourteen Paiges

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Fourteen (14) Paige Harris, Referencing to DarkViperAU writing 14 Page document about Content Creator Reactors

**Comment by NeverKnowDev** [comment]
Pongo has said it alot, he doesnt like adding references because only people who watch that specif Creator or know the reference will get it, everyone else will be left confused.
