### ISSUE TITLE
[Effect Suggestion] Player swap, fake teleport, fake crash potential improvements

### ISSUE THREAD

**Issue by Buzifox** [gta-chaos-mod/ChaosModV#328]
**My suggestions for enhancing currently available effects**

**Player swap**
So it would start as it currently does, take the camera to the sky etc.. What I suggest would be to swap the player character into some random NPC while the camera is at the sky and "reveal" it once it returns down into player control. The player character swap could stay active for a set period of time, say a few minutes. I recall that missions cannot be started while the player character is swapped, so the effect cannot stay permanent. I don't remember that swap during missions had negative effects. It's been a while since I last played with trainers. 

**Fake teleport**
I feel like the fake teleport is too obvious as it doesn't reveal the effect until it has teleported the player back. This could be improved by telling the player a fake teleport location, just like a normal teleport does. Just change the description to fake teleport once the effect returns the player back.

**Fake crash**
I think this effect would be potentially more fun if it worked like normal, but also had a possibility to be activated after a random period of time, or it could activate on some interaction, such as crashing a car or starting a cutscene. Of course to make it less obvious, if it is a delayed one, would be to camouflage it as a different already available effect on the effect list, until it reveals its true nature. Something mostly harmless, like maybe full bright, or even a force field. The camouflage effect would then also disappear once the "crash" happens.

**Comment by kolyaventuri** [comment]
At least regarding improving the fake effects so they _look_ like something different, this is in the works! See #325

**Comment by TheRealAyCe** [comment]
@Last0xygen Do these already have their own tickets? If yes this one can be closed, right? Otherwise: @Buzifox Please put these suggestions each in their own tickets and close this one.

**Comment by kolyaventuri** [comment]
Closing this because player swap doesn't exist anymore, and the fake teleport change has been implemented. I believe that the suggestion for fake crash has been suggested already, however if it doesn't we can re-open a new issue for it
