### ISSUE TITLE
[Effect Suggestion] Spawn Cerberus

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#3289]
**Name of effect**
Spawn Cerberus

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns the Cerberus from the Online Halloween free roam event a bit away from you and it acts the same way as that Cerberus in terms of behaviour, strength and duration.

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
