### ISSUE TITLE
[Effect Suggestion] Busted!

### ISSUE THREAD

**Issue by douganater** [gta-chaos-mod/ChaosModV#3297]
**Busted!**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns some variable of a police car be it a cruiser, Swat truck, NOOSE van and places the player in the back seat.

**Comment by OnlyRealNubs** [comment]
Duplicate #2944

**Comment by douganater** [comment]
Different name but way ahead of me. Nice find.
