### ISSUE TITLE
[Effect Suggestion] Replace All Peds With In-Use Character

### ISSUE THREAD

**Issue by Suptuss** [gta-chaos-mod/ChaosModV#3299]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
Replace all peds to be in-use character such as (Franklin, Michael Or Trevor) in-use character as in the character the player is using. It seems pretty stupid but it could be funny in a way. (1 minute/60 secs lasting)

**Comment by Last0xygen** [comment]
Replacing all peds has already been requested
