### ISSUE TITLE
[Effect Suggestion] Swap Players Keybinds

### ISSUE THREAD

**Issue by Suptuss** [gta-chaos-mod/ChaosModV#3300]
**Name of effect**
Potential name(s) for the effect

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
Swap Players Keybinds Then When Time Is Over, It Will Swap Back.

**Comment by Last0xygen** [comment]
Duplicate
