### ISSUE TITLE
[Effect Suggestion] Groove street home

### ISSUE THREAD

**Issue by Neck1994** [gta-chaos-mod/ChaosModV#3302]
**Name of effect**
Groove street home or Teleport player to groove street

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Teleport the player to the middle of groove street. The name suggest the famous line CJ says in the beginning of SA

**Comment by Last0xygen** [comment]
duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1733

**Comment by ReiDaTecnologia** [comment]
All you had to do is check for duplicates, CJ!

**Comment by anto4440** [comment]
After four months of not checking for duplicates.... it was time to suggest the name 'Groove Street Home'.
