### ISSUE TITLE
[Effect Suggestion] Home sweet home 

### ISSUE THREAD

**Issue by JesusofNazareth69** [gta-chaos-mod/ChaosModV#3303]
**Name of effect**
Potential name(s) for the effect
Home sweet home
Teleport to house
Go back home
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [ X] No duration

**Effect Description**
Description of the effect; what should it do?
Teleport the player to the character's house :
If you play as Michael -> teleport to Michael's house
If you play as Franklin -> teleport to current Franklin's house
If you play as Trevor -> teleport to Trevor's trailer or Floyd's house
If you are in prologue -> do nothing

**Comment by Last0xygen** [comment]
duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/347
