### ISSUE TITLE
[Effect Suggestion] Keep it non lethal 

### ISSUE THREAD

**Issue by JesusofNazareth69** [gta-chaos-mod/ChaosModV#3304]
**Name of effect**
Potential name(s) for the effect
Keep it non lethal 
Non lethal fight
Electric fight
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X ] No duration

**Effect Description**
Description of the effect; what should it do?

Replace everyone's weapons with stun guns

**Comment by ReiDaTecnologia** [comment]
Actually, the stun gun _kills_ people.

**Comment by JesusofNazareth69** [comment]
Yeah I know that's the joke

**Comment by Last0xygen** [comment]
"Give Everyone A Stun Gun" is already an effect
https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Effects/db/Peds/PedsEveryoneWepController.cpp#L40
