### ISSUE TITLE
[Effect Suggestion] Not that wheel, Jesus!

### ISSUE THREAD

**Issue by AgentV12** [gta-chaos-mod/ChaosModV#3308]
When this effect occurs, the "you really should pray" soundbite plays before a random wheel is physically removed from the player's vehicle and given additional velocity (possibly around 1.5x the current velocity or a dynamic variable), so that the severed wheel pings off into the distance. 

If the player is not currently in a vehicle, or if the current vehicle is not applicable, then the soundbite will not be played, and the effect will instead be applied to the applicable vehicle in closest proximity to the player, where the wheel will be flung in the player's direction, even if the vehicle in question is unoccupied or stationary.

**Comment by MoneyWasted** [comment]
Similar effects such as "Detach Random Wheel" already exist.
Also, we are currently not adding anymore "Jesus" themed effects.
