### ISSUE TITLE
[Effect Suggestion] I'm deleting this song/ minor turbulence 

### ISSUE THREAD

**Issue by IchibiGnarosaki** [gta-chaos-mod/ChaosModV#3309]
**Name of effect**
I'm deleting this song

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ]Short
- [x] No duration

**Effect Description**
Puts you I'm a similar scenario like minor tubulance with midnight swin playing, and you get one shoted and die

**Comment by NeverKnowDev** [comment]
This isn't a darkviperau based community. Even if some know who he is, rarely anyone will know the reference. This will be just confusing most people. 
It would be funny for the first time to people who know the reference, and after that it will be boring. 

Not to even speak about the fact that shipping audio files will fill up space quicker and quicker as time goes on. You wouldn't wanna install mod that has 50GB of assets. As well as doing something like this, is possible, but requires a lot of work, possibly adding features to the base itself. 

I know I could have just responded in one sentence, but wanted to make this stuff clear for future submissions.
