### ISSUE TITLE
[Effect Suggestion] Everyone is here!

### ISSUE THREAD

**Issue by Mirandawws** [gta-chaos-mod/ChaosModV#3315]
Everyone is here!

- [ ] Long
- [ ] Short
- [x] No duration

Effect spawns a bus and sets the player in it. If the player has other people with him like in missions they will also get set in the bus.
Since busses have a lot of seats, all of them are filled with a bunch of classic characters. From chaos mod and the story mode.
Griefer Jesus, Companion Brad, Angry Alien, Lamar, DAVEY, Steve Haines etc. They shouldn't be hostile because I'm pretty sure they would just jump out of the bus immediately. The player isn't set in the driver seat. A random classic character like the passengers will be the driver. The driver will follow yellow and purple waypoints like Jesus from "Jesus take the wheel" or Franklin from "Reposession". Also the driver can't be killed like in "Jesus take the wheel"

**Comment by Mirandawws** [comment]
Yeah... how do I delete the old one?

**Comment by ReiDaTecnologia** [comment]
You can't 😉

**Comment by Mirandawws** [comment]
So am I screwed or will this go through?

**Comment by ReiDaTecnologia** [comment]
Don't worry about it, this suggestion is probably a duplicate anyway 🤣

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn", "ped spawn" or "ped driving vehicle" effects. (We have enough already.)
