### ISSUE TITLE
[Effect Suggestion] Spawn Enemy Pilot

### ISSUE THREAD

**Issue by Wingblade20** [gta-chaos-mod/ChaosModV#3317]
The name of the effect is: Spawn Enemy Pilot

[X}No duration

Similar to GTAO's hangar missions, an NPC(s) will spawn in a Laser jet or Valkyrie helicopter, and be aggroed onto the player

**Comment by MoneyWasted** [comment]
We are not currently adding "ped driving vehicle" effects. (We have enough already.)
Also, this would be too overpowered as unless you have a homing missile launcher it is very hard to shoot down jets/helicopters.
