### ISSUE TITLE
Spawn Avon Hertz

### ISSUE THREAD

**Issue by BrozyGG** [gta-chaos-mod/ChaosModV#3322]
**Name of effect**
Potential name(s) for the effect
Spawn Avon Hertz
Spawn Melon Husk
**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawn a hostile npc riding a jetpack that uses the Avon Hertz model

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
