### ISSUE TITLE
[Effect Suggestion]  Attack Animal

### ISSUE THREAD

**Issue by MaatRolo** [gta-chaos-mod/ChaosModV#334]
**Name of effect**
Potential name(s) for the effect
Spawn Cougar
**Duration if timed effect (long or short timed?)**
Animals life

**Effect Description**
Random Enemy, only Meow.

**Comment by TheRealAyCe** [comment]
"Spawn Catto (Large)"

**Comment by pongo1231** [comment]
Part of the mod now
