### ISSUE TITLE
[Effect Suggestion] Spawn Gun Van

### ISSUE THREAD

**Issue by DEATHCON1** [gta-chaos-mod/ChaosModV#3349]
**Name of effect**
Spawn Gun Van

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns the Gun Van from Online with the Gun Van Seller in-back next to the player. The player can interact with the Gun Van Seller and buy everything that they sell, regardless of what week it is. Prices for everything are ones for non-GTA+ Members (Because you don't own GTA+ in Story Mode and it just makes it harder to get the Railgun...).

**Comment by anto4440** [comment]
I think the actual gameplay effect on this would be minimal.. It is not uncommon to lose all of your weapons anyway, so creating a portable gun store does relatively little.

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
