### ISSUE TITLE
[Effect Suggestion] Play Random Cutscene

### ISSUE THREAD

**Issue by 5harpness** [gta-chaos-mod/ChaosModV#3357]
Name of effect
Play Random Cutscene

**Duration**

    Long
    [X] Short
    No duration

Effect Description
It does what it says. When the effect is picked, a random cutscene from the entirety of the story campaign will play. It cannot be skipped.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/3252
