### ISSUE TITLE
[Effect Suggestion] Fake Wanted Level

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#3364]
**Name of effect**
Fake Wanted Level

**Duration (choose one and replace the corresponding "[ ]" with "[X]")**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
The HUD displayed random amount of Wanted Level Stars when you are not chased by the police, and vice versa (There's no wanted level shown when you are chased by cops). It all exist to serve the player's paranoia.

**Comment by Reguas** [comment]
https://github.com/gta-chaos-mod/ChaosModV/pull/3065
