### ISSUE TITLE
1 error

### ISSUE THREAD

**Issue by testtest954** [gta-chaos-mod/ChaosModV#3376]
when i build it only haves 1 error
LNK1104	cannot open file '..\vendor\minhook\build\VC16\lib\Release\libMinHook.x64.lib'
that's it is there a fix?
i tried reopen and close it won't work

**Comment by OnlyRealNubs** [comment]
Open the .sln file in VC16 and build libMinHook as Release

**Comment by OnlyRealNubs** [comment]
Read the README.md for how to build and stop making issues please.

**Comment by testtest954** [comment]
i build the vc17 minhook but it opens that instead

**Comment by OnlyRealNubs** [comment]
Opens what instead

**Comment by OnlyRealNubs** [comment]
The vc16 is the one that is linked. You need to use that one.

**Comment by testtest954** [comment]
then how do i change it?

**Comment by testtest954** [comment]
i am using visual studio 2022

**Comment by testtest954** [comment]
how about i copy the files of vc17 to vc16 that maybe should work

**Comment by testtest954** [comment]
0 failed good

**Comment by testtest954** [comment]
its working
