### ISSUE TITLE
[Effect Suggestion] Minor Turbulence

### ISSUE THREAD

**Issue by McDonaldsIceCreamMachine** [gta-chaos-mod/ChaosModV#3384]
Minor Turbulence

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Player will be teleported to a cargo plane flying over Grapeseed; just like in the actual mission Minor Turbulence.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/1106
