### ISSUE TITLE
Key bind effects.

### ISSUE THREAD

**Issue by MaatRolo** [gta-chaos-mod/ChaosModV#340]
Is your feature request related to a problem? NO

**Describe the solution you'd like**
Key bindings - I'm thinking 'Ctrl+(NUM1-NUM9)' - to start/stop effects

**Describe alternatives you've considered**
None Alternatives

**Additional context**
I'd like to be able to hot key specific effects to trigger them on command.   Most useful example I can think of is Suicide.  Having it bound to CTL+NUM1 if I'm stuck in because of an effect but don't wish to restart mod or page through the (CTRL+,) menu.  This could also be used to bind snow to a Key combo to change weather if you wanted.  

Let me know if this needs further explanation

**Comment by MoDerPo** [comment]
There are 270 effects.

**Comment by MoDerPo** [comment]
use mod menus if you want to start a specific effect not the chaosmod

**Comment by SeanMirrsen** [comment]
I think the request is to be able to "vote" 1/2/3/4 like Twitch chat would, on random upcoming effects, without actually having a Twitch chat or being online at all. With gamepad buttons or keyboard shortcuts.

**Comment by MoDerPo** [comment]
oh yeah I had that idea too (#535)
