### ISSUE TITLE
[Effect Suggestion] Insane inflation

### ISSUE THREAD

**Issue by Mercury958** [gta-chaos-mod/ChaosModV#341]
**Name of effect**
Insane inflation

**Duration:**
60 seconds.

**Effect Description**
Increases price of everything that can be bought by 6x.

**Comment by Thunderstorm64** [comment]
Call it Venezuela's economy

**Comment by EliRickard** [comment]
I see this one, if at all possible, which off the top of my head I severely doubt; as highly situational even more-so than poor boy, as throughout the play through of the game there are very few instances that necessitate the purchase of things, poor boy less situational in this case as it has the potential (while unlikely) to inhibit further gameplay before gaining a suitable balance. Whereas this effect being timed would do little to nothing to effect gameplay unless of course it was not timed which would mean the player would, for the games runtime be using a pseudo corrupted price index.

**Comment by Last0xygen** [comment]
Way too situational & money already controlled via "Poor Boy" and "HESOYAM"
