### ISSUE TITLE
[Effect Suggestion] Jesus Rain

### ISSUE THREAD

**Issue by KrownGewl** [gta-chaos-mod/ChaosModV#3424]
**JESUS RAIN**
Potential name(s) for the effect

**Duration**
- [ ] Long
- X Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?

A bunch of Jesus meme people spawn in the air and drop down to the ground. Some are hostile and some are not. Some can explode, some can make the car bounce.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
