### ISSUE TITLE
[Effect Suggestion] Something nice, not expensive

### ISSUE THREAD

**Issue by Olzu2010** [gta-chaos-mod/ChaosModV#3440]
Adds $7 to the player.

**Comment by ReiDaTecnologia** [comment]
LastOxygen's "Duplicate" message incoming! (Probably)

**Comment by Last0xygen** [comment]
@ReiDaTecnologia 😏 
Not really a duplicate but that’s almost „Nothing“
Also the template is there for a reason and. Should have been used :)

**Comment by Olzu2010** [comment]
> @ReiDaTecnologia 😏 Not really a duplicate but that’s almost „Nothing“ Also the template is there for a reason and. Should have been used :)

Why does it need a template? Isn't it simple enough?

**Comment by Olzu2010** [comment]
> @ReiDaTecnologia 😏 Not really a duplicate but that’s almost „Nothing“ Also the template is there for a reason and. Should have been used :)

Also, I had this weird faint feeling I'd seen this request before. You were right, this was actually a duplicate.
