### ISSUE TITLE
[Effect Suggestion] Real crash

### ISSUE THREAD

**Issue by Nr1Griefer** [gta-chaos-mod/ChaosModV#3443]
**Name of effect**
Real crash or crash

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**

It will simply crash the game but before that it will show effect name for two seconds and then it will crash

**Comment by Nr1Griefer** [comment]
Sorry the name should just be real crash or crash

**Comment by Last0xygen** [comment]
No, not a good effect
