### ISSUE TITLE
[Effect Suggestion] Multiple fake teleport

### ISSUE THREAD

**Issue by Nr1Griefer** [gta-chaos-mod/ChaosModV#3444]
**Name of effect**
Said in description

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It will be just like fake fake teleport but it will teleport you 4 - 20 times. Every teleport will add an fake to the name, but at the end it will change the name to "Multiple fake teleport" to not cover the screen with fakes.

**Comment by Last0xygen** [comment]
Duplicate
