### ISSUE TITLE
[Effect Suggestion] Spawn Companion Big Foot

### ISSUE THREAD

**Issue by BrianAwotwi** [gta-chaos-mod/ChaosModV#3448]
**Name of effect**
Spawn Companion Big Foot

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a friendly Big Foot that has super strength. If the player character has enemies around Big Foot will assist in attacking. It only uses its fists to attack. If Big Foot's attack lands on an enemy, the enemy should go flying in a comedic fashion (as if you had 'Fling Player' + 'Ragdoll' invoked).

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
