### ISSUE TITLE
[Effect Suggestion] Spawn Companion CJ

### ISSUE THREAD

**Issue by ternycz** [gta-chaos-mod/ChaosModV#3453]
**Name of effect**
Spawn Companion CJ

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It should spawn friendly CJ using that model from Hood Safari easter egg. His weapon would be carbine rifle and he would assist the player to defend and to attack.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
