### ISSUE TITLE
[Effect Suggestion] Teleport to random hospital 

### ISSUE THREAD

**Issue by Spawc11** [gta-chaos-mod/ChaosModV#3454]
**Name of effect**
Potential name(s) for the effect

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Description of the effect; what should it do?

**Comment by Spawc11** [comment]
Teleport to random hospital

**Comment by RosyMiranto18** [comment]
Add a Fade in and Out when this effect happens, to made it look like a Death and Loading Screen.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2108
