### ISSUE TITLE
[Effect Suggestion] Ignite Vehicle

### ISSUE THREAD

**Issue by Mattsib01** [gta-chaos-mod/ChaosModV#3455]
Name Of Effect
Ignite Vehicle
**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Ignite the current vehicle the player is in.

**Comment by ReiDaTecnologia** [comment]
The effect "Ignite Player" already do that when the player is in a vehicle (The player just get on fire if on foot).

**Comment by Last0xygen** [comment]
Yes, already part of „ignite player“
