### ISSUE TITLE
Fake restart

### ISSUE THREAD

**Issue by Stitchy77** [gta-chaos-mod/ChaosModV#3457]
**Name of effect**
Potential name(s) for the effect

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Basically, it "restarts" the game, plays out the first prologue cutscene, and there's a splash text or something that says something along the lines of "lets take a step back" or "lets restart".

**Comment by Last0xygen** [comment]
Duplicate
