### ISSUE TITLE
Come with me if you want to live 

### ISSUE THREAD

**Issue by Amessenger3** [gta-chaos-mod/ChaosModV#3458]
Name of effect:
Come with me if you want to live 
Alternate name(s) for the effect:
Judgement day
T2

Choose one and replace the corresponding "[ ]" with "[X]", so it looks like a checked checkbox in the "Preview" tab.
-->
**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Effect will change players clothes to the following:
Black leather jacket 
Black leather trowsers 
Black biker boots 
Grey t-shirt 
Black sunglasses 

Will also put the player and one companion onto a  2 seater bike, if they are already in a vehicle it will change the vehicle to the 2 seater bike and both player and one companion will be on it. 

If there is a second companion, they will spawn in a police vehicle and continue to follow the player.

**Comment by ReiDaTecnologia** [comment]
Aren't this basically "Jesus take the wheel"?

**Comment by Amessenger3** [comment]
> Aren't this basically "Jesus take the wheel"?

Shouldn't be.
With that mod, jesus spawns in a small car and you end up in a passenger seat with him driving.
With this, you remain in control of the vehicle and it's jsut changed to a bike that can accommodate one passenger. It also changes your clothes which is not done with jesus take the wheel.
Further to that a secondary effect is added for a second companion of them spawning in a trooper car which does not happen with jesus take the wheel.
I hope I explained it a bit better here as it should have a pretty different effect to jesus take the wheel

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn", "ped spawn" or "ped driving vehicle" effects. (We have enough already.)
