### ISSUE TITLE
[Bug] Realistic hacking flickers

### ISSUE THREAD

**Issue by Acorlan145** [gta-chaos-mod/ChaosModV#3459]
**Describe the bug**
Realistic hacking flickers ono the dev github builds. (idk how to check what one specifically I downloaded mine from)

**To Reproduce**
Get realistic hacking  -> Maybe this is just my pc being bad, id assume something like this would have been found already. 

**Crash Dump (if a game crash)**
N/A

**Comment by pongo1231** [comment]
Can't replicate on the newest commit. Can you download the [latest artifact](https://github.com/gta-chaos-mod/ChaosModV/actions/runs/5100894826) and try again?

**Comment by ReiDaTecnologia** [comment]
There is this two videos that he sent on discord if it matters pongo
https://discord.com/channels/785656433529716757/785663589356404748/1112428482060886096
https://discord.com/channels/785656433529716757/785663589356404748/1112429049302757467

**Comment by Acorlan145** [comment]
Still happens, latest artifact, fresh GTA V install. https://discord.com/channels/785656433529716757/785663589356404748/1112451029611577385
