### ISSUE TITLE
[Effect Suggestion] Another version of griefer jesus

### ISSUE THREAD

**Issue by Heiijeiio** [gta-chaos-mod/ChaosModV#3463]
**Spawn Griefer jesus 2.0**

**Duration**
- [X] Long
- [X] Short
- [X] No duration

**Effect Description**
Spawns a Jesus right in front of the player/his car and applies a short slow-motion effect similar to when the cars get flung away during the mission: (Legal Trouble), and as Jesus kicks the car/player they get flung away backwards, he should still be able to follow the player after the animation.

**Comment by MoneyWasted** [comment]
not adding any more variations of jesus
