### ISSUE TITLE
[Effect Suggestion] Mrs. Baker call

### ISSUE THREAD

**Issue by NicholasC2** [gta-chaos-mod/ChaosModV#3469]
**Mrs. Baker Call**
Hello! this is Agetha
Agetha Call
Mrs. Baker Call

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Play The Agetha Baker Call and make it unskippable

**Comment by ReiDaTecnologia** [comment]
LastOxygen's duplicate message incoming!

**Comment by NicholasC2** [comment]
wdm?

**Comment by SRG27** [comment]
> wdm?

This has been suggested million times. There's also a pending pull request that adds this effect.

**Comment by NicholasC2** [comment]
Oh lol

**Comment by Last0xygen** [comment]
Duplicate ;)
