### ISSUE TITLE
[Effect Suggestion] GTA 1

### ISSUE THREAD

**Issue by davidman2** [gta-chaos-mod/ChaosModV#3471]
**Name of effect**
GTA 1
**Duration**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
Simple: same thing as GTA 2 But now with potato effect cuz gta 1 is older and has "worse graphics" but imo it's a nice combo and it makes a bit sense.

**Comment by Last0xygen** [comment]
Combos won’t get its own effect, as they’re funnier when they happen naturally
