### ISSUE TITLE
Unable to Access Workshop Tab (Pre 2.0b1)

### ISSUE THREAD

**Issue by Realest-Orange** [gta-chaos-mod/ChaosModV#3492]
After downloading Preview Version 2.0b1 and launching the config executable I went to the workshop tab and was given this error:
![Screenshot 2023-07-17 201349](https://github.com/gta-chaos-mod/ChaosModV/assets/139839199/e4643073-4610-43f0-b057-a5cdc3babe72)
(I have redownloaded and checked my internet connection)

Reproduce:
Downloading the prelease, unzipping the file, launching "ChaosModConfig.exe", and going to the "Workshop" tab.

**Comment by ReiDaTecnologia** [comment]
It might be a server-side issue but only pongo to confirm.

**Comment by pongo1231** [comment]
The SSL certs were expired, should be working now however. Feel free to reopen this issue if the issue still occurs.
