### ISSUE TITLE
[Effect Suggestion] All peds are Call Me Kevin

### ISSUE THREAD

**Issue by GitKoosha** [gta-chaos-mod/ChaosModV#3495]
**Name of effect**
Hey there, Friends!

**Duration**
- [X] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Replace the player's/the peds'/everyone's voicelines with random audio from Call Me Kevin's videos. (take a guess how I got introduced to the mod lol) It can be stuff like his intro or some of his well-known quotes like "Awh, for feck's sake."

**Comment by ReiDaTecnologia** [comment]
The devs don't like adding third-pary files so it's unlikely

**Comment by MoneyWasted** [comment]
> The devs don't like adding third-party files so it's unlikely

this
