### ISSUE TITLE
[Bug] Fake Teleport matters in mission

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#350]
Even when Teleport was "Fake" mission still fails

Any mission, where big distance scripts "Mission Fail", should be active

**Comment by pongo1231** [comment]
It should already spoof the player's position to prevent mission fails. Can you provide examples where this is causing mission fails?

**Comment by JustTunerYT** [comment]
[https://dropmefiles.com/kANGX](url) Low quality due to low PC perfomance. But you can still see the problem

**Comment by Terrain2** [comment]
https://clips.twitch.tv/FlaccidSpoopyCoyoteOpieOP

**Comment by JustTunerYT** [comment]
Already fixed. No one closed it yet, so i will
