### ISSUE TITLE
[Effect Suggestion] Agatha Baker is calling

### ISSUE THREAD

**Issue by MoltenSack** [gta-chaos-mod/ChaosModV#3508]
**Name of effect**
Potential name(s) for the effect
Agatha Baker is calling!, Oh no Agatha Baker, Agatha Baker is Ringing
**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Agatha Baker calls you

**Comment by MoltenSack** [comment]
i just thought of this and i hope is could be added as an effect

**Comment by ReiDaTecnologia** [comment]
A lot of people thought of this as well xD

**Comment by MoltenSack** [comment]
damn, it's a good idea for an effect, right?

**Comment by MoltenSack** [comment]
or no?

**Comment by ReiDaTecnologia** [comment]
As a duplicate, probably not man

**Comment by ReiDaTecnologia** [comment]
Anyway there is a PR to add it anyway
https://github.com/gta-chaos-mod/ChaosModV/pull/3398

**Comment by MoltenSack** [comment]
oh damn.

**Comment by MoltenSack** [comment]
my apologies i did not know it was already/or going to be an effect.

**Comment by ReiDaTecnologia** [comment]
Nah dw, it is normal
