### ISSUE TITLE
[Effect Suggestion] Implode Vehicle

### ISSUE THREAD

**Issue by DarkViperAUfan** [gta-chaos-mod/ChaosModV#3517]
**Name of effect**
Implode Vehicles.
Titanic Sub Simulator.

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Implode/Crush all vehicles within a 50 foot radius from Trevor Michael and Franklin. If the characters happen to be inside the car they will instantly die. There should also be a loud *BOOM* sound effect.

**Comment by Last0xygen** [comment]
Closed as spam

**Comment by DarkViperAUfan** [comment]
I didn't mean to spam

**Comment by DarkViperAUfan** [comment]
I didn't know if I was supposed to leave closed or open

**Comment by DarkViperAUfan** [comment]
> Closed as spam

I didn't know if I should leave open or closed
