### ISSUE TITLE
[Effect Suggestion] Implode Vehicle

### ISSUE THREAD

**Issue by DarkViperAUfan** [gta-chaos-mod/ChaosModV#3518]
**Name of effect**
Implosion
Car Crusher 69
Titanic Submarine Simulator.
**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Implode/Crush all vehicles within a 500 foot radius from Trevor Michael and Franklin. If the characters happen to be inside the car they will instantly die. There should also be a loud BOOM sound effect.[sorry for uploading twice my other one keeps glitching out on herr because my mobile data is garbage. Sorry for uploading twice I also made a slight change to radius.]

**Comment by SRG27** [comment]
Keep it open
