### ISSUE TITLE
[Bug] Limitation of Lua effect shortcuts

### ISSUE THREAD

**Issue by SRG27** [gta-chaos-mod/ChaosModV#3525]
**Describe the bug**
[The mod doesn't load](https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Components/LuaScripts.cpp#L982) shortcuts for Lua effects which require pressing Ctrl, shift or alt because of the way it stores whether a shortcut requires pressing mentioned buttons.

**Comment by Rylxnd** [comment]
This isn’t a bug, but a feature :)

**Comment by Rylxnd** [comment]
What kind of keycode are you trying to set?

**Comment by SRG27** [comment]
#3270 made it so that you can have more shortcuts (before it, you couldn't have "modifier" keys). Now, whether the shortcut requires holding Ctrl, shift or alt is saved by adding 1024, 512 or 256 to the key code.

The code I linked prevents any shortcut with value over 256 from being loaded as a shortcut for a Lua effect, so any shortcut that requires pressing a "modifier" key isn't loaded and won't start the Lua effect that uses the shortcut.

For example, if I wanted to add "Ctrl+Shift+F10" as a shortcut to a normal effect it would get saved as 1657 and the mod would start the effect if I press the shortcut, however if I do the same with a Lua effect, it wouldn't start the effect, because the mod doesn't set the shortcutKeycode attribute for the effect.

**Comment by pongo1231** [comment]
Implemented in #39e3f753391a7eab0fb88bd6b4b10bf63b225228
