### ISSUE TITLE
Launch Player Forward

### ISSUE THREAD

**Issue by M3TRQ** [gta-chaos-mod/ChaosModV#3530]
Launch player forward - just like launch player upward, but instead you launch the player forward, or whichever way the player is facing

**Comment by ReiDaTecnologia** [comment]
I'm pretty sure "Fling player" already do that

**Comment by M3TRQ** [comment]
Not really because “fling player” flings the player in a random direction rather that just forward. The idea would be to launch the player at an absurd speed forwards, making them (hopefully) crash in an object at an extreme speed.

**Comment by ReiDaTecnologia** [comment]
So it will be just Fling Player but the direction is hardcoded? idk man, don't sound unique enough to me

**Comment by MoneyWasted** [comment]
Too similar to other effects that are already implemented.
