### ISSUE TITLE
Spawn Subpar Greifer Jesus

### ISSUE THREAD

**Issue by M3TRQ** [gta-chaos-mod/ChaosModV#3535]
Spawn Subpar Greifer Jesus - spawn Jesus with a SNS pistol instead of a rail-gun. Jesus will still try and kill the player. To make up for his lack of firepower, he should have an increased health pool, requiring 5 headshots to kill.

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
