### ISSUE TITLE
[Feature Suggestion] Search function for Effect Configurator

### ISSUE THREAD

**Issue by Chris6ix** [gta-chaos-mod/ChaosModV#3539]
**Is your feature request related to a problem? Please describe.**
Finding a specific effect in the configurator can be quite annoying as there are so many.

**Describe the solution you'd like**
A simple search bar that would allow you to simply search for a specific effect so that you can quickly disable/edit it.

**Describe alternatives you've considered**
No Alternative. Plus, the more effects the mod gets, the more beneficial a search function is going to be.

**Additional context**
/

**Comment by pongo1231** [comment]
Implemented in 8ce52da22856e433be2aed0ddf667a5fad735df1.

**Comment by Chris6ix** [comment]
Thank you :)
