### ISSUE TITLE
[Bug] 2.0b3 only spawns one effect

### ISSUE THREAD

**Issue by IronClaw99** [gta-chaos-mod/ChaosModV#3542]
**Describe the bug**
This preview version of the Chaos Mod only spawns one effect, either "One Hit KO" or "Now This Is Some Tire' Poppin"

**To Reproduce**
I tried using the Chaos Mod Config and disable and then re-enable every effect.

**Comment by pongo1231** [comment]
Fixed in 2.0b4 (72ff1c154357fbaa244b3a35f258cbb2690efd08 in specific)
