### ISSUE TITLE
[Effect Suggestion] new visual for nothing

### ISSUE THREAD

**Issue by iforgornglfrfr** [gta-chaos-mod/ChaosModV#3547]
**Name of effect**
nothing

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
make nothing say to the person dont *no duration effect* for example: dont flip all vehicles, dont spawn griefer jesus

**Comment by MoneyWasted** [comment]
This is already a feature with the "Nothing" effect and was added to the mod on July 19th, 2023.
