### ISSUE TITLE
[Bug] "Black Hole" effect causes game to crash.

### ISSUE THREAD

**Issue by IronClaw99** [gta-chaos-mod/ChaosModV#3554]
**Describe the bug**
Whenever the "Black Hole" effect is spawned, the game crashes.

**To Reproduce**
I did some testing by choosing the effect manually.

**Comment by Rylxnd** [comment]
I was able to replicate this. I’ll take a look at it tomorrow to see what could be causing the crash. Thanks for the report.

**Comment by IronClaw99** [comment]
Guess I'll have to disable the effect until the issue is fixed.

**Comment by we-script** [comment]
doesn't happen for me thats weird
