### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by SilverDash** [gta-chaos-mod/ChaosModV#357]
**Name of effect**
Jesus rave music on jesus effect spawns.

I noticed a silly editing trick Viper has done in his videos, and I'm surprised it's not actually in the mod!

**Comment by pongo1231** [comment]
There aren't be any custom sounds included with the mod by default (and it'll very likely stay that way). This can be very easily added as a custom sound by people themselves (open the config utility, navigate to the effect you want to play a sound for and click on the "..." button for more information) and included in a custom "soundpack" of some sort though.
