### ISSUE TITLE
[Effect Suggestion] Daddy Issues or Daddy's Little Girl

### ISSUE THREAD

**Issue by Richm246** [gta-chaos-mod/ChaosModV#3577]
**Daddy Issues or Daddy's Little Girl**

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
The same as Jealous Jimmy but Tracey instead

**Comment by ReiDaTecnologia** [comment]
Actually R* was jokingly referring to jimmy when they named the mission "Daddy's Little Girl"
A subtle reference

**Comment by Richm246** [comment]
> Actually R* was jokingly referring to jimmy when they named the mission "Daddy's Little Girl" A subtle reference

Yeah, that's why I picked both for a possible name :P

**Comment by Richm246** [comment]
I made this myself
