### ISSUE TITLE
[Bug] Gears.asi (Manual Transmission mod) not supported by Chaos Mod?

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#3580]
Should be simple to describe how unsupported it is by just saying that gears.asi crashes when entering the car with chaos mod onboard. Although there dont have anything to be an issue running both, i think its the problem regarding overlay, because MTmod uses that too. I thought do a taxi on a wheel with chaos mod, but all hopes broke because of that issue...

**Comment by Rylxnd** [comment]
Can't replicate this. Join the [discord](https://discord.gg/ShssNXBSsx) and shoot me a DM with your logs and Gears.asi configs.
