### ISSUE TITLE
[Effect Suggestion] Spawn Hurse "where is the funeral?

### ISSUE THREAD

**Issue by EliRickard** [gta-chaos-mod/ChaosModV#359]
**Name of effect**
Where is the Funeral?

**Effect Description**
Should Spawn "LURCHER" at Player Coords, can easily be added to VehSpawner and EffectsInfo and is a reference to San Andreas where this was a cheat code. Would be happy to do this myself, if you get busy :)

**Comment by kolyaventuri** [comment]
We're always happy to review PRs and accept contributions if you wanna give implementing it a go!

**Comment by Last0xygen** [comment]
implemented 👍
