### ISSUE TITLE
[Bug] Fake death can cause a real death when executed just wrong

### ISSUE THREAD

**Issue by Terrain2** [gta-chaos-mod/ChaosModV#361]
**Describe the bug**
When you get a fake death in a vehicle you may explode and blast away, the player is not invincible and can still die at this point, presumably this is the same for the ragdoll after the suicide animation, and although harder to reproduce, it's probably the same for when you just die without anything happening, though you'd need someone shooting at you or something like that to really check this

**To Reproduce**
None. It's inconsistent and dependent on luck for which animation, but see [this clip](https://clips.twitch.tv/SuccessfulStupidSangOpieOP)

**Comment by kolyaventuri** [comment]
Fixed in #363. Ignore the reference to the sleepytime effect PR, that was in error
