### ISSUE TITLE
YOU SHALL REMOVE ALL FEMALE AND REPLACE THEM WITH MEN AND DONT TELL ANYONE (AND THE STORY LINE CHARACTERS)

### ISSUE THREAD

**Issue by pillolw5433** [gta-chaos-mod/ChaosModV#3625]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Veloscocity** [comment]
This sounds like a bad idea imo

**Comment by pillolw5433** [comment]
> this guy definitely identifies as an

**Comment by pillolw5433** [comment]
> this guy definitely identifies as an “Alpha Male”

this guy definitely identifies as a "giga chad"
