### ISSUE TITLE
[Bug] workshop effects and sounds not working

### ISSUE THREAD

**Issue by Lizardiez** [gta-chaos-mod/ChaosModV#3632]
I have the workshop items installed but they do not show up at all, like not even in the section where you can enable/disable mods. Also, none of the workshop sounds either

**Comment by pongo1231** [comment]
Can you post your chaoslog.txt inside the chaosmod folder?

**Comment by Lizardiez** [comment]
> Can you post your chaoslog.txt inside the chaosmod folder? Hi, Pongo thanks for the reply, basically for whatever reason my Epic games installed the game twice so I was editing the wrong game directory.
