### ISSUE TITLE
[Effect Suggestion] Spawn Anti-griefer Jesus

### ISSUE THREAD

**Issue by Cerise-H** [gta-chaos-mod/ChaosModV#3639]
**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
It's basically the same as Extreme Griefer Jesus. But instead of an Oppressor MK2, He spawns with a Toreador/ Stromberg. If he gets out of the vehicle, his weapon will be a Heavy Sniper (MK2 if possible), Because that's the most used weapon besides explosives that is used against Griefers. 

Edit: He's also friendly. I almost missed the most important part.

**Comment by ReiDaTecnologia** [comment]
I'm pretty sure it would be just called "Spawn Jesus" xD

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
