### ISSUE TITLE
[Effect Suggestion]christhian christmas

### ISSUE THREAD

**Issue by toastepic** [gta-chaos-mod/ChaosModV#3649]
**Name of effect**
Potential name(s) for the effect

**Duration**
- [x] Long
- [ ] Short
- [ ] No duration

**Effect Description**
Description of the effect; what should it do?
All the nearby peds will become extreme griefer jesus/griefer jesus and when the player dies or he gets away they become normal again but the griefer jesuses will only have one shot and the extreme griefer jesuses will all have only the missile oppresor and will only get 2 rockets

**Comment by Last0xygen** [comment]
Duplicate
