### ISSUE TITLE
[Effect Suggestion] Spawn Sacrilegious Steve

### ISSUE THREAD

**Issue by McHammer12** [gta-chaos-mod/ChaosModV#3651]
**Name of effect** Sacrilegious Steve

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Description of the effect; what should it do?
As with all the other commands which spawns someone, this effect will spawn an NPC of Steve which will attack you, With this one it'll attack you with a sniper rifle

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
