### ISSUE TITLE
[Effect Suggestion] No Signal

### ISSUE THREAD

**Issue by D3DH4CK3R** [gta-chaos-mod/ChaosModV#3658]
**Name of effect**
No Signal

**Duration**
- [ ] Long
- [X] Short
- [ ] No duration

**Effect Description**
The Screen Will Be No Signal

**Comment by ReiDaTecnologia** [comment]
Don't the "No Signal" message change depending of the monitor and the language it is set? that would make the effect not universal and not fool people who know how their monitor's "No Signal" looks like.

**Comment by MoneyWasted** [comment]
As @ReiDaTecnologia pointed out, there are numerous cases where this would not be effective.
