### ISSUE TITLE
[Effect Suggestion] Nap-Time

### ISSUE THREAD

**Issue by EliRickard** [gta-chaos-mod/ChaosModV#366]
**Name of effect**
Nap Time

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
Effect halts ALL cars (inc player) and pushes driver and passengers out, sets time to 9PM, and forces everyone except player to lay down. 

IMPORTANT NOTE:
I have already made this effect but due to me not being a native user of GitHub, it was an included commit in another PR of mine for another effect by mistake, i'm not sure how to submit it separately, github is not my platform of choice.

**Comment by ProfessorBiddle** [comment]
I had trouble figuring this out as well when I first started, you need to
make a new branch based off of the main chaos mod, and put the effect there
with a new PR

**Comment by Da-Best** [comment]
So as i understand you want to disable the player movements for a long duration?

**Comment by Last0xygen** [comment]
„Stop and Stare“ + „everybody ragdolls“
