### ISSUE TITLE
[Effect Suggestion] orbital strike inbound 

### ISSUE THREAD

**Issue by drkNXSUS** [gta-chaos-mod/ChaosModV#3662]
**Name of effect
Orbital strike inbound, alien attack

**Duration**
- [✔️] Long
- [ ] Short
- [ ] No duration

**Effect Description**
If you need to contact me, please use the discord drkNXSUS 

Like meteor shower, but instead, it should be orbital strikes from gta online that strike around the player in random places every 3 ish seconds. So there is then a chance that the player will get hit by one of them. This could last for a minute or so, and so the player will have to drive to try and avoid the incoming strikes.

**Comment by MoneyWasted** [comment]
This is the same as the "Airstrike Inbound" effect.
