### ISSUE TITLE
[Effect Suggestion] Avengers Assemble!

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3665]
**Name of effect**
Avengers Assemble! 

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
This effect causes multiple companions to spawn: Jesus, Chimp, Brad, Impotent Rage, and Alien

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
