### ISSUE TITLE
[Effect Suggestion] Spawn Furious Franklin 

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3667]
**Name of effect**
Spawn Furious Franklin 

**Duration**
- [ ] Long
- [ ] Short
- [x] No duration

**Effect Description**
Spawns Franklin in his Car, who tries to run the player over.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
