### ISSUE TITLE
[Effect Suggestion] Spawn Super Extreme Griefer Jesus 

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3668]
**Name of effect**
Spawn Super Extreme Griefer Jesus 

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns Griefer Jesus with a Kanjali Tank from GTA Online

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
