### ISSUE TITLE
[Effect Suggestion] Spawn Phantom Wedge 

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3669]
**Name of effect**
Spawn Phantom Wedge 

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns the Phantom Wedge from GTA Online

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
