### ISSUE TITLE
[Effect Suggestion] Let's see if you bastards can do 90! (reference to Back to the Future)

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3670]
**Name of effect**
Let's see if you bastards can do 90!

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a Deluxo from GTA Online

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
