### ISSUE TITLE
[Effect Suggestion] And what exactly is an Arnold Schwarzenegger? (reference to Kight Rider)

### ISSUE THREAD

**Issue by MRCHICKENLP** [gta-chaos-mod/ChaosModV#3671]
**Name of effect**
And what exactly is an Arnold Schwarzenegger?

**Duration**
- [ ] Long
- [ ] Short
- [X] No duration

**Effect Description**
Spawns a Ruiner 2000 (Kitt) from GTA Online

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
