### ISSUE TITLE
[Effect Suggestion] Monkey See Monkey Do

### ISSUE THREAD

**Issue by 9ONight** [gta-chaos-mod/ChaosModV#3674]
**Name of effect**
Monkey See Monkey Do

**Duration**
- [ ] Long
- [x] Short
- [ ] No duration

**Effect Description**
An invincible chimp with a machine gun/grenade launcher shows up and does nothing until a certain amount of people are killed (between 1 and 30) and then the chimp kills for the player or kills the player depending on the amount that is killed. The effect lasts for 30 seconds which then the chimp explodes and dies.

**Comment by ReiDaTecnologia** [comment]
average effect suggestion frfr

**Comment by 9ONight** [comment]
> average effect suggestion frfr

Sorry it's my first time and i'm getting used to how this site works.

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
