### ISSUE TITLE
[Feature Suggestion] Discord Announce vote

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [gta-chaos-mod/ChaosModV#3679]
When a mod get chosen, it would be nice if it spit out in the channel which mod got selected so then if you crash, then you can look in the channel and see which mod crashed.

**Comment by SRG27** [comment]
You can tell which mod was last triggered in the log file in the chaosmod folder, though having this feature might still be nice.

**Comment by MoneyWasted** [comment]
As mentioned by @ljbajic you can see all of the effects executed inside the log file in the chaosmod folder. This is unneeded.
