### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by DeepVoiceUK** [gta-chaos-mod/ChaosModV#370]
**Name of effect**
Free Willy

**Duration if timed effect (long or short timed?)**
N/A

**Effect Description**
Spawn Orca whale directly above player (there is one on submarine mission on single player)

**Comment by EliRickard** [comment]
This sounds somewhat similar to the existing Whale Rain effect the only differences being it is a single instance above the player and it's a different model, would it have any interesting mechanics? Or be similar to the other effect in that the whales upon spawning are completely dormant?

**Comment by SeanMirrsen** [comment]
If you're going to reference Free Willy, might as well do something interesting.  
  
Make the effect spawn the Orca right above and behind the camera, and _launch_ it forward, slowing down time to 0.5x for several seconds as it flies overhead.

**Comment by EliRickard** [comment]
> If you're going to reference Free Willy, might as well do something interesting.  
> 
>   
> 
> Make the effect spawn the Orca right above and behind the camera, and _launch_ it forward, slowing down time to 0.5x for several seconds as it flies overhead. Like the final "jump to freedom" scene in the movie.

I had to do a double check but unfortunately there is no native, whale jump animation so it would have to be done in a kinda hacky way like you suggested with the half time launch forward up and then down again style mechanic; but worth a try I guess that could be interesting.
