### ISSUE TITLE
[Bug] GetAllVehs() doesn't return all vehicles after the first call

### ISSUE THREAD

**Issue by juhana** [gta-chaos-mod/ChaosModV#375]
**Describe the bug**

`GetAllVehs()` function doesn't work correctly. It seems that after it has been called the first time any subsequent calls return only the vehicles that were included when it was called the first time even though new vehicles have spawned nearby. Some kind of caching issue? It's also possible that it's not stuck indefinitely but something causes it to pick up new vehicles again later.

I believe this is what's causing people to report that effects like Jumpy Vehicles and Vehicles Explode On Impact don't work for them.

**To Reproduce**

1. Start the Jumpy Vehicles effect, wait for it to finish. Don't stop it by restarting the mod.
2. Take a car that was affected and drive it to another area where new vehicles have spawned
4. Start the Jumpy Vehicles effect again. The only vehicle that's affected is the car that you brought from the first effect's area.

**Comment by TheRealAyCe** [comment]
Isn't the list iterated in GetAllVehs cached at the start of the frame or at least at the first call, as an optimization? Isn't that at least one of the reasons why you are supposed to WAIT(0) after spawning?

**Comment by pongo1231** [comment]
Fixed in 10f6f6a.
