### ISSUE TITLE
[Effect Suggestion] Spawn Companion Jesus

### ISSUE THREAD

**Issue by Jornker** [gta-chaos-mod/ChaosModV#391]
**Name of effect**
spawn companion Jesus

**Effect Description**
Spawn Greifer Jesus as a companion.

**Comment by TheRealAyCe** [comment]
@Last0xygen  Can you edit the title please?

**Comment by Last0xygen** [comment]
> @Last0xygen Can you edit the title please?

Nope, don’t have those rights.
@Jornker please adjust the title :)

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
