### ISSUE TITLE
[Effect Suggestion] Avengers Assemble

### ISSUE THREAD

**Issue by Jornker** [gta-chaos-mod/ChaosModV#392]
**Name of effect**
Avengers Assemble

**Effect Description**
Incredibly rare chance, spawns impotent rage, greifer Jesus jealous jimmy

**Comment by TheRealAyCe** [comment]
@Last0xygen Can you edit the title please?

**Comment by MoneyWasted** [comment]
We are not currently adding "ped spawning" effects. (We have enough already.)
