### ISSUE TITLE
[Effect Suggestion] Fake Extreme Griefer Jesus

### ISSUE THREAD

**Issue by NoMercy194** [gta-chaos-mod/ChaosModV#396]
**Fake Extreme Griefer Jesus**

**just like every fake effect, spawns a fake extreme griefer jesus then gets despawned**

**Comment by svetimsalis** [comment]
Perhaps instead of despawn it could be possible to make so he shoots but does no damage to anyone?

**Comment by NoMercy194** [comment]
> Perhaps instead of despawn it could be possible to make so he shoots but does no damage to anyone?

yeah not a bad idea

**Comment by Numi43** [comment]
Or maybe he could shoot flares?

**Comment by NoMercy194** [comment]
> Or maybe he could shoot flares?

probably

**Comment by kolyaventuri** [comment]
Alternatively, healing bullets

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
