### ISSUE TITLE
Teleport to top of map

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#400]
**Teleport to top of map**

**Get this, it teleports you to the top of the map**

**Comment by trollbreeder** [comment]
like Teleport to Heaven, but only on the Y axis?

**Comment by anto4440** [comment]
No, its as in you open the map and scroll all the way up, the most 'north' that isnt ocean or a rock.

**Comment by Numi43** [comment]
Would be pretty much the same as if you said "Teleport to Paleto Bay Shoreline". Honestly, we kind of got teleport to Mount Chiliad for that.

**Comment by anto4440** [comment]
Yeah, that is pretty much the case. Also why i didnt make a Teleport to bottom of map, its to close to tp to ls airport

**Comment by Numi43** [comment]
Honestly tho, spawning at higher Y coordinate would be funny. Although immediate death.

**Comment by anto4440** [comment]
But Thats just teleport to heaven 2.0. Nothing interesting.

**Comment by Numi43** [comment]
If anything, that´s launch player up 2.0

**Comment by anto4440** [comment]
Precisely.

**Comment by anto4440** [comment]
Closed for relavance.
