### ISSUE TITLE
Bouncing Bullets

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#406]
**Name of effect**
Bouncing Bullets

Short (30 sec)

**Whenever a shot/bullet hits a surface (players included), the will bounce off of that surface. Bullets can still hurt players and npcs. Bullets can bouce 5 times before breking.**

**Comment by Last0xygen** [comment]
Not possible, found no natives for this

**Comment by ProfessorBiddle** [comment]
I think this one probably is possible to an extent, but it would require
some experimentation and will probably be pretty rudimentary and assume all
surfaces are at right angles to the world axis. I'll look into it.

**Comment by anto4440** [comment]
> I think this one probably is possible to an extent, but it would require some experimentation and will probably be pretty rudimentary and assume all surfaces are at right angles to the world axis. I'll look into it.

Well, good luck pal... I think youre probably making a bit too much out of  it, but i wont stop you from trying..

**Comment by ProfessorBiddle** [comment]
It's one of the pretty rare cool ideas now that the volume of suggestions
is so high. It's at least worth a shot.

**Comment by SeanMirrsen** [comment]
I think there should be a native for firing a particular weapon (say, the same weapon the player is holding), and there is probably some way to return the position where the player's last shot landed. Combine the two and you could make it so that bullets (and more silly projectiles like rockets) "ricochet" by firing a copy of the player's current weapon at a random angle out of the last impact point.

**Comment by Last0xygen** [comment]
> I think there should be a native for firing a particular weapon (say, the same weapon the player is holding) out of a specific point (maybe Airstrike Inbound uses it?), and there is probably some way to return the position where the player's last shot landed (Portal Guns probably uses it). Combine the two and you could make it so that bullets (and more silly projectiles like rockets) "ricochet" by firing a copy of the player's current weapon at a random angle out of the last impact point.

This could result in the player dying because it perfectly ricochet back at him because of some random angle.
Getting the impact point would not be the biggest concern, but getting the angle of the surface area, combining all that and so on, just to make this effect work for this „little payout“.

**Comment by SeanMirrsen** [comment]
> This could result in the player dying because it perfectly ricochet back at him because of some random angle.

No, see, that is what people normally refer to as "fun" and "chaotic". :)

**Comment by anto4440** [comment]
I agree ;)
