### ISSUE TITLE
Bad Traffic

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#407]
**Name of effect**
Bad traffic

Short (30 sec)

**Effect Description**
Makes every spawned vehicle terrible. Which cars you will mark as terrible is up to you.

**Comment by Last0xygen** [comment]
same as https://github.com/gta-chaos-mod/ChaosModV/issues/482

**Comment by anto4440** [comment]
Shouldnt it be #482 that was a duplicate of mine? (Since it has a higher number im assuming mine was before it)

**Comment by Last0xygen** [comment]
> Shouldnt it be #482 that was a duplicate of mine? (Since it has a higher number im assuming mine was before it)

„Duplication“ without any judging, in the other PR more things have been said, didn’t want the conversation to be „hidden“ just because this existed before.

**Comment by anto4440** [comment]
Ok thats fair.

Den man. 22. mar. 2021 kl. 11.46 skrev Last0xygen ***@***.***
