### ISSUE TITLE
Beater Vehicles

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#414]
**Name of effect**
Beater Vehicles

Short

**Effect Description**
This effect will affect every loaded vehicle: Every 2-5 seconds, a random part of the vehicle breaks off (bumper, door ect.). Tires can also pop. The effect will not break any vital part of the vehicle (Engines, Plane wings ect.).

**Comment by Numi43** [comment]
Actually, this would be more hilarious if it was "Beater Vehicles"... basically only Beater Tornado and Voodoo (which is Beater by default) would spawn. And they are like the slowest vehicles in the game too.

**Comment by anto4440** [comment]
Thank you, i really couldnt remember the name i was looking for

**Comment by Last0xygen** [comment]
Already implemented with "Crumbling vehicles"
