### ISSUE TITLE
Gta Online Vehicles

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#415]
**Name of effect**
Gta Online Vehicles

Short

**Effect Description**
Only 'Gta Online only' Cars can spawn in traffic.

**Comment by Numi43** [comment]
Maybe it could be named Online Vehicles then?

**Comment by anto4440** [comment]
Your absolutely right.

**Comment by Last0xygen** [comment]
already requested several times (in all variations :D)
Currently not possible without big perfomance issues  and/or already implemented with "random traffic"
