### ISSUE TITLE
[Effect Suggestion] No Wheels

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#416]
**Name of effect**
Remove Nearby Wheels

**Effect Description**
Removes the wheels of all nearby vehicles.  Not by popping them, but by deleting the wheels.

**Comment by TheRealAyCe** [comment]
Here they explain that this is probably impossible: https://github.com/gta-chaos-mod/ChaosModV/issues/107

**Comment by Last0xygen** [comment]
Duplicate #107
