### ISSUE TITLE
[Effect Suggestion] Detonation

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#418]
**Name of effect**
Detonation

**Duration**
Short

**Effect Description**
Starts a timer for 5 seconds.  After 5 seconds is up, detonate the current vehicle the player is driving.

**Comment by Last0xygen** [comment]
Mix of „Explode current vehicle“ and „Need For Speed“

**Comment by ThatDeathbat** [comment]
> Already exists as „Explode current vehicle“ and/or „Need For Speed“

This gives a chance for the player to get away from the car before it explodes

**Comment by TheRealAyCe** [comment]
I agree that this would be better than "explode current vehicle". Can we update the effect to do beeping for a few seconds to warn the player?

**Comment by ThatDeathbat** [comment]
@pongo1231 
Read above comment

**Comment by SeanMirrsen** [comment]
Pongo is the owner of the repository. You don't need to ping him, he is notified of everything.
