### ISSUE TITLE
[Effect Suggestion] Spawn Hostile Juggernaut

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#426]
**Name**
Spawn Juggernaut

**Effect Description**
Spawns a juggernaut with ballistic armor and a minigun.

**Comment by ThatDeathbat** [comment]
It’s like Griefer Jesus, but has armor and a Minigun

**Comment by ProfessorBiddle** [comment]
Alternately a positive effect could be 'Give Ballistic Equipment" which
puts heavy armor on you and gives you an infinite ammo machine gun for a
duration like the online ballistic equipment

**Comment by ThatDeathbat** [comment]
> Alternately a positive effect could be 'Give Ballistic Equipment" which puts heavy armor on you and gives you an infinite ammo machine gun for a duration like the online ballistic equipment

I added that as a request

**Comment by TheRealAyCe** [comment]
Oh look it's my suggestion :P https://github.com/gta-chaos-mod/ChaosModV/issues/98
