### ISSUE TITLE
[Effect Suggestion] Healing Bullets

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#435]
**Name**
Life Stealing Shots

**Duration**
Short

**Description**
Half of all the damage dealt by any gun the player is using is converted to health for the player.  

• **Shots should heal for half the damage the bullet does**

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/193

**Comment by TheRealAyCe** [comment]
And similar to this: https://github.com/gta-chaos-mod/ChaosModV/issues/33
