### ISSUE TITLE
Freinds till the end

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#438]
**Name of effect**
Freinds till the end/Come on, everybody/Safety in numbers

Long

**Effect Description**
For every ally (Including the ones spawned in with mods), you and they get a small (10% as an example) health bonus, and their/your bullets do slightly more damage. This stacks for every ally until the effect is over. HOWEVER: If an ally dies, the opposite effect happens (Stronger than the positive, obviously).

**Comment by TheRealAyCe** [comment]
I think damage is already pretty high, so you wouldn't notice this. Seems a lot of work for very little effect.

**Comment by anto4440** [comment]
The effects percentages can and hopefully will be altered, if thats what you are reeferring to.
If you just think that the effect itself isnt worth it, thats fair.

**Comment by TheRealAyCe** [comment]
I mean that most enemies already die in a single headshot, so even doubling the damage may not be that special. But it would be cool to have NPC allies that can actually kill enemies quickly.

**Comment by anto4440** [comment]
I mostly made this suggestoin because sometimes the player actually had up to 5 allies at a time, and i thought it was a shame that they hardly (can) do anything at all.

**Comment by anto4440** [comment]
Closed for having too minimal an affect on gameplay
