### ISSUE TITLE
Random Projectiles

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#439]
**Name of effect**
Random Projectiles

Short

**Effect Description**
Every Bullet fired will have a random asset loaded in its place. _It does not affect damage, accuracy or recoil, it is purely visual_
Only affects player

**Comment by ThatDeathbat** [comment]
**Randomly shoots Meteor out of a pistol**

**Comment by anto4440** [comment]
It is possible that the train comes out. If that happens, would it be a full train?

**Comment by TheRealAyCe** [comment]
Purely visual? So, no collision? Otherwise a big prop would just wreck the player and the area alike.

**Comment by anto4440** [comment]
There would have to be some scaling or _something_ if collision was active. So i thought that it simply would be visual.
