### ISSUE TITLE
The floor is lava

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#444]
**Name of effect**
The floor is lava

Short

**Effect Description**
Hear me out on this one. When effect is active, if player is on the ground he will get lit on fire. If player gets in a vehicle, the vehicle will instantly get on fire (forcing player to get out, and get set on fire. So player more or less has to be on a vehicle, which can be difficult. All tires also pop.

**Comment by DarrenBellew** [comment]
Maybe this but instead just the road? So if the player or vehicle is soecifically on the road they'll go on fire.
If on a footpath, runway or dirt  etc... They'll be fine

**Comment by anto4440** [comment]
Closed as... uh, it would appear this has been implementd? I'm not quite certain.
