### ISSUE TITLE
[Effect Suggestion] Turn Peds into Monkeys

### ISSUE THREAD

**Issue by HighDepth** [gta-chaos-mod/ChaosModV#458]
**Name of effect**
Turn Peds into Monkeys

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Turns everyone except the player into a monkey.

**Comment by anto4440** [comment]
Name of effect should be:
Reject humanity, return to monke. Or a cut out of that line.

**Comment by Last0xygen** [comment]
turning peds into other peds is not recommended
