### ISSUE TITLE
Pitch shifter (Better template)

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#461]
**Name of effect**
Pitch shifter/Slow audio

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Slows down all audio, as it does in GTA SA. In case of 'High Pitch' being active, this effect will override it and disable it early.

**Comment by anto4440** [comment]
This makes it easier for people to know what the effect does, so you dont need to make 4 comments to clarify.

**Comment by Kristof-30** [comment]
Yeah you can close this because you still think it only slows audio
You can check in youtube how it works
