### ISSUE TITLE
[Feature Suggestion] Change Mercenaries to "MERRYWEATHER FLEET'S HERE BRO!"

### ISSUE THREAD

**Issue by DestroyerXyz** [gta-chaos-mod/ChaosModV#462]
This is a famous line/meme spoken repeatedly by Trevor in the  Derailed mission in which famous Twitch streamer and YouTuber DarkViperAU continuously fails in OHKO(One Hit KO) and Chaos Mod runs. It would be very funny if you change Mercenaries to MERRYWEATHER FLEET'S HERE BRO! and maybe also play Trevor saying the line. BTW, this was suggested by someone on reddit.

**Comment by anto4440** [comment]
The only real problem with this is thats its a long name. Could be bothering to read, and maybe even go longer than the textbox

**Comment by TheRealAyCe** [comment]
You mean, like it was originally proposed? xD https://github.com/gta-chaos-mod/ChaosModV/issues/61

**Comment by DestroyerXyz** [comment]
@TheRealAyCe Oh, I did not know that😅

**Comment by anto4440** [comment]
I Swear, you crack me up, old sport

**Comment by DestroyerXyz** [comment]
@anto4440 I don't think the name length would be a problem as I belive there are longer names

**Comment by anto4440** [comment]
Like?

**Comment by DestroyerXyz** [comment]
Like the car rockets one or the ramp one.

**Comment by anto4440** [comment]
Vehicles Shoot Rockets [Press Lmb]
MERRYWEATHERS FLEETS HERE BRO

**Comment by DestroyerXyz** [comment]
But Vehicles shoot rockets has more characters

**Comment by anto4440** [comment]
So? its about size, not characters

**Comment by DestroyerXyz** [comment]
Size is also almost the same

**Comment by anto4440** [comment]
Look, you have to get the point.

**Comment by DestroyerXyz** [comment]
I don't

**Comment by Last0xygen** [comment]
As stated in the original PR (https://github.com/gta-chaos-mod/ChaosModV/pull/63), the name "Mercenaries" was preferred, as its more generic and self-explanatory

**Comment by DestroyerXyz** [comment]
So maybe just the sound effect as @ThatDeathbat recommended?

**Comment by Last0xygen** [comment]
Already discussed here too :) : https://github.com/gta-chaos-mod/ChaosModV/issues/61#issuecomment-668251263

**Comment by DestroyerXyz** [comment]
Oh well😅😅😅
