### ISSUE TITLE
[Effect Suggestion] GTA Online

### ISSUE THREAD

**Issue by DestroyerXyz** [gta-chaos-mod/ChaosModV#463]
**Name of effect**
Potential name(s) for the effect
GTA Online
**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
Long
**Effect Description**
Description of the effect; what should it do?
Random explosions, spawning money and vehicles and UFOs, NPCs going mad, getting kicked out of session(just displaying a message like in actual Online and teleporting player to Safe House after long load time), spamming messages on the player's phone, make player invincible, etc.

**Comment by anto4440** [comment]
Thats just... Thats just... I mean come on dude.
Doomsday. Airstrike indbounds. Money rain. Invincibility doesent even have anything to do with online! This is just... You know, chaas mod.

**Comment by ThatDeathbat** [comment]
This is all already in the mod.

**Comment by EliRickard** [comment]
Could maybe put player in a cage (NO COLLISION) and spawn an aim buffed, clone of the Michael wearing broken texture clothing items and holding an RPG in similar fashion to the behaviour exhibited by online hackers; and call this "Online Experience" this would just make it a tad more unique as most of the effects mentioned are implemented i either their own effect or another and I don't think recycling makes the chaos mod all that exciting.

**Comment by DestroyerXyz** [comment]
But all of it happening at once?

**Comment by SeanMirrsen** [comment]
Is silly.

Yes, there's something to be said for occasionally just throwing a whole bunch of chaos into the mix, but there was the recent addition of metaeffects for exactly that purpose. And there's only so much chaos that will be meaningful. Debilitating amounts of chaos just cause people to stop playing until it's over.

**Comment by DestroyerXyz** [comment]
People can disable it if they really hate it

**Comment by anto4440** [comment]
Fair enough. One of the few lines that is near impossible to argue with.

**Comment by Da-Best** [comment]
We had gta online traffic but that got removed for some reason but I think making the 5 min loading screen and tp to safe house especially if you get tped into the air will just cause multiple mission fails then possibly a softlock if the safehouse they tp to is locked. During the game all three characters move houses so keeping track of the safe house they are in would be pretty hard seeing if the mod fails to tp them to the right safe house it could lead to them being trapped inside of the wrong house.

**Comment by DestroyerXyz** [comment]
GTA may have a variable for the character's current safehouse which can be queried by ScriptHookV

**Comment by anto4440** [comment]
At last, the thread can finally rest, knowing damn well it did not go out with a fight. C'est Finale.

**Comment by DestroyerXyz** [comment]
Yeah, I was cleaning out all my old dead issues.
