### ISSUE TITLE
[Effect Suggestion] Random gun every kill

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#467]
**Name of effect**
Gun Randomizer |OR| Random Gun Every Kill

**Duration**
Long

**Effect Description**
Every kill you get changes the gun you are using to a different random gun.

**Comment by ThatDeathbat** [comment]
The Idea came to mind after reading the “Gun Game” recommendation from 3 hours ago

**Comment by ProfessorBiddle** [comment]
Duplicate #465

**Comment by ThatDeathbat** [comment]
Thats why I mentioned #465 in my previous comment.  You just never specified what order the guns would go in, so this would be easier to code into the game.

**Comment by anto4440** [comment]
I mean, normally i would insult you to hell for stealing someone else's idea, but you have earned my respect. 
Biddle, use ya fucking eyes, will ya?

**Comment by ProfessorBiddle** [comment]
I literally said random in #465. Why don't _you_ use your eyes.

**Comment by anto4440** [comment]
Apologies if I am missing something obvious, but i cant understand what you mean by 'I said random in #465' Could you try to make the sentence more clear? Have a nice day, man.

**Comment by ThatDeathbat** [comment]
I’m wrong here, he did say random in his post.  I was expecting that there would be an order in which the guns would be given since most **Gun Games** have an order in which the guns are given.

**Comment by anto4440** [comment]
Ouch, that sucks dude. I apologize. Only thing I have in defence is that for some reason, i didnt receive a message when the comment was posted. Have a nice day.

**Comment by TheRealAyCe** [comment]
So, seeing as how this seems to be more or less a duplicate, this ticket should be closed, right?
