### ISSUE TITLE
[Effect Suggestion] Hunger

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#468]
**Name of effect**
Hunger, Hungry, Kill or Be Killed

**Duration if timed effect (long or short timed?)**
Short, I think

**Effect Description**
Like was suggested in #193, you have a countdown bar somewhere on the screen. If it reaches the end, you start losing your health and eventually die (instead of a separate bar you can use just straight up player's hp). To fill it up you need to deal damage to peds. The only problem here is that there is no way to tell the player how to fill the bar except the effect's name, so the last name "Kill or Be Killed" is better, just maybe need to change it to something like "Kill or Die"

**Comment by anto4440** [comment]
Hmm, that is actually an interesting idea. But one of the problems I see is that in case of no enemies, this quickly becomes peds, then cops. And if youre in a mission where you either cant hurt/kill anybody or there are no people to kill, the effect is just death.
