### ISSUE TITLE
No mission fails

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#470]
**Name of effect**
No mission fails

**Duration if timed effect (long or short timed?)**
short or long

**Effect Description**
I dont know if its possible, but the effect will prevent the current mission (if one is active) from failing. You can essentually do anything in the duration. This one is very controversial, i know.

**Comment by anto4440** [comment]
alright, time to face a million comments.

**Comment by SeanMirrsen** [comment]
I mean. Would be fun if it were possible. Different missions fail for different reasons, there's whole bunches of triggers on each mission that will fail it.

I suppose if there's a way to find all of them and just prevent them from triggering it would work, but then if you've failed the mission while the effect is active, and the triggers don't trip once the effect runs out, then you've just softlocked the player.

Overall: Fun idea, but could be impractically difficult to implement, and might have a higher than average chance of softlocks. Could be worth looking into.

**Comment by anto4440** [comment]
I would still be possible to die as the player. This will result in a mission fail, its meant as way of having boundary breaks, killing people without changing the game itself.

**Comment by pongo1231** [comment]
Not really possible (at least in any feasible manner without taking count of every possible mission fail on a per mission basis).
