### ISSUE TITLE
Complete current mission

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#471]
**Name of effect**
Complete current mission

**Effect Description**
Instantly completes the current mission. Again, i cant prove that it will be possible everytime, and some cutscenes will maybe screw up, but the poor players need a good effect.

**Comment by SeanMirrsen** [comment]
Like the "no mission fail", this is also highly unlikely to be possible with any reliability. Teleport to Waypoint is the closest we have to this effect. And even that tends to kill the player if they're in a vehicle when they're not supposed to be. :P

**Comment by anto4440** [comment]
I know, I highly doubt that this effect will be implemented into the game.

**Comment by ProfessorBiddle** [comment]
Maybe a timed effect "Teleport to map marker" could work here, a little
like the option in Enhanced Native Trainer, would be the most useful effect
possible pretty much

**Comment by Thunderstorm64** [comment]
I don't think in gta 5 this is possible. Sucks, but hey, I'm not a programmer

**Comment by pongo1231** [comment]
This is indeed not possible from what I've seen (would need to be adjusted for every mission in the game).

**Comment by anto4440** [comment]
Thats why i made #472
