### ISSUE TITLE
Suggestion: Potato PC

### ISSUE THREAD

**Issue by Thunderstorm64** [gta-chaos-mod/ChaosModV#473]
**Name of effect**
Potato Power, Bad PC

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Lowers framerate (If possible) down to 15 fps and makes the game look like it's on lowest settings.

**Comment by ProfessorBiddle** [comment]
Alternately run the game in 800*600 for 90s, or simulate that somehow

**Comment by anto4440** [comment]
Not 15 fps dude. thats too terrible. 20.

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/279 and https://github.com/gta-chaos-mod/ChaosModV/issues/244, already fixed with https://github.com/gta-chaos-mod/ChaosModV/pull/373
Please use the search :)
