### ISSUE TITLE
Personal Lapdance

### ISSUE THREAD

**Issue by Thunderstorm64** [gta-chaos-mod/ChaosModV#475]
**Name of effect**
Lap dance, Personal Lap dance

**Effect Description**
Spawns Hooker Model doing the lap dance animation in front of player

**Comment by anto4440** [comment]
No, no, no. Unfortunate moments could occur. Imagine a child getting that effect... actually, that makes me happy to think of.

**Comment by Thunderstorm64** [comment]
The child's already playing GTA so.... I don't think that would matter. Doesn't have to be in first person either.

**Comment by anto4440** [comment]
non first person would be hilarious. Just locking the player in the sofa-chair with the stripper locked in front of him no matter what he did.

**Comment by ThatDeathbat** [comment]
I think this shouldn’t be added, unless the top stayed on when she did it.

**Comment by Nexaer** [comment]
Replace hooker with Lester (or some other character) to make the effect stream friendly.

**Comment by MoneyWasted** [comment]
As long as we can keep it not NSFW then it would be fine.
