### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Yuurst** [gta-chaos-mod/ChaosModV#477]
**Describe the bug**
'Give everyone a random weapon' does not give the player a random weapon.

**To Reproduce**
I have only had this effect occur in missions, Military Hardware being the one I can remember most vividly, and every time it occured it didn't give a random weapon to the player. I think I even had it occur without having any weapons once, so it probably can't be coincidentally giving me a weapon I already had.

**Crash Dump (if a game crash)**
N/A

**Comment by Last0xygen** [comment]
Should be fixed with https://github.com/gta-chaos-mod/ChaosModV/commit/09b08a810cd977d106a01a9ab8ab8690ea89819f
