### ISSUE TITLE
[Improvement] Remove sound from fake crash

### ISSUE THREAD

**Issue by kolyaventuri** [gta-chaos-mod/ChaosModV#481]
**Describe the bug**
`Fake Crash` effect should not trigger the effect trigger sound, if set.

**To Reproduce**
- Trigger fake crash

**Comment by JustTunerYT** [comment]
I was about to post it as well LULW
Here's clip from that: https://clips.twitch.tv/SourRepleteTapirPoooound

**Comment by Last0xygen** [comment]
already removed  :)
