### ISSUE TITLE
[Effect Suggestion] spawn tryhard

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#484]
**Name of effect**
Spawn a tryhard

**Effect Description**
Spawn  a Tryhard on oppressor mk2

**Comment by TheBatmanReal** [comment]
the tryhard outfit 
if you need 
https://www.mediafire.com/file/p05ihe0t6npf5xt/tryhard.xml/file
(freemode male)

**Comment by pongo1231** [comment]
Would just be a reskin of "Extreme Griefer Jesus", not that interesting in my opinion.
