### ISSUE TITLE
[Effect Suggestion] Rickroll

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#486]
**Name of effect**
Potential name(s) for the effect
Rickroll

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
short

**Effect Description**
Description of the effect; what should it do?
play Rick astley song 
never gonna give you up

**Comment by anto4440** [comment]
Why would- that wouldnt affect the game at all.

**Comment by Da-Best** [comment]
Wouldnt that just get the streamer/ youtuber copyright claimed/ dmca'd
