### ISSUE TITLE
[Effect Suggestion] Spawn companion Griefer jessus

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#488]
**Name of effect**
Potential name(s) for the effect
Spawn friendly Griefer jessus

**Effect Description**
Description of the effect; what should it do?
Spawn friendly Griefer jessus
Spawn companion Griefer jessus

**Comment by anto4440** [comment]
Kinda throws the greifer part out of the window. Also i have seen billions of suggestions on this single effect.

**Comment by Last0xygen** [comment]
Exists already with „spawn random companion“
