### ISSUE TITLE
[Effect Suggestion] Spawn Knight Rider

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#491]
**Name of effect**
Potential name(s) for the effect
Spawn Knight Rider

**Effect Description**
Description of the effect; what should it do?

spawn an invisible enemy who drive the ruiner 2000
to look like the car is without a driver and try to kill The Player

**Comment by anto4440** [comment]
Why is it called knight rider? Did you mean 'night rider'?

**Comment by SeanMirrsen** [comment]
> 
> Why is it called knight rider? Did you mean 'night rider'?

Knight Rider. David Hasselhoff? K.I.T.T.? The all-black sentient sportscar with the red light going back and forth?

Surely I can't be that old that there's people that don't know Knight Rider anymore. :|

**Comment by anto4440** [comment]
Never heard of it.

**Comment by SeanMirrsen** [comment]
Let me introduce you then.

https://www.youtube.com/watch?v=enUjYiHKQhk

**Comment by SeanMirrsen** [comment]
The Ruiner 2000 vehicle from GTA Online is basically a replica of KITT from the show.

**Comment by anto4440** [comment]
Thats great. Altough i fear that noone will ever get that reference

**Comment by Last0xygen** [comment]
„Spawn random vehicle“ already exists 
Anspänne effects for each car would be way too excessive

**Comment by TheBatmanReal** [comment]
i forgot to add o look like the car is without a driver and try to kill The Player
sorry :)

**Comment by ThatDeathbat** [comment]
This is basically the same thing as “Extreme Griefer Jesus”

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn", "ped spawn" or "ped driving vehicle" effects. (We have enough already.)
