### ISSUE TITLE
[Effect Suggestion] Player dance When shoot

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#493]
**Name of effect**
Potential name(s) for the effect
Player dance When shoot

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
long

**Effect Description**
Description of the effect; what should it do?
Player dance the in the hood dance or any other dance
 When shoot

**Comment by anto4440** [comment]
If you get shot multiple times, do you switch dance animation or restart you dance? How long will you continue to dance for? Does it apply to peds aswell?

**Comment by Last0xygen** [comment]
Combination of „in the hood“ and „player ragdolls when shot“ 
I don’t think this would be a good effect
