### ISSUE TITLE
[Effect Suggestion] Rick roll qr code

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#494]
**Name of effect**
Potential name(s) for the effect
QR CODE
**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
short

**Effect Description**
Description of the effect; what should it do?

put a rickroll qr code on the screen

**Comment by anto4440** [comment]
Again, no. duplicate of #486

**Comment by ThatDeathbat** [comment]
Pretty bad idea.

**Comment by Last0xygen** [comment]
This is not really interesting. After seeing it once the "fun" is gone, sorry
