### ISSUE TITLE
[Effect Suggestion]  you whill not getting in cars!!

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#495]
**Name of effect**
Potential name(s) for the effect
 you will not getting in cars!!

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
Description of the effect; what should it do?

every time the player tries to get into a car he will leave immediately

**Comment by anto4440** [comment]
Thats the same as lock all vehicles.
