### ISSUE TITLE
[Effect Suggestion] Guilty/Not-Guilty

### ISSUE THREAD

**Issue by Catz4Lyfe777** [gta-chaos-mod/ChaosModV#496]
**Name of effect**
Potential name(s) for the effect

Objection!
Ace Attorney

**Effect Description**
Description of the effect; what should it do?
A small cutscene of a random defense and prosecution attorneys from the Ace Attorney franchise will play in which each the defense and prosecution say "Objection!" once. After both of them say "Objection!" the Judge will slam his gavel and give you a verdict of "Guilty" or "Not-Guilty" (which both have a 50% chance of happening).
If found "Guilty" the player will get bad effects to happen more frequently. 
If found "Not-Guilty" the player will instead get good effects to happen more frequently.

**Comment by anto4440** [comment]
I think Guilty and not guilty should increase or decrease/remove/disable ones wanted level.

**Comment by Last0xygen** [comment]
I think you have no idea how much work that would be 😐and a „random good or bad“ effect has already been suggested

**Comment by anto4440** [comment]
Me or him?

**Comment by Catz4Lyfe777** [comment]
> I think Guilty and not guilty should increase or decrease/remove/disable ones wanted level.

Actually that might be better

**Comment by Last0xygen** [comment]
Already in the works without any animation 
https://github.com/gta-chaos-mod/ChaosModV/pull/163
