### ISSUE TITLE
[Effect Suggestion] you are being arrested

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#497]
**Name of effect**
Potential name(s) for the effect
you are being arrested

**Effect Description**
Description of the effect; what should it do?

spawn a police driving a police car and put the player
in the back seat

**Comment by anto4440** [comment]
This one just has a lack of stuff happening. I think it would work better if player was locked in cop vehicle, and the cop drove to a police station. Once the cop arrived, the player would be free to leave.

**Comment by TheBatmanReal** [comment]
anto4440 good idea

**Comment by anto4440** [comment]
Thank you

**Comment by Last0xygen** [comment]
Already done https://github.com/gta-chaos-mod/ChaosModV/pull/308
