### ISSUE TITLE
[Effect Suggestion] Spawn Opreessor Mk2

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#498]
**Name of effect**
Potential name(s) for the effect
Spawn Opreessor Mk2

**Effect Description**
Description of the effect; what should it do?

Spawn Opreessor Mk2

**Comment by anto4440** [comment]
Would be too easy for the player. We dont need any more spawn X. Extreme greifer jesus is better at this

**Comment by Last0xygen** [comment]
Already down with „spawn random vehicle“

**Comment by anto4440** [comment]
Alright from now on ill just use that
