### ISSUE TITLE
[Effect Suggestion] Aimbot

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#499]
**Name of effect**
Potential name(s) for the effect
Aimbot
**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section
Long

**Effect Description**
Description of the effect; what should it do?

Gives The Player  Aimbot

**Comment by anto4440** [comment]
Actually smart idea. I believe that i got this one once but didnt think about it. It feels fair that such a thing would happen

**Comment by TheRealAyCe** [comment]
What exactly is an "aimbot" here?

**Comment by anto4440** [comment]
I assume it hits an enemy everytime, in the head
