### ISSUE TITLE
[Effect Suggestion] Spinning Camera

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#502]
**Name of effect**
Spinning Camera, Camera Spin

**Duration if timed effect (long or short timed?)**
Long, but I believe it can get pretty dizzy, so depends on testing

**Effect Description**
Afair you can spin your camera full 360 in the game, so this effect would force the spin.

**Comment by anto4440** [comment]
How fast?

**Comment by Last0xygen** [comment]
> How fast?

Fast enough to be not slow and slow enough to not make you vomit 🤪

**Comment by Vidubelay** [comment]
100% for short, I don't think this effect is gaining anything from being long and short will do the job well enough
