### ISSUE TITLE
Name: Spawn Loco Lamar[Effect Suggestion]

### ISSUE THREAD

**Issue by 810CK-A1D** [gta-chaos-mod/ChaosModV#503]
Effect Name: Spawn Loco Lamar
What it does: Spawns a enemy lamar with a minigun

**Comment by anto4440** [comment]
Covered with 'Spawn Random Enemy'

**Comment by 810CK-A1D** [comment]
Yeah, but same for spawn jealous jimmy

**Comment by anto4440** [comment]
He was an exception, i guess

**Comment by Last0xygen** [comment]
i don't think this adds much to the mod, sorry
