### ISSUE TITLE
[Bug] Pacifist not detecting cover shooting?

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#505]
https://youtu.be/6SdZHuL4gLs?t=3489

Shouldn't that be disallowed by Pacifist?

**Comment by anto4440** [comment]
Pacifist in generel keeps confusing me. What exactly is it supposed to do?

**Comment by SeanMirrsen** [comment]
Whenever you would point a weapon at someone, you die. Whether you take aim down the sights and look at someone you can shoot, or just look at someone and press the fire button, causing you to bring the weapon up to fire. Right now you can still fire at non-living things, blindfire from cover, and you can still melee people and use explosives.

It should really cause you to die if you kill someone, even through roundabout means. A "true" pacifist effect should probably cause you to die if you so much as harm someone else, even with a punch, and should detect if you've run someone over with a car. But that's probably up to the limits of what the mod can do.

**Comment by ProfessorBiddle** [comment]
> It should really cause you to die if you kill someone,

If someone can figure out how to do this that would be awesome, I spent hours trying to get this to work and had to settle for the aiming down the sights thing

**Comment by SeanMirrsen** [comment]
Doesn't the game track your kill counts? You could try to monitor those and trigger on one increasing.

**Comment by ProfessorBiddle** [comment]
> Doesn't the game track your kill counts? You could try to monitor those
> and trigger on one increasing.
>

This is how I originally intended to do it, but I couldn't find a way of
accessing that in script hook. If you have an idea on how I'd be happy to
implement it

>

**Comment by SeanMirrsen** [comment]
> Doesn't the game track your kill counts? You could try to monitor those and trigger on one increasing.
> This is how I originally intended to do it, but I couldn't find a way of accessing that in script hook. If you have an idea on how I'd be happy to implement it

Looking through the documentation, perhaps experiment with STATS::STAT_GET_INT? Find the hash for player's total kills and track that.

**Comment by Last0xygen** [comment]
Already implemented now :)
