### ISSUE TITLE
[Effect Suggestion] Slingshot

### ISSUE THREAD

**Issue by trollbreeder** [gta-chaos-mod/ChaosModV#518]
**Name of effect**
Slingshot

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Player can no longer move normally. Instead, when the player holds a movement key (such as WASD) and then lets go, the player is launched in that direction. The longer you hold, the more powerful the launch (maybe launch can be boosted further with shift/the sprint button?)
Indicate power of launch with something on the hud, perhaps a bar or something.

**Comment by kolyaventuri** [comment]
Similar to #269

**Comment by MoneyWasted** [comment]
Duplicate/too similar to #269
