### ISSUE TITLE
[Effect Suggestion] Shapeshifting Bullets

### ISSUE THREAD

**Issue by OHSHIET** [gta-chaos-mod/ChaosModV#527]
**Name of effect**
Shapeshifting Bullets, Shapeshifter's Bullets

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
When you shoot a ped, you become the ped you shot and take the ped's model. The original idea was that you also teleport to the place where that ped was, and your character becomes a ped, so you can now "switch" between other peds and your character, but that just seemed too difficult considering what would your character do after you've switched to another ped. Without it this effect may be not very interesting, also that it can softlock the game, but with the opportunity to shoot allies I think it'd be more interesting. Maybe you can even make this with objects too?

**Comment by kolyaventuri** [comment]
This has the potential to have really weird effects during missions, but it's certainly worth exploring. Might just softlock in areas...
