### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by Yuurst** [gta-chaos-mod/ChaosModV#528]
**Name of effect**
You Seem Pale

**Duration if timed effect (long or short timed?)**
N/A

**Effect Description**
Teleports you to random hospital (or nearest one, whatever you think is best)

**Comment by TheRealAyCe** [comment]
Kind of a duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/223

**Comment by Last0xygen** [comment]
duplicate
