### ISSUE TITLE
Big bang

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#529]
**Name of effect**
Big bang

**Effect Description**
This is sort of two effects combined. Sort of: Every loaded asset will be teleported right to the player, and then they will be launched away with enormous force. Kinda like Teleport everything to  player and forcefeild, but i think it makes sense.

**Comment by TheRealAyCe** [comment]
Big Bang :D

**Comment by anto4440** [comment]
You're absolutely right

**Comment by MoDerPo** [comment]
that's a great idea!

**Comment by anto4440** [comment]
Closing this as it has been added. However i have never seen it in game.

**Comment by TheRealAyCe** [comment]
> Closing this as it has been added. However i have never seen it in game.

That's because the Pull Request is still open and not merged in. :(
