### ISSUE TITLE
Fake TP can be better

### ISSUE THREAD

**Issue by LoneWolf68559** [gta-chaos-mod/ChaosModV#531]
When the Fake TP is chosen it TPs you to the random location and than back. It can be more Fake if it first said for example Teleport to Mount Chiliad but as it is Fake it teleports you there with a Teleport to Mount Chiliad and as it returns you back to original position it now overwrites the text Teleport To Mount Chiliad to Fake TP.

**Comment by SeanMirrsen** [comment]
Already in the works. #325
