### ISSUE TITLE
Mild Griefer Jesus

### ISSUE THREAD

**Issue by chiiiaro** [gta-chaos-mod/ChaosModV#538]
**Name of effect**
Mild Griefer Jesus

**Effect Description**
Spawns a Griefer Jesus that follows the player, endlessly rambling. Should be an ally so he can't just be killed

**Comment by MoDerPo** [comment]
that's not a griefer tho

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
