### ISSUE TITLE
[Effect Suggestion] Invert controlls

### ISSUE THREAD

**Issue by MoDerPo** [gta-chaos-mod/ChaosModV#542]
**Name of effect**
Backwards

**Duration if timed effect (long or short timed?)**
long enough to get used to it and then it's hard to get used to normal controlls again

**Effect Description**
I think you get the idea

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16

**Comment by MoDerPo** [comment]
not quite: I mean all controlls (left right backwards forwards) and also it should be long enough that you get used to it and then when it's over you have to get used to the normal controlls again

**Comment by Last0xygen** [comment]
Which is the same as in the old request, but everything together 👍

**Comment by MoDerPo** [comment]
oh ok
