### ISSUE TITLE
[Effect Suggestion] Can't fall of the bike

### ISSUE THREAD

**Issue by MoDerPo** [gta-chaos-mod/ChaosModV#548]
**Name of effect**
Seatbelt

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
makes it impossible to ragdoll out of a vehicle

**Comment by Last0xygen** [comment]
Should already work with „no ragdoll “ 🤔

**Comment by MoDerPo** [comment]
Hmm maybe I'm not home rn but imma try later

**Comment by ProfessorBiddle** [comment]
This could work a bit like the "No falling off/out" option in Enhanced Native Trainer

**Comment by MoDerPo** [comment]
yeah or like seatbelt in kiddons modest

**Comment by MoDerPo** [comment]
I'll try if the no ragdoll works now

**Comment by MoDerPo** [comment]
I tried to change the config but every time I clicked save the Config App crashed...

**Comment by Last0xygen** [comment]
Just tested, already working with "no ragdoll"
