### ISSUE TITLE
[Feature Suggestion] Fake effects should have a decoy

### ISSUE THREAD

**Issue by MoDerPo** [gta-chaos-mod/ChaosModV#550]
**Is your feature request related to a problem? Please describe.**
It's often very obvious that for example a fake crash is fake because it happens right at the moment where an effect is supposed to happen.

**Describe the solution you'd like**
It would be great if for fake teleport it would tell you the according effect that it's resembling (e.g. Tp to Airport). The fake crash could have something like teleport everything to player or other effects that can cause problems so it's more believable.

**Describe alternatives you've considered**
Well there are not really any other things I could've done....

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/531, already in progress https://github.com/gta-chaos-mod/ChaosModV/pull/325

**Comment by TheRealAyCe** [comment]
Thanks for reporting, but search issues (also closed ones) before opening bugs. Like this: https://github.com/gta-chaos-mod/ChaosModV/issues?q=fake
