### ISSUE TITLE
[Effect Suggestion] The last supper

### ISSUE THREAD

**Issue by Synfetic** [gta-chaos-mod/ChaosModV#561]
**Name of effect**
Potential name(s) for the effect
The last supper

not timed

**Effect Description**
Description of the effect; what should it do?
griefer Jesus spawns with 12 random NPCS (npcs are not hostile to player while griefer Jesus is) (12 disciples)

**Comment by DestroyerXyz** [comment]
Weird

**Comment by Last0xygen** [comment]
Spawning that many friendly NPCs may cause problems with the mod as reported by pongo.
Also, this effect is "Spawn griefer jesus" with 12 random npc spawns, so not a really unique effect idea, sorry :)
