### ISSUE TITLE
[Effect Suggestion] Play TESV Intro Cutscene

### ISSUE THREAD

**Issue by dongk99** [gta-chaos-mod/ChaosModV#564]
**Name of effect**
Play TESV Intro cutscene
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
20s
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?
Plays TESV Intro cutscene.

**Comment by SeanMirrsen** [comment]
As hilarious as it would be, unless someone actually manages to recreate the Skyrim intro in GTAV and make it usable by this mod, this will sadly forever be impossible.

**Comment by dongk99** [comment]
> As hilarious as it would be, unless someone actually manages to recreate the Skyrim intro in GTAV and make it usable by this mod, this will sadly forever be impossible.

would it be possible to play the intro as a video and just cover the whole screen?

**Comment by MoneyWasted** [comment]
Sadly we currently have no way of playing videos. Though it could be added with some clever modifications and implementations.

**Comment by Last0xygen** [comment]
This cannot be made, either by code limitations or copyright ;)
