### ISSUE TITLE
[Effect Suggestion] Companion Jesus

### ISSUE THREAD

**Issue by DestroyerXyz** [gta-chaos-mod/ChaosModV#565]
**Name of effect**
Potential name(s) for the effect
Companion Jesus

**Effect Description**
Description of the effect; what should it do?
An ally Jesus instead of an enemy

**Comment by DestroyerXyz** [comment]
A little bit like #538

**Comment by Last0xygen** [comment]
Already suggested several times, please use the search: https://github.com/gta-chaos-mod/ChaosModV/issues?q=Jesus
😁
