### ISSUE TITLE
Fake Crash [Effect Suggestion]

### ISSUE THREAD

**Issue by Mattia2510MC** [gta-chaos-mod/ChaosModV#570]
When Fake Crash is chosen, it should say nothing in the effects and randomly activate in the next 30 seconds. Now the effect is really predictable, since it makes the sound and activates at the same time

**Comment by TheRealAyCe** [comment]
A good idea, but then there would be no effect text, making it obvious that fake crash was chosen (except for the first few times).

**Comment by kolyaventuri** [comment]
The sound activating when it shouldn't is a known issue with Fake Crash. See #481

**Comment by Mattia2510MC** [comment]
> A good idea, but then there would be no effect text, making it obvious that fake crash was chosen (except for the first few times).

Sorry, I used bad phrasing. I means that the effect text should be NOTHING

**Comment by badmanbrad001** [comment]
maybe it causes a random effect before the fake crash when its chosen during the time until it activates

**Comment by TA40** [comment]
A better way to solve this:
If "Fake Crash" is chosen, make a random effect (really random or maybe from a small list) and activate the Fake crash sometime in 25 seconds.
