### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by iceman-06** [gta-chaos-mod/ChaosModV#571]
**Name of effect**
Default Keybinds

**Duration if timed effect (long or short timed?)**
60

**Effect Description**
Change you keybinds to the default, it might not be that good since not everyone has changed there binds (If you think this is bad I have an I idea that's you might like)

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/246 or https://github.com/gta-chaos-mod/ChaosModV/issues/16
