### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by iceman-06** [gta-chaos-mod/ChaosModV#572]
**Name of effect**
Random Keybinds
What Does This Do?

**Duration if timed effect (long or short timed?)**
60

**Effect Description**
Randomizes your keybinds or swaps them to keys that are already bound to something (don't forget to disable stuff like windows key)

**Comment by TheRealAyCe** [comment]
Duplicate? https://github.com/gta-chaos-mod/ChaosModV/issues/291

**Comment by Last0xygen** [comment]
Same as #246 or #16
