### ISSUE TITLE
[Effect Suggestion] Dream Luck (Meta)

### ISSUE THREAD

**Issue by kolyaventuri** [gta-chaos-mod/ChaosModV#573]
**Name of effect**
"Dream Luck"

**Duration if timed effect (long or short timed?)**
- Long? Probably enough time to get through 2 cycles

**Effect Description**
Ensures that only super helpful effects can be voted for, _or_ enforces super helpful effects instead of what was picked.
For example:
- Teleport to Waypoint
- Give All Weapons
- HESOYAM
- Upgrade Vehicle

**Comment by OHSHIET** [comment]
I already suggested something like this #509. Even if you mean only the best of the best effects, I don't think it's so different.

**Comment by Last0xygen** [comment]
duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/509
