### ISSUE TITLE
[Effect Suggestion] Increase Gamespeed

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#576]
Increase Gamespeed by 1.5, 2.0, 3.0 etc., just like San Andreas

**Comment by ProfessorBiddle** [comment]
Not possible unfortunately, the function only works to reduce gamespeed.

**Comment by Last0xygen** [comment]
Not possible using natives, would create other problems if it would work, like heavy load on the pc performance 😅
