### ISSUE TITLE
[Effect Suggestion] WW2

### ISSUE THREAD

**Issue by SoggyMangoSteam** [gta-chaos-mod/ChaosModV#577]
**Name of effect**
WW2, Kamikaze, Raining Planes

**Duration if timed effect (long or short timed?)**
Long timed

**Effect Description**
Cause nokota (or any) planes to fall from the sky, it will keep raining planes until the effect is over, and unless the effects are reset, keep any dead or alive planes spawned, not too many planes else the game is going to crash because it cant handle tons of that same thing spawned in a short matter.

**Comment by Last0xygen** [comment]
Sounds like "Vehicle Rain" but only planes, not too different
