### ISSUE TITLE
[Effect Suggestion] Player drive-by peds

### ISSUE THREAD

**Issue by Mortrix1** [gta-chaos-mod/ChaosModV#578]
**Name of effect**
Player drive-by peds

**Duration if timed effect (long or short timed?)**
Long time (about as long as 'Peds drive-by player')

**Effect Description**
This effect would be the reverse of the current effect 'Peds drive-by player'. Instead of peds shooting the player, while in cars. The player will shoot (auto aim and trigger) peds while the player is driving a vehicle. The shooting will be completely automatic, and will also switch weapon if a gun is empty.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/499
