### ISSUE TITLE
[Effect Suggestion] Jesus is everywhere

### ISSUE THREAD

**Issue by Shadow-GOD-op** [gta-chaos-mod/ChaosModV#579]
**Name of effect**
Jesus is everywhere

**Effect Description**
Spawns 4 Griefer Jesus all around player.

**Comment by SeanMirrsen** [comment]
I like the reference, but it's way too simple I think. Just more Jesuses is not meaningfully worse than one, and it's not particularly creative.

What if, instead, all cops become Jesus. With the railgun. And your wanted level, if you have one, can't be lower than 3 stars. So the slightest sin causes an army of Jesuses to go after you.

**Comment by TheRealAyCe** [comment]
Or Peds become Jesus Agent Smith style.

**Comment by Shadow-GOD-op** [comment]
> **Name of effect**
> Jesus is everywhere
> 
> **Effect Description**
> Spawns 4 Griefer Jesus all around player.

Another way of this effect would be that all current peds are replaced with the griefer jesus ped model but they are not hostile.

**Comment by Sillekram** [comment]
To take that further, what if all peds have jesus player model and hold rail gun but only one or 2 is hostile, could be a fun guessing game.

**Comment by Last0xygen** [comment]
I don't think we need another Griefer jesus effect, which doesn't add anything different to the existing effects, sorry :)
