### ISSUE TITLE
Everything is invinsible

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#581]
**Name of effect**
Everything is invinsible / Everything is unbreakable

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Kind of freezes every asset, but not really: Nothing can break, get scratched, or even die/take damage as npc and players. However, even though nothing can get hurt, you are still free to walk or drive around.

Note: I got the idea from good ol' Matto, with this link pretty perfectly summing up what i mean. https://youtu.be/nER8hYJ81pE?t=4987

**Comment by Last0xygen** [comment]
Sounds a lot like https://github.com/gta-chaos-mod/ChaosModV/issues/187

**Comment by anto4440** [comment]
Peds still work, they just cant take damage
