### ISSUE TITLE
[Effect Suggestion]

### ISSUE THREAD

**Issue by ZSSmain** [gta-chaos-mod/ChaosModV#585]
**Name of effect**
I must go, my planet needs me

**Duration if timed effect (long or short timed?)**
about 20 seconds

**Effect Description**
If the player is in a vehicle of any kind they will get out of it into a standing position. After they either exit the vehicle or the effect activates while on foot the player will begin to rise into the air without ragdolling until the effect ends.

**Comment by Last0xygen** [comment]
this is „invert gravity“ without ragdolling, not a really „new“ effect
