### ISSUE TITLE
[Effect Suggestion] Spawn Random Object

### ISSUE THREAD

**Issue by zech78** [gta-chaos-mod/ChaosModV#602]
**Name of effect**
Spawn Random Object

**Effect Description**
Spawns in a random object found in the game (such as light poles, boxes, crates, etc)

**Comment by TheRealAyCe** [comment]
This? https://github.com/gta-chaos-mod/ChaosModV/issues/519

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/519
