### ISSUE TITLE
[Effect Suggestion] Ocean Man

### ISSUE THREAD

**Issue by ashgamer-06** [gta-chaos-mod/ChaosModV#603]
**Name of effect**
Ocean Man

**Effect Description**
Teleport into random body of water

**Comment by kolyaventuri** [comment]
Duplicate of #266 ?

**Comment by ashgamer-06** [comment]
> Duplicate of #266 ?

Oh, didn't see that one.

**Comment by kolyaventuri** [comment]
> > Duplicate of #266 ?
> 
> Oh, didn't see that one.

All good :+1: I'll close this one out
