### ISSUE TITLE
[Suggestion] Merryweather's here bro!

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#61]
Spawn ane enemy helicopter that shoots you (with rockets?)

**Comment by pongo1231** [comment]
Implemented in #63

**Comment by TheRealAyCe** [comment]
@Last0xygen You've been going at these suggestions, great job! :+1:  Do you think it's possible to add the "Merryweather Fleet's here bro!" alert sound to the event, just like in the Impotent Rage one?

**Comment by Last0xygen** [comment]
@TheRealAyCe I looked into that actually, but didn't find a way to trigger a campaign speech line

**Comment by TheRealAyCe** [comment]
@Last0xygen Oh well, too bad.

**Comment by TheRealAyCe** [comment]
@Last0xygen Right now the mercenaries seem to not be aggressive enough. Half the time it seems like you can't even notice them. Maybe you have an idea how to fix that? Are they not pursuing the player?

**Comment by Last0xygen** [comment]
@TheRealAyCe i know. I guess the spawn too far away.
There’s already a fix for them to gespawn consistent (https://github.com/gta-chaos-mod/ChaosModV/pull/89).
I guess I have to adjust the random spawn location too, as it may be too far away 😅

**Comment by TheRealAyCe** [comment]
@Last0xygen Oh, it's not merged in yet. What a pity. :( Hopefully the next Chaos stream will feature an updated version (which requires an updates version to be released...)
