### ISSUE TITLE
[Effect Suggestion] teleporting slot machine

### ISSUE THREAD

**Issue by badmanbrad001** [gta-chaos-mod/ChaosModV#610]
**Name of effect**
jackpot telepot

**Duration if timed effect (long or short timed?)**
instant

**Effect Description**
rapidly teleport to locations (random and in no order) slowing down over a duration of about 10 second until it stops at one location

**Comment by Last0xygen** [comment]
teleports require reloading all nearby props. quickly loading several locations will be performance hell 😅
