### ISSUE TITLE
[Effect Suggestion] Fake Jesus

### ISSUE THREAD

**Issue by ballisticdragons** [gta-chaos-mod/ChaosModV#621]
**Name of effect**
Mercy, Fake Extreme Griefer Jesus, Companion Jesus

**Effect Description**
Spawn a Neutral or even friendly extreme griefer jesus entity. When jesus shows up it's almost always bad I want to throw some for a loop

**Comment by TheRealAyCe** [comment]
This? https://github.com/gta-chaos-mod/ChaosModV/issues/391 (and many other closed ones)

**Comment by Last0xygen** [comment]
Duplicate
