### ISSUE TITLE
[Effect Suggestion] Flash Gernades

### ISSUE THREAD

**Issue by ballisticdragons** [gta-chaos-mod/ChaosModV#625]
**Name of effect**
Flash Gernades

**Duration if timed effect (long or short timed?)**
Makes peds close to the explosion brainless (if not killed immediately so slight delay after the explosion) the effect lasts for 10 seconds 

**Effect Description**
Any thrown item (molotov, snowball, sticky bomb, proximity mines, etc.) becomes a flash bang that makes nearby peds brainless for 10 seconds but also makes the screen bright for you for a 5 seconds if you're caught in the radius

**Comment by Last0xygen** [comment]
Sounds way too situational.
The player has to own and use a throwable weapon while this effect is active
