### ISSUE TITLE
[Effect Suggestion] Everyone gets a random vehicle

### ISSUE THREAD

**Issue by Fireheart318** [gta-chaos-mod/ChaosModV#626]
Name - Everyone gets a random vehicle

Duration - Short
This effect is instant and permanent but is applied to newly-spawned NPCs for a short time.

Description - Every NPC and player is put into their own randomly-chosen vehicle. If multiple characters are in the same vehicle, they each get their own. Each vehicle is chosen randomly - one guy could get a motorcycle, while the guy next to him gets a boat.

**Comment by Last0xygen** [comment]
Already exists as „Random Traffic“
