### ISSUE TITLE
[Effect Suggestion] Aimbot

### ISSUE THREAD

**Issue by GerdTheAwesome** [gta-chaos-mod/ChaosModV#628]
Aimbot
Potential name(s) for the effect
Insane Aimbot

**Duration if timed effect (long or short timed?)**
Mid

**Effect Description**
Gives the player insane aimbot and shot every one in the head. Automatic shot or the player have to shot him self

**Comment by Last0xygen** [comment]
Already suggested. Please use the search before opening a new issue :) (https://github.com/gta-chaos-mod/ChaosModV/issues?q=Aimbot)
Duplicate of https://github.com/gta-chaos-mod/ChaosModV/issues/499
