### ISSUE TITLE
[Effect Suggestion] Jesus take a wheel

### ISSUE THREAD

**Issue by joemama12345679** [gta-chaos-mod/ChaosModV#629]
**Jesus Take a Wheel**

**Jesus spawns inside your vehicle holding a wheel and one of your vehicle wheels is removed.**

**Comment by badmanbrad001** [comment]
jesus takes a wheel?

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/107
