### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect's Idea

### ISSUE THREAD

**Issue by gvyb7** [gta-chaos-mod/ChaosModV#636]
Remove last checkpoint 

If a player is in a mission and receives a checkpoint if they die and this effect was activated they spawn at the most recent checkpoint they got before that

**Comment by TheRealAyCe** [comment]
@gvyb7 Please update the issue title to the effect name.

Besides that, I think this is not possible.

**Comment by Last0xygen** [comment]
Not possible as far as I know
