### ISSUE TITLE
[Effect Suggestion] Infinity Gauntlet

### ISSUE THREAD

**Issue by BlaiseDebeste** [gta-chaos-mod/ChaosModV#637]
Infinity Gauntlet, The Snap, The Blip, Thanos Take the Wheel, Infinity Snap,

Fifty percent of all nearby NPC's die instantly. The player character has a fifty/fifty chance of immediately dying.

**Comment by Last0xygen** [comment]
Sounds too much like „obliterate surrounding peds“ with a 50/50 chance involved

**Comment by BlaiseDebeste** [comment]
Thanks for taking the time to read this! I love your content!
