### ISSUE TITLE
[MetaEffect Suggestion] F*** you, chat

### ISSUE THREAD

**Issue by ProfessorBiddle** [gta-chaos-mod/ChaosModV#641]
**Name of effect**
"F*** you, chat,"
"Dictatorship"
"Unpopular Decisions"

**Duration if timed effect (long or short timed?)**
 Long timed.

**Effect Description**
Choose the least popular vote instead of the most popular, or inverse percentages for proportional voting. Would have to be dependent on twitch integration.

**Comment by SeanMirrsen** [comment]
Duplicate of #523 , no?

**Comment by Last0xygen** [comment]
Duplicate #523
