### ISSUE TITLE
[Effect Suggestion] Faster than train

### ISSUE THREAD

**Issue by wonsznaparapecie** [gta-chaos-mod/ChaosModV#642]
**Name of effect**
Beat it!

**Effect Description**
Not a timed effect, random event that happens rarely, without voting.
After prologue heist protagonits are making it before train, loosing cops and driving off to sunset, Mission ends with success and credits are rolling ending the game.

Inspired by all lame jokes from DarkViperAU.

**Comment by Last0xygen** [comment]
Too situational and, most importantly, not possible 😅 sorry
