### ISSUE TITLE
[Effect Suggestion] Teleport to random safehouse

### ISSUE THREAD

**Issue by gvyb7** [gta-chaos-mod/ChaosModV#644]
**Name of effect**
Teleport to random safehouse

**Effect Description**
Teleport the player to a random safehouse that any story mode character lives/ has lived at any stage in the game

**Comment by anto4440** [comment]
This has been asked before

**Comment by anto4440** [comment]
Twice.

**Comment by Last0xygen** [comment]
Duplicate
