### ISSUE TITLE
Code style question

### ISSUE THREAD

**Issue by byhemechi** [gta-chaos-mod/ChaosModV#65]
Going through the code for the voting overlay, is there any reason in particular that the docs for all the classes are in separate interfaces?

**Comment by Elias-Graf** [comment]
The reason why there are interfaces is to make implementations "drop-in" replacements for each other, as long as they derive from the same interface. If you document the methods in the classes, You (or anyone else) will have to document every method in every class separately. This way your editor, at least the good ones, will pick up on the comment declared in the implemented interface. If you check some private methods, you will see that they are documented in the class itself.

**Comment by byhemechi** [comment]
That is absolutely a fair point. Really could have figured it myself now i think about it.
