### ISSUE TITLE
[Effect Suggestion] Spawn Friendly Jesus

### ISSUE THREAD

**Issue by BryhtFlow** [gta-chaos-mod/ChaosModV#650]
**Name of effect**
Spawn Friendly Jesus

**Effect Description**
Spawns Jesus who acts as an ally with a railgun

**Comment by Last0xygen** [comment]
Already suggested several times, see https://github.com/gta-chaos-mod/ChaosModV/issues/621, https://github.com/gta-chaos-mod/ChaosModV/issues/582, https://github.com/gta-chaos-mod/ChaosModV/issues/391, https://github.com/gta-chaos-mod/ChaosModV/issues/565
please use the search: https://github.com/gta-chaos-mod/ChaosModV/issues?q=Jesus :)
