### ISSUE TITLE
[Effect Suggestion] Time Freeze

### ISSUE THREAD

**Issue by rndmninja** [gta-chaos-mod/ChaosModV#653]
**Name of effect**
Freeze Time, Pause, Stop Time, Time Freeze, Timeout

**Duration if timed effect (long or short timed?)**
15-25 seconds

**Effect Description**
The effect should freeze the day and night cycle and if possible it could freeze dialog and NPCs. Player is allowed to kill these NPCs but the death animation is not shown until the effect ends. The bullets won't be frozen 'cause they are hitscan but any projectile could be frozen.

Thank you,
love your work.

**Comment by anto4440** [comment]
Suggested twice already (Maybe more, maybe the two others had slight changes, but this one is not going to work due to... something)

**Comment by Last0xygen** [comment]
Freezing day night cycle for 30 second would not be obvious, the rest sounds a lot like „peds are brainless“
