### ISSUE TITLE
[Effect Suggestion] Griefer Jesus Update

### ISSUE THREAD

**Issue by Spambalot** [gta-chaos-mod/ChaosModV#657]
Make Griefer Jesus respawn in the same spot one time after being killed (like a "resurrection"). This could also be applied to Extreme Griefer Jesus, or only one of the two.

**Comment by anto4440** [comment]
oh no, greifer jesus has already done enough problems, he doesnt need to respawn.

**Comment by pongo1231** [comment]
I agree with the comment above, I think he's enough of a burden for players right now already.
