### ISSUE TITLE
[Effect Suggestion] Fake Griefer Jesus

### ISSUE THREAD

**Issue by MineedTV** [gta-chaos-mod/ChaosModV#661]
**Name of effect**
Fake Griefer Jesus, Fake Jesus

**Effect Description**
Spawns in a Jesus NPC that despawns after a second or so / whose shots do not deal damage/ explode stuff

**Comment by Last0xygen** [comment]
Already suggested several times, see https://github.com/gta-chaos-mod/ChaosModV/issues/621, https://github.com/gta-chaos-mod/ChaosModV/issues/582, https://github.com/gta-chaos-mod/ChaosModV/issues/391, https://github.com/gta-chaos-mod/ChaosModV/issues/565, https://github.com/gta-chaos-mod/ChaosModV/issues/650
please use the search: https://github.com/gta-chaos-mod/ChaosModV/issues?q=Jesus :)
