### ISSUE TITLE
[Effect Suggestion] spawn Florida man

### ISSUE THREAD

**Issue by RobertAwesome** [gta-chaos-mod/ChaosModV#662]
**spawn Florida man**
Potential name(s) for the effect
Florida man

**Effect Description**
Spawns ones of the hillbillies looking npc that has a lot of help that attacks the players, he could have a shotgun because its Florida, or he has  Wrench. Up to you

**Comment by anto4440** [comment]
No more spawn something something

**Comment by Last0xygen** [comment]
Not a really „unique“ idea, sorry
