### ISSUE TITLE
kill,kill,kill

### ISSUE THREAD

**Issue by breadpilledbro** [gta-chaos-mod/ChaosModV#665]
**Name of effect**
kill,kill,kill

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Player will get a timer, simular to need for speed, but instead of speeding up to not explode, player needs to start killing people, otherwise he will explode

**Comment by anto4440** [comment]
Too easy to just take ou

**Comment by pongo1231** [comment]
Was already implemented as The Blade Hungers effect which has been removed since
