### ISSUE TITLE
[Feature Suggestion] Show vote percentage and if random of successful vote.

### ISSUE THREAD

**Issue by Jameth13** [gta-chaos-mod/ChaosModV#666]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The on-screen successful would show its percentage.
eg, "[45%] Spawn Greifer Jesus" instead of just "Spawn Greifer Jesus".

Also, if the effect was selected from Random Effect, this should also be shown.
eg, "[5% rnd] Spawn Greifer Jesus" means 5% of votes were for Random Effect and Spawn Greifer Jesus was chosen.

**Describe alternatives you've considered**
N/A

**Additional context**
This addition would allow a streamer to know if chat intentionally screwed them, or accidentally screwed them xD

**Comment by TheRealAyCe** [comment]
Good idea imo

**Comment by Last0xygen** [comment]
Same as https://github.com/gta-chaos-mod/ChaosModV/issues/270
