### ISSUE TITLE
[Feature Suggestion] Effect Groups

### ISSUE THREAD

**Issue by SeanMirrsen** [gta-chaos-mod/ChaosModV#667]
I'm just out of control with these original feature names, aren't I?

_What are Polyeffects?_
We're getting massive amounts of suggestions for very common types of effects. Spawning this or that vehicle, teleport to this or that location, give this or that weapon, spawn this or that creature, NPC, or enemy. While some of them might even be funny or interesting, they're not very _creative_, and the existing effects system means they would hog effect slots, coming up in the random queue disproportionately often.

Solution? Basically effect groups. "Polyeffects" are groups of effects that are, for the purposes of voting, treated as a single effect. The effects that comprise them do not, individually, appear in the effect list - they're treated as if they are disabled. But, when a "polyeffect" comes up in voting, a specific effect from its constituent effects list is chosen to be displayed and voted on.

So that, for instance, we could have a few tens of "teleport to location" effects. Mount Chiliad, the airport, the military base, heaven, ocean depths, top of maze bank tower, literally anywhere else. But when choosing effects to populate the voting list, none of them would ever be chosen. Instead, there would be a "teleport polyeffect", just one effect instead of dozens. And only if it's chosen to be in the list, instead of "teleport polyeffect", the name of one of the effects would be shown, for instance "Teleport to Heaven". And that effect would be the one activated if it's chosen.

_Setup considerations:_
Polyeffects (or "effect groups" if you want) could be assigned through the settings app, just choosing a "group name" for the effect if the effect belongs in one, or leaving it blank if it doesn't.

The individual effects could still be optionally called upon through various means, for instance random effect could choose from the whole list, or a metaeffect could force the polyeffects to be disabled and force the voting choices to be populated from the full list.

**Comment by ntill** [comment]
I have nothing useful to say other than that this would be an incredibly appreciated feature as a user of the mod.

**Comment by TheRealAyCe** [comment]
Yes! This is what I've been proposing for a while now. Thank you for putting it in a dedicated ticket. I think rejecting all those wacky ideas just because "we have enough teleports" is not ideal - let's change the code so that we can add more teleports/enemy templates/jesus things etc. without destroying the balance. You could even keep the names for voting, no need to "hide" the specific location the target is teleported to.

**Comment by SeanMirrsen** [comment]
> You could even keep the names for voting, no need to "hide" the specific location the target is teleported to.

Yes, that's what I tried to clarify with my explanation. Basically, the name of the "polyeffect" effect group would never be seen by the player or chat (if one is present). When the polyeffect comes up, they'd see one of the effect names in the group instead, and would vote on it as though it's that effect. The 'grouping' is purely internal, and I think it makes a lot more sense to implement it in this generalized way (as "groups" that even the end user could define through the settings app, or include or exclude effects from the grouping as they wish), rather than hardcoded randomly-selected effect lists for individual categories.

**Comment by Thunderstorm64** [comment]
Yes, I think it's a good idea that will work well.

**Comment by pongo1231** [comment]
Renamed it to "Effect Groups" since it's clearer in its intention. Definitely agree though, this would allow for a much wider variety of effects which can be easily categorized into one specific group (like "Teleports" or "Insta-Kills") and will likely be implemented in 1.9.1 (at least in a basic form).
