### ISSUE TITLE
[Effect Suggestion] Suicidal Peds

### ISSUE THREAD

**Issue by Thunderstorm64** [gta-chaos-mod/ChaosModV#669]
**Name of effect**
Ped Suicide, Suicidal Peds.

**Effect Description**
Makes all peds nearby on foot commit suicide like the player. Player is not affected.

**Comment by anto4440** [comment]
This is too close to explode all nearby peds, i think. there are just too many effects that alredy kills all npc's around the player. Besides, nothing overly interesting would really happen.
