### ISSUE TITLE
[Effect Suggestion] Flashbang

### ISSUE THREAD

**Issue by DeadlySilence22** [gta-chaos-mod/ChaosModV#672]
**Flashbang**

**Short Time (Similar to Blind)**

**An effect where the screen if turned white similar to the effect of Flashbang for a short duration of time. Could be coupled with a sound effect of a flashbang.**

**Comment by Last0xygen** [comment]
Already in the works 
https://github.com/gta-chaos-mod/ChaosModV/pull/624

**Comment by DeadlySilence22** [comment]
> Already in the works
> #624

Nice. 🤞👍
