### ISSUE TITLE
[Effect Suggestion] Fake Suicide

### ISSUE THREAD

**Issue by LizardQueen27** [gta-chaos-mod/ChaosModV#675]
**Name of effect**
Fake Suicide

**Effect Description**
Pretty much just Fake Death with the Suicide animation of the character putting a gun to their head, and then the same screen as Fake Death “Wasted: Just Kidding, Keep Playing”

**Comment by SeanMirrsen** [comment]
That's... literally what Fake Death already is.

**Comment by anto4440** [comment]
Bro thats hopw faje death works
Besides, you should suggest to change fake death, not make a second identical one.

**Comment by Last0xygen** [comment]
Already implemented, no change
