### ISSUE TITLE
no options for 0hKO to be applied on player only

### ISSUE THREAD

**Issue by welheizel** [gta-chaos-mod/ChaosModV#677]
Would be nice if there was an option where 0hKO could be applied only to the playable character, or have two 0hko's , the usual one is Peds and a new one in Player section

**Comment by anto4440** [comment]
I actually agree with you.

**Comment by anto4440** [comment]
But couldnt you just make an effect suggetstion called Tko or Tohko?

**Comment by welheizel** [comment]
> But couldnt you just make an effect suggetstion called Tko or Tohko?

yeah true, or that, works both ways, can be something that u can turn on and off tho, cuz i tried to copy DarkviperAu's 0 hit run, realized that the difference the effect can make on gameplay if it just effected the player or if it effected everyone
so yeah can be another effect all of it's own

**Comment by pongo1231** [comment]
Don't really think that's needed, especially since dedicated OHKO mods exist (now).
