### ISSUE TITLE
[Effect Suggestion] Snipers

### ISSUE THREAD

**Issue by TheChilliPL** [gta-chaos-mod/ChaosModV#678]
**Name of effect**
Snipers

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Spawning snipers on a set of predefined coordinates near the player (maybe not too near, you could set minimum and maximum distance needed for the spawn). The spawn points should be on rooftops, high billboards, etc. If the sniper spawned on a rooftop etc., they should stay there and try to kill the player.

I could help with gathering some coordinates of rooftops, etc.

**Comment by TheRealAyCe** [comment]
What's the maximum range that NPCs can target the player from?
Manual coordinates sound like a bad idea. But maybe a couple hundred checks can be made on random spots in the player's vicinity to find ones that are higher than the player yet have good visibility.

**Comment by TheChilliPL** [comment]
Don't know how you could find good sniping positions without a lot of manual coordinates, though. Also not sure about the range

**Comment by Last0xygen** [comment]
Placing snipers manually would be very time consuming and also not applicable to every position in the map (not possible in the upper part of the map)
And by removing that, we're stuck with mercenaries using snipers
