### ISSUE TITLE
[Effect Suggestion] jesus take the wheel improvement

### ISSUE THREAD

**Issue by 0rangeGhost** [gta-chaos-mod/ChaosModV#679]
**Duration if timed effect (long or short timed?)**
at least short timed, but preferably long

**Effect Description**
jesus take the wheel is very fun effect, but people mostly bail out of car immediately when jesus takes the wheel, loosing all its fun
suggestion is to lock player inside vehicle for some time, so people could enjoy the ride on passenger seat :)

**Comment by Da-Best** [comment]
If thes lock is temporary and not permanent then it will be better as it can cause softlocks especially if you are on missions where you need to drive a car to somewhere.

**Comment by Powercube7** [comment]
yall bail from the car? I just let jesus drive me to where i want

**Comment by MoneyWasted** [comment]
This can cause soft locks during missions.
