### ISSUE TITLE
Up-to-date issue

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#68]
Even when i updated ChaosModV to 'current version' 1.7.2, config window still tells me, that new update is available. It confuses me
![Up-to-date issue](https://user-images.githubusercontent.com/63610557/88697678-690e7280-d11e-11ea-9771-d2e007f9bb11.PNG)

**Comment by pongo1231** [comment]
Did you make sure to drag and drop all files (and replace all existing ones if prompted)? The newest one is 1.7.3 and it also displays correctly in the latest config utility.

**Comment by JustTunerYT** [comment]
Yes, i even dragged each file into their folder.
I downloaded the last version of ChaosModV (1.7.2) on GTA5-mods, which was latest version. There was no 1.7.3 version

**Comment by pongo1231** [comment]
Have you tried opening the mod page and then refreshing the page? Could just be your browser loading a cached version of the page.

**Comment by JustTunerYT** [comment]
I entered download site 3 or more times, there was no 1.7.3. 
But now when i checked, there is 1.7.3. When i'll try newest version, i will close this issue.

**Comment by JustTunerYT** [comment]
After update it doesn't say now. Sorry for misunderstanding
