### ISSUE TITLE
[Effect Suggestion] there aren't cougars in this mission!

### ISSUE THREAD

**Issue by 0rangeGhost** [gta-chaos-mod/ChaosModV#680]
**Name of effect**
there aren't cougars in this mission!

**Effect Description**
spawn a cougar/any hostile animal behind the player that will hunt player

**Comment by Numi43** [comment]
A better name would be "Matto´s Nightmare" or "Speedrunner´s Nightmare".

**Comment by SeanMirrsen** [comment]
Better yet, "Here There Be Cougars", referencing Bradbury's "Here There Be Tygers".

The effect could periodically cast rays (or fire invisible bullets) behind the camera, spawning a cougar wherever the ray/bullet lands. The key is to spawn the cougar behind the camera, not the player, so that the player never sees the cougar spawn.

**Comment by TheRealAyCe** [comment]
There aren't _enough_ cougars in this mission!

**Comment by Hackermanxdd** [comment]
THIS BETTER BE ADDED IN THE NEXT UPDATE

**Comment by ProfessorBiddle** [comment]
> THIS BETTER BE ADDED IN THE NEXT UPDATE
>

It definetely will (not) if you keep asking like this

>

**Comment by TheRealAyCe** [comment]
People work on what they want to work on. If none of the programmers want to code this, it will not be done. The suggestion phase is just to reject bad/duplicate ideas.

**Comment by Da-Best** [comment]
The only thing that is the issue is that cougars only attack when you are on foot and not when you are in cars so if this happens when you are in a car then it basically does nothing.

**Comment by SeanMirrsen** [comment]
Then for once it'll be an effect that only works if you're on foot, rather then only when you're in a vehicle.

**Comment by pongo1231** [comment]
Part of the mod now
