### ISSUE TITLE
[Effect Suggestion] GTA 4 cars

### ISSUE THREAD

**Issue by Erc195** [gta-chaos-mod/ChaosModV#683]
**Name of effect**
GTA 4 cars
**Duration if timed effect (long or short timed?)**
long

**Effect Description**
Makes all cars on streets be only the ones Rockstar bring back from GTA 4 back to GTA 5

**Comment by Last0xygen** [comment]
I don’t think it’s possible to add vehicles yourself.

**Comment by Thunderstorm64** [comment]
I think he meant the vehicles from gta 4 that are already in gta 5 like the Cavalcade
