### ISSUE TITLE
[Effect Suggestion] Spawn Train 

### ISSUE THREAD

**Issue by liamjmbta** [gta-chaos-mod/ChaosModV#684]
Spawn Train 

**Effect Description**
Spawns a train

**Comment by 0rangeGhost** [comment]
i think it's better not just spawn, but spawn infront of player at some distance and give it some speed towards player enough to kill him, distance should be barely enough to evade it

**Comment by TheRealAyCe** [comment]
Please use search https://github.com/gta-chaos-mod/ChaosModV/issues/562

**Comment by Last0xygen** [comment]
Duplicate
