### ISSUE TITLE
[Effect Suggestion] Amazing Fps

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#687]
**Name of effect**
Amazing fps

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Optimizes Fps to the limit: All graphics go to their lowest, render distance low, You get the point. Change everything to make higher fps.

**Comment by Da-Best** [comment]
As i understand you want to make the game go into low render distance?

**Comment by Last0xygen** [comment]
Seems like „low render distance“ to me
