### ISSUE TITLE
[Effect Suggestion] who TF is that

### ISSUE THREAD

**Issue by Hackermanxdd** [gta-chaos-mod/ChaosModV#692]
**Name of effect**
Who TF is that

**Effect Description**
Shows a fake mission fail screen that says "Gustavo Mota died."

**Comment by Last0xygen** [comment]
"same" as "Fake Death"

**Comment by TheRealAyCe** [comment]
And a dupe https://github.com/gta-chaos-mod/ChaosModV/issues/275 :P
