### ISSUE TITLE
[Effect Suggestion] Rapture!

### ISSUE THREAD

**Issue by Fansheep** [gta-chaos-mod/ChaosModV#693]
**Name of effect**
Rapture! / Chaos On It's Fullest

**Duration if timed effect**
short

**Effect Description**
Adds doomsday weather and slight camera shaking. While active, makes random peds get inverted gravity and sets other random peds on fire. All peds drive in panic state (Won't stop if you get in their way). None of the effects applied to peds are applied to player.

Optional effect: Spawns an invincible Griefer Jesus in a location not so far from the player (100-500m).

**Comment by Last0xygen** [comment]
Sounds like "Invert Gravity" with "Stormy Weather", not really "unique"
