### ISSUE TITLE
[Effect Suggestion] Naked 

### ISSUE THREAD

**Issue by liamjmbta** [gta-chaos-mod/ChaosModV#696]
**Name of effect**
naked, remove player clothes 
 
**Effect Description**
removes all clothes from player

**Comment by anto4440** [comment]
Too little happening.

**Comment by liamjmbta** [comment]
> Too little happening.

i thought it would be funny if a character is just suddenly naked in a mission

**Comment by Fansheep** [comment]
Pls dont apply this effect to Trevor

**Comment by Last0xygen** [comment]
> > Too little happening.
> 
> i thought it would be funny if a character is just suddenly naked in a mission

I get where you’re coming from, but this is part of „random player clothes“, an additional variant is not needed imo
