### ISSUE TITLE
[Effect Suggestion] Taxes

### ISSUE THREAD

**Issue by Fansheep** [gta-chaos-mod/ChaosModV#697]
**Name of effect**
Taxes

**Duration if timed effect**
Long

**Effect Description**
Charges player 100$ for every 10 seconds. If player has no money left (or not enough left), then the player is obliterated.

**Comment by anto4440** [comment]
Either you are unaffected or you die instantly

**Comment by Fansheep** [comment]
> Either you are unaffected or you die instantly

This is how the world works, my man

**Comment by anto4440** [comment]
> > Either you are unaffected or you die instantly
> 
> This is how the world works, my man

Well see when your effect inevitably doesnt get added.

**Comment by anto4440** [comment]
What are you trying to accomplish by saying that? I mean, its not like Pongo is gonna add due to realism.

**Comment by Fansheep** [comment]
> What are you trying to accomplish by saying that? I mean, its not like Pongo is gonna add due to realism.

This was my sense of humor, and it appears you have misunderstood it. I know this effect may not be really added, but i still try to think of something unique and interesting that might help this mod develop.

P.s. You're going on r/Wooooosh

**Comment by ProfessorBiddle** [comment]
>
> P.s. You're going on r/Wooooosh
>

wow

>

**Comment by Last0xygen** [comment]
Sounds like suicide with some extra steps
