### ISSUE TITLE
[Effect Suggestion] All Peds are Companions 

### ISSUE THREAD

**Issue by Jonatin0** [gta-chaos-mod/ChaosModV#699]
All Peds are Companions

Turns all peds in area to companions able to help in fights and get into your car.

**Comment by anto4440** [comment]
You cant make this shit up.

**Comment by TheRealAyCe** [comment]
Somewhat available with "You are famous"

**Comment by pongo1231** [comment]
As mentioned in a similar suggestion there is a hard limit on concurrent companions which means this isn't a feasible idea to implement.
