### ISSUE TITLE
[Effect Suggestion] The Viet Nam War Flashback

### ISSUE THREAD

**Issue by Djnkout** [gta-chaos-mod/ChaosModV#702]
**Name of effect**
Viet Nam flashback, The trees are speaking

**Effect Description**
Spawn an enemy on every tree/bush. Or better yet, turn the trees into enemies.

**Comment by anto4440** [comment]
The trees arent objects, the are a part of the map. I believe the same applies for bushes. Therefore, its impossible to turn them into enemies, and spawning an enemy close to them would require manual coding of every bush and tree.

**Comment by Djnkout** [comment]
> And Veitnam is a single word. Or, technically a name.

Viet Nam is actually different words putting together, from a Vietnamese

**Comment by anto4440** [comment]
But Vietnam is still only one name, right?

**Comment by Last0xygen** [comment]
For one, there should be a limit on the enemy count (20 enemies if you’re in the forest? :D).
Ok the other hand, an effect like this already exists with „Killer Clowns“ which spawns random enemies, regardless of bushes and trees
