### ISSUE TITLE
[Effect Suggestion] Griefer mode

### ISSUE THREAD

**Issue by MrFatCatMan** [gta-chaos-mod/ChaosModV#704]
Name
Griefer mode

Duration
1 minute

Description
The chacracer model is changes in to griefer Jesus and the players weapons are taken away and is given a railgun with infinite ammo which the player is then attacked by the player model npc enemy which has all of the player weapons and is cloned every time he is killed

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
Also, changing the players model breaks things.
