### ISSUE TITLE
[Effect Suggestion] Lottery

### ISSUE THREAD

**Issue by ThatDeathbat** [gta-chaos-mod/ChaosModV#708]
**Name of effect**
Life or Death Lottery

**Effect Description**
There’s a 1 in 20 (5%) chance to survive this effect.

Play’s a dice rolling sound.
If Death: Play “Aw Fuck” Micheal voiceline and explode shortly after.

If live: Play a happier sound and give the player 500k in cash

**Comment by ThatDeathbat** [comment]
Ayyyyy

**Comment by anto4440** [comment]
Either you die or there is no effect.

**Comment by Last0xygen** [comment]
Similar effect already worked on 
https://github.com/gta-chaos-mod/ChaosModV/pull/163
