### ISSUE TITLE
[Effect Suggestion] Teleport to Cayo Perico

### ISSUE THREAD

**Issue by Geekoo2** [gta-chaos-mod/ChaosModV#710]
**Name of effect**
Teleport to Cayo Perico

**Effect Description**
Teleports you to Cayo Perico where you will be stuck there until you mission fail or another effect kills you and you spawn back at Los Santos

**Comment by Fansheep** [comment]
This is not a very possible effect, due to the fact that Cayo Perico will need to be manually added to the story mode to work. Plus even if it's added, you will still be able to easily escape from there.

**Comment by Da-Best** [comment]
To add on Cayo Perico island in gta 5 if it does get added in will be extremely laggy seeing all the chunks to load in. They can get out with the boats or planes that are usually there or get spawned in.

**Comment by Last0xygen** [comment]
Can’t be done efficiently, also not a really hot effect for chaos mod
