### ISSUE TITLE
[Effect Suggestion] Inverted controls

### ISSUE THREAD

**Issue by Etherealistic** [gta-chaos-mod/ChaosModV#713]
**Name of effect**
Inverted controls
Switched up

**Duration if timed effect (long or short timed?)**
Short timed

**Effect Description**
Works on characters and all vehicles. If you want to go right, you need to turn as if you wanted to go left and vice versa. If you want to go forward, you need to press the backwards key. An easily counter-intuitive effect!

**Comment by MoDerPo** [comment]
#16 and in the comments it also says forwards and backwards.

**Comment by Last0xygen** [comment]
Duplicate #16
