### ISSUE TITLE
[MetaEffect Suggestion] Reversed odds of twitch voting.

### ISSUE THREAD

**Issue by ZSSmain** [gta-chaos-mod/ChaosModV#719]
**Name of effect**
(Meta) reversed odds

**Duration if timed effect (long or short timed?)**
Until next effect

**Effect Description**
If chaos mod is being controlled by twitch chat the higher percentage of votes for an effect will make it less likely while the lower percentage of votes will make it more likely.

**Comment by Last0xygen** [comment]
Already suggested #641
