### ISSUE TITLE
[Effect Suggestion] STOP

### ISSUE THREAD

**Issue by badmanbrad001** [gta-chaos-mod/ChaosModV#720]
**Name of effect**
stop
**Duration if timed effect (long or short timed?)**
long

**Effect Description**
when the player reaches a certain speed a invincible stop sign gets spawned in front of them stopping them instantly

**Comment by TheRealAyCe** [comment]
As a timer thing? Because as a one-time effect this seems very situational. Maybe the effect could be combined with the existing Speed Limit.

**Comment by Last0xygen** [comment]
This already kind of exists with „30mph speed limit“ and/or „stop and stare“
I don’t think an effect this similar is needed
