### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by frrvuyt** [gta-chaos-mod/ChaosModV#721]
**Name of effect**
Car gun

**Duration if timed effect (long or short timed?)**
Long 

**Effect Description**
The effect is where everyones guns shootd cars out and it could be random cars and also can only just be for the player and not everyone.

**Comment by Fibbo0** [comment]
cool idea

**Comment by Last0xygen** [comment]
@frrvuyt  Please rename the title
