### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by frrvuyt** [gta-chaos-mod/ChaosModV#722]
**Name of effect**
Teleport to north yankton

**Effect Description**
teleports you to north yankton untill mission fail or death

**Comment by Last0xygen** [comment]
@frrvuyt Please rename the title

**Comment by Da-Best** [comment]
This could have some softlock potential as if you are not in a mission then you will be stuck at north yankton. This especially applies if you can only play as 1 character as there is no switch you can do.

**Comment by Last0xygen** [comment]
This seems like a softlock-effect and nothing else 😅
