### ISSUE TITLE
[Effect Suggestion] 

### ISSUE THREAD

**Issue by Shadow-GOD-op** [gta-chaos-mod/ChaosModV#726]
**Name of effect**
Meta effect- opposite voting

**Duration if timed effect (long or short timed?)**
Meta effect- long effect

**Effect Description**
The least voted effect is picked

**Comment by Last0xygen** [comment]
same as https://github.com/gta-chaos-mod/ChaosModV/issues/719 and https://github.com/gta-chaos-mod/ChaosModV/issues/641

**Comment by SeanMirrsen** [comment]
Not to mention #523
