### ISSUE TITLE
[Effect Suggestion] New suggestion 

### ISSUE THREAD

**Issue by hetsonii** [gta-chaos-mod/ChaosModV#727]
Add new effects by combining effects that already exists.
ex. 1> Full Acceleration after 2 seconds of teleporting at the top of mount chiliad/ maze bank tower.
2> Give all weapons after 2 seconds of teleporting to waypoint.
3> 'Peds are brainless' after 2 seconds of 'all peds attack player'
####726

**Comment by EliRickard** [comment]
I can't see this improving gameplay or the mod any any meaningful way. What's more the things mentioned would largely counter act or just aren't at all related.

**Comment by Da-Best** [comment]
The peds are brainless after all peds attack player just defeats the purpose of peds attack player as the peds cant do anything. TP to waypoint and give all weapons do not mix in any way. You already keep your speed when you tp anywhere so if you are driving you would already fall off.

**Comment by hetsonii** [comment]
> The peds are brainless after all peds attack player just defeats the purpose of peds attack player as the peds cant do anything. TP to waypoint and give all weapons do not mix in any way. You already keep your speed when you tp anywhere so if you are driving you would already fall off.

**Comment by hetsonii** [comment]
> The peds are brainless after all peds attack player just defeats the purpose of peds attack player as the peds cant do anything. TP to waypoint and give all weapons do not mix in any way. You already keep your speed when you tp anywhere so if you are driving you would already fall off.

**Comment by hetsonii** [comment]
> The peds are brainless after all peds attack player just defeats the purpose of peds attack player as the peds cant do anything. TP to waypoint and give all weapons do not mix in any way. You already keep your speed when you tp anywhere so if you are driving you would already fall off.


Those were some examples. They can combine any 2 effects and make a new one like that.

**Comment by Da-Best** [comment]
like combo time meta? ofc this started way before that but that know exists
