### ISSUE TITLE
[Effect Suggestion] **Griefer Jesus Take The Wheel**

### ISSUE THREAD

**Issue by SurelyYouBeJestin** [gta-chaos-mod/ChaosModV#732]
**Name of effect**
Griefer Jesus Take The Wheel

**Effect Description**
It's like Jesus Take The Wheel, but if you pull him out of the car he pulls out a railgun and shoots you.

And perhaps it would be funny to make it a 50/50 chance of him being equipped with snowballs, or a railgun

**Comment by MoneyWasted** [comment]
We are currently not adding anymore "Jesus" themed effects.
