### ISSUE TITLE
[Effect Suggestion] Spawn griefer jesus at waypoint (or destination)

### ISSUE THREAD

**Issue by PiMoNFeeD** [gta-chaos-mod/ChaosModV#734]
**Name of effect**
Spawn griefer jesus at waypoint

**Effect Description**
Just spawns a griefer jesus on the waypoint or destination (if possible because we all know the distance might be too far away)

**Comment by Last0xygen** [comment]
Making this a separate effect is not really distinct enough and adding it to the current "spawn griefer jesus" effect is not a good addition to the effect itself
