### ISSUE TITLE
[Effect Suggestion] All Peds are drunk

### ISSUE THREAD

**Issue by imadethisfor1page** [gta-chaos-mod/ChaosModV#736]
**Everyone is drunk**

**Duration is short**

All Peds are drunk, including drivers, pilots, boaters, and the player so all vehicles go haywire.

**Comment by Da-Best** [comment]
I do not get how this will help/ make the game difficult. It could just be like GTA Online traffic( an old effect that got removed)

**Comment by imadethisfor1page** [comment]
Its technically chaotic. And if you are driving fast on the road and because you and the peds are drunk, you will crash ALOT, potentially slowing you down where the mod has a good chance to kill you and you can mission fail. (If the person even gets away that is.)

**Comment by imadethisfor1page** [comment]
I also do not know what GTA Online traffic is, so also fill me in on that.

**Comment by Da-Best** [comment]
> I also do not know what GTA Online traffic is, so also fill me in on that.

It was an effect where it made the peds drive into around chaotic like you would see in gta online so basically traffic magnet but they would just serve into you I think it was. I never really saw it in play before it got removed.

**Comment by imadethisfor1page** [comment]
I understand. Since I think that Pilots would be best if drunk, should traffic magnet let it be possible for planes to crash into the player?
