### ISSUE TITLE
[Effect Suggestion] Arthur Morgan

### ISSUE THREAD

**Issue by imadethisfor1page** [gta-chaos-mod/ChaosModV#737]
**Arthur Morgan!**

**Duration is long**
Unless you only turn the character into Arthur Morgan without him talking, keep the timer.

**Effect Description**
It turns the character into Arthur Morgan and maybe also says random lines of him talking, including custom lines which could be made for a streamer.
Or just teleport the player to a random part in RDR2's map.

**Comment by Fansheep** [comment]
There's litteraly no way rn to teleport from GTA V to a random part of RDR2's map

**Comment by Fibbo0** [comment]
this is impossible unless addon peds

**Comment by Last0xygen** [comment]
Not possible
