### ISSUE TITLE
[Effect Suggestion] Change Character

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#738]
**Name of effect**
Change Character

**Duration if timed effect (long or short timed?)**
Immediate effect

**Effect Description**
Swap character to any of the (up to) other 2 available characters

**Comment by Fibbo0** [comment]
good idea but will they count as official charecters?

**Comment by DarrenBellew** [comment]
> good idea but will they count as official charecters?

I mean say if you're michael, it'll switch to franklin or trevor. But ofc if you haven't unlocked trevor it won't pick trevor.

**Comment by TheRealAyCe** [comment]
Related: https://github.com/gta-chaos-mod/ChaosModV/issues/322

**Comment by Last0xygen** [comment]
Already suggested
