### ISSUE TITLE
[Effect Suggestion] Vow of Poverty

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#739]
**Name of effect**
Vow of Poverty

**Duration if timed effect (long or short timed?)**
1-2 minutes

**Effect Description**
If player earns any money for this duration, the player will die immediately.

**Comment by Da-Best** [comment]
if this happens whilst on a mission where you collect money wouldn't that be a 1-2 mins fail loop

**Comment by Last0xygen** [comment]
I don't think there's a way to communicate the effect to any player. it would just kill them "randomly"
