### ISSUE TITLE
[Effect Suggestion] Caged

### ISSUE THREAD

**Issue by FAR95d** [gta-chaos-mod/ChaosModV#742]
**Name of effect**
Caged

**Effect Description**
Spawn fences around and above the player

**Comment by anto4440** [comment]
fences?

**Comment by Da-Best** [comment]
That can lead to softlocks like near the beginning of the game where the player doesn't have explosives

**Comment by Last0xygen** [comment]
This would be just as good as "Player Swap", freezing the player in place.
Making it permanent (which this suggestion states) is even "worse" as it completely softlocks the player
