### ISSUE TITLE
[Effect Suggestion] Spawn Cougar(s)

### ISSUE THREAD

**Issue by Banilinho** [gta-chaos-mod/ChaosModV#746]
Spawn Cougar, Spawn Cougars

Spawns a Cougar behind or near the player, could be more, if the effect too easy to survive

i think that this is a simple effect and a nice reference to OHKO, and acts more like a filler so more powerfull options don't appear so often

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/680
