### ISSUE TITLE
'Explosive Bullets' does not mean 'Explosive Melee Weapons'

### ISSUE THREAD

**Issue by JustTunerYT** [gta-chaos-mod/ChaosModV#75]
Effect 'Explosive Bullets' affect melee weapons, which should not do. After this effect appears, shotten bullets explodes, that's right. But when player attacks someone or hit something with melee weapon, it explode player and something (ped, car, object)

**Comment by pongo1231** [comment]
A good idea could be to merge "Explosive Punches" into "Explosive Bullets" and rename it to something like "Explosive Combat". " Explosive Punches" by itself does barely anything the vast majority of the time so combining both into 1 effect would make more sense.

**Comment by pongo1231** [comment]
Implemented now.
