### ISSUE TITLE
[Effect Suggestion] 

### ISSUE THREAD

**Issue by beepbeepsheep69** [gta-chaos-mod/ChaosModV#751]
Effect name-Double trouble

Effect Description
This effect should spawn two Grefer Jesuses (this could be normal grefers or extreme)

**Comment by anto4440** [comment]
I think it would be better if it duplicated all enemies. Of course, not so many that it would cause problems, but it would ba an actual challenge.

**Comment by Last0xygen** [comment]
I don't think thats a good addition to this mod
