### ISSUE TITLE
[Effect Suggestion] Never Gonna Give You Up - Musical Horns

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#752]
**Name of effect**
Never Gonna Honk You Up

**Duration if timed effect (long or short timed?)**
some duration, not sure

**Effect Description**
All vehicles, or current vehicle, honk to the rhythm of Never Gonna Give You Up by Rick Astley

**Comment by anto4440** [comment]
what if noone even honked in the first place? also, someone would have to manually make that honking tune.

**Comment by TheRealAyCe** [comment]
Unless you or someone else can provide a textfile transcribing that rythm into delays I doubt anyone would want to take the time to do this. But given that, as long as it's just a rythm it shouldn't be impossible to make cars honk with certain delays. You are not thinking of different pitches of honks right?

**Comment by Da-Best** [comment]
Are you talking about the full song with words or just the melody? If it is with words then it can get the youtuber/ streamer copyright claimed/ vod muted

**Comment by DarrenBellew** [comment]
If course, just a melody

Islarf @ OnePlus 6T

**Comment by Last0xygen** [comment]
Not really possible to time honks that specific for multiple vehicles. 
It's pretty much CPU dependend, if vehicles can honk at that time and even then, i don't see any advantages over "all vehicles honk" that would be worth it
