### ISSUE TITLE
[Effect Suggestion] Reset Game

### ISSUE THREAD

**Issue by 7w2** [gta-chaos-mod/ChaosModV#753]
**Reset Game**
Potential name(s) for the effect

**Effect Description**
Resets the game, but it's only a 0.05% chance of happening without twitch controls, and with twitch controls it's **ONLY** available in "Random Effect" and it's a super rare chance.

**Comment by Da-Best** [comment]
I do not think that a mod can start the game again and if it can it would just be annoying and they can just load the save file that they made and restart there.

**Comment by Last0xygen** [comment]
Resetting the game is not a good effect
