### ISSUE TITLE
[Kinda An Effect Suggestion] 

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#756]
**Name of effect**
Lock XXX to Money.

**Duration if timed effect (long or short timed?)**
Idk it depends on the effect in question.

**Effect Description**
Hey there! this is a bit of a different effect suggestion, since there are no specifics. But i Had this idea where the players money could affect their Fps or Fov or something like that. There ae of course a couple problems: What should the baseline of money be, and how much would one million (or any amount really) Affect the other value? And this is where i decided to make this an idea, but one that other people would have to help me with finishing.

**Comment by Da-Best** [comment]
So if i am understanding correctly you want the money to be stuck at a certain amount so the player can not gain or lose money?

**Comment by kolyaventuri** [comment]
While that sounds neat, at least for the idea of locking FPS to money it would fall apart pretty quickly. What happens if you have $10,000,000 in game but a potato PC that can't run beyond 30fps?

**Comment by Da-Best** [comment]
It will also be annoying at the beginning of the game as you don't have any money so the fps will be low. Especially if you are streaming it could lead to fps being low on stream which doesn't look good

**Comment by anto4440** [comment]
Hm... I was thinking about it being locked to the change of money, so 200 or 200.000.000 wouldnt matter, only the change of money. The only problem is that change is rare.
