### ISSUE TITLE
[Effect Suggestion] Blimp strat

### ISSUE THREAD

**Issue by lauke1010** [gta-chaos-mod/ChaosModV#758]
**Name of effect**
Blimp strat

**Effect Description**
It teleports the player into a blimp that is then tp'ed to the Galileo Observatory like the speedrun strat. Undecided if the player should keep his momentum or not.

**Comment by anto4440** [comment]
That just a 'Teleport to XXX'

**Comment by ZeliTheZealot** [comment]
The player should be given the correct position and momentum such that, in a few seconds, he will be well poised to dive out of the blimp at the correct position to do the actual blimp strat
