### ISSUE TITLE
This isn't really an effect but...

### ISSUE THREAD

**Issue by retrored5** [gta-chaos-mod/ChaosModV#760]
**Name of effect**
Good chaos
**Duration if timed effect (long or short timed?)**

**Effect Description**
It would be a new version of chaos that only contains the good effects like give all weapons, upgrade current vehicle, teleport to waypoint, etc.

**Comment by Last0xygen** [comment]
Already suggested https://github.com/gta-chaos-mod/ChaosModV/issues/509
