### ISSUE TITLE
[Effect Suggestion] OUR GOD IS AN AWESOME GOD

### ISSUE THREAD

**Issue by Powercube7** [gta-chaos-mod/ChaosModV#764]
Petition to have the "Our god is an awesome god" song in matto's videos to be included by default in the mod when griefer jesus spawns

**Comment by Last0xygen** [comment]
Not possible die to copyright

**Comment by lZevex** [comment]
The song's been used in viper's videos several times, no copyright issues at all, so why would it affect others?

**Comment by MoneyWasted** [comment]
The reason why YouTuber’s don’t get a copyright notice is that the record label has not applied for YouTube's content ID system. The "Greifer Jesus song" named "Awesome God" by Phillip Kin is part of the album "Nitro Praise 4" and the rights to that album are owned by NSoul Records Inc. They are a christian record label based out of California. You can view all of the songs they own the rights to here. https://www.discogs.com/label/1205-NSoul
