### ISSUE TITLE
[Effect Suggestion] Improve Fake Death

### ISSUE THREAD

**Issue by Gorlix1337** [gta-chaos-mod/ChaosModV#765]
Fake Death

Default, already existing delay.

Improve:
Instead of suddenly fake killing and then telling that its fake death, show that the chaos effect is Death, and then switch it to fake death.
For example: (im not a programmer please dont kill me)
*fake death appears*
if(guy is not in vehicle)
{
show fake death message "Suicide"
}
elseif(guy is in vehicle)
{
show fake death message "Explode Current Vehicle"
}

And then after fake death went through, change the print to "Fake Death"

sorry for my bad english 😄

**Comment by anto4440** [comment]
Yeah, i agree.

**Comment by Last0xygen** [comment]
Already in the works https://github.com/gta-chaos-mod/ChaosModV/pull/325
