### ISSUE TITLE
[Effect Suggestion] Equality

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#768]
**Name of effect**
Equality/Confusing gravity

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Makes any and all object have the exact same gravity.

**Comment by Fansheep** [comment]
That won't change anything tho...

**Comment by Da-Best** [comment]
so basically Insane gravity and invert gravity?

**Comment by anto4440** [comment]
Yeah i only realised this now.
