### ISSUE TITLE
[Effect Suggestion] Do A Barrel Roll!

### ISSUE THREAD

**Issue by Fansheep** [gta-chaos-mod/ChaosModV#769]
**Name of effect**
Do A Barrel Roll!

**Duration if timed effect**
Short

**Effect Description**
Player's screen starts slowly rolling... Litteraly...

**Comment by TheRealAyCe** [comment]
The vomit comet is back :D https://github.com/gta-chaos-mod/ChaosModV/issues/502

**Comment by anto4440** [comment]
Wooohooo!
I wanna write 'Duplicate of XXX' this time!

**Comment by Last0xygen** [comment]
Duplicate #502

**Comment by Da-Best** [comment]
Spinning camera is only the camera i thought of this as being front rolling over and over again? maybe just me miss understanding it
