### ISSUE TITLE
[Effect Suggestion] Improvised Weaponry

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#774]
**Name of effect**
Improvised Weaponry.

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
When effect is active, whenever the player (only the player) shoots a ranged weapon a random loaded object gets moved in place of the bullet. This is *not* #439, this one uses actual assets (More like Catto guns, but instead of spawning cats random loaded objects are used). A bit of specific modification is needed in order to prevent player from getting crushed on larger objects.

**Comment by kolyaventuri** [comment]
How is this not identical to #439? Feels like that one has assets that don't collide with anything, and this one actually does? They don't seem different enough to justify having two versions.

**Comment by anto4440** [comment]
No, difference is this uses loaded assets, and #439 just Visually randomized the look of the bullets.
