### ISSUE TITLE
[Effect Suggestion] Stop right there criminal scum

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#779]
**Name of effect**
Stop right there criminal scum!

**Duration if timed effect (long or short timed?)**
Immediate

**Effect Description**
The player is busted / arrested.
If not, spawn a ton of cops around the player and force them to get busted (deny movement and combat) 
(would have to change to 1 star I suppose)

**Comment by Last0xygen** [comment]
Already in the works https://github.com/gta-chaos-mod/ChaosModV/pull/308

**Comment by DarrenBellew** [comment]
Fair enough!
