### ISSUE TITLE
[Effect Suggestion] Red Light City

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#784]
**Name of effect**
Red Light City

**Duration if timed effect (long or short timed?)**
1-2 minuted

**Effect Description**
Replace all pedestrians with, and only spawn, strippers and prostitutes for a duration

**Comment by anto4440** [comment]
I dont think enough happens.

**Comment by Last0xygen** [comment]
Not really possible to replace all press efficiently.
Also not a really unique and/or funny effect
