### ISSUE TITLE
[Effect Suggestion] Rising tide

### ISSUE THREAD

**Issue by TheMoltenFace** [gta-chaos-mod/ChaosModV#787]
**Name of effect**
Rising tide
Tsunami

**Duration if timed effect (long or short timed?)**
Long timed

**Effect Description**
Increases water lvl, choose the multiplier by yourself

**Comment by TheRealAyCe** [comment]
This? https://github.com/gta-chaos-mod/ChaosModV/issues/619

**Comment by TheMoltenFace** [comment]
It looks really simillar, but not exactly this. In this variant the water
lvl changes instantly, also the weather doesn't change

**Comment by TheMoltenFace** [comment]
oh there's another, and also i've just saw that water lvl changing is impossible in one of those tickets
