### ISSUE TITLE
[Effect Suggestion] Spawn Viewers

### ISSUE THREAD

**Issue by LennartOschika** [gta-chaos-mod/ChaosModV#790]
This is an effect from someone on Discord that doesn't know how to post here ( https://discord.com/channels/268280696601051136/268280696601051136/820320433340940308 )

Basically, spawn as many people around the player as the number of Twitch viewers (or the ped limit). They all have the "You are famous" effect, and of the player kills any one of these peds, a random twitch viewer gets banned from the stream for 10 minutes.

**Comment by Da-Best** [comment]
What if you are not streaming and banning someone from the twitch chat will just make them leave the stream meaning less people. And you will need a moderator of chat to ban someone only if they make a twitch bot

**Comment by Thunderstorm64** [comment]
That's the dumbest thing I've ever heard.
