### ISSUE TITLE
[Effect Suggestion] Skydiving

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#791]
**Name of effect**
Skydiving

**Duration if timed effect (long or short timed?)**
Immediate

**Effect Description**
Put player in heaven outside of vehicle and give them a parachute if they don't have one

**Comment by Da-Best** [comment]
Seems like #676

**Comment by DarrenBellew** [comment]
> Seems like #676

That just gives player the ability to fly

**Comment by Da-Best** [comment]
My mistake I understood it wrong

**Comment by anto4440** [comment]
I think you should add that as an improvement to teleport to heaven. So when teleport to heaven is chosen, player receives a parachute.

**Comment by Last0xygen** [comment]
duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/142
