### ISSUE TITLE
[Effect Suggestion] Lockdown

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#794]
**Name of effect**
Lockdown

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Remove all peds and vehicles on the road. Don't spawn new peds / peds in vehicles for the duration.

**Comment by anto4440** [comment]
I cant believe it. I cannot find a 'No traffic' effect suggested before.

**Comment by Da-Best** [comment]
> I cant believe it. I cannot find a 'No traffic' effect suggested before.

i don't think it was suggested on here i think it was put in before they opened this github forum thing and when this was in viper's discord server

**Comment by Last0xygen** [comment]
„No traffic“ is already an effect in Chaos

**Comment by anto4440** [comment]
Oh thats why

**Comment by kolyaventuri** [comment]
Closing because No Traffic already exists
