### ISSUE TITLE
[Effect Suggestion] Peyote

### ISSUE THREAD

**Issue by huskymaddog** [gta-chaos-mod/ChaosModV#797]
**Name of effect**
Peyote

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Turns the player into a random animal, as if they consumed a peyote. Long effect, however it may conclude early if the player dies before the timer ends.

**Comment by anto4440** [comment]
idk, setting it to long would be pretty boring. either you die early, or you just stay as an animal unable to do things for a long time.

**Comment by Last0xygen** [comment]
Already requested several times. If it happens during a mission it could potentially softlock the game, needs extra handling once you die and so on.
Currently not a possible effect for chaos
