### ISSUE TITLE
[Effect Suggestion] Sharknado

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#799]
**Name of effect**
Sharknado

**Duration if timed effect (long or short timed?)**
Medium

**Effect Description**
Shark Tornado

**Comment by anto4440** [comment]
I hate to ask, but could you elaborate on the effect description? Maybe add an explanation to what is does, what 'shark tornado'ø means, how long medium length is... You know, the thing you might wanna know when implementing an effect.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/604
