### ISSUE TITLE
[Effect Suggestion] Shorter Chaos Timer / Longer Chaos Timer

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#800]
**Name of effect**
- 0.5x Chaos Timer
- 2x Chaos Timer

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
One or both effects.
Modify the duration between effects / voting time to be double or half the normal duration for a time

**Comment by lZevex** [comment]
All of these already exist

**Comment by Da-Best** [comment]
Both are meta's and already exist

**Comment by Last0xygen** [comment]
Yup, already made those ;)
