### ISSUE TITLE
[Effect Suggestion] Exit Current Mission

### ISSUE THREAD

**Issue by jdefgh** [gta-chaos-mod/ChaosModV#804]
**Name of effect**
Exit Current Mission, Quit Current Mission, Quit Mission or Exit Mission

**Effect Description**
Exits current missions if on mission.

**Comment by anto4440** [comment]
Yeah, not only is it not interesting, its outright a bad effect. Its the exact opposite of what we wish to achieve.

**Comment by kolyaventuri** [comment]
Despite missions being a large part of the game, this feels too situational. if you're outside a mission, or are playing with chaos mod after completing story mode, this won't ever do anything
