### ISSUE TITLE
[Feature Suggestion] Edit catto guns to have a cat on the front like the cat silencer in postal 2

### ISSUE THREAD

**Issue by emil302s** [gta-chaos-mod/ChaosModV#807]
i just think it could be fun when catto guns is activate that there would be a cat infront of the guns

![Example](https://user-images.githubusercontent.com/15109742/111180634-83159c00-85ad-11eb-8290-551576b626bb.jpg)

**Comment by Last0xygen** [comment]
I don’t think that would be suitable for this mod
