### ISSUE TITLE
[Effect Suggestion] Acid Rain

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#809]
**Name of effect**
Acid Rain

**Duration if timed effect (long or short timed?)**
1.5 minutes

**Effect Description**
Player when under direct rain will periodically take an amount ot damage. Being in a vehicle with a closed roof or inside / under a building or cave would prevent damage. (Being under a roof on a bike would ofc prevent damage)

**Comment by Last0xygen** [comment]
Already suggested #480 please use the search with any filters to see if something has already been suggested, i.e. https://github.com/gta-chaos-mod/ChaosModV/issues?q=Acid
