### ISSUE TITLE
[Effect Suggestion] WTF THATS OP

### ISSUE THREAD

**Issue by htorw** [gta-chaos-mod/ChaosModV#815]
**Name of effect**
WTF THATS OP

**Duration if timed effect (long or short timed?)**
30 seconds 

**Effect Description**
infinite rapid fire bottomless clip railgun
pew mother fking pew

**Comment by Last0xygen** [comment]
„Rapid fire“ already exists

**Comment by htorw** [comment]
true but not a rapid fire railgun aka wtf thats op

**Comment by Last0xygen** [comment]
Every gun has Rapidfire, not only the railgun.
Making a new effect which only affects the railgun? I don’t know... seems like a step backwards

**Comment by htorw** [comment]
when i thought about it in my head "more effects is always better" kinda thing. eh

**Comment by htorw** [comment]
I totally agree with that. Uniqueness?
but that still goes back to rapid fire + alien weapon and all other really unique weapons
