### ISSUE TITLE
[Effect Suggestion] Euphoria physics like in GTA IV

### ISSUE THREAD

**Issue by Akosywok** [gta-chaos-mod/ChaosModV#817]
**Name of effect**
GTA IV ragdoll

**Duration if timed effect (long or short timed?)**
long

**Effect Description**
It uses the euphoria game engine for ragdoll effects.

**Comment by juhana** [comment]
This isn't feasible by any stretch.

**Comment by kolyaventuri** [comment]
+1 on the infeasibility. While I believe there are individual mods that enable this, the complexity in implementing and maintaining an effect like this far outweigh the benefits of the effect itself.
