### ISSUE TITLE
[Bug] Brake Boosting

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#821]
If you brake lightly enough, you won't be boosted. Discovered this on viper's stream

**Comment by Last0xygen** [comment]
Can't reproduce.
Everytime i start braking  i get boosted. Any links to this happening?
If you brake while standing still you're not braking but reversing -> no boost.
Otherwise i can't reproduce it

**Comment by lZevex** [comment]
Found it but he was reversing which explains it. But it did give me an idea for a Reverse boosting effect (Boosts your vehicle backwards when you reverse) Thanks
