### ISSUE TITLE
Griefer Jesus should walk on water

### ISSUE THREAD

**Issue by dusannemec** [gta-chaos-mod/ChaosModV#823]
Watching The BEST of Twitch Controls GTA V Chaos! (Chat Randomly Mods The Game) #2 again. And I saw Griefer Jesus swimming. I don't know if it's possible, but he should walk on water for cases that he is spawned on water.

**Comment by TheRealAyCe** [comment]
I suggested it here already: https://github.com/gta-chaos-mod/ChaosModV/issues/144
I could have sworn there was another ticket open for this exact thing already, but I can't find it right now.

**Comment by anto4440** [comment]
Seems like a lot of effort for an extraordinarily specific outcome..

**Comment by kolyaventuri** [comment]
With the way the mod is set up, this isn't currently possible. Or, more specifically, it would have to be a long timed effect, and even then it would only be for the duration of the effect, for an extremely specific use case.
