### ISSUE TITLE
[Effect Suggestion] teleport to Light house 

### ISSUE THREAD

**Issue by Airtastik** [gta-chaos-mod/ChaosModV#824]
**Name of effect**
Potential name(s) teleport to Lighthouse 

**Effect Description**
teleports player to the Lighthouse on the east side of the map

**Comment by anto4440** [comment]
I cant find where it was previously, but this is literally a *copy paste* of a previous effect suggestion. why did you do this?

**Comment by Airtastik** [comment]
It isn't, the other suggestion teleports to a different location.

**Comment by kolyaventuri** [comment]
It isn't as obviously searchable, but this is a duplicate of #448, minus being in a tractor.
