### ISSUE TITLE
[Effect Suggestion] Spawn juggernaut 

### ISSUE THREAD

**Issue by Airtastik** [gta-chaos-mod/ChaosModV#826]
**Name of effect**
Are you for real?? or Spawn juggernaut 

**Effect Description**
Spawns juggernaut enemy with Heavy armor and a minigun

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/98
https://github.com/gta-chaos-mod/ChaosModV/issues/426

**Comment by Last0xygen** [comment]
Duplicate #98
#426
