### ISSUE TITLE
[Effect Suggestion] Flip current vehicle

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#831]
**Name of effect**
Flip current vehicle

**Duration if timed effect (long or short timed?)**
Immediate

**Effect Description**
Immediately flips current vehicle upside down (or 180 degrees). This should happen even if in a boat, bike, car, plane, tank. Anything.

**Comment by kolyaventuri** [comment]
Functionally already exists as "Flip All Vehicles." One that just affects the vehicle you're in isn't quite different enough

**Comment by DarrenBellew** [comment]
> Functionally already exists as "Flip All Vehicles." One that just affects the vehicle you're in isn't quite different enough

Oh I searched "flip" but nothing showed up
