### ISSUE TITLE
[Effect Suggestion] Input Lag

### ISSUE THREAD

**Issue by Nachoskik** [gta-chaos-mod/ChaosModV#834]
Potential names: Input Lag, Pentium, Toaster pc.

30sec duration.

It should emulate the infamous input lag, making 
keys register late and stay pressed more than you
actually press them.

**Comment by Rathalin** [comment]
This effect could replace the current "Drunk" effect since you react slower under the influence.

**Comment by TheRealAyCe** [comment]
Or maybe merge into Console Experience to make it even more unbearable.

**Comment by anto4440** [comment]
oh yeah, i remember this one! #545 #767

**Comment by Last0xygen** [comment]
duplicate  https://github.com/gta-chaos-mod/ChaosModV/issues/545
