### ISSUE TITLE
[Effect Suggestion] Explosive Traffic

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#840]
**Name of effect**
Explosive Traffic

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Whenever any vehicle collides with anything (not by simply driving on the road) it will explode

**Comment by Last0xygen** [comment]
so... you mean "vehicles explode on impact"?

**Comment by DarrenBellew** [comment]
Oh, i searched for it. how can i search "existing suggestions". having no filter seems to pick them up

**Comment by Last0xygen** [comment]
i don't know if there has been a suggestion for this effect 🤔
