### ISSUE TITLE
[Effect Suggestion] Confusing Waypoints

### ISSUE THREAD

**Issue by DarrenBellew** [gta-chaos-mod/ChaosModV#843]
**Name of effect**
Confusing Waypoints

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
For duration place random purple waypoint on map if out of mission. If in mission, randomly move the mission waypoint to somewhere else in the map. (Of course the destination stays the same).

The goal is to secretly make them follow the waypoint on the map to the wrong location, if following it, however if the player knows the actual location they, hopefully, won't be affected by it.

**Comment by anto4440** [comment]
Idk man it feels like an instant effect.
