### ISSUE TITLE
[Effect Suggestion] Binoculars, short effect.

### ISSUE THREAD

**Issue by KatieDeForest** [gta-chaos-mod/ChaosModV#847]
**Name of effect**
Insane zoom
Binoculars 

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Either make the whole screen zoom in like you are using Binoculars, or make it so you are looking through two holes in the screen, just like the DVD effect, just static and shaped like two circles.

**Comment by TheRealAyCe** [comment]
Reverse of Quake FOV, I like it.
