### ISSUE TITLE
[Effect Suggestion] Eat Random Peyote Plant

### ISSUE THREAD

**Issue by CPLJimmy** [gta-chaos-mod/ChaosModV#849]
**Name of effect**
Either literally "Eat Random Peyote Plant" or maybe one of the lines of dialogue that a character says when they become an animal.  Like Franklins "I'm a pigeon now."

**Duration if timed effect (long or short timed?)**
Short timed... this effect will prevent progress so should be short.

**Effect Description**
Self-evident, makes the character player instantly stop and eat a peyote plant, if in a vehicle they exit vehicle to accomplish this.  Of course, eating a peyote plant instantly transforms the player into a random animal for a short period of time.  In normal gameplay the transformation lasts until you die, but for chaos should be a short timer.

I personally just want to see DarkViper in a shoot out with Merryweather and suddenly turns into a pig or something.

**Comment by zzguy12** [comment]
This could be streamlined a lot..

Name of effect
"Polymorph"

Duration if timed effect (long or short timed?)
Short Timed

Effect Description
Turn a player into a random animal.

**Comment by Last0xygen** [comment]
Duplicate 
https://github.com/gta-chaos-mod/ChaosModV/issues/797
