### ISSUE TITLE
[Effect Suggestion] Carmageddon

### ISSUE THREAD

**Issue by Djangoultra** [gta-chaos-mod/ChaosModV#852]
**Name of effect**
Carmageddon

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
Like the GTA San Andreas chaos mod effect, this consists in cars on fire (near to explode) falling from the sky.

**Comment by 810CK-A1D** [comment]
Already done with vehicle rain, i dont think this will be effective

**Comment by Last0xygen** [comment]
yup, already done with "Vehicle Rain" :)
