### ISSUE TITLE
[Effect Suggestion] Heavy Vehicles 

### ISSUE THREAD

**Issue by 810CK-A1D** [gta-chaos-mod/ChaosModV#853]
Name of effect
Heavy vehicles

Duration of effect
Long timed

Effect Description
All vehicles nearby become heavy, meaning it can ram cars with ease and no loss of control

**Comment by Last0xygen** [comment]
Please adjust the title to add the name of the effect

**Comment by 810CK-A1D** [comment]
The effect name is already there, but if you mean something else i dont quite understand what you mean

**Comment by Last0xygen** [comment]
![E82C67CA-EA33-416F-B4CC-F75D32B10725](https://user-images.githubusercontent.com/41595552/112239639-1f434100-8c47-11eb-99d7-9a918e6a026c.jpeg)

Add the title of the effect after „[effect suggestion]“

**Comment by 810CK-A1D** [comment]
Alr Just done it

**Comment by Last0xygen** [comment]
Nice
Now repeat for your other suggestions too please 😅
#622 and #541

**Comment by 810CK-A1D** [comment]
alright done

**Comment by Last0xygen** [comment]
After thinking about this again, i gues this effect is a less chaotic version of "Forcefield" as it only affects other vehicles if you're driving and getting REALLY close (hitting) them
