### ISSUE TITLE
Effect Suggestion||Griefer Jesus Hell

### ISSUE THREAD

**Issue by asapoiua** [gta-chaos-mod/ChaosModV#863]
Name of effect
Griefer Jesus Hell

Duration if timed effect (long or short timed?)
Short

Effect Description
Turns nearby npcs into griefer jesus

**Comment by Last0xygen** [comment]
already suggested several times, see https://github.com/gta-chaos-mod/ChaosModV/issues/714 or https://github.com/gta-chaos-mod/ChaosModV/issues/579
