### ISSUE TITLE
[Effect Suggestion] Replace current vehicle with one of the same type

### ISSUE THREAD

**Issue by SirHaxe** [gta-chaos-mod/ChaosModV#872]
**Name of effect**
Replace current vehicle 

**Effect Description**
If you for example are in a plane, replace it with a plane, if you are on a bike, replace it with a bike
Alternative: replace aviation vehicle with aviation vehicle

**Comment by Last0xygen** [comment]
"Replace current vehicle" already exists but replaces it with any vehicle to be more chaotic
