### ISSUE TITLE
[Effect Suggestion] All cars drive like Comet

### ISSUE THREAD

**Issue by MakaAlb** [gta-chaos-mod/ChaosModV#875]
**Name of effect**
All cars drive like Comet

**Duration if timed effect (long or short timed?)**
Long

**Effect Description**
All cars have same driving characteristics as Comet.

**Comment by Thunderstorm64** [comment]
no

**Comment by dumbdumb89** [comment]
to do this you would have to change handling.meta in the game files, making it permanent

**Comment by MakaAlb** [comment]
Thank you for explanation.
