### ISSUE TITLE
[Effect Suggestion] Merryweather Fleet's Here Bro

### ISSUE THREAD

**Issue by Aljotzi** [gta-chaos-mod/ChaosModV#878]
**Effect Name**
Merryweather Fleet's Here Bro

**Effect Description**
Teleport to Trevor's shooting location from Derailed and spawn two merryweather boats nearby

**Comment by Last0xygen** [comment]
Effect already exists as "Mercenaries", which wont teleport you but sends Mercenaries after you :)
