### ISSUE TITLE
[Effect Suggestion] Remove weapons from everyone and give them a musket

### ISSUE THREAD

**Issue by kewlonez** [gta-chaos-mod/ChaosModV#884]
**Name of effect**
Musket Mayhem

**Effect Description**
Removes everybody's weapons and equips them with a musket gun.

**Comment by yungmepsi** [comment]
i actually kinda like this one lmao bump

**Comment by TheRealAyCe** [comment]
Duplicate? https://github.com/gta-chaos-mod/ChaosModV/issues/450

**Comment by Last0xygen** [comment]
Yup, duplicate #450
