### ISSUE TITLE
Grouped effects are too unlikely to come up

### ISSUE THREAD

**Issue by juhana** [gta-chaos-mod/ChaosModV#885]
I just watched two streams playing with Twitch voting for a combined total of 5 hours with the latest version. During that time options to spawn peds or to teleport came up fewer than 10 times in total.

I did the math and it looks like handling effect group probabilities as if they were one single effect makes them way too rare. For example before the grouping there was about 16% chance of seeing a ped spawn effect as an option in each Twitch voting round. Now it's about 1.3%. During a normal 2-hour stream you used to get on average about 40 ped spawn options, now you get 3. You'll see either version of Griefer Jesus as an option on average once every 4.5 hours with Twitch voting, without it once every 14 hours (used to be once every 45 minutes with Twitch and once every 2 hours without.)

It might be better to assign fixed percentages to effect groups, for example 10% chance of ped spawn, 10% chance of teleport etc. and then once the group has been chosen using those probabilities, pick a random effect from inside the group.

**Comment by SeanMirrsen** [comment]
The simple solution is having the effect groups have separately defined weights, so that they can be made more or less likely to occur. 

Granted, it's 'simple' mechanically, but it'll take a bit of work to make it so they're user-adjustable.

**Comment by juhana** [comment]
The quickest and simplest fix would be to have smaller groups with max. 3-4 effects each, e.g. both Griefer Jesuses in one group, Jimmy, Alien and Impotent Rage in an "enemies on foot" group, Agent, Blue Sultan and Balla Squad in an "enemies in vehicles" group etc. so that it'd lower the total occurrences but not as much. Then you could add more effects to those groups in the future without affecting their probabilities.

**Comment by SeanMirrsen** [comment]
No, that is not a good solution. It's the equivalent of stuffing loose socks into your trouser pockets to make the mess in the room seem smaller. Adding configurable weights to the effect groups is a much simpler and more robust solution, that allows the probability to be tweaked with ease.

**Comment by juhana** [comment]
"Simpler" as in easier to implement. Creating a whole new configuration category is not simple.
