### ISSUE TITLE
[Effect Suggestion] Fatigue

### ISSUE THREAD

**Issue by lZevex** [gta-chaos-mod/ChaosModV#888]
Your weapons do less damage and have a slower fire rate

**Comment by Last0xygen** [comment]
„Minimal weapon damage“ already exists, 
Reducing the Fire Rate ist too situational to be an inconvenience for the player

**Comment by lZevex** [comment]
Reducing fire rate isn't situational, it makes killing NPCs take much longer and you kind of have to kill them to progress. Not every effect has to instantly fail the mission, and it's kind of unfair that you'd rather add a "Spawn Biker" effect over this.

**Comment by Last0xygen** [comment]
> Reducing fire rate isn't situational, it makes killing NPCs take much longer and you kind of have to kill them to progress. 

Yea, but this effect/result is already implemented as "One Bullet Mags" 😃 

> Not every effect has to instantly fail the mission,

agreed, never said otherwise 😃 👍 

> and it's kind of unfair that you'd rather add a "Spawn Biker" effect over this.

You're more than welcome to code it, but please don't tell me what to do, which effect to code or when to respond, THAT would be unfair 😉

**Comment by lZevex** [comment]
One bullet mags just means you have to keep reloading and doesn't just affect the player, with this effect the fire rate can be reduced to any speed, and coming to think of it you could reduce accuracy and reload speed too. It would be a completely unique variant of the existing gun effects
