### ISSUE TITLE
[Effect Suggestion] Cougar Pack

### ISSUE THREAD

**Issue by Qaplan** [gta-chaos-mod/ChaosModV#892]
**Name of effect**
Cougar spawn, Cougar pack, Evil cougar, or something like that.

**Effect Description**
Description of the effect; what should it do?
It will spawn around 3 or 4 cougars, that will try and kill the player.

**Comment by Last0xygen** [comment]
Already suggested https://github.com/gta-chaos-mod/ChaosModV/issues/680
