### ISSUE TITLE
[Effect Suggestion] Quick Sprunk Stop...

### ISSUE THREAD

**Issue by SonnyEvans** [gta-chaos-mod/ChaosModV#894]
**Name of effect**
Quick Sprunk Stop

**Duration if timed effect (long or short timed?)**
Spawns object

**Effect Description**
Spawns static or dynamic Sprunk vending machine object a few feet in front of the player. The term ''Quick Sprunk Stop'' would get a new meaning if the player is driving down the highway at high speed without the seatbelt on. It could also provide useful cover in firefights or less handy blockage of doors!

[Vending_machine_%28GTA4%29_%28Sprunk%29](https://user-images.githubusercontent.com/81496955/112739528-4fefe700-8f75-11eb-9cba-635dbb6e8638.jpg)

**Comment by MoneyWasted** [comment]
If this is the actual Sonny Evans. I'll be more than happy to add this for you.

**Comment by SonnyEvans** [comment]
It would be an honor for real!

**Comment by MoneyWasted** [comment]
> It would be an honor for real!

Awesome I'll work on getting it implemented.

**Comment by SonnyEvans** [comment]
Awesome, if you need anything from me let me know!

**Comment by Last0xygen** [comment]
Made the effect but be aware, that the interaction with the machine is not possible with this. This would require custom code to „fake“ it, would be too much. 
hope it’s still ok :)

**Comment by Thunderstorm64** [comment]
is it the real SonnyEvans considering the account made this as he first post?

**Comment by SonnyEvans** [comment]
> is it the real SonnyEvans considering the account made this as he first post?

I am, I'm in the discord. You can verify my profile there

**Comment by MoneyWasted** [comment]
> Made the effect but be aware, that the interaction with the machine is not possible with this. This would require custom code to „fake“ it, would be too much.
> hope it’s still ok :)

Would like to correct you. Yes you can have interaction with a vending machine. I have the code written in Lua for FiveM. I won't explain how I did it here as it would be a pretty long explanation but when I get it written into C++ I'll send review the PR with the changes.
