### ISSUE TITLE
[Effect Suggestion] spawn companion griffer Jesus

### ISSUE THREAD

**Issue by Defalt333** [gta-chaos-mod/ChaosModV#896]
spawn companion griffer Jesus

**Effect Description**
Spawn companion griffer Jesus that follow the player and have a railgun (And it's also a good way to scare Matt when he spawn)

**Comment by TheRealAyCe** [comment]
Like this? https://github.com/gta-chaos-mod/ChaosModV/issues/565 many duplicates for this one i think

**Comment by Last0xygen** [comment]
yup, duplicate of #565 and #391
