### ISSUE TITLE
[Effect Suggestion] Spawn Companion Pavel

### ISSUE THREAD

**Issue by ThisIsMurica** [gta-chaos-mod/ChaosModV#904]
**Name of effect**
Spawn companion Pavel

**Effect Description**
This effect spawns the NPC Pavel with a minigun (or any gun) to help out the player.

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/489 duplicate

**Comment by Last0xygen** [comment]
Duplicate #489
