### ISSUE TITLE
[Effect Suggestion] COUGARS DON'T SPAWN IN MISSIONS!

### ISSUE THREAD

**Issue by alguienrrr** [gta-chaos-mod/ChaosModV#906]
**Name of effect**
COUGARS DON'T SPAWN IN MISSIONS!

**Duration if timed effect (long or short timed?)**
Either long or short, not sure which would be best

**Effect Description**
Spawn cougars around the player which are aggressive against it

**Comment by Last0xygen** [comment]
Please use the search before requesting a new effect :)
https://github.com/gta-chaos-mod/ChaosModV/issues?q=Cougar
