### ISSUE TITLE
[Effect Suggestion] swim anywhere/flood map

### ISSUE THREAD

**Issue by yungmepsi** [gta-chaos-mod/ChaosModV#909]
**Name of effect**
idk not good w names mayb like under the sea or flooded or bikini bottom or something

**Duration if timed effect (long or short timed?)**
probably long

**Effect Description**
not sure if this would be possible or if it would just crash everyones pc or not even b supported by the gta engine or w.e lmao but like flood the map up to the height limit or the tops of most buildings in the city and force the player and all the npcs and stuff to swim everywhere (maybe with infinite air or something) or alternatively just force the player and all npcs into a swimming movement animation or w.e where they can swim in any direction through the air as if they dived almost kinda like a controllable no gravity effect

**Comment by TheRealAyCe** [comment]
lmao duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/619 https://github.com/gta-chaos-mod/ChaosModV/issues/729

**Comment by Last0xygen** [comment]
yeah, seems like duplicate #619 #729
