### ISSUE TITLE
[Effect Suggestion] Spawn Cougar

### ISSUE THREAD

**Issue by HDXY1** [gta-chaos-mod/ChaosModV#916]
**Spawn Cougar**
Spawn Big Floppa, Cat lover, "THERE AINT COUGARS IN MISSIONS"

**Effect Description**
Spawns a cougar, based on the funny event that happened with DarkViperAU when he played through his pretty recent One Hit One Kill (OHKO) in this clip: https://www.youtube.com/watch?v=DlxkZOdCNlw 

Also named big floppa because as an alternative in case this got spammed, spawns a cougar (Nearly looks like caracal, can be improved with a model replacement of a caracal)

**Comment by Last0xygen** [comment]
Already requested 6 times
Please use the search before requesting a new effect :)
https://github.com/gta-chaos-mod/ChaosModV/issues?q=Cougar
