### ISSUE TITLE
Spawn Companion Brad Edit

### ISSUE THREAD

**Issue by BlaiseDebeste** [gta-chaos-mod/ChaosModV#917]
Whenever Companion Brad spawns and Dave Norton is nearby, Dave opens fire on Brad because he should be dead in a grave in North Yankton.

**Comment by Aljotzi** [comment]
This makes no sense... there are very few missions where this would work ("Three's Company", "By The Book", "Monkey Business" and "The Wrap Up") and it just seems unnecessary.

**Comment by Last0xygen** [comment]
way too specific, i dont think this would be a good addition
