### ISSUE TITLE
[[Effect Suggestion]] by RosyMiranto

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#919]
I could have use the format below, however i have so many effect suggestions that it's not possible for me to do it. If you request it however, i shall do it as fast as i can, but for now, everything i suggested is listed in this Document. it contains various new effects and tweaks to the older ones. If you have any question, feel free to mention it on the Reply.

[Chaos Mod Ideas.docx](https://github.com/gta-chaos-mod/ChaosModV/files/6240351/Chaos.Mod.Ideas.docx)

**Name of effect**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
If not a timed effect, remove this section

**Effect Description**
Description of the effect; what should it do?

**Comment by TheRealAyCe** [comment]
Please change/remove this post and create the ideas as individual tickets. Nobody wants to download a docx or interact with a collection-of-ideas post. The ticket should have the title of the effect in their names, see how other suggestion tickets do it.

**Comment by Last0xygen** [comment]
Also, please use the search before requesting duplicates (I.e. https://github.com/gta-chaos-mod/ChaosModV/issues?q=Skyfall)

**Comment by RosyMiranto18** [comment]
I understand that. However, i'm not too sure if i should be the one who deleted this at least until i put up every other individual suggestion. I already had receive the feedback from some of the suggestion i had and i'll take a proper time to make every other ones correctly according to the guide. Once my body is well enough for me to be able to sit without bleeding myself. Thank you for the words however. And yes, with the Search Function as well.
