### ISSUE TITLE
[Effect Suggestion] Teleport to Mount Gordo

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#930]
**Name of effect**
**Teleport to Mount Gordo**

**Duration if timed effect (long or short timed?)**
One-time

**Effect Description**
Teleport to the most chill place to have a Yoga, arguably having a worse descent than Chiliad. At least you can find a ghost in midnight.

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/2408
