### ISSUE TITLE
[Effect Suggestion] Gfred Spirit

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#931]
**Name of Effect**
**Gfred Spirit**

**Duration if timed effect (long or short timed?)**
One-time

**Effect Description**
Teleported to a secluded island east of El Gordo Lifehouse. The good news is, no momentum to lunge you into the water immediately. The bad news is, you still have to ditch the car anyway. So began swimming to the Lighthouse and grab a bicycle or tractor to start Broughy1322’s famous Weekly Cannonball Run Event, Gfred.

**Comment by Last0xygen** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/2408 Duplicate
