### ISSUE TITLE
[Effect Suggestion] The Alt Strat

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#936]
**Name of effect**
**The Alt Strat**

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
Forces you to pull up the Character Switch Menu. However this is not the same as Character Swap where you’re stuck in the cloud during the effect. Instead, this works just like OHKO.

**Comment by TheRealAyCe** [comment]
This now seems to be the main ticket: https://github.com/gta-chaos-mod/ChaosModV/issues/1056

**Comment by Last0xygen** [comment]
yeah, using the other request
