### ISSUE TITLE
[Effect Suggestion] Spawn Companion Jesse

### ISSUE THREAD

**Issue by AxmPlays** [gta-chaos-mod/ChaosModV#945]
**Name of effect**
Spawn Companion Jesse/Jesus

**Effect Description**
It's Jesus with a railgun but doesn't attack you and defends you, just like Brad with an RPG.

**Comment by Last0xygen** [comment]
duplicate of #565, #391 #908, https://github.com/gta-chaos-mod/ChaosModV/issues/910 and #896
