### ISSUE TITLE
[Effect Suggestion] Spawn Gas Tank

### ISSUE THREAD

**Issue by Aljotzi** [gta-chaos-mod/ChaosModV#947]
**Name of effect**
Spawn Gas Tank

**Duration if timed effect (long or short timed?)**
Instant

**Effect Description**
Spawns a gas tank (like the one at the airfield that you blow up during "Nervous Ron" or the one that Trevor crashes into during "Something Sensible")

**Comment by anto4440** [comment]
Nope. Either it will have the effect of Spawn bale trailer, or explode current vehicle

**Comment by Aljotzi** [comment]
> Nope. Either it will have the effect of Spawn bale trailer, or explode current vehicle

Thats a good point
