### ISSUE TITLE
[Effect Suggestion] Covid

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#950]
**quarantine**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
 Long

Description of the effect; what should it do?
**no peds or cars in the road**

**Comment by Da-Best** [comment]
close to #794

**Comment by Aljotzi** [comment]
This seems way too close to the "No Traffic" effect just without peds spawning.

**Comment by Last0xygen** [comment]
„No traffic“ already exists, see discussion #794
