### ISSUE TITLE
[Effect Suggestion] Covid (idea 2)

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#951]
**you have covid**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
Iong

Description of the effect; what should it do?
**if you touch someone he dies**

**Comment by anto4440** [comment]
Ever heard of midas touch?

**Comment by Last0xygen** [comment]
I agree, this seems way too similar to „Midas touch“ and gives no advantages over it
