### ISSUE TITLE
[Effect Suggestion] dog simulator

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#952]
**dog simulator**
Potential name(s) for the effect

**Duration if timed effect (long or short timed?)**
long

Description of the effect; what should it do?
turns the player into a dog (when the effect ends, the player returns to normal)

**Comment by TheRealAyCe** [comment]
https://github.com/gta-chaos-mod/ChaosModV/issues/797 not possible

**Comment by Last0xygen** [comment]
Duplicate, #797
