### ISSUE TITLE
[Effect Suggestion] Farming Simulator

### ISSUE THREAD

**Issue by TheBatmanReal** [gta-chaos-mod/ChaosModV#954]
**Farming Simulator**
Potential name(s) for the effect

Description of the effect; what should it do?
**teleports the player to a farm on a tractor**

**Comment by anto4440** [comment]
I Swear to  god. I have seen this somewhere before. I know it.

**Comment by Last0xygen** [comment]
Found it: https://github.com/gta-chaos-mod/ChaosModV/issues/448
Duplicate

**Comment by anto4440** [comment]
Nice.

Den tir. 6. apr. 2021 kl. 09.41 skrev Last0xygen ***@***.***>:
