### ISSUE TITLE
[Effect Suggestion] Tank Bois

### ISSUE THREAD

**Issue by Salzdose** [gta-chaos-mod/ChaosModV#958]
**Name of effect**
Tank Bois

**Duration if timed effect (long or short timed?)**
Immediatly

**Effect Description**
Same as Bus Bois, but it puts all NPCs into Rhinos

**Comment by TheRealAyCe** [comment]
"Tanks alot"

**Comment by anto4440** [comment]
i am confident the engine canty handle that.

**Comment by juhana** [comment]
If it can handle Bus Bois, why couldn't it handle this?

**Comment by anto4440** [comment]
it could handle bus bois. it crashed in the beginning.

Den tir. 6. apr. 2021 kl. 17.55 skrev Juhana Leinonen <
***@***.***>:

**Comment by juhana** [comment]
Yes, and the issue was fixed and it doesn't crash anymore.

**Comment by anto4440** [comment]
By changing it so that everything doesnt spawn in at once. If you actually
were active on the platform, i wouldnt have to babysit you like this.

Den tir. 6. apr. 2021 kl. 18.14 skrev Juhana Leinonen <
***@***.***>:

**Comment by juhana** [comment]
Ok, sorry. I thought that when the suggestion said "same as Bus Bois" it meant "same as the current version of Bus Bois" but apparently it's "same as the old version of Bus Bois that crashed the game" instead.

**Comment by Last0xygen** [comment]
> By changing it so that everything doesnt spawn in at once. If you actually were active on the platform, i wouldnt have to babysit you like this.

???



> Ok, sorry. I thought that when the suggestion said "same as Bus Bois" it meant "same as the current version of Bus Bois" but apparently it's "same as the old version of Bus Bois that crashed the game" instead.

It’s a valid request, we‘ll see if it gets implemented

**Comment by anto4440** [comment]
> Ok, sorry. I thought that when the suggestion said "same as Bus Bois" it meant "same as the current version of Bus Bois" but apparently it's "same as the old version of Bus Bois that crashed the game" instead.

Yeah thats fair, my bad. I had a though day yesterday, sorry for letting it out on you.

**Comment by ntill** [comment]
I feel like this would be pretty funny with the "Invade And Persuade" tank instead of the Rhino.  Would prevent a lot of collision issues.

**Comment by JustTunerYT** [comment]
Imagine "All Peds Attack Player" with this effect. I wonder, if they would ACTUALLY shoot you from tank fire gun. Wait... Via remembering either pacifist or ohko run, some peds DID shoot tank gun. So will peds?
