### ISSUE TITLE
[Suggestion] Rotate all vehicles to face player

### ISSUE THREAD

**Issue by oxguy3** [gta-chaos-mod/ChaosModV#96]
Imagine every single vehicle on the map suddenly being rotated (on all three axes) to face the player while maintaining their existing position and velocity. If the player is somewhere with a lot of moving vehicles (i.e. driving on the highway), suddenly every car would be on a crash course to them. I imagine the effect would be like a less instantaneous version of "teleport everything to player".

**Comment by Kevinakk** [comment]
https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Effects/db/Misc/MiscEverythingFacePlayer.cpp

**Comment by oxguy3** [comment]
Wow, and here I thought I had some brilliant original idea. Mea culpa!
