### ISSUE TITLE
[Metaeffect Suggestion] More options

### ISSUE THREAD

**Issue by anto4440** [gta-chaos-mod/ChaosModV#960]
**Name of effect**
More options (Meta)

**Duration if timed effect (long or short timed?)**
Short

**Effect Description**
For duration of effect, effect options will change from 4 to 8.

**NOTE:** This effect will only work with twitch controls.

**Comment by TheRealAyCe** [comment]
Remember that you need to have different voting numbers for consecutive voting cycles. With 4 options this is easy (1-4 and 5-8), but with 8 we will have to go 2-digit. (1-8, 9-16)

**Comment by Da-Best** [comment]
To add onto that not everyone that does chaos does twitch plays. People do play by themselves trying out the challenge and may not know that the meta exists if it is enabled on default

**Comment by anto4440** [comment]
> Remember that you need to have different voting numbers for consecutive voting cycles. With 4 options this is easy (1-4 and 5-8), but with 8 we will have to go 2-digit. (1-8, 9-16)

Yeah I see that now. I actually thought it was a glitch that just never got patched.

**Comment by TheRealAyCe** [comment]
No reason to close this in my opinion. I like it.

**Comment by anto4440** [comment]
So what? Its a useless suggestion, so it should be closed.

**Comment by TheRealAyCe** [comment]
Why useless? Do we already have this suggestion in another ticket?

**Comment by anto4440** [comment]
Useless because its impossible to implement, and therefore without use.

**Comment by SeanMirrsen** [comment]
It's not impossible. It's at best mildly inconvenient.

The only reason why the numbers need to cycle is that Twitch blocks identical messages from the same user. It's an issue with 4 choices, and will be much less of an issue with 8 choices.

A much bigger problem is the UI space. The overlay will be quite excessively large if it has to display 8 options, especially in ingame mode. If you solve that, you can do it. Worst that will happen is some people will have to add an extra message between votes when this effect is active.

**Comment by anto4440** [comment]
Its an inconvenience, bad for the UI, and isn't interesting enough for me to be unhappy about it being closed.
