### ISSUE TITLE
[Effect Suggestion] My Super Cool Effect Idea

### ISSUE THREAD

**Issue by Platapus10** [gta-chaos-mod/ChaosModV#961]
Fus Ro Da**Name of effect**
Potential name(s) 

**Effect Description**
Description of the effect; what should it do?
This effect should push the character or car depending depending where the character is and you should hear the skyrim dragonborn say fus ro da and then this effect happens

**Comment by anto4440** [comment]
What??

Thats one of the worst descriptions yet!

**Comment by Last0xygen** [comment]
Custom sounds can be set by every user themselves and won’t be provided by default.
A boost could be implemented but for a one time boost this doesn’t seem interesting enough, sorry
