### ISSUE TITLE
[Effect Suggestion] Mobile Radio

### ISSUE THREAD

**Issue by pipecek** [gta-chaos-mod/ChaosModV#964]
**Name of effect**
Mobile Radio

**Duration if timed effect (long or short-timed?)**
long. The same as mobile TV

**Effect Description**
This lets you listen to any radio station even outside of cars. It's a pretty useless effect but an effect nonetheless.

**Comment by TheRealAyCe** [comment]
Apparently the main target audience for this seems to be streamers, who deactivate the radio due to copyright issues.

**Comment by Da-Best** [comment]
this is similar to #428

**Comment by Last0xygen** [comment]
Duplicate #428
