### ISSUE TITLE
[Effect Suggestion] Emergency Meeting

### ISSUE THREAD

**Issue by Proxtx** [gta-chaos-mod/ChaosModV#966]
**Name of effect**
Emergency Meeting

**Effect Description**
All main characters get teleported to the top of the Maze bank tower (to hold an emergency meeting).

**Comment by Aljotzi** [comment]
This seems way too close to being "Teleport to Maze Bank"

**Comment by Last0xygen** [comment]
I don’t see how this would be a good addition to the mod
