### ISSUE TITLE
[Effect Suggestion] Crazy Train

### ISSUE THREAD

**Issue by Meepyneepy** [gta-chaos-mod/ChaosModV#967]
**Name of effect**
Crazy Train , Train from Hell , Traininator

**Duration if timed effect (long or short timed?)**
Long.

**Effect Description**
Alter the speed of the train to reach incredibly high speeds.

I've played with this in the past, and it will eliminate and disintegrate anything in its path. It's fun and terrifying, especially when the train is only visible for a few frames.

**Comment by Last0xygen** [comment]
I don’t know, this seems veeeeeery situational. You only use the train once while playing story mode 🤔
And getting the effect while you’re doing would be very low
