### ISSUE TITLE
[Suggestion] LS Noire

### ISSUE THREAD

**Issue by TheRealAyCe** [gta-chaos-mod/ChaosModV#97]
Set a color filter to make the game black/white or grayscale or otherwise vintage

Could also change cars (existing or only new ones?) to "oldtimey" car skins, if that's possible

**Comment by Ecko27** [comment]
If this gets implemented, it should give character a suit, and the fedora. Then it would be truly LS Noire :)

**Comment by TheRealAyCe** [comment]
@Ecko27 Yes please :D
