### ISSUE TITLE
[Effect Suggestion] Spawn Unholy Trinity

### ISSUE THREAD

**Issue by RosyMiranto18** [gta-chaos-mod/ChaosModV#972]
**Name of effect**
**Spawn Unholy Trinity**

**Duration if timed effect (long or short timed?)**
One-time

**Effect Description**
The good news is, this is not any of the Jesus. The bad news is, you will encounter either the Tractor, the Lawnmower, or the Dozer.

**Comment by MoneyWasted** [comment]
We are not currently adding "vehicle spawn" effects. (We have enough already.)
