### ISSUE TITLE
[Effect Suggestion] Christian Squad

### ISSUE THREAD

**Issue by nyancatec** [gta-chaos-mod/ChaosModV#981]
Christian squad

Effect spawns Griefer Jesus and Extreme Griefer Jesus (and if in car, Jesus take the wheel takes the effect), but they're on your team, and are trying to protect you. If you die, they start floating to the heaven (until they despawn).

If Jesus takes the wheel is activated, He'll wait for other Jesuses to get in the vehicle. If there's no seat for 1 Jesus, He'll go to heaven, same if there's no seat for 2nd one.

**Comment by Aljotzi** [comment]
Too similar to #868 #863 #751 and #714

**Comment by Aljotzi** [comment]
> Too similar to #868 #863 #751 and #714

There are likely more of them further down the list but you get the idea.

**Comment by Last0xygen** [comment]
Duplicate
