### ISSUE TITLE
[Effect Suggestion] Jump Scare

### ISSUE THREAD

**Issue by AlphaBrother007** [gta-chaos-mod/ChaosModV#984]
**Name of effect**
Potential name(s) for the effect
Jumpscare
**Effect Description**
Description of the effect; what should it do?
An image should flash on the screen for a bit with some loud noise to spook the player. This image can either stay the same or can have multiple options. It can be something as simple as Trevor looking scary and going "Boo!" or screaming. I could see the Killer Clowns faces, or even Wade's face in clown makeup. It doesn't really matter what the image is, just as long as flashes on the screen for a brief moment, the loud sound plays at the same time, it fades out.

**Comment by anto4440** [comment]
it was not the first time. #772. And again, Why the hell would you want that? You arenbt playing a horror game, you are playing chaos mod!

**Comment by Last0xygen** [comment]
Duplicate #772

**Comment by anto4440** [comment]
Its a shame that I cant close suggestions.

**Comment by Last0xygen** [comment]
> Its a shame that I cant close suggestions.

Well, you would have closed the „tank Bois“ request, which was easy to implement 😉

**Comment by anto4440** [comment]
...no? I mean i get that i thought it wouldnt work, but i wouldnt close it. (I would only have the nerve to close direct duplicates)

**Comment by AlphaBrother007** [comment]
> it was not the first time. #772. And again, Why the hell would you want that? You arenbt playing a horror game, you are playing chaos mod!

Gosh, idk, maybe because it would be funny? Why the hell would you want On Demand TV? You're not watching tv, you're playing a video game! Why the hell would you want Virtual Reality? You're not playing VR you're playing on pc! Why the hell would you want Suicide? Or ignite player? Or Destroy Current Vehicle? Or any effect that just immediately kills the player because those are all technically duplicates? Sorry for the suggestion, Jesus...

**Comment by anto4440** [comment]
I didnt mean it like that.

Den ons. 7. apr. 2021 kl. 16.38 skrev AlphaBrother007 <
***@***.***>:
