### ISSUE TITLE
[Effect Suggestion] flip controls

### ISSUE THREAD

**Issue by 810CK-A1D** [gta-chaos-mod/ChaosModV#986]
**Name of effect**
Flip control

**Duration if timed effect (long or short timed?)**
Long timed

**Effect Description**
Basically flips controls, meaning the forward key is now the backward key and left key is now right, and vice versa

**Comment by Last0xygen** [comment]
Duplicate https://github.com/gta-chaos-mod/ChaosModV/issues/16
